'use strict';
/* v7 AI-GENERATED KAWAII SPRITES — actual generated image assets used at runtime. */
(function(){
const S={ready:false,img:new Image(),sprites:{}};window.AI_SPRITES=S;S.img.src='assets/ai-art-direction.png?v=7';
const slots={hero:[30,198,82,92],mothling:[13,888,126,100],slimeking:[142,888,126,100],frostcub:[274,888,126,100],emberling:[402,888,126,100],crystalbeetle:[527,888,126,100],wraith:[655,888,126,100],treant:[783,888,126,100],rifthound:[913,888,126,100],mimic:[1042,888,126,100],witchcat:[1170,888,126,100],voidling:[1298,888,126,100],starsprite:[1420,888,116,100]};
function extract(box){const[x,y,w,h]=box,c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d');g.drawImage(S.img,x,y,w,h,0,0,w,h);const d=g.getImageData(0,0,w,h),a=d.data;for(let i=0;i<a.length;i+=4){const r=a[i],gg=a[i+1],b=a[i+2],mx=Math.max(r,gg,b),mn=Math.min(r,gg,b),lum=(r+gg+b)/3;if(lum<58&&mx-mn<50)a[i+3]=0;else if(lum<72&&mx-mn<28)a[i+3]=Math.min(a[i+3],90)}g.putImageData(d,0,0);return c}
S.img.onload=()=>{for(const[k,v]of Object.entries(slots))S.sprites[k]=extract(v);S.ready=true};
const map={moth:'mothling',bee:'mothling',king:'slimeking',slime:'slimeking',pink:'slimeking',snowbun:'frostcub',frostling:'frostcub',frostStag:'frostcub',emberling:'emberling',magmaToad:'emberling',crystalbeetle:'crystalbeetle',golem:'crystalbeetle',ghost:'wraith',wraithQueen:'wraith',wisp:'wraith',treant:'treant',shroomknight:'treant',riftHound:'rifthound',wolf:'rifthound',mimic:'mimic',voidling:'voidling',worldEater:'voidling',starbeast:'starsprite'};
const fallbackMob=drawMobSprite;drawMobSprite=function(q,t,cx,cy){const key=map[q.type],spr=key&&S.sprites[key];if(!S.ready||!spr)return fallbackMob(q,t,cx,cy);const def=mobDefs[q.type],sx=q.x-player.x+cx,sy=q.y-player.y+cy;if(sx<-100||sx>w+100||sy<-120||sy>h+120)return;const boss=def.boss,size=(boss?92:56)*(q.elite?1.1:1),bob=Math.sin(t*(q.type==='moth'||q.type==='bee'?8:4)+(q.ph||0))*3,tilt=Math.sin(t*3+(q.ph||0))*.035;ctx.save();ctx.translate(Math.round(sx),Math.round(sy+bob));ctx.rotate(tilt);if(q.hit>0)ctx.globalAlpha=.62;shadow(0,size*.32,size*.3);if(q.elite){ctx.strokeStyle='#ffe073dd';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,size*.47+Math.sin(t*5)*3,0,Math.PI*2);ctx.stroke()}if(def.boss){ctx.globalCompositeOperation='lighter';ctx.globalAlpha=.18;ctx.fillStyle='#ffd56f';ctx.beginPath();ctx.arc(0,-size*.15,size*.57+Math.sin(t*3)*4,0,Math.PI*2);ctx.fill();ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1}ctx.drawImage(spr,-size/2,-size*.72,size,size);if(q.statusT>0){ctx.fillStyle=q.status==='burn'?'#ff9d6a':q.status==='slow'?'#a8efff':q.status==='void'?'#cda5ff':'#ff9fbe';ctx.fillRect(-8,-size*.74-5,16,3)}if(def.boss||q.hp<q.max){rect(-def.r,-size*.72-12,def.r*2,4,'#222a36aa');rect(-def.r,-size*.72-12,def.r*2*Math.max(0,q.hp/q.max),4,def.boss?'#f4cf62':'#ef829f')}ctx.restore()};
const fallbackPlayer=drawPlayerSprite;drawPlayerSprite=function(t,cx,cy){const spr=S.sprites.hero;if(!S.ready||!spr)return fallbackPlayer(t,cx,cy);const moving=Math.hypot(player.vx,player.vy)>.1||keys.KeyW||keys.KeyA||keys.KeyS||keys.KeyD||keys.ArrowUp||keys.ArrowDown||keys.ArrowLeft||keys.ArrowRight,bob=moving?Math.sin(t*11)*2:0,step=moving&&Math.sin(t*11)>0;ctx.save();ctx.translate(Math.round(cx),Math.round(cy+bob));if(invuln>0&&Math.floor(invuln*18)%2===0)ctx.globalAlpha=.45;if(spawnShield>0){ctx.strokeStyle='#fff8d6dd';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,27+Math.sin(t*5)*2,0,Math.PI*2);ctx.stroke()}shadow(0,19,14);rect(-9,11+(step?1:0),7,10,'#6f587b');rect(2,11+(step?0:1),7,10,'#6f587b');rect(-12,0,24,16,'#d982b3');rect(-14,4,5,8,'#ffe9dd');rect(9,4,5,8,'#ffe9dd');ctx.drawImage(spr,-20,-29,40,45);drawWeaponSprite(0,3,player.dir,weapon);if(window.COMBAT&&COMBAT.fury>=100){ctx.globalCompositeOperation='lighter';ctx.strokeStyle='#ffd86dcc';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-2,30+Math.sin(t*7)*3,0,Math.PI*2);ctx.stroke()}ctx.restore()};
const st=document.createElement('style');st.textContent='#start{background-image:linear-gradient(#11192ba8,#16172ab0),url("assets/ai-art-direction.png?v=7");background-size:cover;background-position:center}.card{background:#fffdf8f1!important;backdrop-filter:blur(8px);border-color:#ffe3f1!important}.primary{background:linear-gradient(#f5abd0,#df73ad)!important}';document.head.appendChild(st);
})();