'use strict';
/* v7 AI-GENERATED KAWAII SPRITES — uses the generated art asset committed in assets/. */
(function(){
const S={ready:false,img:new Image(),sprites:{}};window.AI_SPRITES=S;S.img.src='assets/ai-art-direction.png?v=7';
const slots={mothling:[13,888,126,100],slimeking:[142,888,126,100],frostcub:[274,888,126,100],emberling:[402,888,126,100],crystalbeetle:[527,888,126,100],wraith:[655,888,126,100],treant:[783,888,126,100],rifthound:[913,888,126,100],mimic:[1042,888,126,100],witchcat:[1170,888,126,100],voidling:[1298,888,126,100],starsprite:[1420,888,116,100]};
function extract(box){const[x,y,w,h]=box,c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d');g.drawImage(S.img,x,y,w,h,0,0,w,h);const d=g.getImageData(0,0,w,h),a=d.data;for(let i=0;i<a.length;i+=4){const r=a[i],gg=a[i+1],b=a[i+2],mx=Math.max(r,gg,b),mn=Math.min(r,gg,b),lum=(r+gg+b)/3;if(lum<58&&mx-mn<50)a[i+3]=0;else if(lum<72&&mx-mn<28)a[i+3]=Math.min(a[i+3],100)}g.putImageData(d,0,0);return c}
S.img.onload=()=>{for(const[k,v]of Object.entries(slots))S.sprites[k]=extract(v);S.ready=true};
const map={moth:'mothling',bee:'mothling',king:'slimeking',slime:'slimeking',pink:'slimeking',snowbun:'frostcub',frostling:'frostcub',frostStag:'frostcub',emberling:'emberling',magmaToad:'emberling',crystalbeetle:'crystalbeetle',golem:'crystalbeetle',ghost:'wraith',wraithQueen:'wraith',wisp:'wraith',treant:'treant',shroomknight:'treant',riftHound:'rifthound',wolf:'rifthound',mimic:'mimic',voidling:'voidling',worldEater:'voidling',starbeast:'starsprite'};
const fallback=drawMobSprite;drawMobSprite=function(q,t,cx,cy){const key=map[q.type],spr=key&&S.sprites[key];if(!S.ready||!spr)return fallback(q,t,cx,cy);const def=mobDefs[q.type],sx=q.x-player.x+cx,sy=q.y-player.y+cy;if(sx<-100||sx>w+100||sy<-120||sy>h+120)return;const boss=def.boss,size=(boss?88:54)*(q.elite?1.1:1),bob=Math.sin(t*(q.type==='moth'||q.type==='bee'?8:4)+(q.ph||0))*3;ctx.save();ctx.translate(Math.round(sx),Math.round(sy+bob));if(q.hit>0)ctx.globalAlpha=.62;shadow(0,size*.32,size*.3);if(q.elite){ctx.strokeStyle='#ffe073cc';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,size*.47+Math.sin(t*5)*3,0,Math.PI*2);ctx.stroke()}if(def.boss){ctx.globalCompositeOperation='lighter';ctx.globalAlpha=.16;ctx.fillStyle='#ffd56f';ctx.beginPath();ctx.arc(0,-size*.15,size*.55+Math.sin(t*3)*4,0,Math.PI*2);ctx.fill();ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1}ctx.drawImage(spr,-size/2,-size*.72,size,size);if(q.statusT>0){ctx.fillStyle=q.status==='burn'?'#ff9d6a':q.status==='slow'?'#a8efff':q.status==='void'?'#cda5ff':'#ff9fbe';ctx.fillRect(-8,-size*.74-5,16,3)}if(def.boss||q.hp<q.max){rect(-def.r,-size*.72-12,def.r*2,4,'#222a36aa');rect(-def.r,-size*.72-12,def.r*2*Math.max(0,q.hp/q.max),4,def.boss?'#f4cf62':'#ef829f')}ctx.restore()};
const st=document.createElement('style');st.textContent='#start{background-image:linear-gradient(#11192bb5,#16172ab8),url("assets/ai-art-direction.png?v=7");background-size:cover;background-position:center}.card{background:#fffdf8f2!important;backdrop-filter:blur(8px)}';document.head.appendChild(st);
})();