'use strict';
/* v7 AI-GENERATED KAWAII SPRITES — transparent atlas generated from approved AI art. */
(function(){
const S={ready:false,error:false,img:new Image(),cells:{hero:[0,0],mothling:[1,0],slimeking:[2,0],frostcub:[3,0],emberling:[0,1],crystalbeetle:[1,1],wraith:[2,1],treant:[3,1],rifthound:[0,2],mimic:[1,2],witchcat:[2,2],voidling:[3,2],starsprite:[0,3]}};window.AI_SPRITES=S;
const atlasParts=['assets/ai-kawaii-atlas.part1?v=7','assets/atlas-2.b64?v=7','assets/atlas-3.b64?v=7'];
Promise.all(atlasParts.map(u=>fetch(u).then(r=>{if(!r.ok)throw new Error('atlas '+r.status);return r.text()}))).then(parts=>{const data=parts[0].slice(0,20000)+parts[1]+parts[2];S.img.onload=()=>{S.ready=true;S.error=false};S.img.onerror=()=>{S.error=true};S.img.src='data:image/png;base64,'+data}).catch(()=>{S.error=true});
const map={
slime:'slimeking',pink:'slimeking',frog:'slimeking',king:'slimeking',magmaToad:'slimeking',
bee:'mothling',moth:'mothling',bat:'mothling',
snowbun:'frostcub',frostling:'frostcub',frostStag:'frostcub',
emberling:'emberling',cactus:'emberling',serpent:'emberling',
crystalbeetle:'crystalbeetle',golem:'crystalbeetle',crab:'crystalbeetle',
ghost:'wraith',wraithQueen:'wraith',wisp:'wraith',skeleton:'wraith',
treant:'treant',shroomknight:'treant',mushroom:'treant',
riftHound:'rifthound',wolf:'rifthound',boar:'rifthound',
mimic:'mimic',voidling:'voidling',worldEater:'voidling',starbeast:'starsprite'};
const hue={pink:330,frog:115,king:70,magmaToad:20,bee:45,moth:290,bat:260,cactus:105,serpent:145,crab:15,golem:205,skeleton:35,mushroom:325,boar:20,worldEater:280,starbeast:220};
function cell(name,x,y,w,h,filter='none'){const c=S.cells[name];if(!c||!S.ready)return false;ctx.save();ctx.filter=filter;ctx.drawImage(S.img,c[0]*128,c[1]*128,128,128,x,y,w,h);ctx.restore();return true}
const fallbackMob=drawMobSprite;drawMobSprite=function(q,t,cx,cy){const key=map[q.type];if(!S.ready||!key)return fallbackMob(q,t,cx,cy);const def=mobDefs[q.type],sx=q.x-player.x+cx,sy=q.y-player.y+cy;if(sx<-110||sx>w+110||sy<-130||sy>h+130)return;const boss=def.boss,size=(boss?100:66)*(q.elite?1.1:1),bob=Math.sin(t*(q.type==='moth'||q.type==='bee'||q.type==='bat'?8:4)+(q.ph||0))*3,tilt=Math.sin(t*3+(q.ph||0))*.035,filter=hue[q.type]!==undefined?`hue-rotate(${hue[q.type]}deg) saturate(1.08)`:'none';ctx.save();ctx.translate(Math.round(sx),Math.round(sy+bob));ctx.rotate(tilt);if(q.hit>0)ctx.globalAlpha=.62;shadow(0,size*.27,size*.26);if(q.elite){ctx.strokeStyle='#ffe073dd';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,size*.4+Math.sin(t*5)*3,0,Math.PI*2);ctx.stroke()}if(def.boss){ctx.globalCompositeOperation='lighter';ctx.globalAlpha=.18;ctx.fillStyle='#ffd56f';ctx.beginPath();ctx.arc(0,-size*.12,size*.5+Math.sin(t*3)*4,0,Math.PI*2);ctx.fill();ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1}cell(key,-size/2,-size*.7,size,size,filter);if(q.statusT>0){ctx.fillStyle=q.status==='burn'?'#ff9d6a':q.status==='slow'?'#a8efff':q.status==='void'?'#cda5ff':'#ff9fbe';ctx.fillRect(-8,-size*.72-5,16,3)}if(def.boss||q.hp<q.max){rect(-def.r,-size*.72-12,def.r*2,4,'#222a36aa');rect(-def.r,-size*.72-12,def.r*2*Math.max(0,q.hp/q.max),4,def.boss?'#f4cf62':'#ef829f')}ctx.restore()};
const fallbackPlayer=drawPlayerSprite;drawPlayerSprite=function(t,cx,cy){if(!S.ready)return fallbackPlayer(t,cx,cy);const moving=Math.hypot(player.vx,player.vy)>.1||keys.KeyW||keys.KeyA||keys.KeyS||keys.KeyD||keys.ArrowUp||keys.ArrowDown||keys.ArrowLeft||keys.ArrowRight,bob=moving?Math.sin(t*11)*2:0,lean=moving?Math.sin(t*11)*.025:0;ctx.save();ctx.translate(Math.round(cx),Math.round(cy+bob));ctx.rotate(lean);if(invuln>0&&Math.floor(invuln*18)%2===0)ctx.globalAlpha=.45;if(spawnShield>0){ctx.strokeStyle='#fff8d6dd';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,28+Math.sin(t*5)*2,0,Math.PI*2);ctx.stroke()}shadow(0,20,15);cell('hero',-39,-48,78,78);drawWeaponSprite(0,4,player.dir,weapon);if(window.COMBAT&&COMBAT.fury>=100){ctx.globalCompositeOperation='lighter';ctx.strokeStyle='#ffd86dcc';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-2,31+Math.sin(t*7)*3,0,Math.PI*2);ctx.stroke()}ctx.restore()};
const st=document.createElement('style');st.textContent='#start{background:radial-gradient(circle at 50% 45%,#704f7788,#15182be8),linear-gradient(#222b3acb,#25233acb)}.card{background:#fffdf8f1!important;backdrop-filter:blur(8px);border-color:#ffe3f1!important}.primary{background:linear-gradient(#f5abd0,#df73ad)!important}';document.head.appendChild(st);
window.__TWBB_ART_TEST__={get:()=>({ready:S.ready,error:S.error,sprites:Object.keys(S.cells).length,mapped:Object.keys(map).length})};
})();