function gainXp(n){xp+=n;while(xp>=xpNeed){xp-=xpNeed;level++;xpNeed=Math.floor(5+level*2.35);maxHp+=7;hp=Math.min(maxHp,hp+15);toast('★ Level '+level+' · stronger and tougher');sound('level');puff(player.x,player.y,'#fff0a1',14,130)}hud()}
function rollWeapon(bonus=0){const r=Math.random()+bonus*.06,idx=r>.995?7:r>.97?6:r>.90?5:r>.82?4:r>.68?3:r>.52?2:r>.28?1:0;return weapons[idx]}
function maybeDrop(x,y,boss=false){const r=Math.random();if(boss||r<.19)drops.push({x,y,type:'weapon',weapon:rollWeapon(boss?2.5:0),t:28,bob:Math.random()*6});else if(r<.43||hp<maxHp*.48)drops.push({x,y,type:'food',t:22,bob:Math.random()*6})}
function equipMaybe(next){if(next.rarity>weapon.rarity||next.power>weapon.power*1.08){weapon=next;toast('✦ '+rarity[next.rarity]+' '+next.name+' equipped');sound('loot');puff(player.x,player.y,next.rarity>=3?'#f2d780':'#e9b7d0',10,90)}else toast(next.name+' found · your weapon is better');hud()}
function killMob(q){const i=mobs.indexOf(q);if(i>=0)mobs.splice(i,1);kills++;gainXp(mobDefs[q.type].xp);maybeDrop(q.x,q.y,q.type==='king');puff(q.x,q.y,q.type==='king'?'#f4d975':'#fff0d2',q.type==='king'?25:10,q.type==='king'?170:100);sound(q.type==='king'?'boss':'hit');if(q.type==='king'){relics+=3;toast('♛ King Slime defeated · +3 relics');bossTimer=100}else if(Math.random()<.5)spawnMob()}
function targetForAttack(range){let best=null,bestScore=1e9;for(const q of mobs){const dx=q.x-player.x,dy=q.y-player.y,d=Math.hypot(dx,dy);if(d>range||!lineClear(player.x,player.y,q.x,q.y))continue;const ang=Math.atan2(dy,dx),delta=Math.abs(Math.atan2(Math.sin(ang-player.dir),Math.cos(ang-player.dir)));const score=d+delta*48;if(delta<.95||d<48){if(score<bestScore){bestScore=score;best=q}}}return best}
function damageMob(q,dmg,kb){q.hp-=dmg;q.hit=.13;const dx=q.x-player.x,dy=q.y-player.y,d=Math.hypot(dx,dy)||1;moveBody(q,dx/d*kb,dy/d*kb,mobDefs[q.type].r*.72);puff(q.x,q.y,'#fff4d6',5,75);if(q.hp<=0)killMob(q)}
function attack(){if(!started||dead||attackCd>0)return;attackCd=weapon.cd;spawnShield=0;const target=targetForAttack(weapon.range);if(target)player.dir=Math.atan2(target.y-player.y,target.x-player.x);const dmg=(7+level*1.45)*weapon.power;if(weapon.type==='ranged'){shots.push({x:player.x+Math.cos(player.dir)*18,y:player.y+Math.sin(player.dir)*18,vx:Math.cos(player.dir)*455,vy:Math.sin(player.dir)*455,t:weapon.range/455,dmg,kb:weapon.kb,kind:weapon.kind});sound('loot')}else{particles.push({slash:true,a:player.dir,t:.14,col:'#fff1bf'});if(target&&Math.hypot(target.x-player.x,target.y-player.y)<=weapon.range)damageMob(target,dmg,weapon.kb);sound('hit')}}
function hurt(amount,from){if(invuln>0||spawnShield>0||dead)return;let mult=run<35?.65:1;if(hp<maxHp*.3)mult*=.85;hp-=amount*mult;invuln=.88;regenDelay=4;screenShake=8;sound('hurt');puff(player.x,player.y,'#ef8fa9',9,115);if(from){const dx=player.x-from.x,dy=player.y-from.y,d=Math.hypot(dx,dy)||1;moveBody(player,dx/d*17,dy/d*17,PLAYER_R)}hud();if(hp<=0)die()}
function die(){dead=true;started=false;holdAttack=false;document.getElementById('dlevel').textContent=level;document.getElementById('dtime').textContent=formatTime(run);document.getElementById('ddisc').textContent=discovered.size;document.getElementById('dkills').textContent=kills;document.getElementById('dweapon').textContent='Final weapon: '+rarity[weapon.rarity]+' '+weapon.name+' · '+regionCount+' regions charted';document.getElementById('death').classList.remove('hide')}
function formatTime(s){return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')}
function updateCompass(){let best=null,bd=1e9;for(const l of landmarks){if(l.found)continue;const d=Math.hypot(l.x-player.x,l.y-player.y);if(d<bd){bd=d;best=l}}const el=document.getElementById('compass');if(!best){el.textContent='◇ Keep exploring…';return}const a=Math.atan2(best.y-player.y,best.x-player.x),dir=['→','↘','↓','↙','←','↖','↑','↗'][Math.round((a<0?a+Math.PI*2:a)/(Math.PI/4))%8];el.textContent=dir+'  '+(bd<180?'Something strange is close':bd<420?'A mystery is nearby':'Follow the pull')+'  ·  '+Math.round(bd/10)*10+'m'}
function discover(l){if(l.found)return;l.found=true;discovered.add(l.id);const def=landmarkDefs[l.type];relics++;sound('discover');puff(l.x,l.y,'#fff0a6',22,150);if(l.type===1||l.type===5)hp=maxHp;else if(l.type===4){maxHp+=5;hp=Math.min(maxHp,hp+10)}else if(l.type===0||l.type===2)gainXp(l.type===2?5:3);else if(l.type===3){drops.push({x:l.x-18,y:l.y+24,type:'weapon',weapon:rollWeapon(2),t:35,bob:1});drops.push({x:l.x+18,y:l.y+24,type:'weapon',weapon:rollWeapon(1.6),t:35,bob:3});relics++}else if(l.type===6){drops.push({x:l.x,y:l.y+26,type:'weapon',weapon:rollWeapon(.8),t:30,bob:2});drops.push({x:l.x+20,y:l.y+30,type:'food',t:25,bob:4})}else if(l.type===7){drops.push({x:l.x,y:l.y+26,type:'weapon',weapon:rollWeapon(2.8),t:40,bob:2});relics+=2}toast('◇ '+def.name+' · '+def.text);hud();updateCompass()}
function updateRegions(){const rx=Math.floor(player.x/640),ry=Math.floor(player.y/640),key=rx+','+ry;if(key!==lastRegionKey){lastRegionKey=key;regionCount++;refreshLandmarks();toast('🗺 '+biomeNames[biomeAtWorld(player.x,player.y)]+' · region '+regionCount);updateCompass()}}
function updatePlayer(dt){let mx=player.vx,my=player.vy;if(keys.KeyW||keys.ArrowUp)my-=1;if(keys.KeyS||keys.ArrowDown)my+=1;if(keys.KeyA||keys.ArrowLeft)mx-=1;if(keys.KeyD||keys.ArrowRight)mx+=1;const d=Math.hypot(mx,my);if(d>1){mx/=d;my/=d}if(Math.hypot(mx,my)>.07)player.dir=Math.atan2(my,mx);const speed=160;moveBody(player,mx*speed*dt,my*speed*dt,PLAYER_R)}
function updateMobs(dt){for(let i=mobs.length-1;i>=0;i--){const q=mobs[i],def=mobDefs[q.type];q.hit=Math.max(0,q.hit-dt);q.contact=Math.max(0,q.contact-dt);q.charge=Math.max(0,q.charge-dt);let dx=player.x-q.x,dy=player.y-q.y,d=Math.hypot(dx,dy)||1;if(d>920&&q.type!=='king'){mobs.splice(i,1);continue}let vx=0,vy=0;if(d<330||q.type==='king'){
if(def.ai==='zig'){const wig=Math.sin(run*4+q.seed)*.8,vx=dx/d*Math.cos(wig)-dy/d*Math.sin(wig),vy=dy/d*Math.cos(wig)+dx/d*Math.sin(wig);moveBody(q,vx*def.spd*dt,vy*def.spd*dt,def.r*.72)}
else if(def.ai==='strafe'){const s=Math.sin(run*1.7+q.seed)>0?1:-1;vx=dx/d*.45-dy/d*.78*s;vy=dy/d*.45+dx/d*.78*s;moveBody(q,vx*def.spd*dt,vy*def.spd*dt,def.r*.72)}
else if(def.ai==='orbit'){const target=d>150?1:-.25;vx=dx/d*target-dy/d*.75;vy=dy/d*target+dx/d*.75;moveBody(q,vx*def.spd*dt,vy*def.spd*dt,def.r*.72)}
else if(def.ai==='charge'&&d<190){if(q.charge<=0){q.charge=.95;q.chargeDir=Math.atan2(dy,dx)}const charging=q.charge<.45,spd=charging?def.spd*2.6:def.spd*.18;moveBody(q,Math.cos(q.chargeDir)*spd*dt,Math.sin(q.chargeDir)*spd*dt,def.r*.72)}
else if(def.ai==='hop'){q.hop+=dt;const hop=Math.sin(q.hop*5)>-.2?1:.1;moveBody(q,dx/d*def.spd*hop*dt,dy/d*def.spd*hop*dt,def.r*.72)}
else if(def.ai==='phase'){moveBody(q,dx/d*def.spd*dt,dy/d*def.spd*dt,def.r*.62)}
else{moveBody(q,dx/d*def.spd*dt,dy/d*def.spd*dt,def.r*.72)}}
for(let j=i-1;j>=0;j--){const o=mobs[j],sx=q.x-o.x,sy=q.y-o.y,sd=Math.hypot(sx,sy)||1,min=(def.r+mobDefs[o.type].r)*.62;if(sd<min){const push=(min-sd)*.18;moveBody(q,sx/sd*push,sy/sd*push,def.r*.72);moveBody(o,-sx/sd*push,-sy/sd*push,mobDefs[o.type].r*.72)}}
const hitD=PLAYER_R+def.r*.68;if(d<hitD&&q.contact<=0){q.contact=1.05;hurt(def.dmg,q)}}}
function updateShots(dt){for(let i=shots.length-1;i>=0;i--){const s=shots[i],ox=s.x,oy=s.y;s.x+=s.vx*dt;s.y+=s.vy*dt;s.t-=dt;if(blockedCircle(s.x,s.y,4)){puff(s.x,s.y,'#fff1b0',4,55);shots.splice(i,1);continue}let hit=null;for(const q of mobs)if(Math.hypot(q.x-s.x,q.y-s.y)<mobDefs[q.type].r*.75+5){hit=q;break}if(hit){damageMob(hit,s.dmg,s.kb);shots.splice(i,1);continue}if(s.t<=0||Math.hypot(s.x-ox,s.y-oy)>520)shots.splice(i,1)}}
function updateDrops(dt){for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.t-=dt;if(Math.hypot(d.x-player.x,d.y-player.y)<25){if(d.type==='food'){hp=Math.min(maxHp,hp+Math.max(12,maxHp*.3));toast('🍓 Strawberry · health restored');sound('loot')}else equipMaybe(d.weapon);drops.splice(i,1);hud();continue}if(d.t<=0)drops.splice(i,1)}}
function update(dt){run+=dt;attackCd=Math.max(0,attackCd-dt);invuln=Math.max(0,invuln-dt);spawnShield=Math.max(0,spawnShield-dt);regenDelay=Math.max(0,regenDelay-dt);screenShake=Math.max(0,screenShake-28*dt);bossTimer-=dt;if(holdAttack)attack();updatePlayer(dt);updateMobs(dt);updateShots(dt);updateDrops(dt);for(const p of particles){p.x+=(p.vx||0)*dt;p.y+=(p.vy||0)*dt;p.t-=dt}particles=particles.filter(p=>p.t>0);if(regenDelay<=0&&hp<maxHp)hp=Math.min(maxHp,hp+(hp<maxHp*.3?3.2:2.05)*dt);if(mobs.length<7+Math.min(9,Math.floor(run/45))&&Math.random()<dt*.7)spawnMob();if(bossTimer<=0&&!mobs.some(m=>m.type==='king')){spawnMob('king');bossTimer=999;toast('♛ Something huge is squishing nearby…');sound('boss')}for(const l of landmarks)if(!l.found&&Math.hypot(l.x-player.x,l.y-player.y)<42)discover(l);updateRegions();if(Math.floor(run*3)%3===0)updateCompass();if(tutorialStep===0&&run>2){tutorialStep=1;toast('🕹 Drag anywhere on the left to move')}else if(tutorialStep===1&&run>8){tutorialStep=2;toast('⚔ Hold BONK to attack · aim assist is gentle')}else if(tutorialStep===2&&run>16){tutorialStep=3;toast('◇ Follow the compass for discoveries')}hud()}
