function gainXp(n){xp+=n;while(xp>=xpNeed){xp-=xpNeed;level++;xpNeed=Math.floor(6+level*2.6);maxHp+=7;hp=Math.min(maxHp,hp+16);toast('★ Level '+level+' · stronger and tougher');sound('level');puff(player.x,player.y,'#fff0a1',16,130)}hud()}
function rollWeapon(bonus=0){const tier=dangerAt(player.x,player.y),r=Math.random()+bonus*.05+tier*.018;let pool=weapons.filter(w=>w.rarity<=Math.min(5,1+Math.floor(tier*.95)+Math.floor(bonus)));if(r>.995&&tier>=4)pool=weapons.filter(w=>w.rarity===5);else if(r>.965&&tier>=2)pool=weapons.filter(w=>w.rarity>=4);else if(r>.87)pool=weapons.filter(w=>w.rarity>=3&&w.rarity<=4);else if(r>.65)pool=weapons.filter(w=>w.rarity>=2&&w.rarity<=3);else if(r>.35)pool=weapons.filter(w=>w.rarity>=1&&w.rarity<=2);else pool=weapons.filter(w=>w.rarity<=1);return pool[(Math.random()*pool.length)|0]||weapons[0]}
function maybeDrop(x,y,boss=false,elite=false){const r=Math.random();if(boss||elite||r<.17){const wp=rollWeapon(boss?3.3:elite?1.6:0);drops.push({x,y,type:'weapon',weapon:wp,t:wp.rarity>=4?50:32,bob:Math.random()*6})}else if(r<.39||hp<maxHp*.45)drops.push({x,y,type:'food',t:24,bob:Math.random()*6})}
function weaponScore(w){return w.power*(1+(w.range>160?.14:0))*(1/(.7+w.cd*.3))}
function equipMaybe(next){const better=next.rarity>weapon.rarity||weaponScore(next)>weaponScore(weapon)*1.08;if(better){weapon=next;toast('✦ '+rarity[next.rarity]+' '+next.name+' equipped');sound(next.rarity>=5?'mythic':'loot');puff(player.x,player.y,rarityColor[next.rarity],next.rarity>=4?18:10,next.rarity>=4?150:95)}else toast(rarity[next.rarity]+' '+next.name+' · current weapon is stronger');hud()}
function killMob(q){const i=mobs.indexOf(q);if(i>=0)mobs.splice(i,1);kills++;const def=mobDefs[q.type];gainXp(def.xp*(q.elite?2:1));maybeDrop(q.x,q.y,!!def.boss,q.elite);puff(q.x,q.y,def.boss?'#f4d975':q.elite?'#d7abff':'#fff0d2',def.boss?28:q.elite?18:10,def.boss?180:110);sound(def.boss?'boss':'hit');if(def.boss){relics+=def.tier>=4?5:3;toast('♛ '+bossDisplayName(q.type)+' defeated · relics recovered');bossTimer=85+Math.random()*45}else if(Math.random()<.45)spawnMob()}
function bossDisplayName(type){return({king:'King Slime',wraithQueen:'Wraith Queen',magmaToad:'Magma Toad',frostStag:'Frost Stag',worldEater:'The World Eater'})[type]||'Boss'}
function angleDelta(a,b){return Math.abs(Math.atan2(Math.sin(a-b),Math.cos(a-b)))}
function targetForAttack(range){let best=null,bestScore=1e9;for(const q of mobs){const dx=q.x-player.x,dy=q.y-player.y,d=Math.hypot(dx,dy);if(d>range||!lineClear(player.x,player.y,q.x,q.y))continue;const ang=Math.atan2(dy,dx),delta=angleDelta(ang,player.dir);if(delta>1.35&&d>48)continue;const dangerBonus=mobDefs[q.type].boss?-65:q.elite?-30:0,score=d+delta*38+dangerBonus;if(score<bestScore){bestScore=score;best=q}}
if(hostileTarget&&hostileTarget.hostile&&hostileTarget.hp>0){const d=Math.hypot(hostileTarget.x-player.x,hostileTarget.y-player.y);if(d<=range&&lineClear(player.x,player.y,hostileTarget.x,hostileTarget.y)){const delta=angleDelta(Math.atan2(hostileTarget.y-player.y,hostileTarget.x-player.x),player.dir);const score=d+delta*35-45;if(score<bestScore){best=hostileTarget;bestScore=score}}}return best}
function damageMob(q,dmg,kb){q.hp-=dmg;q.hit=.14;const dx=q.x-player.x,dy=q.y-player.y,d=Math.hypot(dx,dy)||1;moveBody(q,dx/d*kb,dy/d*kb,(mobDefs[q.type]?.r||12)*.68);puff(q.x,q.y,'#fff4d6',5,75);if(q.hp<=0)killMob(q)}
function damageWanderer(q,dmg,kb){if(!q.hostile)return;q.hp-=dmg;q.hit=.15;const dx=q.x-player.x,dy=q.y-player.y,d=Math.hypot(dx,dy)||1;moveBody(q,dx/d*kb,dy/d*kb,10);puff(q.x,q.y,'#ffd1e3',6,85);if(q.hp<=0){const i=wanderers.indexOf(q);if(i>=0)wanderers.splice(i,1);if(hostileTarget===q)hostileTarget=null;drops.push({x:q.x,y:q.y,type:'weapon',weapon:q.weapon,t:35,bob:2});gainXp(6+dangerAt(q.x,q.y)*2);toast(q.name+' was defeated · weapon dropped');sound('loot')}}
function fireAttack(target){attackCd=weapon.cd;const tx=target?target.x:null,ty=target?target.y:null;if(target)player.dir=Math.atan2(ty-player.y,tx-player.x);const dmg=(7.4+level*1.5)*weapon.power;if(weapon.type==='ranged'){shots.push({x:player.x+Math.cos(player.dir)*18,y:player.y+Math.sin(player.dir)*18,vx:Math.cos(player.dir)*470,vy:Math.sin(player.dir)*470,t:weapon.range/470,dmg,kb:weapon.kb,kind:weapon.kind,targetType:wanderers.includes(target)?'wanderer':'mob'});sound('loot')}else{particles.push({slash:true,a:player.dir,t:.14,col:rarityColor[weapon.rarity]});if(target&&Math.hypot(target.x-player.x,target.y-player.y)<=weapon.range){wanderers.includes(target)?damageWanderer(target,dmg,weapon.kb):damageMob(target,dmg,weapon.kb)}sound('hit')}}
function autoBonk(){if(!started||dead||attackCd>0)return;const target=targetForAttack(weapon.range);if(target)fireAttack(target)}
function hurt(amount,from){if(invuln>0||spawnShield>0||dead)return;let mult=run<38?.62:1;if(hp<maxHp*.3)mult*=.84;hp-=amount*mult;invuln=.86;regenDelay=4.2;screenShake=8;sound('hurt');puff(player.x,player.y,'#ef8fa9',9,115);if(from){const dx=player.x-from.x,dy=player.y-from.y,d=Math.hypot(dx,dy)||1;moveBody(player,dx/d*18,dy/d*18,PLAYER_R)}hud();if(hp<=0)die()}
function die(){dead=true;started=false;document.getElementById('dlevel').textContent=level;document.getElementById('dtime').textContent=formatTime(run);document.getElementById('ddisc').textContent=discovered.size;document.getElementById('dkills').textContent=kills;document.getElementById('dweapon').textContent='Final weapon: '+rarity[weapon.rarity]+' '+weapon.name+' · '+regionCount+' regions charted';document.getElementById('death').classList.remove('hide')}
function formatTime(s){return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')}
function updateCompass(){let best=null,bd=1e9;for(const l of landmarks){if(l.found)continue;const d=Math.hypot(l.x-player.x,l.y-player.y);if(d<bd){bd=d;best=l}}const el=document.getElementById('compass');if(!best){el.textContent='◇ Push farther into the unknown…';return}const a=Math.atan2(best.y-player.y,best.x-player.x),dir=['→','↘','↓','↙','←','↖','↑','↗'][Math.round((a<0?a+Math.PI*2:a)/(Math.PI/4))%8];el.textContent=dir+'  '+(bd<160?'Something extraordinary is close':bd<420?'A discovery is nearby':'A distant signal is calling')+' · '+Math.round(bd/10)*10+'m'}
function landmarkReward(l){const type=landmarkDefs[l.type].kind,tier=dangerAt(l.x,l.y);if(['grove','spring'].includes(type))hp=maxHp;else if(type==='elder'){maxHp+=6;hp=Math.min(maxHp,hp+18)}else if(['ruins','obelisk','choir'].includes(type))gainXp(3+tier*2);else if(type==='crater'){drops.push({x:l.x-18,y:l.y+24,type:'weapon',weapon:rollWeapon(2+tier*.3),t:45,bob:1});drops.push({x:l.x+18,y:l.y+24,type:'weapon',weapon:rollWeapon(1.4+tier*.2),t:40,bob:3});relics++}else if(type==='camp'){drops.push({x:l.x,y:l.y+26,type:'weapon',weapon:rollWeapon(.7),t:35,bob:2});drops.push({x:l.x+22,y:l.y+30,type:'food',t:30,bob:4})}else if(type==='vault'){drops.push({x:l.x,y:l.y+28,type:'weapon',weapon:rollWeapon(2.7+tier*.35),t:55,bob:2});relics+=2}else if(type==='shrine'){hp=maxHp;maxHp+=4;drops.push({x:l.x+18,y:l.y+22,type:'weapon',weapon:rollWeapon(2.1),t:42,bob:1})}else if(type==='lantern'){gainXp(8);worldEventTimer=Math.min(worldEventTimer,8)}else if(type==='grave'){for(let i=0;i<2;i++)spawnMob(tier>=4?'golem':'skeleton',true);drops.push({x:l.x,y:l.y+28,type:'weapon',weapon:rollWeapon(2.4),t:50,bob:2})}else if(type==='gate'){drops.push({x:l.x,y:l.y+28,type:'weapon',weapon:rollWeapon(3.4),t:60,bob:2});relics+=3}else if(type==='worldheart'){maxHp+=10;hp=maxHp;drops.push({x:l.x,y:l.y+30,type:'weapon',weapon:rollWeapon(4.1),t:70,bob:2});relics+=4}}
function discover(l){if(l.found)return;l.found=true;discovered.add(l.id);const def=landmarkDefs[l.type];relics++;sound('discover');puff(l.x,l.y,'#fff0a6',24,155);landmarkReward(l);toast('◇ '+def.name+' · '+def.text);hud();updateCompass()}
function updateRegions(){const rx=Math.floor(player.x/640),ry=Math.floor(player.y/640),key=rx+','+ry;if(key!==lastRegionKey){lastRegionKey=key;regionCount++;refreshLandmarks();regionBanner=regionName(player.x,player.y);regionBannerTimer=2.8;toast('🗺 '+regionBanner+' · danger '+(dangerAt(player.x,player.y)+1));updateCompass();if(regionCount%2===0&&wanderers.length<MAX_WANDERERS)spawnWanderer()}}
function updatePlayer(dt){let mx=player.vx,my=player.vy;if(keys.KeyW||keys.ArrowUp)my-=1;if(keys.KeyS||keys.ArrowDown)my+=1;if(keys.KeyA||keys.ArrowLeft)mx-=1;if(keys.KeyD||keys.ArrowRight)mx+=1;const d=Math.hypot(mx,my);if(d>1){mx/=d;my/=d}if(Math.hypot(mx,my)>.07)player.dir=Math.atan2(my,mx);moveBody(player,mx*164*dt,my*164*dt,PLAYER_R)}
function aiMove(q,def,dt,dx,dy,d){if(d>370&&!def.boss)return;let vx=0,vy=0;if(def.ai==='zig'||def.ai==='pack'){const wig=Math.sin(run*(def.ai==='pack'?5:4)+q.seed)*(def.ai==='pack'?.48:.78);vx=dx/d*Math.cos(wig)-dy/d*Math.sin(wig);vy=dy/d*Math.cos(wig)+dx/d*Math.sin(wig);moveBody(q,vx*def.spd*dt,vy*def.spd*dt,def.r*.68)}else if(def.ai==='strafe'){const s=Math.sin(run*1.7+q.seed)>0?1:-1;vx=dx/d*.45-dy/d*.78*s;vy=dy/d*.45+dx/d*.78*s;moveBody(q,vx*def.spd*dt,vy*def.spd*dt,def.r*.68)}else if(def.ai==='orbit'){const target=d>155?1:-.25;vx=dx/d*target-dy/d*.74;vy=dy/d*target+dx/d*.74;moveBody(q,vx*def.spd*dt,vy*def.spd*dt,def.r*.68)}else if(def.ai==='charge'&&d<215){if(q.charge<=0){q.charge=1.05;q.chargeDir=Math.atan2(dy,dx);q.telegraph=.55}const charging=q.charge<.47,spd=charging?def.spd*2.7:def.spd*.13;moveBody(q,Math.cos(q.chargeDir)*spd*dt,Math.sin(q.chargeDir)*spd*dt,def.r*.68)}else if(def.ai==='hop'){q.hop+=dt;const hop=Math.sin(q.hop*5)>-.15?1:.08;moveBody(q,dx/d*def.spd*hop*dt,dy/d*def.spd*hop*dt,def.r*.68)}else if(def.ai==='phase'){moveBody(q,dx/d*def.spd*dt,dy/d*def.spd*dt,def.r*.57)}else{moveBody(q,dx/d*def.spd*dt,dy/d*def.spd*dt,def.r*.68)}}
function updateMobs(dt){for(let i=mobs.length-1;i>=0;i--){const q=mobs[i],def=mobDefs[q.type];q.hit=Math.max(0,q.hit-dt);q.contact=Math.max(0,q.contact-dt);q.charge=Math.max(0,q.charge-dt);q.telegraph=Math.max(0,q.telegraph-dt);let dx=player.x-q.x,dy=player.y-q.y,d=Math.hypot(dx,dy)||1;if(d>980&&!def.boss){mobs.splice(i,1);continue}aiMove(q,def,dt,dx,dy,d);for(let j=i-1;j>=0;j--){const o=mobs[j],sx=q.x-o.x,sy=q.y-o.y,sd=Math.hypot(sx,sy)||1,min=(def.r+mobDefs[o.type].r)*.58;if(sd<min){const push=(min-sd)*.16;moveBody(q,sx/sd*push,sy/sd*push,def.r*.65)}}const hitD=PLAYER_R+def.r*.64;if(d<hitD&&q.contact<=0){q.contact=1.06;hurt(def.dmg*(q.elite?1.2:1),q)}}}
function updateWanderers(dt){for(let i=wanderers.length-1;i>=0;i--){const q=wanderers[i];q.hit=Math.max(0,q.hit-dt);q.contact=Math.max(0,q.contact-dt);q.think-=dt;const dx=player.x-q.x,dy=player.y-q.y,d=Math.hypot(dx,dy)||1;if(d>1100){wanderers.splice(i,1);if(hostileTarget===q)hostileTarget=null;continue}if(q.hostile){q.dir=Math.atan2(dy,dx);const desired=q.weapon.type==='ranged'?190:55,move=d>desired?1:d<desired*.7?-0.5:0;moveBody(q,dx/d*72*move*dt,dy/d*72*move*dt,10);if(d<q.weapon.range&&lineClear(q.x,q.y,player.x,player.y)&&q.contact<=0){q.contact=q.weapon.cd+0.35;hurt((6+dangerAt(q.x,q.y)*1.8)*q.weapon.power*.72,q)}}else if(q.think<=0){q.think=1.2+Math.random()*2.2;q.dir+=(-1+Math.random()*2)*1.6}if(!q.hostile)moveBody(q,Math.cos(q.dir)*24*dt,Math.sin(q.dir)*24*dt,10)}}
function updateShots(dt){for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;s.t-=dt;if(blockedCircle(s.x,s.y,4)){puff(s.x,s.y,'#fff1b0',4,55);shots.splice(i,1);continue}let hit=null;for(const q of mobs)if(Math.hypot(q.x-s.x,q.y-s.y)<mobDefs[q.type].r*.7+5){hit=q;break}if(hit){damageMob(hit,s.dmg,s.kb);shots.splice(i,1);continue}for(const q of wanderers)if(q.hostile&&Math.hypot(q.x-s.x,q.y-s.y)<15){damageWanderer(q,s.dmg,s.kb);shots.splice(i,1);hit=q;break}if(hit)continue;if(s.t<=0)shots.splice(i,1)}}
function updateDrops(dt){for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.t-=dt;if(Math.hypot(d.x-player.x,d.y-player.y)<27){if(d.type==='food'){hp=Math.min(maxHp,hp+Math.max(13,maxHp*.3));toast('Strawberry · health restored');sound('loot')}else equipMaybe(d.weapon);drops.splice(i,1);hud();continue}if(d.t<=0&&!d.spawnGift)drops.splice(i,1)}}
function spawnWorldEvent(){const tier=dangerAt(player.x,player.y);worldEventTimer=42+Math.random()*38;if(tier<1)return;const roll=Math.random();if(roll<.35){const pt=safeSpawnAround(player.x,player.y,220,420);drops.push({x:pt.x,y:pt.y,type:'weapon',weapon:rollWeapon(1.5+tier*.35),t:28,bob:1});toast('☄ A star fragment just landed nearby');sound('discover')}else if(roll<.68){const count=2+tier;for(let i=0;i<count;i++)spawnMob(tier>=4?'voidling':tier>=3?'golem':'wolf',true);toast('⚠ A hunting pack has found your trail')}else{hp=Math.min(maxHp,hp+8);toast('✦ A warm wind passes through the region')}}
function chooseBoss(){const tier=dangerAt(player.x,player.y);if(tier>=4&&Math.random()<.18)return'worldEater';if(tier>=4)return Math.random()<.5?'magmaToad':'frostStag';if(tier>=3)return'wraithQueen';return'king'}
function update(dt){run+=dt;attackCd=Math.max(0,attackCd-dt);invuln=Math.max(0,invuln-dt);spawnShield=Math.max(0,spawnShield-dt);regenDelay=Math.max(0,regenDelay-dt);screenShake=Math.max(0,screenShake-30*dt);bossTimer-=dt;worldEventTimer-=dt;regionBannerTimer=Math.max(0,regionBannerTimer-dt);updatePlayer(dt);updateMobs(dt);updateWanderers(dt);updateShots(dt);updateDrops(dt);for(const p of particles){p.x+=(p.vx||0)*dt;p.y+=(p.vy||0)*dt;p.t-=dt}particles=particles.filter(p=>p.t>0);if(autoAttack)autoBonk();if(regenDelay<=0&&hp<maxHp)hp=Math.min(maxHp,hp+(hp<maxHp*.3?3.3:2.0)*dt);const cap=8+Math.min(18,Math.floor(run/42)+dangerAt(player.x,player.y)*2);if(mobs.length<cap&&Math.random()<dt*(.72+dangerAt(player.x,player.y)*.09))spawnMob();if(wanderers.length<2&&Math.random()<dt*.018)spawnWanderer();if(bossTimer<=0&&!mobs.some(m=>mobDefs[m.type].boss)){const boss=chooseBoss();spawnMob(boss,true);bossTimer=999;toast('♛ '+bossDisplayName(boss)+' is roaming this region…');sound('boss')}if(worldEventTimer<=0)spawnWorldEvent();for(const l of landmarks)if(!l.found&&Math.hypot(l.x-player.x,l.y-player.y)<44)discover(l);updateRegions();if(Math.floor(run*2.5)%3===0)updateCompass();if(tutorialStep===0&&run>2){tutorialStep=1;toast('🕹 Drag on the left side to move')}else if(tutorialStep===1&&run>7){tutorialStep=2;toast('⚔ Auto-Bonk attacks nearby monsters')}else if(tutorialStep===2&&run>13){tutorialStep=3;toast('Tap a Wanderer to challenge them to PvP')}else if(tutorialStep===3&&run>20){tutorialStep=4;toast('◇ Follow the compass · farther regions are deadlier')}hud()}
