'use strict';
/* v10 — the five highest-value gameplay systems: choices, weapon identity, encounters, risk/reward, run goals. */
(function(){
const V={version:10,choices:[],choicePending:false,affixes:new WeakMap(),contracts:[],contract:null,streak:0,streakT:0,encounterT:14,encounters:0,shards:0};window.GAMEPLAY_V10=V;
const affixPool=[
 ['Vampiric','Kills restore health',w=>w.v10Life=.7],['Volatile','Hits can explode',w=>w.v10Blast=.18],['Swift','Faster attacks, lower durability',w=>{w.v10Speed=.86;w.v10Fragile=.82}],['Sturdy','Much greater durability',w=>w.v10Durable=1.55],['Hunter','Extra damage to elites and bosses',w=>w.v10Boss=1.32],['Frenzied','Damage rises during rampages',w=>w.v10Frenzy=1.25],['Glacial','Chance to slow enemies',w=>w.v10Slow=.24],['Ember','Chance to burn enemies',w=>w.v10Burn=.22],['Echoing','Chance to repeat a strike',w=>w.v10Echo=.16],['Lucky','Improves drops while equipped',w=>w.v10Luck=.22],['Executioner','Crushes wounded enemies',w=>w.v10Execute=1.45],['Guardian','Kills briefly shield you',w=>w.v10Guard=.45]
];
function affixWeapon(w){if(!w||V.affixes.has(w))return;const count=w.rarity>=5?2:w.rarity>=3?1:0,list=[];for(let i=0;i<count;i++){const a=affixPool[(Math.abs(hash(w.name.length*31+i,w.rarity,910+i))*affixPool.length)|0];if(!list.some(x=>x[0]===a[0])){list.push(a);a[2](w)}}V.affixes.set(w,list);if(list.length)w.v10Affix=list.map(a=>a[0]).join(' + ')}
for(const w of weapons)affixWeapon(w);
const oldRoll=rollWeapon;rollWeapon=function(b=0){const w=oldRoll(b);affixWeapon(w);return w};
/* Level-ups now create decisions instead of being an automatic stat tick. */
const perks=[
 ['Heart','+12 max HP and heal 12',()=>{maxHp+=12;hp=Math.min(maxHp,hp+12)}],['Haste','+7% movement speed this run',()=>player.v10Speed=(player.v10Speed||1)*1.07],['Fury','Start fights with extra momentum',()=>{if(window.COMBAT_V8)COMBAT_V8.momentum=Math.min(100,COMBAT_V8.momentum+28)}],['Repair','Restore current weapon durability',()=>{if(window.DEEP_V9){DEEP_V9.weaponHits=DEEP_V9.weaponMax}}],['Fortune','Improve future rare drops',()=>V.shards+=2],['Berserk','+12% weapon damage, -6 max HP',()=>{player.v10Damage=(player.v10Damage||1)*1.12;maxHp=Math.max(20,maxHp-6);hp=Math.min(hp,maxHp)}],['Dashcraft','Dash cooldown improves',()=>player.v10Dash=(player.v10Dash||1)*.86],['Scavenger','Weapons last 20% longer',()=>player.v10Dur=(player.v10Dur||1)*1.2],['Regen','Faster recovery out of combat',()=>player.v10Regen=(player.v10Regen||0)+1.1]
];
function offerPerks(){if(V.choicePending)return;V.choicePending=true;V.choices=[];while(V.choices.length<3){const p=perks[(Math.random()*perks.length)|0];if(!V.choices.includes(p))V.choices.push(p)}const names=V.choices.map((p,i)=>(i+1)+': '+p[0]).join(' · ');toast('★ LEVEL CHOICE · '+names+' · tap screen thirds');}
const oldGain=gainXp;gainXp=function(n){const before=level;oldGain(n);if(level>before)offerPerks()};
function choosePerk(x){if(!V.choicePending)return false;const i=Math.max(0,Math.min(2,Math.floor(x/(w/3)))),p=V.choices[i];p[2]();V.choicePending=false;toast('★ '+p[0]+' · '+p[1]);sound('level');hud();return true}
addEventListener('pointerdown',e=>{if(V.choicePending){e.preventDefault();e.stopImmediatePropagation();choosePerk(e.clientX)}},true);
/* Weapon affixes alter moment-to-moment combat, not merely numbers. */
const oldDamage=damageMob;damageMob=function(q,dmg,kb){affixWeapon(weapon);let d=dmg*(player.v10Damage||1);if(weapon.v10Boss&&(q.elite||mobDefs[q.type].boss))d*=weapon.v10Boss;if(weapon.v10Execute&&q.hp/q.max<.28)d*=weapon.v10Execute;if(weapon.v10Frenzy&&window.COMBAT_V8&&COMBAT_V8.killChain>=3)d*=weapon.v10Frenzy;const alive=q.hp>0;oldDamage(q,d,kb);if(alive&&q.hp>0&&weapon.v10Blast&&Math.random()<weapon.v10Blast){for(const o of mobs.slice())if(o!==q&&Math.hypot(o.x-q.x,o.y-q.y)<75)oldDamage(o,d*.28,16);puff(q.x,q.y,'#ffd58a',14,135)}if(q.hp>0&&weapon.v10Slow&&Math.random()<weapon.v10Slow){q.deepSpeed=Math.min(q.deepSpeed||1,.68);setTimeout(()=>{if(q)q.deepSpeed=1},1200)}if(q.hp>0&&weapon.v10Burn&&Math.random()<weapon.v10Burn){let ticks=3;const id=setInterval(()=>{if(--ticks<0||q.hp<=0){clearInterval(id);return}oldDamage(q,Math.max(1,d*.08),4)},330)}};
const oldFire=fireAttack;fireAttack=function(t){const cd=weapon.cd;affixWeapon(weapon);if(weapon.v10Speed)weapon.cd=cd*weapon.v10Speed;oldFire(t);weapon.cd=cd;if(t&&weapon.v10Echo&&Math.random()<weapon.v10Echo)setTimeout(()=>{if(t.hp>0)oldDamage(t,(5+level)*weapon.power*.5,weapon.kb*.35)},85)};
const oldKill=killMob;killMob=function(q){const wasBoss=mobDefs[q.type].boss,elite=q.elite;oldKill(q);V.streak++;V.streakT=5;if(weapon.v10Life)hp=Math.min(maxHp,hp+weapon.v10Life*(wasBoss?8:elite?4:1));if(weapon.v10Guard&&(wasBoss||elite)){invuln=Math.max(invuln,weapon.v10Guard)}if(V.contract){V.contract.progress++;if(V.contract.progress>=V.contract.goal)completeContract()}};
/* Micro-objectives give exploration a reason beyond wandering. */
const contractTypes=[['Cull','Defeat creatures',12],['Elite Hunt','Defeat dangerous prey',8],['Rampage','Keep the bonks coming',15],['Frontier','Survive the frontier',18]];
function newContract(){const c=contractTypes[(Math.random()*contractTypes.length)|0];V.contract={name:c[0],text:c[1],goal:c[2]+dangerAt(player.x,player.y)*2,progress:0};toast('◇ CONTRACT · '+V.contract.name+' · '+V.contract.text+' '+V.contract.goal)}
function completeContract(){V.shards++;const c=V.contract;V.contract=null;hp=Math.min(maxHp,hp+14);drops.push({x:player.x+30,y:player.y+18,type:'weapon',weapon:rollWeapon(2+V.shards*.25),t:55,bob:2});toast('✓ '+c.name+' COMPLETE · reward cache');sound('discover');setTimeout(newContract,7000)}
/* Curated encounter beats interrupt procedural sameness. */
const encounterNames=['Elite Duel','Wisp Crossfire','Stampede','Treasure Guardian','Ambush Ring','Boss Herald','Crystal Nest','Rift Pack','Moon Hunt','Relic Siege'];
function encounter(){if(!started||dead)return;V.encounters++;const tier=dangerAt(player.x,player.y),kind=V.encounters%encounterNames.length,name=encounterNames[kind];toast('⚠ ENCOUNTER · '+name);sound('boss');const count=kind===0?1:kind===4?7:3+Math.min(5,tier);for(let i=0;i<count;i++)spawnMob(undefined,kind===0||kind===3||tier>=3&&i===0);if(kind===3||kind===6)drops.push({x:player.x+(Math.random()-.5)*180,y:player.y+(Math.random()-.5)*180,type:'weapon',weapon:rollWeapon(1.8+tier*.25),t:50,bob:3});V.encounterT=32+Math.random()*28}
const oldPlayer=updatePlayer;updatePlayer=function(dt){oldPlayer(dt);if(player.v10Speed&&player.v10Speed!==1){/* compensate after base movement with a small directional boost */const m=Math.hypot(player.vx,player.vy);if(m>.1)moveBody(player,player.vx*164*(player.v10Speed-1)*dt,player.vy*164*(player.v10Speed-1)*dt,PLAYER_R)}};
const oldUpdate=update;update=function(dt){oldUpdate(dt);V.streakT-=dt;if(V.streakT<=0)V.streak=0;V.encounterT-=dt;if(V.encounterT<=0)encounter();if(!V.contract&&run>9)newContract()};
const oldHud=hud;hud=function(){oldHud();const el=document.getElementById('wp');if(el&&weapon.v10Affix)el.textContent+=' · '+weapon.v10Affix;const co=document.getElementById('compass');if(co&&V.contract)co.dataset.contract=V.contract.name+' '+V.contract.progress+'/'+V.contract.goal};
window.__TWBB_V10_TEST__={get:()=>({version:10,perks:perks.length,affixes:affixPool.length,encounters:encounterNames.length,contract:V.contract&&V.contract.name,streak:V.streak})};
})();