// v13 tap-to-steer persistent auto-run + PvP targeting.
const padzone=document.getElementById('padzone'),pad=document.getElementById('pad'),nub=document.getElementById('nub');
let lastTap=0,lastTapAngle=0;
if(padzone){padzone.style.display='none';padzone.style.pointerEvents='none'}
function directionFromTap(x,y){return Math.atan2(y-h/2,x-w/2)}
function challengeAtScreen(sx,sy){if(!started)return false;const wx=player.x+(sx-w/2),wy=player.y+(sy-h/2);let best=null,bd=38;for(const q of wanderers){const d=Math.hypot(q.x-wx,q.y-wy);if(d<bd){bd=d;best=q}}if(!best)return false;if(!best.hostile){best.hostile=true;hostileTarget=best;spawnShield=0;toast('⚔ '+best.name+' is now HOSTILE');sound('hostile');puff(best.x,best.y,'#ff7892',14,120)}else{hostileTarget=best;toast('Targeting '+best.name)}return true}
function steerTap(e){if(!started)return;if(challengeAtScreen(e.clientX,e.clientY))return;const a=directionFromTap(e.clientX,e.clientY),now=performance.now();if(window.EXPANSION_V13)EXPANSION_V13.setHeading(a);else{player.dir=a;player.vx=Math.cos(a);player.vy=Math.sin(a)}if(now-lastTap<310&&Math.abs(Math.atan2(Math.sin(a-lastTapAngle),Math.cos(a-lastTapAngle)))<.55&&window.COMBAT)COMBAT.dash();lastTap=now;lastTapAngle=a;e.preventDefault()}
c.addEventListener('pointerdown',steerTap);
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if((e.code==='ShiftLeft'||e.code==='ShiftRight')&&window.COMBAT)COMBAT.dash()});addEventListener('keyup',e=>{keys[e.code]=false});
function startGame(){reset();started=true;dead=false;if(window.COMBAT){COMBAT.combo=0;COMBAT.fury=0;COMBAT.dashCd=0}if(window.EXPANSION_V13)EXPANSION_V13.setHeading(0);document.getElementById('start').classList.add('hide');document.getElementById('death').classList.add('hide');toast('Tap a direction once · you keep running · Auto-Bonk attacks');try{if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume()}catch(_){}}
document.getElementById('play').addEventListener('click',startGame);document.getElementById('again').addEventListener('click',startGame);document.getElementById('sound').addEventListener('click',function(){audioOn=!audioOn;this.textContent=audioOn?'♪':'×';if(audioOn)sound('loot')});
function boot(){window.__TWBB_TEST__={blockedCircle,moveBody,terrainAt,landmarkForCell,dangerAt,biomeAtWorld,startGame,challengeAtScreen,getState:()=>({started,dead,hp,level,kills,x:player.x,y:player.y,mobs:mobs.length,wanderers:wanderers.length,landmarks:landmarks.length,danger:dangerAt(player.x,player.y),weapon:weapon.name,env:window.ENV?ENV.version:0,combat:window.COMBAT?{combo:COMBAT.combo,fury:COMBAT.fury}:null,combat8:window.COMBAT_V8?COMBAT_V8.version:0,biomes8:window.BIOMES_V8?BIOMES_V8.version:0,ai:window.AI_DIRECTOR?AI_DIRECTOR.version:0,rebuild:window.REBUILD_V12?REBUILD_V12.version:0,expansion:window.EXPANSION_V13?EXPANSION_V13.version:0,balance:window.__TWBB_V12_BALANCE_TEST__?true:false,art:window.AI_SPRITES?AI_SPRITES.ready:false})};reset();if(window.EXPANSION_V13)EXPANSION_V13.setHeading(0);requestAnimationFrame(loop)}
function loadEnvironment(){const immersion=document.createElement('script');immersion.src='environment.js?v=13';immersion.onload=boot;immersion.onerror=()=>boot();document.head.appendChild(immersion)}
const balance=document.createElement('script');balance.src='v12-balance-fix.js?v=13';balance.onload=loadEnvironment;balance.onerror=loadEnvironment;document.head.appendChild(balance);