// Mobile-first controls + PvP challenge targeting + v7 combat controls
const padzone=document.getElementById('padzone'),pad=document.getElementById('pad'),nub=document.getElementById('nub');let pid=null,origin={x:0,y:0},moved=0,lastRightTap=0;
function movePointer(e){if(e.pointerId!==pid||!started)return;const dx=e.clientX-origin.x,dy=e.clientY-origin.y,d=Math.hypot(dx,dy)||1,s=Math.min(48,d);moved=Math.max(moved,d);player.vx=dx/d*s/48;player.vy=dy/d*s/48;nub.style.left=(31+dx/d*s)+'px';nub.style.top=(31+dy/d*s)+'px';if(s>5)player.dir=Math.atan2(dy,dx)}
function challengeAtScreen(sx,sy){if(!started)return false;const wx=player.x+(sx-w/2),wy=player.y+(sy-h/2);let best=null,bd=34;for(const q of wanderers){const d=Math.hypot(q.x-wx,q.y-wy);if(d<bd){bd=d;best=q}}if(!best)return false;if(!best.hostile){best.hostile=true;hostileTarget=best;spawnShield=0;toast('⚔ '+best.name+' is now HOSTILE');sound('hostile');puff(best.x,best.y,'#ff7892',14,120)}else{hostileTarget=best;toast('Targeting '+best.name)}return true}
padzone.addEventListener('pointerdown',e=>{if(!started)return;pid=e.pointerId;origin={x:e.clientX,y:e.clientY};moved=0;pad.style.display='block';pad.style.left=e.clientX+'px';pad.style.top=e.clientY+'px';try{padzone.setPointerCapture(pid)}catch(_){}movePointer(e);e.preventDefault()});padzone.addEventListener('pointermove',movePointer);function endPointer(e){if(e.pointerId!==pid)return;const wasTap=moved<9,x=e.clientX,y=e.clientY;pid=null;player.vx=player.vy=0;pad.style.display='none';nub.style.left='31px';nub.style.top='31px';if(wasTap)challengeAtScreen(x,y)}padzone.addEventListener('pointerup',endPointer);padzone.addEventListener('pointercancel',endPointer);
c.addEventListener('pointerup',e=>{if(e.clientX<=w*.48||!started)return;const now=performance.now();if(now-lastRightTap<310&&window.COMBAT){COMBAT.dash();lastRightTap=0;return}lastRightTap=now;challengeAtScreen(e.clientX,e.clientY)});
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();keys[e.code]=true});addEventListener('keyup',e=>{keys[e.code]=false});
function startGame(){reset();started=true;dead=false;if(window.COMBAT){COMBAT.combo=0;COMBAT.fury=0;COMBAT.dashCd=0}document.getElementById('start').classList.add('hide');document.getElementById('death').classList.add('hide');toast('⚔ Auto-Bonk active · read enemy tells · double-tap right to dash');try{if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume()}catch(_){}}
document.getElementById('play').addEventListener('click',startGame);document.getElementById('again').addEventListener('click',startGame);document.getElementById('sound').addEventListener('click',function(){audioOn=!audioOn;this.textContent=audioOn?'♪':'×';if(audioOn)sound('loot')});
function boot(){window.__TWBB_TEST__={blockedCircle,moveBody,terrainAt,landmarkForCell,dangerAt,biomeAtWorld,startGame,challengeAtScreen,getState:()=>({started,dead,hp,level,kills,x:player.x,y:player.y,mobs:mobs.length,wanderers:wanderers.length,landmarks:landmarks.length,danger:dangerAt(player.x,player.y),weapon:weapon.name,env:window.ENV?ENV.version:0,combat:window.COMBAT?{combo:COMBAT.combo,fury:COMBAT.fury}:null,ai:window.AI_DIRECTOR?AI_DIRECTOR.version:0,art:window.AI_SPRITES?AI_SPRITES.ready:false})};reset();requestAnimationFrame(loop)}
const immersion=document.createElement('script');immersion.src='environment.js?v=7';immersion.onload=boot;immersion.onerror=()=>boot();document.head.appendChild(immersion);