// v12 edge-press movement + PvP targeting. No virtual joystick.
const padzone=document.getElementById('padzone'),pad=document.getElementById('pad'),nub=document.getElementById('nub');
let pid=null,moved=0,lastEdgeTap=0,edgeStart=0,edgeX=0,edgeY=0;
if(padzone){padzone.style.display='none';padzone.style.pointerEvents='none'}
function edgeVector(x,y){const cx=w/2,cy=h/2,dx=x-cx,dy=y-cy,d=Math.hypot(dx,dy)||1;return{x:dx/d,y:dy/d}}
function isEdge(x,y){const band=Math.min(118,Math.min(w,h)*.22);return x<band||x>w-band||y<band||y>h-band}
function challengeAtScreen(sx,sy){if(!started)return false;const wx=player.x+(sx-w/2),wy=player.y+(sy-h/2);let best=null,bd=38;for(const q of wanderers){const d=Math.hypot(q.x-wx,q.y-wy);if(d<bd){bd=d;best=q}}if(!best)return false;if(!best.hostile){best.hostile=true;hostileTarget=best;spawnShield=0;toast('⚔ '+best.name+' is now HOSTILE');sound('hostile');puff(best.x,best.y,'#ff7892',14,120)}else{hostileTarget=best;toast('Targeting '+best.name)}return true}
function beginEdge(e){if(!started||pid!==null)return;if(!isEdge(e.clientX,e.clientY)){challengeAtScreen(e.clientX,e.clientY);return}pid=e.pointerId;edgeStart=performance.now();edgeX=e.clientX;edgeY=e.clientY;moved=0;const v=edgeVector(edgeX,edgeY);player.vx=v.x;player.vy=v.y;player.dir=Math.atan2(v.y,v.x);try{c.setPointerCapture(pid)}catch(_){}e.preventDefault()}
function moveEdge(e){if(e.pointerId!==pid||!started)return;edgeX=e.clientX;edgeY=e.clientY;const v=edgeVector(edgeX,edgeY);player.vx=v.x;player.vy=v.y;player.dir=Math.atan2(v.y,v.x);moved++}
function endEdge(e){if(e.pointerId!==pid)return;const held=performance.now()-edgeStart;pid=null;player.vx=player.vy=0;if(held<220&&moved<3){const now=performance.now();if(now-lastEdgeTap<310&&window.COMBAT){COMBAT.dash();lastEdgeTap=0}else lastEdgeTap=now}}
c.addEventListener('pointerdown',beginEdge);c.addEventListener('pointermove',moveEdge);c.addEventListener('pointerup',endEdge);c.addEventListener('pointercancel',endEdge);
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight'].includes(e.code))e.preventDefault();keys[e.code]=true});addEventListener('keyup',e=>{keys[e.code]=false});
function startGame(){reset();started=true;dead=false;if(window.COMBAT){COMBAT.combo=0;COMBAT.fury=0;COMBAT.dashCd=0}document.getElementById('start').classList.add('hide');document.getElementById('death').classList.add('hide');toast('Hold an edge to move · Auto-Bonk attacks · every biome hunts differently');try{if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume()}catch(_){}}
document.getElementById('play').addEventListener('click',startGame);document.getElementById('again').addEventListener('click',startGame);document.getElementById('sound').addEventListener('click',function(){audioOn=!audioOn;this.textContent=audioOn?'♪':'×';if(audioOn)sound('loot')});
function boot(){window.__TWBB_TEST__={blockedCircle,moveBody,terrainAt,landmarkForCell,dangerAt,biomeAtWorld,startGame,challengeAtScreen,getState:()=>({started,dead,hp,level,kills,x:player.x,y:player.y,mobs:mobs.length,wanderers:wanderers.length,landmarks:landmarks.length,danger:dangerAt(player.x,player.y),weapon:weapon.name,env:window.ENV?ENV.version:0,combat:window.COMBAT?{combo:COMBAT.combo,fury:COMBAT.fury}:null,combat8:window.COMBAT_V8?COMBAT_V8.version:0,biomes8:window.BIOMES_V8?BIOMES_V8.version:0,ai:window.AI_DIRECTOR?AI_DIRECTOR.version:0,rebuild:window.REBUILD_V12?REBUILD_V12.version:0,balance:window.__TWBB_V12_BALANCE_TEST__?true:false,art:window.AI_SPRITES?AI_SPRITES.ready:false})};reset();requestAnimationFrame(loop)}
function loadEnvironment(){const immersion=document.createElement('script');immersion.src='environment.js?v=12';immersion.onload=boot;immersion.onerror=()=>boot();document.head.appendChild(immersion)}
const balance=document.createElement('script');balance.src='v12-balance-fix.js?v=12';balance.onload=loadEnvironment;balance.onerror=loadEnvironment;document.head.appendChild(balance);