'use strict';
/* v7 SMART ENEMY COMBAT — stateful roles, prediction, spacing, telegraphs and boss phases. */
(function(){
const A={version:7,enemyShots:[],decisions:0};window.SMART_AI=A;
const TAU=Math.PI*2;
function brain(q){return q.brain||(q.brain={think:Math.random()*.5,attack:Math.random()*.5,strafe:Math.random()<.5?-1:1,burst:0,phase:1,retreat:0,skill:1+Math.random()*2,windup:0,aim:0})}
function role(type,d){if(d.boss)return'boss';if(['wisp','moth','ghost','frostling','starbeast'].includes(type))return'ranged';if(['wolf','riftHound','bat','bee'].includes(type))return'flanker';if(['boar','mimic','golem','frostStag'].includes(type))return'charger';if(['crab','crystalbeetle','shroomknight'].includes(type))return'duelist';return'melee'}
function pred(q,lead=.35){const vx=(player.vx||0)*164,vy=(player.vy||0)*164;return{x:player.x+vx*lead,y:player.y+vy*lead,dx:player.x+vx*lead-q.x,dy:player.y+vy*lead-q.y}}
function slide(q,vx,vy,spd,dt,r){const d=Math.hypot(vx,vy)||1;moveBody(q,vx/d*spd*dt,vy/d*spd*dt,r)}
function shoot(q,def,speed=220,spread=0,count=1){const p=pred(q,.32),base=Math.atan2(p.dy,p.dx);for(let i=0;i<count;i++){const a=base+(i-(count-1)/2)*spread;A.enemyShots.push({x:q.x,y:q.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,t:2.5,r:def.boss?6:4,dmg:def.dmg*(def.boss?.72:.58),col:def.boss?'#d9a6ff':'#ff9cb7'})}}
function radial(q,def,n=8,speed=180){for(let i=0;i<n;i++){const a=i/n*TAU+run*.35;A.enemyShots.push({x:q.x,y:q.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,t:2.2,r:5,dmg:def.dmg*.5,col:'#bca7ff'})}}
function bossMove(q,def,dt,dx,dy,d,b){const frac=q.hp/q.max;b.phase=frac<.34?3:frac<.68?2:1;if(b.windup>0){b.windup-=dt;q.telegraph=Math.max(q.telegraph,b.windup);return}b.skill-=dt;if(b.skill<=0){b.skill=Math.max(.85,2.7-b.phase*.45)+Math.random()*.7;const roll=Math.random();if(roll<.38){b.windup=.55;q.telegraph=.55;b.aim=Math.atan2(dy,dx);b.burst=.42}else if(roll<.72){q.telegraph=.45;shoot(q,def,190+b.phase*25,.18,1+b.phase)}else{q.telegraph=.55;radial(q,def,5+b.phase*2,150+b.phase*18)}}if(b.burst>0){b.burst-=dt;slide(q,Math.cos(b.aim),Math.sin(b.aim),def.spd*(3+b.phase*.35),dt,def.r*.67);return}const side=b.strafe,desired=120+b.phase*18;if(d>desired+35)slide(q,dx,dy,def.spd*(1+.12*b.phase),dt,def.r*.67);else slide(q,-dy*side,dx*side,def.spd*.78,dt,def.r*.67)}
function smartMove(q,def,dt,dx,dy,d){const b=brain(q),r=def.r*.67,kind=role(q.type,def);b.think-=dt;b.attack-=dt;b.retreat=Math.max(0,b.retreat-dt);if(def.boss)return bossMove(q,def,dt,dx,dy,d,b);if(b.think<=0){b.think=.35+Math.random()*.65;A.decisions++;if(Math.random()<.32)b.strafe*=-1;if(q.hp/q.max<.24&&!q.elite&&Math.random()<.48)b.retreat=.8+Math.random()*.8}if(b.retreat>0){slide(q,-dx,-dy,def.spd*1.2,dt,r);return}const p=pred(q,kind==='charger'?.18:.28),px=p.dx,py=p.dy;if(kind==='ranged'){if(d<115)slide(q,-dx,-dy,def.spd*1.15,dt,r);else if(d>235)slide(q,px,py,def.spd*.75,dt,r);else slide(q,-dy*b.strafe,dx*b.strafe,def.spd*.82,dt,r);if(b.attack<=0&&d<330&&lineClear(q.x,q.y,player.x,player.y)){b.attack=1.5+Math.random()*.75;q.telegraph=.38;shoot(q,def,230+dangerAt(q.x,q.y)*8,.12,1)}return}if(kind==='flanker'){const side=b.strafe,ox=dx*.5-dy*side*.9,oy=dy*.5+dx*side*.9;if(d>95)slide(q,ox,oy,def.spd*1.1,dt,r);else slide(q,-dy*side,dx*side,def.spd*.95,dt,r);return}if(kind==='charger'){if(b.burst>0){b.burst-=dt;slide(q,Math.cos(b.aim),Math.sin(b.aim),def.spd*3.1,dt,r);return}if(b.attack<=0&&d<245){b.attack=2.1+Math.random()*.6;b.windup=.52;b.aim=Math.atan2(py,px);q.telegraph=.52}if(b.windup>0){b.windup-=dt;if(b.windup<=0)b.burst=.38;return}if(d>120)slide(q,px,py,def.spd*.62,dt,r);else slide(q,-dy*b.strafe,dx*b.strafe,def.spd*.45,dt,r);return}if(kind==='duelist'){const side=b.strafe;if(d>86)slide(q,dx-dy*side*.42,dy+dx*side*.42,def.spd,dt,r);else if(d<45)slide(q,-dx,-dy,def.spd*.75,dt,r);else slide(q,-dy*side,dx*side,def.spd*.7,dt,r);return}if(d>46)slide(q,px-dy*b.strafe*.15,py+dx*b.strafe*.15,def.spd,dt,r)}
aiMove=smartMove;
updateMobs=function(dt){for(let i=mobs.length-1;i>=0;i--){const q=mobs[i],def=mobDefs[q.type];if(!q||!def)continue;q.hit=Math.max(0,(q.hit||0)-dt);q.contact=Math.max(0,(q.contact||0)-dt);q.charge=Math.max(0,(q.charge||0)-dt);q.telegraph=Math.max(0,(q.telegraph||0)-dt);let dx=player.x-q.x,dy=player.y-q.y,d=Math.hypot(dx,dy)||1;if(d>1050&&!def.boss){mobs.splice(i,1);continue}smartMove(q,def,dt,dx,dy,d);for(let j=i-1;j>=0;j--){const o=mobs[j];if(!o||!mobDefs[o.type])continue;const sx=q.x-o.x,sy=q.y-o.y,sd=Math.hypot(sx,sy)||1,min=(def.r+mobDefs[o.type].r)*.64;if(sd<min){const push=(min-sd)*.2;moveBody(q,sx/sd*push,sy/sd*push,def.r*.64)}}dx=player.x-q.x;dy=player.y-q.y;d=Math.hypot(dx,dy)||1;const hitD=PLAYER_R+def.r*.62;if(d<hitD&&q.contact<=0&&q.telegraph<=.05){q.contact=.9+Math.random()*.28;hurt(def.dmg*(q.elite?1.18:1),q)}}for(let i=A.enemyShots.length-1;i>=0;i--){const s=A.enemyShots[i];s.t-=dt;const steps=Math.max(1,Math.ceil(Math.hypot(s.vx*dt,s.vy*dt)/7));let hit=false;for(let k=0;k<steps;k++){s.x+=s.vx*dt/steps;s.y+=s.vy*dt/steps;if(blockedCircle(s.x,s.y,s.r)){hit=true;break}if(Math.hypot(s.x-player.x,s.y-player.y)<PLAYER_R+s.r){hurt(s.dmg,s);hit=true;break}}if(hit||s.t<=0)A.enemyShots.splice(i,1)}};
A.roleFor=(t)=>role(t,mobDefs[t]);A.brain=brain;window.__TWBB_AI_TEST__={roleFor:A.roleFor,get:()=>({version:A.version,shots:A.enemyShots.length,decisions:A.decisions})};
})();