'use strict';
/* v7 AI-art sprite renderer. Uses a generated Tsum-inspired atlas with procedural animation. */
(function(){
const atlas=new Image();atlas.src='assets/tsum-atlas.png?v=7';const TILE=96;
const map={slime:1,pink:6,bee:4,frog:7,bat:10,boar:5,mushroom:3,ghost:11,crab:6,wisp:11,snowbun:2,skeleton:9,cactus:12,wolf:5,moth:4,mimic:3,crystalbeetle:8,emberling:4,frostling:10,golem:9,shroomknight:3,serpent:7,treant:12,voidling:11,starbeast:10,riftHound:5,king:1,wraithQueen:11,magmaToad:7,frostStag:10,worldEater:9};
function tile(i,x,y,size,flip=false,alpha=1){if(!atlas.complete)return false;ctx.save();ctx.globalAlpha=alpha;if(flip){ctx.translate(x*2,0);ctx.scale(-1,1)}ctx.drawImage(atlas,i*TILE,0,TILE,TILE,Math.round(x-size/2),Math.round(y-size*.58),size,size);ctx.restore();return true}
function shadow(x,y,r){ctx.save();ctx.globalAlpha=.18;ctx.fillStyle='#403654';ctx.beginPath();ctx.ellipse(x,y+8,r*.75,r*.28,0,0,Math.PI*2);ctx.fill();ctx.restore()}
const oldMob=drawMob;drawMob=function(q,sx,sy,t){if(!atlas.complete)return oldMob(q,sx,sy,t);const def=mobDefs[q.type],boss=!!def.boss,base=boss?Math.max(62,def.r*3.0):Math.max(34,def.r*2.45),speed=Math.hypot(player.x-q.x,player.y-q.y)<260?8:4,bob=Math.sin(t*speed+q.seed)*2.2,squash=q.hit>0?.84:1+Math.sin(t*speed+q.seed)*.025;shadow(sx,sy,def.r);ctx.save();ctx.translate(sx,sy+bob);ctx.scale(1/squash,squash);if(q.elite){ctx.shadowBlur=18;ctx.shadowColor='#d6a4ff'}tile(map[q.type]??1,0,0,base,(player.x-q.x)<0,q.hit>0?.72:1);ctx.restore();if(q.elite){ctx.strokeStyle='#d29cff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(sx,sy,def.r+8+Math.sin(t*5)*2,0,Math.PI*2);ctx.stroke()}if(q.telegraph>0){ctx.strokeStyle='#ff7892';ctx.lineWidth=3;ctx.beginPath();ctx.arc(sx,sy,def.r+12+(1-q.telegraph/.6)*10,0,Math.PI*2);ctx.stroke()}if(def.boss){ctx.fillStyle='#ffffffdd';ctx.fillRect(sx-35,sy-def.r-25,70,6);ctx.fillStyle='#ee789c';ctx.fillRect(sx-35,sy-def.r-25,70*Math.max(0,q.hp/(q.maxHp||q.hp)),6)}};
const oldPlayer=drawPlayer;drawPlayer=function(t){if(!atlas.complete)return oldPlayer(t);const moving=Math.hypot(player.vx,player.vy)>.08,bob=moving?Math.sin(t*11)*2:Math.sin(t*3)*1,flip=Math.cos(player.dir)<0;shadow(w/2,h/2,14);ctx.save();if(invuln>0&&Math.floor(t*18)%2===0)ctx.globalAlpha=.55;tile(0,w/2,h/2+bob,52,flip,1);ctx.restore();drawWeapon(w/2,h/2+bob,player.dir,weapon,1);if(spawnShield>0){ctx.strokeStyle='#fff8';ctx.lineWidth=2;ctx.beginPath();ctx.arc(w/2,h/2,27+Math.sin(t*4)*2,0,Math.PI*2);ctx.stroke()}};
window.TSUM_SPRITES={atlas,map};
})();