'use strict';
(() => {
const c=document.getElementById('g'),ctx=c.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;
let W=innerWidth,H=innerHeight,DPR=Math.min(2,devicePixelRatio||1),last=performance.now();
function resize(){W=innerWidth;H=innerHeight;c.width=W*DPR;c.height=H*DPR;c.style.width=W+'px';c.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize,{passive:true});resize();
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const hash=(x,y,s=0)=>{const n=Math.sin(x*127.1+y*311.7+s*74.7+731.927)*43758.5453;return n-Math.floor(n)};
const palettes=[
 {name:'Meadow',a:'#cfe9ad',b:'#b9dc98',accent:'#f5a9c7',haz:'#4f9e5e'}, {name:'Blossom Woods',a:'#edcddd',b:'#d9b6cf',accent:'#fff1a1',haz:'#9b6997'},
 {name:'Moon Fields',a:'#b9d7ca',b:'#9fc2b2',accent:'#c5b2f2',haz:'#687c9c'}, {name:'Misty Marsh',a:'#a5c4b3',b:'#8eab9a',accent:'#85d8de',haz:'#536f66'},
 {name:'Emberlands',a:'#e3aa91',b:'#cc8975',accent:'#ffd06f',haz:'#a44f41'}, {name:'Frostvale',a:'#dceef3',b:'#bcdbe5',accent:'#9dccf2',haz:'#6d9bb0'},
 {name:'Crystal Steppe',a:'#c5d2e8',b:'#a7b7d5',accent:'#a38be4',haz:'#6f68a7'}, {name:'Sunken Garden',a:'#b6d6bd',b:'#91bd9d',accent:'#f09fbe',haz:'#4f8b68'},
 {name:'Duskwild',a:'#96a49e',b:'#737f7a',accent:'#d395cf',haz:'#4d4d5f'}, {name:'Starfall Reach',a:'#8799bc',b:'#66779d',accent:'#ffd26b',haz:'#575f99'}
];
function biomeAt(x,y){const S=1450,gx=Math.floor(x/S),gy=Math.floor(y/S);let best=0,bd=1e30;for(let yy=gy-1;yy<=gy+1;yy++)for(let xx=gx-1;xx<=gx+1;xx++){const px=(xx+.18+hash(xx,yy,8)*.64)*S,py=(yy+.18+hash(xx,yy,9)*.64)*S,d=(x-px)**2+(y-py)**2;if(d<bd){bd=d;const tier=clamp(Math.floor(Math.hypot(px,py)/1550),0,4),pools=[[0,1],[0,1,2,3],[2,3,4,5,6],[4,5,6,7,8],[6,7,8,9]][tier];best=pools[Math.floor(hash(xx,yy,11)*pools.length)]}}return best}
function dangerAt(x,y){return clamp(Math.floor(Math.hypot(x,y)/1150),0,5)}
function obstacleAt(x,y){const cx=Math.floor(x/150),cy=Math.floor(y/150),r=hash(cx,cy,41);if(r<.60)return null;const b=biomeAt(cx*150,cy*150),ox=(cx+.2+hash(cx,cy,42)*.6)*150,oy=(cy+.2+hash(cx,cy,43)*.6)*150;const big=r>.94;return{x:ox,y:oy,r:big?34:22,b,kind:big?'big':'small'}}
function blocked(x,y,r=12){const cx=Math.floor(x/150),cy=Math.floor(y/150);for(let yy=cy-1;yy<=cy+1;yy++)for(let xx=cx-1;xx<=cx+1;xx++){const o=obstacleAt(xx*150,yy*150);if(o&&Math.hypot(x-o.x,y-o.y)<r+o.r)return true}return false}
function moveBody(o,dx,dy,r=12){const steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/7)),sx=dx/steps,sy=dy/steps;for(let i=0;i<steps;i++){if(!blocked(o.x+sx,o.y,r))o.x+=sx;if(!blocked(o.x,o.y+sy,r))o.y+=sy}}
const weaponFamilies={
 sword:{range:78,cd:.42,power:1,kind:'melee',label:'Sword',pattern:'arc'}, spear:{range:115,cd:.55,power:1.08,kind:'melee',label:'Spear',pattern:'line'},
 daggers:{range:62,cd:.24,power:.72,kind:'melee',label:'Daggers',pattern:'flurry'}, hammer:{range:86,cd:.78,power:1.62,kind:'melee',label:'Hammer',pattern:'blast'},
 bow:{range:330,cd:.55,power:.93,kind:'ranged',label:'Bow',pattern:'shot'}, wand:{range:285,cd:.48,power:1.02,kind:'ranged',label:'Wand',pattern:'orb'},
 chakram:{range:250,cd:.46,power:.92,kind:'ranged',label:'Chakram',pattern:'bounce'}, cannon:{range:270,cd:.76,power:1.48,kind:'ranged',label:'Cannon',pattern:'blast'}
};
const rarity=['Common','Uncommon','Rare','Epic','Legendary','Mythic'],rcol=['#eee8dd','#82d79c','#65bcef','#b892f1','#f4c952','#ff7bd5'];
const prefixes=['Twig','Iron','Rose','Moon','Storm','Frost','Ember','Prism','Royal','Void','Astral','World'];
function makeWeapon(tier=0,bonus=0){const kinds=Object.keys(weaponFamilies),r=clamp(Math.floor(Math.random()*2+tier*.68+bonus),0,5),kind=kinds[(Math.random()*kinds.length)|0],f=weaponFamilies[kind],name=prefixes[clamp(r*2+(Math.random()*2|0),0,prefixes.length-1)]+' '+f.label;return{name,rarity:r,kind,...f,power:f.power*(1+r*.37),durMax:Math.round((32+r*14)*(f.cd>.65?1.25:f.cd<.3?.82:1)),dur:0}}
const player={x:0,y:0,r:11,heading:0,steer:0,speed:172,hp:52,maxHp:52,level:1,xp:0,xpNeed:7,weapon:null,attack:0,dash:0,dashT:0,invuln:0,flow:0,power:1,speedMod:1,regen:0,fortune:0};
let mobs=[],shots=[],drops=[],particles=[],started=false,dead=false,time=0,kills=0,relics=0,lastBiome=-1,eventT=22,epicT=38,spawnT=0,choice=null,toastT=0;
const roles=['chaser','flanker','charger','sniper','orbiter','turret','swarm','tank'];
const biomeNames=[
 ['Clover Slime','Pollen Bee','Meadow Boar','Sun Hare','Clover Wolf','Dandelion Giant'],
 ['Petal Imp','Rose Moth','Sakura Wolf','Lantern Wisp','Bloom Treant','Thorn Knight'],
 ['Moon Wisp','Silver Ghost','Lunar Hound','Dream Moth','Pale Knight','Star Beast'],
 ['Bog Frog','Reed Crab','Mire Serpent','Fen Ghost','Spore Knight','Marsh Golem'],
 ['Cinder Imp','Ash Boar','Scorch Serpent','Coal Golem','Magma Knight','Fire Wisp'],
 ['Snow Hare','Rime Wolf','Frost Wisp','Ice Beetle','Glacier Golem','White Stag'],
 ['Shard Beetle','Prism Wisp','Glass Moth','Gem Golem','Crystal Knight','Facet Beast'],
 ['Lotus Crab','Vine Serpent','Moss Treant','Drowned Ghost','Garden Knight','Bloom Beast'],
 ['Night Bat','Grave Hound','Hollow Knight','Gloom Wisp','Rift Stalker','Dusk Treant'],
 ['Comet Wisp','Void Hound','Astral Knight','Star Beast','Rift Golem','Cosmic Stalker']
];
const epicNames=[
 ['Verdant Dragon','Sun Griffin'],['Sakura Dragon','Blossom Phoenix'],['Moon Dragon','Silver Pegasus'],['Bog Hydra','Mire Leviathan'],['Ember Dragon','Ash Phoenix'],
 ['Frost Dragon','Ice Kirin'],['Prism Dragon','Gem Colossus'],['Lotus Dragon','Vine Chimera'],['Void Dragon','Grave Cerberus'],['Astral Dragon','Cosmic Hydra']
];
function mobSpec(b,i,epic=false){const tier=dangerAt(player.x,player.y),role=epic?(i?'tank':'sniper'):roles[(i+b*3)%roles.length],base=epic?4.2:1+(i%3)*.22;return{name:epic?epicNames[b][i]:biomeNames[b][i],role,hp:(18+b*8+i*6)*base*(1+tier*.08),spd:(42+(i%4)*9)*(epic?.82:1),dmg:(7+b*1.6+i*.7)*(epic?1.65:1),r:epic?31:11+(i%3)*3,xp:epic?20+b*3:1+Math.floor(b/2)+(i>3?1:0),b,epic,cd:.5+Math.random(),side:Math.random()<.5?-1:1}}
function spawnMob(epic=false){const b=biomeAt(player.x,player.y),i=epic?(Math.random()*2|0):(Math.random()*6|0),s=mobSpec(b,i,epic),a=Math.random()*TAU,d=230+Math.random()*210;let x=player.x+Math.cos(a)*d,y=player.y+Math.sin(a)*d;if(blocked(x,y,s.r)){x=player.x-Math.cos(a)*d;y=player.y-Math.sin(a)*d}mobs.push({...s,x,y,hpNow:s.hp,max:s.hp,hit:0,tele:0,state:'seek',dashT:0,aim:0});if(epic){say('✦ EPIC · '+s.name+' ✦');screenShake(10)}}
function nearest(range=999){let best=null,bd=range;for(const m of mobs){const d=dist(player,m);if(d<bd){bd=d;best=m}}return best}
function hurt(n){if(player.invuln>0||dead)return;player.hp-=n;player.invuln=.52;player.flow=Math.max(0,player.flow-26);puff(player.x,player.y,'#ff8eae',12);shake=9;if(player.hp<=0)die()}
function damage(m,n,kb=18){if(!m||m.hpNow<=0)return;m.hpNow-=n;m.hit=.12;const d=Math.hypot(m.x-player.x,m.y-player.y)||1;moveBody(m,(m.x-player.x)/d*kb,(m.y-player.y)/d*kb,m.r);puff(m.x,m.y,rcol[player.weapon.rarity],5);if(m.hpNow<=0)kill(m)}
function kill(m){const idx=mobs.indexOf(m);if(idx>=0)mobs.splice(idx,1);kills++;player.flow=clamp(player.flow+(m.epic?35:8),0,100);gainXp(m.xp);if(m.epic){relics+=2+Math.floor(m.b/3);dropWeapon(m.x,m.y,2.4);say('♛ '+m.name+' defeated · epic cache')}else{const r=Math.random();if(r<.16+player.fortune*.03)dropWeapon(m.x,m.y,0);else if(r<.28)drops.push({x:m.x,y:m.y,type:'food',t:18})}puff(m.x,m.y,m.epic?'#ffd66b':'#fff2d8',m.epic?28:10)}
function dropWeapon(x,y,bonus){const w=makeWeapon(dangerAt(x,y),bonus);w.dur=w.durMax;drops.push({x,y,type:'weapon',weapon:w,t:32});}
function gainXp(n){player.xp+=n;while(player.xp>=player.xpNeed){player.xp-=player.xpNeed;player.level++;player.xpNeed=Math.floor(7+player.level*2.4);offerChoice()}}
const perks=[
 ['HEART','+14 max HP',()=>{player.maxHp+=14;player.hp=Math.min(player.maxHp,player.hp+18)}],['HASTE','+8% run speed',()=>player.speedMod*=1.08],['POWER','+11% damage',()=>player.power*=1.11],
 ['DASH','Dash recharges faster',()=>player.dashBonus=(player.dashBonus||1)*.86],['REPAIR','Fully repair weapon',()=>player.weapon.dur=player.weapon.durMax],['FLOW','Flow lasts longer',()=>player.flowHold=(player.flowHold||1)*.72],
 ['FORTUNE','Better weapon drops',()=>player.fortune++],['REGEN','Recover slowly out of danger',()=>player.regen+=.65]
];
function offerChoice(){if(choice)return;const a=[];while(a.length<3){const p=perks[Math.random()*perks.length|0];if(!a.includes(p))a.push(p)}choice=a;renderChoice()}
function renderChoice(){const box=document.getElementById('choices');box.innerHTML='';for(const p of choice){const b=document.createElement('button');b.className='choice';b.innerHTML='<b>'+p[0]+'</b><span>'+p[1]+'</span>';b.onpointerdown=e=>{e.stopPropagation();p[2]();choice=null;box.classList.remove('showChoice')};box.appendChild(b)}box.classList.add('showChoice')}
function fire(){const w=player.weapon,t=nearest(w.range);if(!t)return;player.attack=w.cd*(1-player.flow*.0025);player.weapon.dur--;if(player.weapon.dur<=0){say('💥 '+w.name+' broke');player.weapon=makeWeapon(0,0);player.weapon.dur=Math.min(18,player.weapon.durMax)}const dmg=(7+player.level*1.1)*w.power*player.power*(1+player.flow*.0035);const a=Math.atan2(t.y-player.y,t.x-player.x);if(w.kind==='melee'){
 if(w.pattern==='blast'){for(const m of [...mobs])if(dist(player,m)<w.range+20)damage(m,dmg*.78,48);shake=7}else if(w.pattern==='line'){for(const m of [...mobs]){const d=dist(player,m),da=Math.abs(Math.atan2(Math.sin(Math.atan2(m.y-player.y,m.x-player.x)-a),Math.cos(Math.atan2(m.y-player.y,m.x-player.x)-a)));if(d<w.range&&da<.38)damage(m,dmg,30)}}else if(w.pattern==='flurry'){damage(t,dmg,.1);setTimeout(()=>{if(started&&!dead&&t.hpNow>0)damage(t,dmg*.62,12)},90)}else{for(const m of [...mobs]){const d=dist(player,m),da=Math.abs(Math.atan2(Math.sin(Math.atan2(m.y-player.y,m.x-player.x)-a),Math.cos(Math.atan2(m.y-player.y,m.x-player.x)-a)));if(d<w.range&&da<.85)damage(m,dmg,26)}}
 } else {const count=w.pattern==='blast'?3:1;for(let i=0;i<count;i++){const aa=a+(i-(count-1)/2)*.11;shots.push({x:player.x,y:player.y,vx:Math.cos(aa)*470,vy:Math.sin(aa)*470,t:w.range/470,dmg:dmg*(count>1?.62:1),kb:w.pattern==='blast'?42:18,bounce:w.pattern==='bounce'?1:0,friendly:true})}}
}
function enemyShot(m,count=1,speed=190,mult=.7){const a=Math.atan2(player.y-m.y,player.x-m.x);for(let i=0;i<count;i++){const aa=a+(i-(count-1)/2)*.18;shots.push({x:m.x,y:m.y,vx:Math.cos(aa)*speed,vy:Math.sin(aa)*speed,t:3,dmg:m.dmg*mult,friendly:false})}}
function updateMob(m,dt){m.hit=Math.max(0,m.hit-dt);m.tele=Math.max(0,m.tele-dt);m.cd-=dt;const dx=player.x-m.x,dy=player.y-m.y,d=Math.hypot(dx,dy)||1,nx=dx/d,ny=dy/d;const mv=(x,y,s)=>moveBody(m,x*s*dt,y*s*dt,m.r*.7);if(m.epic){if(m.role==='sniper'){if(d>175)mv(nx,ny,m.spd*.65);else mv(-ny, nx,m.spd*.65);if(m.cd<=0){m.cd=1.35;m.tele=.42;enemyShot(m,5,230,.55)}}else{if(d>110)mv(nx,ny,m.spd*.55);if(m.cd<=0){m.cd=1.7;m.tele=.55;enemyShot(m,8,170,.48)}}}
 else if(m.role==='chaser')mv(nx,ny,m.spd);else if(m.role==='flanker')mv(nx-ny*m.side*.65,ny+nx*m.side*.65,m.spd);else if(m.role==='orbiter'){mv(nx*.2-ny*m.side,ny*.2+nx*m.side,m.spd*.88);if(m.cd<=0){m.cd=1.65;enemyShot(m,3,175,.62)}}
 else if(m.role==='charger'){if(m.dashT>0){m.dashT-=dt;mv(Math.cos(m.aim),Math.sin(m.aim),m.spd*2.9)}else if(m.cd<=0&&d<230){m.cd=1.7;m.tele=.38;m.aim=Math.atan2(dy,dx);m.dashT=.26}else mv(nx,ny,m.spd*.72)}
 else if(m.role==='sniper'){if(d<190)mv(-nx,-ny,m.spd*.7);else if(d>300)mv(nx,ny,m.spd*.4);if(m.cd<=0){m.cd=1.8;m.tele=.48;enemyShot(m,1,285,.85)}}
 else if(m.role==='turret'){if(d<150)mv(-nx,-ny,m.spd*.45);if(m.cd<=0){m.cd=1.45;enemyShot(m,3,210,.58)}}else if(m.role==='swarm')mv(nx-ny*m.side*.35,ny+nx*m.side*.35,m.spd*1.25);else if(m.role==='tank'){mv(nx,ny,m.spd*.62);if(m.cd<=0&&d<105){m.cd=1.5;enemyShot(m,5,135,.48,.35)}}
 if(d<player.r+m.r*.72&&player.invuln<=0)hurt(m.dmg)}
function updateShots(dt){for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;s.t-=dt;if(blocked(s.x,s.y,4)){if(s.bounce){s.vx*=-1;s.vy*=-1;s.bounce--}else{s.t=0}}if(s.friendly){for(const m of [...mobs])if(Math.hypot(m.x-s.x,m.y-s.y)<m.r+5){damage(m,s.dmg,s.kb);s.t=0;break}}else if(Math.hypot(player.x-s.x,player.y-s.y)<player.r+5){hurt(s.dmg);s.t=0}if(s.t<=0)shots.splice(i,1)}}
function updateDrops(dt){for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.t-=dt;if(Math.hypot(d.x-player.x,d.y-player.y)<28){if(d.type==='food'){player.hp=Math.min(player.maxHp,player.hp+16);say('♡ Health restored')}else{const cur=player.weapon,ratio=cur.dur/cur.durMax,score=x=>x.power*(1+x.rarity*.18)/(x.cd+.4);if(score(d.weapon)>score(cur)*.92||ratio<.35){player.weapon=d.weapon;say('✦ '+rarity[d.weapon.rarity]+' '+d.weapon.name)}else{cur.dur=Math.min(cur.durMax,cur.dur+8+d.weapon.rarity*3);say('🔧 Salvaged weapon · repaired')}}drops.splice(i,1)}else if(d.t<=0)drops.splice(i,1)}}
function chooseSteer(){const base=player.heading,probes=[0,.18,-.18,.34,-.34,.55,-.55,.8,-.8,1.1,-1.1,1.45,-1.45];for(const o of probes){const a=base+o;if(!blocked(player.x+Math.cos(a)*34,player.y+Math.sin(a)*34,player.r)&&!blocked(player.x+Math.cos(a)*18,player.y+Math.sin(a)*18,player.r))return a}return base}
function dash(){if(player.dash>0||dead||!started)return;player.dash=1.55*(player.dashBonus||1);player.dashT=.18;player.invuln=.28;player.flow=clamp(player.flow+8,0,100);puff(player.x,player.y,'#ffffff',9)}
function setHeading(x,y){const a=Math.atan2(y-H/2,x-W/2);player.heading=a;player.steer=a}
let lastTap=0,lastTapA=0;c.addEventListener('pointerdown',e=>{if(!started||dead||choice)return;const a=Math.atan2(e.clientY-H/2,e.clientX-W/2),now=performance.now();if(now-lastTap<300&&Math.abs(Math.atan2(Math.sin(a-lastTapA),Math.cos(a-lastTapA)))<.7)dash();setHeading(e.clientX,e.clientY);lastTap=now;lastTapA=a;e.preventDefault()});
function update(dt){if(!started||dead||choice)return;time+=dt;player.attack=Math.max(0,player.attack-dt);player.dash=Math.max(0,player.dash-dt);player.invuln=Math.max(0,player.invuln-dt);toastT=Math.max(0,toastT-dt);if(toastT<=0)document.getElementById('toast').classList.remove('show');
 const b=biomeAt(player.x,player.y);if(b!==lastBiome){lastBiome=b;say('✦ '+palettes[b].name+' · '+['open pursuit','petal ambush','ranged pressure','surrounding threats','burst damage','fast hunters','projectile lattice','control + attrition','night ambush','endgame chaos'][b])}
 if(player.dashT>0){player.dashT-=dt;moveBody(player,Math.cos(player.heading)*430*dt,Math.sin(player.heading)*430*dt,player.r);for(const m of [...mobs])if(dist(player,m)<player.r+m.r+16)damage(m,(8+player.level)*player.power,55)}else{player.steer=chooseSteer();moveBody(player,Math.cos(player.steer)*player.speed*player.speedMod*dt,Math.sin(player.steer)*player.speed*player.speedMod*dt,player.r)}
 if(player.attack<=0)fire();for(const m of [...mobs])updateMob(m,dt);updateShots(dt);updateDrops(dt);spawnT-=dt;const tier=dangerAt(player.x,player.y),target=8+tier*3+Math.min(8,Math.floor(time/55));if(spawnT<=0&&mobs.length<target){spawnMob(false);spawnT=.38+Math.random()*.28}
 eventT-=dt;if(eventT<=0){const n=3+tier*2;for(let i=0;i<n;i++)spawnMob(false);say('⚠ '+palettes[b].name.toUpperCase()+' SURGE');eventT=20+Math.random()*16}
 epicT-=dt;if(epicT<=0){if(!mobs.some(m=>m.epic)&&Math.random()<.18+tier*.09)spawnMob(true);epicT=26+Math.random()*28}
 if(player.regen&&time%1<dt&&player.hp<player.maxHp&&mobs.every(m=>dist(player,m)>220))player.hp=Math.min(player.maxHp,player.hp+player.regen);const decay=dt*(player.flowHold||1)*(mobs.length?2.2:4);player.flow=Math.max(0,player.flow-decay);updateHUD()}
let shake=0;function screenShake(n){shake=Math.max(shake,n)}
function puff(x,y,col,n=7){for(let i=0;i<n;i++){const a=Math.random()*TAU,s=25+Math.random()*70;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,t:.35+Math.random()*.3,col})}}
function drawObstacle(o,cx,cy){const x=o.x-player.x+cx,y=o.y-player.y+cy,p=palettes[o.b];ctx.fillStyle='#0002';ctx.beginPath();ctx.ellipse(x,y+o.r*.7,o.r*.8,o.r*.35,0,0,TAU);ctx.fill();ctx.fillStyle=p.haz;ctx.beginPath();ctx.arc(x,y,o.r,0,TAU);ctx.fill();ctx.fillStyle=p.accent;ctx.fillRect(x-o.r*.22,y-o.r*.65,o.r*.44,o.r*.35)}
function drawMob(m,cx,cy){const x=m.x-player.x+cx,y=m.y-player.y+cy,p=palettes[m.b],flash=m.hit>0;ctx.save();ctx.translate(x,y);ctx.fillStyle='#0002';ctx.beginPath();ctx.ellipse(0,m.r*.65,m.r*.8,m.r*.35,0,0,TAU);ctx.fill();if(m.epic){ctx.strokeStyle='#ffd86f';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,m.r+7+Math.sin(time*5)*2,0,TAU);ctx.stroke()}ctx.fillStyle=flash?'#fff':p.haz;ctx.beginPath();ctx.arc(0,0,m.r,0,TAU);ctx.fill();ctx.fillStyle=p.accent;ctx.beginPath();ctx.arc(-m.r*.28,-m.r*.16,m.r*.18,0,TAU);ctx.arc(m.r*.28,-m.r*.16,m.r*.18,0,TAU);ctx.fill();ctx.fillStyle='#263040';ctx.beginPath();ctx.arc(-m.r*.25,-m.r*.15,2,0,TAU);ctx.arc(m.r*.25,-m.r*.15,2,0,TAU);ctx.fill();if(m.tele>0){ctx.strokeStyle='#ff6f82';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,m.r+12+Math.sin(time*12)*3,0,TAU);ctx.stroke()}if(m.epic||m.hpNow<m.max){ctx.fillStyle='#2229';ctx.fillRect(-m.r,-m.r-12,m.r*2,4);ctx.fillStyle=m.epic?'#ffd45d':'#ef7998';ctx.fillRect(-m.r,-m.r-12,m.r*2*clamp(m.hpNow/m.max,0,1),4)}if(m.epic){ctx.font='900 9px system-ui';ctx.textAlign='center';ctx.fillStyle='#fff8d4';ctx.fillText('✦ '+m.name+' ✦',0,-m.r-20)}ctx.restore()}
function draw(){const p=palettes[biomeAt(player.x,player.y)],cx=W/2,cy=H/2;ctx.fillStyle=p.a;ctx.fillRect(0,0,W,H);const gx=Math.floor((player.x-W/2)/48),gy=Math.floor((player.y-H/2)/48);for(let y=gy;y<gy+H/48+3;y++)for(let x=gx;x<gx+W/48+3;x++){if(hash(x,y,2)>.78){ctx.fillStyle=p.b;ctx.fillRect(x*48-player.x+cx,y*48-player.y+cy,2,2)}}
 const ocx=Math.floor(player.x/150),ocy=Math.floor(player.y/150);for(let yy=ocy-5;yy<=ocy+5;yy++)for(let xx=ocx-5;xx<=ocx+5;xx++){const o=obstacleAt(xx*150,yy*150);if(o)drawObstacle(o,cx,cy)}for(const d of drops){const x=d.x-player.x+cx,y=d.y-player.y+cy;if(d.type==='food'){ctx.fillStyle='#ef7594';ctx.beginPath();ctx.arc(x,y,8,0,TAU);ctx.fill()}else{ctx.strokeStyle=rcol[d.weapon.rarity];ctx.lineWidth=d.weapon.rarity>=4?5:3;ctx.beginPath();ctx.arc(x,y,9+Math.sin(time*5)*2,0,TAU);ctx.stroke();ctx.fillStyle='#fff';ctx.fillRect(x-2,y-9,4,18)}}for(const s of shots){ctx.fillStyle=s.friendly?rcol[player.weapon.rarity]:'#ff7890';ctx.beginPath();ctx.arc(s.x-player.x+cx,s.y-player.y+cy,s.friendly?4:5,0,TAU);ctx.fill()}for(const m of mobs)drawMob(m,cx,cy);
 ctx.save();ctx.translate(cx,cy);ctx.rotate(player.steer);ctx.fillStyle='#0002';ctx.beginPath();ctx.ellipse(0,12,14,6,0,0,TAU);ctx.fill();ctx.fillStyle='#fff1e6';ctx.beginPath();ctx.arc(0,0,13,0,TAU);ctx.fill();ctx.fillStyle='#ef90bd';ctx.beginPath();ctx.arc(-5,-8,6,0,TAU);ctx.arc(5,-8,6,0,TAU);ctx.fill();ctx.fillStyle='#293041';ctx.fillRect(3,-2,3,3);ctx.fillStyle=rcol[player.weapon.rarity];ctx.fillRect(10,-2,20,4);if(player.invuln>0){ctx.strokeStyle='#fff9';ctx.beginPath();ctx.arc(0,0,20,0,TAU);ctx.stroke()}ctx.restore();
 for(let i=particles.length-1;i>=0;i--){const q=particles[i];q.x+=q.vx/60;q.y+=q.vy/60;q.t-=1/60;ctx.globalAlpha=clamp(q.t*2,0,1);ctx.fillStyle=q.col;ctx.fillRect(q.x-player.x+cx,q.y-player.y+cy,3,3);ctx.globalAlpha=1;if(q.t<=0)particles.splice(i,1)}if(shake>0)shake=Math.max(0,shake-1)}
function updateHUD(){document.getElementById('hp').textContent=Math.max(0,Math.ceil(player.hp));document.getElementById('maxhp').textContent=player.maxHp;document.getElementById('hpfill').style.width=(100*clamp(player.hp/player.maxHp,0,1))+'%';document.getElementById('lv').textContent=player.level;document.getElementById('xp').textContent=player.xp+'/'+player.xpNeed;document.getElementById('weapon').textContent=rarity[player.weapon.rarity]+' · '+player.weapon.name+' · '+player.weapon.dur+'/'+player.weapon.durMax;document.getElementById('danger').textContent='Danger '+(dangerAt(player.x,player.y)+1);document.getElementById('biome').textContent=palettes[biomeAt(player.x,player.y)].name;document.getElementById('relics').textContent=relics;document.getElementById('flowfill').style.width=player.flow+'%'}
function say(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');toastT=2.2}
function reset(){mobs=[];shots=[];drops=[];particles=[];time=0;kills=0;relics=0;lastBiome=-1;eventT=18;epicT=32;spawnT=.5;dead=false;choice=null;player.x=player.y=0;player.heading=0;player.steer=0;player.hp=player.maxHp=52;player.level=1;player.xp=0;player.xpNeed=7;player.attack=0;player.dash=0;player.dashT=0;player.invuln=2.4;player.flow=0;player.power=1;player.speedMod=1;player.regen=0;player.fortune=0;player.dashBonus=1;player.flowHold=1;player.weapon=makeWeapon(0,0);player.weapon.dur=player.weapon.durMax;document.getElementById('death').classList.add('hide');document.getElementById('choices').classList.remove('showChoice');updateHUD()}
function die(){dead=true;started=false;document.getElementById('dtime').textContent=Math.floor(time/60)+':'+String(Math.floor(time%60)).padStart(2,'0');document.getElementById('dkills').textContent=kills;document.getElementById('dlevel').textContent=player.level;document.getElementById('drelics').textContent=relics;document.getElementById('death').classList.remove('hide')}
function start(){reset();started=true;document.getElementById('start').classList.add('hide');say('Tap a direction to run · double-tap to Rush')}
document.getElementById('play').onclick=start;document.getElementById('again').onclick=start;
function loop(now){const dt=Math.min(.034,(now-last)/1000||.016);last=now;update(dt);draw();requestAnimationFrame(loop)}reset();requestAnimationFrame(loop);
window.__TWBB_V14__={version:14,biomeAt,dangerAt,spawnEpic:()=>spawnMob(true),state:()=>({started,dead,time,kills,relics,biome:palettes[biomeAt(player.x,player.y)].name,mobs:mobs.length,weapon:player.weapon.name,flow:player.flow})};
})();