'use strict';
(() => {
const c=document.getElementById('g'),ctx=c.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;
let W=innerWidth,H=innerHeight,DPR=Math.min(2,devicePixelRatio||1),last=performance.now();
function resize(){W=innerWidth;H=innerHeight;c.width=W*DPR;c.height=H*DPR;c.style.width=W+'px';c.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize,{passive:true});resize();
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const hash=(x,y,s=0)=>{const n=Math.sin(x*127.1+y*311.7+s*74.7+731.927)*43758.5453;return n-Math.floor(n)};
const palettes=[
{name:'Meadow',a:'#cfe9ad',b:'#b9dc98',accent:'#f5a9c7',haz:'#4f9e5e'},{name:'Blossom Woods',a:'#edcddd',b:'#d9b6cf',accent:'#fff1a1',haz:'#9b6997'},
{name:'Moon Fields',a:'#b9d7ca',b:'#9fc2b2',accent:'#c5b2f2',haz:'#687c9c'},{name:'Misty Marsh',a:'#a5c4b3',b:'#8eab9a',accent:'#85d8de',haz:'#536f66'},
{name:'Emberlands',a:'#e3aa91',b:'#cc8975',accent:'#ffd06f',haz:'#a44f41'},{name:'Frostvale',a:'#dceef3',b:'#bcdbe5',accent:'#9dccf2',haz:'#6d9bb0'},
{name:'Crystal Steppe',a:'#c5d2e8',b:'#a7b7d5',accent:'#a38be4',haz:'#6f68a7'},{name:'Sunken Garden',a:'#b6d6bd',b:'#91bd9d',accent:'#f09fbe',haz:'#4f8b68'},
{name:'Duskwild',a:'#96a49e',b:'#737f7a',accent:'#d395cf',haz:'#4d4d5f'},{name:'Starfall Reach',a:'#8799bc',b:'#66779d',accent:'#ffd26b',haz:'#575f99'}];
function biomeAt(x,y){const S=1450,gx=Math.floor(x/S),gy=Math.floor(y/S);let best=0,bd=1e30;for(let yy=gy-1;yy<=gy+1;yy++)for(let xx=gx-1;xx<=gx+1;xx++){const px=(xx+.18+hash(xx,yy,8)*.64)*S,py=(yy+.18+hash(xx,yy,9)*.64)*S,d=(x-px)**2+(y-py)**2;if(d<bd){bd=d;const tier=clamp(Math.floor(Math.hypot(px,py)/1550),0,4),pools=[[0,1],[0,1,2,3],[2,3,4,5,6],[4,5,6,7,8],[6,7,8,9]][tier];best=pools[Math.floor(hash(xx,yy,11)*pools.length)]}}return best}
function dangerAt(x,y){return clamp(Math.floor(Math.hypot(x,y)/1150),0,5)}
function obstacleAt(x,y){const cx=Math.floor(x/150),cy=Math.floor(y/150),r=hash(cx,cy,41);if(r<.60)return null;const b=biomeAt(cx*150,cy*150),ox=(cx+.2+hash(cx,cy,42)*.6)*150,oy=(cy+.2+hash(cx,cy,43)*.6)*150,big=r>.94;return{x:ox,y:oy,r:big?34:22,b}}
function blocked(x,y,r=12){const cx=Math.floor(x/150),cy=Math.floor(y/150);for(let yy=cy-1;yy<=cy+1;yy++)for(let xx=cx-1;xx<=cx+1;xx++){const o=obstacleAt(xx*150,yy*150);if(o&&Math.hypot(x-o.x,y-o.y)<r+o.r)return true}return false}
function moveBody(o,dx,dy,r=12){const steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/7)),sx=dx/steps,sy=dy/steps;for(let i=0;i<steps;i++){if(!blocked(o.x+sx,o.y,r))o.x+=sx;if(!blocked(o.x,o.y+sy,r))o.y+=sy}}
const rarity=['Common','Uncommon','Rare','Epic','Legendary','Mythic'],rcol=['#eee8dd','#82d79c','#65bcef','#b892f1','#f4c952','#ff7bd5'];
const player={x:0,y:0,r:11,heading:0,speed:172,hp:52,maxHp:52,level:1,xp:0,xpNeed:7,attack:0,invuln:0,power:1,speedMod:1,regen:0,fortune:0,flow:0,wand:null};
function freshWand(){return{name:'Twig Wand',rarity:0,damage:1,fireRate:1,projectileSpeed:1,size:1,range:1,projectiles:1,spread:0,pierce:0,bounce:0,path:'straight',homing:0}}
let mobs=[],shots=[],drops=[],particles=[],started=false,dead=false,time=0,kills=0,relics=0,lastBiome=-1,eventT=22,epicT=38,spawnT=0,choice=null,toastT=0,shake=0;
const input={moveId:null,shootId:null,mx:0,my:0,shoot:false};
const roles=['chaser','flanker','charger','sniper','orbiter','turret','swarm','tank'];
const biomeNames=[['Clover Slime','Pollen Bee','Meadow Boar','Sun Hare','Clover Wolf','Dandelion Giant'],['Petal Imp','Rose Moth','Sakura Wolf','Lantern Wisp','Bloom Treant','Thorn Knight'],['Moon Wisp','Silver Ghost','Lunar Hound','Dream Moth','Pale Knight','Star Beast'],['Bog Frog','Reed Crab','Mire Serpent','Fen Ghost','Spore Knight','Marsh Golem'],['Cinder Imp','Ash Boar','Scorch Serpent','Coal Golem','Magma Knight','Fire Wisp'],['Snow Hare','Rime Wolf','Frost Wisp','Ice Beetle','Glacier Golem','White Stag'],['Shard Beetle','Prism Wisp','Glass Moth','Gem Golem','Crystal Knight','Facet Beast'],['Lotus Crab','Vine Serpent','Moss Treant','Drowned Ghost','Garden Knight','Bloom Beast'],['Night Bat','Grave Hound','Hollow Knight','Gloom Wisp','Rift Stalker','Dusk Treant'],['Comet Wisp','Void Hound','Astral Knight','Star Beast','Rift Golem','Cosmic Stalker']];
const epicNames=[['Verdant Dragon','Sun Griffin'],['Sakura Dragon','Blossom Phoenix'],['Moon Dragon','Silver Pegasus'],['Bog Hydra','Mire Leviathan'],['Ember Dragon','Ash Phoenix'],['Frost Dragon','Ice Kirin'],['Prism Dragon','Gem Colossus'],['Lotus Dragon','Vine Chimera'],['Void Dragon','Grave Cerberus'],['Astral Dragon','Cosmic Hydra']];
function mobSpec(b,i,epic=false){const tier=dangerAt(player.x,player.y),role=epic?(i?'tank':'sniper'):roles[(i+b*3)%roles.length],base=epic?4.2:1+(i%3)*.22;return{name:epic?epicNames[b][i]:biomeNames[b][i],role,hp:(18+b*8+i*6)*base*(1+tier*.08),spd:(42+(i%4)*9)*(epic?.82:1),dmg:(7+b*1.6+i*.7)*(epic?1.65:1),r:epic?31:11+(i%3)*3,xp:epic?20+b*3:1+Math.floor(b/2)+(i>3?1:0),b,epic,cd:.5+Math.random(),side:Math.random()<.5?-1:1}}
function spawnMob(epic=false){const b=biomeAt(player.x,player.y),i=epic?(Math.random()*2|0):(Math.random()*6|0),s=mobSpec(b,i,epic),a=Math.random()*TAU,d=230+Math.random()*210;let x=player.x+Math.cos(a)*d,y=player.y+Math.sin(a)*d;if(blocked(x,y,s.r)){x=player.x-Math.cos(a)*d;y=player.y-Math.sin(a)*d}mobs.push({...s,x,y,hpNow:s.hp,max:s.hp,hit:0,tele:0,dashT:0,aim:0});if(epic){say('✦ EPIC · '+s.name+' ✦');shake=10}}
function nearest(range=999){let best=null,bd=range;for(const m of mobs){const d=dist(player,m);if(d<bd){bd=d;best=m}}return best}
function hurt(n){if(player.invuln>0||dead)return;player.hp-=n;player.invuln=.52;player.flow=Math.max(0,player.flow-22);puff(player.x,player.y,'#ff8eae',12);shake=9;if(player.hp<=0)die()}
function damage(m,n,kb=12){if(!m||m.hpNow<=0)return;m.hpNow-=n;m.hit=.12;const d=Math.hypot(m.x-player.x,m.y-player.y)||1;moveBody(m,(m.x-player.x)/d*kb,(m.y-player.y)/d*kb,m.r);puff(m.x,m.y,rcol[player.wand.rarity],5);if(m.hpNow<=0)kill(m)}
const powerups=[
{key:'rapid',icon:'⚡',name:'Rapid Spark',desc:'faster fire',apply:w=>w.fireRate*=1.18},
{key:'heavy',icon:'✹',name:'Heavy Orb',desc:'bigger + harder',apply:w=>{w.damage*=1.22;w.size*=1.14}},
{key:'multi',icon:'✦',name:'Twin Cast',desc:'+1 projectile',apply:w=>{w.projectiles=Math.min(5,w.projectiles+1);w.spread=Math.max(.12,w.spread+.035)}},
{key:'pierce',icon:'➶',name:'Piercing Rune',desc:'pierce +1',apply:w=>w.pierce=Math.min(5,w.pierce+1)},
{key:'bounce',icon:'↝',name:'Ricochet Rune',desc:'bounce +1',apply:w=>w.bounce=Math.min(4,w.bounce+1)},
{key:'wave',icon:'〰',name:'Wave Rune',desc:'sine projectile path',apply:w=>w.path='wave'},
{key:'spiral',icon:'◎',name:'Spiral Rune',desc:'spiralling projectiles',apply:w=>w.path='spiral'},
{key:'homing',icon:'⌁',name:'Seeking Rune',desc:'projectiles bend to targets',apply:w=>w.homing=Math.min(.12,w.homing+.035)},
{key:'speed',icon:'➤',name:'Comet Tip',desc:'faster + longer shots',apply:w=>{w.projectileSpeed*=1.16;w.range*=1.12}}
];
function dropPowerup(x,y,quality=0){const p=powerups[Math.random()*powerups.length|0];drops.push({x,y,type:'power',power:p,t:24,quality})}
function kill(m){const idx=mobs.indexOf(m);if(idx>=0)mobs.splice(idx,1);kills++;player.flow=clamp(player.flow+(m.epic?32:7),0,100);gainXp(m.xp);if(m.epic){relics+=2+Math.floor(m.b/3);dropPowerup(m.x,m.y,2);dropPowerup(m.x+18,m.y,2);say('♛ '+m.name+' defeated · rune cache')}else{const r=Math.random();if(r<.25+player.fortune*.025)dropPowerup(m.x,m.y,0);else if(r<.34)drops.push({x:m.x,y:m.y,type:'food',t:18})}puff(m.x,m.y,m.epic?'#ffd66b':'#fff2d8',m.epic?28:10)}
function gainXp(n){player.xp+=n;while(player.xp>=player.xpNeed){player.xp-=player.xpNeed;player.level++;player.xpNeed=Math.floor(7+player.level*2.4);offerChoice()}}
const perks=[['HEART','+14 max HP',()=>{player.maxHp+=14;player.hp=Math.min(player.maxHp,player.hp+18)}],['HASTE','+8% movement',()=>player.speedMod*=1.08],['ARCANE','+11% wand damage',()=>player.power*=1.11],['FORTUNE','More rune drops',()=>player.fortune++],['REGEN','Recover slowly out of danger',()=>player.regen+=.65],['OVERCHARGE','+10% fire rate',()=>player.wand.fireRate*=1.1]];
function offerChoice(){if(choice)return;const a=[];while(a.length<3){const p=perks[Math.random()*perks.length|0];if(!a.includes(p))a.push(p)}choice=a;const box=document.getElementById('choices');box.innerHTML='';for(const p of choice){const b=document.createElement('button');b.className='choice';b.innerHTML='<b>'+p[0]+'</b><span>'+p[1]+'</span>';b.onpointerdown=e=>{e.stopPropagation();p[2]();choice=null;box.classList.remove('showChoice')};box.appendChild(b)}box.classList.add('showChoice')}
function fire(){if(player.attack>0)return;const w=player.wand,t=nearest(460*w.range);if(!t)return;player.attack=.34/w.fireRate;const baseA=Math.atan2(t.y-player.y,t.x-player.x);player.heading=baseA;const dmg=(7+player.level*.9)*w.damage*player.power*(1+player.flow*.003);for(let i=0;i<w.projectiles;i++){const offs=(i-(w.projectiles-1)/2)*w.spread,aa=baseA+offs,spd=470*w.projectileSpeed;shots.push({x:player.x,y:player.y,vx:Math.cos(aa)*spd,vy:Math.sin(aa)*spd,t:1.05*w.range,dmg:dmg*(w.projectiles>1?.82:1),friendly:true,pierce:w.pierce,bounce:w.bounce,size:4.5*w.size,path:w.path,age:0,baseA:aa,baseSpd:spd,homing:w.homing,hit:new Set()})}puff(player.x+Math.cos(baseA)*19,player.y+Math.sin(baseA)*19,rcol[w.rarity],3)}
function enemyShot(m,count=1,speed=190,mult=.7){const a=Math.atan2(player.y-m.y,player.x-m.x);for(let i=0;i<count;i++){const aa=a+(i-(count-1)/2)*.18;shots.push({x:m.x,y:m.y,vx:Math.cos(aa)*speed,vy:Math.sin(aa)*speed,t:3,dmg:m.dmg*mult,friendly:false,size:5})}}
function updateMob(m,dt){m.hit=Math.max(0,m.hit-dt);m.tele=Math.max(0,m.tele-dt);m.cd-=dt;const dx=player.x-m.x,dy=player.y-m.y,d=Math.hypot(dx,dy)||1,nx=dx/d,ny=dy/d,mv=(x,y,s)=>moveBody(m,x*s*dt,y*s*dt,m.r*.7);if(m.epic){if(m.role==='sniper'){if(d>175)mv(nx,ny,m.spd*.65);else mv(-ny,nx,m.spd*.65);if(m.cd<=0){m.cd=1.35;m.tele=.42;enemyShot(m,5,230,.55)}}else{if(d>110)mv(nx,ny,m.spd*.55);if(m.cd<=0){m.cd=1.7;m.tele=.55;enemyShot(m,8,170,.48)}}}else if(m.role==='chaser')mv(nx,ny,m.spd);else if(m.role==='flanker')mv(nx-ny*m.side*.65,ny+nx*m.side*.65,m.spd);else if(m.role==='orbiter'){mv(nx*.2-ny*m.side,ny*.2+nx*m.side,m.spd*.88);if(m.cd<=0){m.cd=1.65;enemyShot(m,3,175,.62)}}else if(m.role==='charger'){if(m.dashT>0){m.dashT-=dt;mv(Math.cos(m.aim),Math.sin(m.aim),m.spd*2.9)}else if(m.cd<=0&&d<230){m.cd=1.7;m.tele=.38;m.aim=Math.atan2(dy,dx);m.dashT=.26}else mv(nx,ny,m.spd*.72)}else if(m.role==='sniper'){if(d<190)mv(-nx,-ny,m.spd*.7);else if(d>300)mv(nx,ny,m.spd*.4);if(m.cd<=0){m.cd=1.8;m.tele=.48;enemyShot(m,1,285,.85)}}else if(m.role==='turret'){if(d<150)mv(-nx,-ny,m.spd*.45);if(m.cd<=0){m.cd=1.45;enemyShot(m,3,210,.58)}}else if(m.role==='swarm')mv(nx-ny*m.side*.35,ny+nx*m.side*.35,m.spd*1.25);else{mv(nx,ny,m.spd*.62);if(m.cd<=0&&d<105){m.cd=1.5;enemyShot(m,5,135,.48)}}if(d<player.r+m.r*.72&&player.invuln<=0)hurt(m.dmg)}
function updateShots(dt){for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.age=(s.age||0)+dt;if(s.friendly){if(s.homing){let t=null,bd=160;for(const m of mobs){const d=Math.hypot(m.x-s.x,m.y-s.y);if(d<bd&&!s.hit.has(m)){t=m;bd=d}}if(t){const ta=Math.atan2(t.y-s.y,t.x-s.x),ca=Math.atan2(s.vy,s.vx),da=Math.atan2(Math.sin(ta-ca),Math.cos(ta-ca));const na=ca+da*s.homing*60*dt,sp=Math.hypot(s.vx,s.vy);s.vx=Math.cos(na)*sp;s.vy=Math.sin(na)*sp}}if(s.path==='wave'){const a=Math.atan2(s.vy,s.vx)+Math.sin(s.age*16)*.022,speed=Math.hypot(s.vx,s.vy);s.vx=Math.cos(a)*speed;s.vy=Math.sin(a)*speed}else if(s.path==='spiral'){const a=Math.atan2(s.vy,s.vx)+.065*60*dt,speed=Math.hypot(s.vx,s.vy);s.vx=Math.cos(a)*speed;s.vy=Math.sin(a)*speed}}s.x+=s.vx*dt;s.y+=s.vy*dt;s.t-=dt;if(blocked(s.x,s.y,s.size||4)){if(s.bounce>0){s.vx*=-1;s.vy*=-1;s.bounce--}else s.t=0}if(s.friendly){for(const m of [...mobs])if(!s.hit.has(m)&&Math.hypot(m.x-s.x,m.y-s.y)<m.r+(s.size||4)){s.hit.add(m);damage(m,s.dmg,10);if(s.pierce>0)s.pierce--;else{s.t=0;break}}}else if(Math.hypot(player.x-s.x,player.y-s.y)<player.r+(s.size||5)){hurt(s.dmg);s.t=0}if(s.t<=0)shots.splice(i,1)}}
function updateDrops(dt){for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.t-=dt;if(Math.hypot(d.x-player.x,d.y-player.y)<30){if(d.type==='food'){player.hp=Math.min(player.maxHp,player.hp+16);say('♡ Health restored')}else{d.power.apply(player.wand);player.wand.rarity=clamp(player.wand.rarity+(Math.random()<.22+d.quality*.18?1:0),0,5);player.wand.name=rarity[player.wand.rarity]+' Wand';say(d.power.icon+' '+d.power.name+' · '+d.power.desc)}drops.splice(i,1)}else if(d.t<=0)drops.splice(i,1)}}
function update(dt){if(!started||dead||choice)return;time+=dt;player.attack=Math.max(0,player.attack-dt);player.invuln=Math.max(0,player.invuln-dt);toastT=Math.max(0,toastT-dt);if(toastT<=0)document.getElementById('toast').classList.remove('show');if(Math.hypot(input.mx,input.my)>.05){player.heading=Math.atan2(input.my,input.mx);moveBody(player,input.mx*player.speed*player.speedMod*dt,input.my*player.speed*player.speedMod*dt,player.r)}if(input.shoot)fire();const b=biomeAt(player.x,player.y);if(b!==lastBiome){lastBiome=b;say('✦ '+palettes[b].name)}for(const m of [...mobs])updateMob(m,dt);updateShots(dt);updateDrops(dt);spawnT-=dt;const tier=dangerAt(player.x,player.y),target=8+tier*3+Math.min(8,Math.floor(time/55));if(spawnT<=0&&mobs.length<target){spawnMob(false);spawnT=.38+Math.random()*.28}eventT-=dt;if(eventT<=0){for(let i=0;i<3+tier*2;i++)spawnMob(false);say('⚠ '+palettes[b].name.toUpperCase()+' SURGE');eventT=20+Math.random()*16}epicT-=dt;if(epicT<=0){if(!mobs.some(m=>m.epic)&&Math.random()<.18+tier*.09)spawnMob(true);epicT=26+Math.random()*28}if(player.regen&&time%1<dt&&player.hp<player.maxHp&&mobs.every(m=>dist(player,m)>220))player.hp=Math.min(player.maxHp,player.hp+player.regen);player.flow=Math.max(0,player.flow-dt*(mobs.length?2:4));updateHUD()}
function puff(x,y,col,n=7){for(let i=0;i<n;i++){const a=Math.random()*TAU,s=25+Math.random()*70;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,t:.35+Math.random()*.3,col})}}
function drawObstacle(o,cx,cy){const x=o.x-player.x+cx,y=o.y-player.y+cy,p=palettes[o.b];ctx.fillStyle='#0002';ctx.beginPath();ctx.ellipse(x,y+o.r*.7,o.r*.8,o.r*.35,0,0,TAU);ctx.fill();ctx.fillStyle=p.haz;ctx.beginPath();ctx.arc(x,y,o.r,0,TAU);ctx.fill();ctx.fillStyle=p.accent;ctx.fillRect(x-o.r*.22,y-o.r*.65,o.r*.44,o.r*.35)}
function drawMob(m,cx,cy){const x=m.x-player.x+cx,y=m.y-player.y+cy,p=palettes[m.b];ctx.save();ctx.translate(x,y);ctx.fillStyle='#0002';ctx.beginPath();ctx.ellipse(0,m.r*.65,m.r*.8,m.r*.35,0,0,TAU);ctx.fill();if(m.epic){ctx.strokeStyle='#ffd86f';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,m.r+7+Math.sin(time*5)*2,0,TAU);ctx.stroke()}ctx.fillStyle=m.hit>0?'#fff':p.haz;ctx.beginPath();ctx.arc(0,0,m.r,0,TAU);ctx.fill();ctx.fillStyle=p.accent;ctx.beginPath();ctx.arc(-m.r*.28,-m.r*.16,m.r*.18,0,TAU);ctx.arc(m.r*.28,-m.r*.16,m.r*.18,0,TAU);ctx.fill();ctx.fillStyle='#263040';ctx.beginPath();ctx.arc(-m.r*.25,-m.r*.15,2,0,TAU);ctx.arc(m.r*.25,-m.r*.15,2,0,TAU);ctx.fill();if(m.tele>0){ctx.strokeStyle='#ff6f82';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,m.r+12+Math.sin(time*12)*3,0,TAU);ctx.stroke()}if(m.epic||m.hpNow<m.max){ctx.fillStyle='#2229';ctx.fillRect(-m.r,-m.r-12,m.r*2,4);ctx.fillStyle=m.epic?'#ffd45d':'#ef7998';ctx.fillRect(-m.r,-m.r-12,m.r*2*clamp(m.hpNow/m.max,0,1),4)}ctx.restore()}
function draw(){const p=palettes[biomeAt(player.x,player.y)],cx=W/2,cy=H/2;ctx.fillStyle=p.a;ctx.fillRect(0,0,W,H);const gx=Math.floor((player.x-W/2)/48),gy=Math.floor((player.y-H/2)/48);for(let y=gy;y<gy+H/48+3;y++)for(let x=gx;x<gx+W/48+3;x++)if(hash(x,y,2)>.78){ctx.fillStyle=p.b;ctx.fillRect(x*48-player.x+cx,y*48-player.y+cy,2,2)}const ocx=Math.floor(player.x/150),ocy=Math.floor(player.y/150);for(let yy=ocy-5;yy<=ocy+5;yy++)for(let xx=ocx-5;xx<=ocx+5;xx++){const o=obstacleAt(xx*150,yy*150);if(o)drawObstacle(o,cx,cy)}for(const d of drops){const x=d.x-player.x+cx,y=d.y-player.y+cy;if(d.type==='food'){ctx.fillStyle='#ef7594';ctx.beginPath();ctx.arc(x,y,8,0,TAU);ctx.fill()}else{ctx.fillStyle='#fff8df';ctx.strokeStyle=rcol[player.wand.rarity];ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,11+Math.sin(time*6)*2,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#30384a';ctx.font='900 12px system-ui';ctx.textAlign='center';ctx.fillText(d.power.icon,x,y+4)}}for(const s of shots){ctx.fillStyle=s.friendly?rcol[player.wand.rarity]:'#ff7890';ctx.beginPath();ctx.arc(s.x-player.x+cx,s.y-player.y+cy,s.size||5,0,TAU);ctx.fill()}for(const m of mobs)drawMob(m,cx,cy);ctx.save();ctx.translate(cx,cy);ctx.rotate(player.heading);ctx.fillStyle='#0002';ctx.beginPath();ctx.ellipse(0,12,14,6,0,0,TAU);ctx.fill();ctx.fillStyle='#fff1e6';ctx.beginPath();ctx.arc(0,0,13,0,TAU);ctx.fill();ctx.fillStyle='#ef90bd';ctx.beginPath();ctx.arc(-5,-8,6,0,TAU);ctx.arc(5,-8,6,0,TAU);ctx.fill();ctx.fillStyle=rcol[player.wand.rarity];ctx.fillRect(8,-2,25,4);ctx.fillStyle='#fff';ctx.fillRect(28,-4,7,8);if(player.invuln>0){ctx.strokeStyle='#fff9';ctx.beginPath();ctx.arc(0,0,20,0,TAU);ctx.stroke()}ctx.restore();for(let i=particles.length-1;i>=0;i--){const q=particles[i];q.x+=q.vx/60;q.y+=q.vy/60;q.t-=1/60;ctx.globalAlpha=clamp(q.t*2,0,1);ctx.fillStyle=q.col;ctx.fillRect(q.x-player.x+cx,q.y-player.y+cy,3,3);ctx.globalAlpha=1;if(q.t<=0)particles.splice(i,1)}}
function updateHUD(){document.getElementById('hp').textContent=Math.max(0,Math.ceil(player.hp));document.getElementById('maxhp').textContent=player.maxHp;document.getElementById('hpfill').style.width=100*clamp(player.hp/player.maxHp,0,1)+'%';document.getElementById('lv').textContent=player.level;document.getElementById('xp').textContent=player.xp+'/'+player.xpNeed;document.getElementById('weapon').textContent=rarity[player.wand.rarity]+' Wand · '+player.wand.projectiles+'× · '+player.wand.path;document.getElementById('danger').textContent='Danger '+(dangerAt(player.x,player.y)+1);document.getElementById('biome').textContent=palettes[biomeAt(player.x,player.y)].name;document.getElementById('relics').textContent=relics;document.getElementById('flowfill').style.width=player.flow+'%'}
function say(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');toastT=2.2}
function reset(){mobs=[];shots=[];drops=[];particles=[];time=0;kills=0;relics=0;lastBiome=-1;eventT=18;epicT=32;spawnT=.5;dead=false;choice=null;input.mx=input.my=0;input.shoot=false;player.x=player.y=0;player.heading=0;player.hp=player.maxHp=52;player.level=1;player.xp=0;player.xpNeed=7;player.attack=0;player.invuln=2.4;player.flow=0;player.power=1;player.speedMod=1;player.regen=0;player.fortune=0;player.wand=freshWand();document.getElementById('death').classList.add('hide');document.getElementById('choices').classList.remove('showChoice');updateHUD()}
function die(){dead=true;started=false;input.shoot=false;document.getElementById('dtime').textContent=Math.floor(time/60)+':'+String(Math.floor(time%60)).padStart(2,'0');document.getElementById('dkills').textContent=kills;document.getElementById('dlevel').textContent=player.level;document.getElementById('drelics').textContent=relics;document.getElementById('death').classList.remove('hide')}
function start(){reset();started=true;document.getElementById('start').classList.add('hide');document.getElementById('controls').classList.remove('hide');say('Move with the joystick · hold SHOOT to cast')}
document.getElementById('play').onclick=start;document.getElementById('again').onclick=start;
const joy=document.getElementById('joystick'),knob=document.getElementById('joyknob'),shoot=document.getElementById('shoot');
function joyMove(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.31,d=Math.hypot(dx,dy)||1,k=Math.min(1,max/d),x=dx*k,y=dy*k;knob.style.transform=`translate(${x}px,${y}px)`;input.mx=x/max;input.my=y/max}
joy.addEventListener('pointerdown',e=>{if(!started||choice)return;input.moveId=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e);e.preventDefault()});joy.addEventListener('pointermove',e=>{if(e.pointerId===input.moveId)joyMove(e)});function joyEnd(e){if(e.pointerId!==input.moveId)return;input.moveId=null;input.mx=input.my=0;knob.style.transform='translate(0,0)'}joy.addEventListener('pointerup',joyEnd);joy.addEventListener('pointercancel',joyEnd);
shoot.addEventListener('pointerdown',e=>{if(!started||choice)return;input.shootId=e.pointerId;input.shoot=true;shoot.classList.add('pressed');shoot.setPointerCapture(e.pointerId);fire();e.preventDefault()});function shootEnd(e){if(e.pointerId!==input.shootId)return;input.shootId=null;input.shoot=false;shoot.classList.remove('pressed')}shoot.addEventListener('pointerup',shootEnd);shoot.addEventListener('pointercancel',shootEnd);
function loop(now){const dt=Math.min(.034,(now-last)/1000||.016);last=now;update(dt);draw();requestAnimationFrame(loop)}reset();requestAnimationFrame(loop);
window.__TWBB_V15__={version:15,biomeAt,dangerAt,spawnEpic:()=>spawnMob(true),dropRune:()=>dropPowerup(player.x+55,player.y),state:()=>({started,dead,time,kills,relics,mobs:mobs.length,wand:{...player.wand}})};
})();