(()=>{
'use strict';
const C=document.getElementById('g'),X=C.getContext('2d');X.imageSmoothingEnabled=false;
const $=id=>document.getElementById(id),rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),TAU=Math.PI*2;
let W=0,H=0,DPR=1,last=0,started=false,dead=false,paused=false,time=0,spawnT=0,shotT=0,toastT=0,screenShake=0;
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*DPR;C.height=H*DPR;C.style.width=W+'px';C.style.height=H+'px';X.setTransform(DPR,0,0,DPR,0,0);X.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const BIOMES=[
['Sunny Meadow','#9ad66f','#70b95d','#fff3a0','breeze',['Bunny','Chick','Field Mouse']],
['Birch Forest','#79bd68','#4f9258','#e7f0cf','leaves',['Squirrel','Hedgehog','Fawn']],
['Bluebell Woods','#75965d','#4c7252','#8f82d7','pollen',['Dormouse','Badger','Fox']],
['Mossy Creek','#63b79d','#46827c','#b5f0df','current',['Frog','Otter','Heron']],
['Bamboo Grove','#78b85f','#4f8d55','#d6ef8c','bamboo',['Red Panda','Macaque','Boar']],
['Tropical Jungle','#4a9e61','#2e6c4c','#efcc63','rain',['Toucan','Capybara','Jaguar']],
['Mangrove Swamp','#518c72','#315c57','#d6ce7d','mud',['Mudskipper','Caiman','Anaconda']],
['Crystal Cave','#4b526f','#33384f','#92e6ff','dark',['Bat','Cave Lizard','Bear']],
['Glowworm Grotto','#394b66','#283347','#7bf2c1','glow',['Glow Moth','Axolotl','Cave Salamander']],
['Red Canyon','#c97958','#8e503f','#ffd08a','dust',['Roadrunner','Coyote','Bighorn']],
['Desert Dunes','#d8b967','#a77c47','#fff0ad','heat',['Jerboa','Fennec','Camel']],
['Oasis Palms','#70b786','#4d8e6e','#ffe89a','mirage',['Peacock','Gazelle','Cobra']],
['Savanna','#c7b85d','#8b934c','#efd985','sun',['Meerkat','Zebra','Lion']],
['Termite Plains','#b89f5e','#846e4b','#e3c87a','mounds',['Pangolin','Warthog','Hyena']],
['Rocky Highlands','#8d967f','#68705f','#c9d1bd','wind',['Marmot','Goat','Eagle']],
['Pine Mountains','#568164','#3d5f4d','#c8e3d0','gust',['Pika','Elk','Wolf']],
['Alpine Snow','#b8d8df','#86aeb9','#ffffff','snow',['Snow Hare','Yak','Snow Leopard']],
['Frozen Lake','#9ecbd8','#6fa4b4','#dff7ff','ice',['Penguin','Seal','Polar Bear']],
['Taiga','#527369','#384f4d','#b9d2c4','frost',['Lynx','Moose','Brown Bear']],
['Autumn Forest','#c27d4c','#805641','#f4c86b','leaves',['Chipmunk','Deer','Black Bear']],
['Misty Wetlands','#73988f','#506d6d','#c6d9c7','fog',['Crane','Beaver','Alligator']],
['Volcanic Slopes','#6e5149','#49383a','#ff8c52','ash',['Fire Skink','Ram','Komodo']],
['Lava Cavern','#493f45','#2f2931','#ff6846','embers',['Lava Newt','Magma Crab','Cave Dragon']],
['Coral Shore','#63b8bd','#3d8e9b','#ffd0a8','tide',['Hermit Crab','Sea Turtle','Reef Shark']],
['Kelp Coast','#438c87','#2e6567','#8ed5a6','waves',['Sea Otter','Octopus','Orca']],
['Moonlit Marsh','#3f5570','#2a3b52','#b9b2ff','fireflies',['Owl','Marsh Cat','Night Crocodile']],
['Ancient Ruins','#746c67','#514c4a','#d3b777','runes',['Gecko','Baboon','Panther']],
['Cloud Forest','#5f8b7e','#45665e','#d1f0db','clouds',['Quetzal','Tapir','Puma']],
['Storm Peaks','#566276','#394553','#c3dcff','storm',['Alpine Fox','Ibex','Thunder Eagle']],
['Elder Wilds','#394c43','#27372f','#e6c870','wild',['Dire Wolf','Giant Bear','Elder Stag']]
].map((b,i)=>({i,name:b[0],ground:b[1],shade:b[2],accent:b[3],effect:b[4],animals:b[5]}));
const RING=780;
const state={kills:0,relics:0,discoveries:new Set(),runes:[],bestRing:0};
const player={x:0,y:0,r:12,hp:60,maxHp:60,speed:170,lv:1,xp:0,next:8,power:1,fire:1,proj:1,spread:0,pierce:0,bounce:0,homing:0,crit:.05,range:1,shield:0,heading:0};
let mobs=[],shots=[],enemyShots=[],drops=[],landmarks=[],particles=[];
const input={mx:0,my:0,shoot:false,pid:null};
function biomeIndex(x=player.x,y=player.y){return clamp(Math.floor(Math.hypot(x,y)/RING),0,BIOMES.length-1)}
function biome(){return BIOMES[biomeIndex()]}
function tierAt(x,y){return biomeIndex(x,y)+1}
function worldToScreen(x,y){return{x:W/2+(x-player.x),y:H/2+(y-player.y)}}
function hash(n){return Math.abs(Math.sin(n*127.1)*43758.5453)%1}
function cellHash(cx,cy,s=0){return hash(cx*91.7+cy*173.3+s*17.1)}
function pxRect(x,y,w,h,c){X.fillStyle=c;X.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function drawPixelAnimal(m){const p=worldToScreen(m.x,m.y),s=m.size,flip=m.vx<0?-1:1;X.save();X.translate(Math.round(p.x),Math.round(p.y));X.scale(flip,1);const u=Math.max(2,Math.round(s/6));
 X.fillStyle='#0003';X.fillRect(-3*u,2*u,6*u,2*u);
 pxRect(-3*u,-2*u,6*u,4*u,m.c);pxRect(-2*u,-4*u,4*u,3*u,m.c);pxRect(-3*u,-5*u,u,2*u,m.c);pxRect(2*u,-5*u,u,2*u,m.c);
 pxRect(-u,-4*u,u,u,'#fff7f0');pxRect(u,-4*u,u,u,'#fff7f0');pxRect(-u+1,-4*u+1,1,1,'#293143');pxRect(u+1,-4*u+1,1,1,'#293143');
 pxRect(-u,-2*u,2*u,u,m.accent);pxRect(-3*u,2*u,u,2*u,m.dark);pxRect(2*u,2*u,u,2*u,m.dark);
 if(m.elite){X.strokeStyle='#ffe77a';X.lineWidth=2;X.strokeRect(-4*u,-6*u,8*u,10*u)}X.restore();
 const bw=Math.max(18,s*2.1);if(m.hp<m.maxHp||m.elite){X.fillStyle='#1c2330aa';X.fillRect(p.x-bw/2,p.y-s-11,bw,4);X.fillStyle=m.elite?'#ffd765':'#ff7794';X.fillRect(p.x-bw/2,p.y-s-11,bw*(m.hp/m.maxHp),4)} }
function drawPlayer(){const p={x:W/2,y:H/2},u=3;X.save();X.translate(Math.round(p.x),Math.round(p.y));if(screenShake)X.translate(rnd(-screenShake,screenShake),rnd(-screenShake,screenShake));
 X.fillStyle='#0003';X.fillRect(-11,10,22,6);pxRect(-9,-9,18,20,'#fff0f5');pxRect(-7,-15,5,8,'#fff0f5');pxRect(2,-15,5,8,'#fff0f5');pxRect(-5,-6,3,3,'#293143');pxRect(3,-6,3,3,'#293143');pxRect(-2,-1,4,2,'#f28bad');pxRect(-9,8,5,5,'#e9b6c9');pxRect(4,8,5,5,'#e9b6c9');
 X.rotate(player.heading);pxRect(6,-2,15,4,'#8c684d');pxRect(18,-5,5,10,'#b8f0dd');pxRect(20,-3,5,6,'#fff0a6');X.restore(); }
function drawGround(){const b=biome(),idx=b.i;X.fillStyle=b.ground;X.fillRect(0,0,W,H);const cell=56,startX=Math.floor((player.x-W/2)/cell)-1,endX=Math.ceil((player.x+W/2)/cell)+1,startY=Math.floor((player.y-H/2)/cell)-1,endY=Math.ceil((player.y+H/2)/cell)+1;
 for(let cy=startY;cy<=endY;cy++)for(let cx=startX;cx<=endX;cx++){let wx=cx*cell,wy=cy*cell,p=worldToScreen(wx,wy),h=cellHash(cx,cy,idx);if(h>.56){X.fillStyle=b.shade;let k=3+Math.floor(h*4);X.fillRect(Math.round(p.x+8),Math.round(p.y+11),k,3);X.fillRect(Math.round(p.x+11),Math.round(p.y+8),3,k)}if(h>.78){X.fillStyle=b.accent;X.fillRect(Math.round(p.x+31),Math.round(p.y+25),4,4);X.fillRect(Math.round(p.x+29),Math.round(p.y+27),8,2)}}
 const ring=biomeIndex();if(ring<29){X.strokeStyle='#ffffff25';X.lineWidth=3;X.setLineDash([8,16]);X.beginPath();const r=(ring+1)*RING,center=worldToScreen(0,0);X.arc(center.x,center.y,r,0,TAU);X.stroke();X.setLineDash([])} }
function drawEffects(){const b=biome(),t=time;if(['rain','storm'].includes(b.effect)){X.strokeStyle='#d9efff88';X.lineWidth=1;for(let i=0;i<40;i++){let x=(i*97+t*260)%W,y=(i*53+t*420)%H;X.beginPath();X.moveTo(x,y);X.lineTo(x-4,y+10);X.stroke()}}if(b.effect==='snow'||b.effect==='frost'){X.fillStyle='#fff9';for(let i=0;i<32;i++){let x=(i*83+t*18)%W,y=(i*47+t*36)%H;X.fillRect(x,y,2,2)}}if(b.effect==='fog'||b.effect==='clouds'){X.fillStyle='#e7f3ee18';for(let i=0;i<5;i++)X.fillRect(((i*211+t*16)% (W+250))-120,80+i*100,220,44)}if(b.effect==='embers'||b.effect==='ash'){for(let i=0;i<22;i++){X.fillStyle=b.effect==='embers'?'#ffb35f88':'#d8c9be55';X.fillRect((i*79+t*(15+i%3*8))%W,(H-(i*43+t*22)%H),2,2)}}if(b.effect==='fireflies'||b.effect==='glow'){X.fillStyle='#efff7acc';for(let i=0;i<16;i++)X.fillRect((i*119+Math.sin(t+i)*25)%W,(i*61+Math.cos(t*1.2+i)*20)%H,2,2)} }
function landmarkKind(i){return['chest','shrine','camp','spring','tablet','nest'][i%6]}
function ensureLandmarks(){let ring=biomeIndex();for(let r=Math.max(0,ring-1);r<=Math.min(29,ring+1);r++)for(let j=0;j<4;j++){let a=hash(r*77+j*17)*TAU,rad=(r+.25+.45*hash(r*33+j))*RING,id=r+'-'+j;if(!landmarks.some(l=>l.id===id))landmarks.push({id,ring:r,x:Math.cos(a)*rad,y:Math.sin(a)*rad,kind:landmarkKind(r+j),used:false})}}
function drawLandmark(l){let p=worldToScreen(l.x,l.y);if(p.x<-40||p.x>W+40||p.y<-40||p.y>H+40)return;let b=BIOMES[l.ring];X.save();X.translate(Math.round(p.x),Math.round(p.y));X.fillStyle='#0003';X.fillRect(-13,9,26,6);if(l.kind==='chest'){pxRect(-12,-7,24,16,l.used?'#777':'#8b5b3f');pxRect(-12,-7,24,5,'#c88a55');pxRect(-2,-2,4,6,'#ffe77a')}else if(l.kind==='shrine'){pxRect(-8,-15,16,27,'#d8d0c4');pxRect(-12,8,24,5,'#8f8b86');pxRect(-3,-11,6,6,b.accent)}else if(l.kind==='camp'){pxRect(-14,1,28,10,'#795846');pxRect(-2,-10,4,14,'#ffb65e');pxRect(-7,-5,14,4,'#ff7f59')}else if(l.kind==='spring'){X.fillStyle='#8ce4e8';X.fillRect(-15,-4,30,13);X.fillStyle='#d7ffff';X.fillRect(-9,-1,12,2)}else if(l.kind==='tablet'){pxRect(-9,-16,18,29,'#8e918a');pxRect(-4,-10,8,3,b.accent);pxRect(-4,-4,8,3,b.accent)}else{pxRect(-14,2,28,8,'#8d6d48');pxRect(-9,-3,18,5,'#d9bf83')}X.restore(); }
function interactLandmarks(){for(let l of landmarks){if(l.used||dist(player,l)>30)continue;l.used=true;state.discoveries.add(l.id);if(l.kind==='chest'){dropRune(l.x,l.y,true);dropRune(l.x+12,l.y,true);toast('Treasure cache! Two charms found ✦')}else if(l.kind==='shrine'){player.maxHp+=4;player.hp=Math.min(player.maxHp,player.hp+16);state.relics++;toast('Ancient shrine: +4 max hearts ◇')}else if(l.kind==='spring'){player.hp=Math.min(player.maxHp,player.hp+28);toast('Restorative spring ♡')}else if(l.kind==='camp'){player.shield=Math.min(30,player.shield+12);toast('Trail camp: gained 12 ward')}else if(l.kind==='tablet'){player.power*=1.04;toast('Wild rune: wand power increased')}else{gainXP(4+tierAt(l.x,l.y));toast('Curious nest: knowledge gained')}updateHUD()}}
const animalColors=['#f5c7b8','#cba67a','#d8c2a0','#93a96f','#b9958a','#91b6b0','#d49c65','#a1a5c2'];
function spawnMob(forceElite=false){let ring=biomeIndex(),b=BIOMES[ring],ang=rnd(0,TAU),rad=Math.max(W,H)*.7+rnd(80,180),x=player.x+Math.cos(ang)*rad,y=player.y+Math.sin(ang)*rad,actual=tierAt(x,y),species=b.animals[Math.min(2,Math.floor(Math.random()*3))],ferocity=1+actual*.16,size=9+actual*.72+rnd(-2,3),elite=forceElite||(actual%5===0&&Math.random()<.035),hp=(13+actual*4.8)*(elite?4.5:1),role=actual<5?'skitter':actual<10?'chase':actual<16?'pounce':actual<22?'strafe':'apex';mobs.push({x,y,vx:0,vy:0,size,hp,maxHp:hp,species,ring:actual-1,role,elite,c:animalColors[(actual+species.length)%animalColors.length],dark:'#6f5d55',accent:b.accent,hit:0,atk:rnd(.2,1.2),phase:rnd(0,TAU),ferocity})}
function updateMob(m,dt){let dx=player.x-m.x,dy=player.y-m.y,d=Math.hypot(dx,dy)||1,nx=dx/d,ny=dy/d,s=42+m.ferocity*12;if(m.role==='skitter'){s*=.72;nx+=Math.sin(time*2+m.phase)*.25;ny+=Math.cos(time*2+m.phase)*.25}else if(m.role==='pounce'&&m.atk<.2)s*=3.2;else if(m.role==='strafe'){let tx=-ny,ty=nx;nx=nx*.55+tx*Math.sin(time+m.phase)*.75;ny=ny*.55+ty*Math.sin(time+m.phase)*.75}else if(m.role==='apex')s*=1.12;m.vx=nx*s;m.vy=ny*s;m.x+=m.vx*dt;m.y+=m.vy*dt;m.atk-=dt;m.hit=Math.max(0,m.hit-dt);
 if(d<m.size+12&&m.atk<=0){damagePlayer((4+m.ferocity*1.4)*(m.elite?1.55:1));m.atk=.75;let k=18;m.x-=nx*k;m.y-=ny*k}
 if((m.role==='strafe'||m.role==='apex')&&m.atk<=0&&d<430){enemyShots.push({x:m.x,y:m.y,vx:nx*(125+m.ferocity*8),vy:ny*(125+m.ferocity*8),life:3,damage:3+m.ferocity,r:4+(m.elite?2:0),c:BIOMES[m.ring].accent});m.atk=m.role==='apex'?.6:1.2}}
function damagePlayer(n){if(player.shield>0){let a=Math.min(player.shield,n);player.shield-=a;n-=a}if(n<=0)return;player.hp-=n;screenShake=5;particlesBurst(player.x,player.y,'#ff7794',8);if(player.hp<=0)gameOver();updateHUD()}
function nearestTarget(){let best=null,bd=460*player.range;for(let m of mobs){let d=dist(player,m);if(d<bd){bd=d;best=m}}return best}
function fire(){if(shotT>0||paused||dead)return;let t=nearestTarget(),a=t?Math.atan2(t.y-player.y,t.x-player.x):player.heading;player.heading=a;let count=player.proj,spread=player.spread||(.12*(count-1)),base=.32/player.fire;shotT=base;for(let i=0;i<count;i++){let off=count===1?0:(i-(count-1)/2)*spread/Math.max(1,count-1),aa=a+off,spd=390+player.lv*2;shots.push({x:player.x+Math.cos(aa)*18,y:player.y+Math.sin(aa)*18,vx:Math.cos(aa)*spd,vy:Math.sin(aa)*spd,life:1.15*player.range,damage:(8+player.lv*.65)*player.power,pierce:player.pierce,bounce:player.bounce,hit:new Set(),r:4+Math.min(3,player.power-1),c:biome().accent,crit:Math.random()<player.crit})}particlesBurst(player.x+Math.cos(a)*18,player.y+Math.sin(a)*18,biome().accent,3)}
function updateShots(dt){for(let s of shots){if(player.homing&&mobs.length){let t=mobs.reduce((a,b)=>dist(s,b)<dist(s,a)?b:a,mobs[0]),a=Math.atan2(t.y-s.y,t.x-s.x),spd=Math.hypot(s.vx,s.vy),ca=Math.atan2(s.vy,s.vx),dif=Math.atan2(Math.sin(a-ca),Math.cos(a-ca));ca+=dif*Math.min(1,dt*player.homing);s.vx=Math.cos(ca)*spd;s.vy=Math.sin(ca)*spd}s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(let m of mobs){if(s.hit.has(m)||dist(s,m)>m.size+s.r)continue;s.hit.add(m);let dmg=s.damage*(s.crit?1.8:1);m.hp-=dmg;m.hit=.08;particlesBurst(m.x,m.y,s.c,5);if(m.hp<=0)killMob(m);if(s.pierce>0)s.pierce--;else{s.life=0;break}}}shots=shots.filter(s=>s.life>0);for(let s of enemyShots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(dist(s,player)<s.r+10){damagePlayer(s.damage);s.life=0}}enemyShots=enemyShots.filter(s=>s.life>0)}
function killMob(m){let i=mobs.indexOf(m);if(i>=0)mobs.splice(i,1);state.kills++;gainXP(1+Math.floor((m.ring+1)/3));particlesBurst(m.x,m.y,m.accent,m.elite?18:8);let chance=.22+(m.ring*.006);if(m.elite||Math.random()<chance)dropRune(m.x,m.y,m.elite);else if(Math.random()<.1)drops.push({x:m.x,y:m.y,type:'berry',life:16,spin:0});if(m.elite){state.relics++;toast('Apex '+m.species+' defeated! ◇')}updateHUD()}
const RUNES=[
['Quickleaf','fire',1.12,'Faster casting'],['Star Seed','power',1.13,'Stronger bolts'],['Twin Petal','proj',1,'Extra projectile'],['Needle Fern','pierce',1,'Piercing'],['Moon Eye','homing',.8,'Seeking shots'],['Longtail','range',1.12,'Longer reach'],['Lucky Bell','crit',.04,'Critical chance'],['Thorn Crown','spread',.08,'Wider volley'],['Heart Berry','maxHp',5,'More hearts'],['Swift Paw','speed',8,'Move faster']];
function dropRune(x,y,rare=false){let r=RUNES[Math.floor(Math.random()*RUNES.length)];drops.push({x:x+rnd(-10,10),y:y+rnd(-10,10),type:'rune',rune:r,rare,life:22,spin:0})}
function applyRune(r,rare){let [name,key,val]=r,m=rare?1.45:1;if(key==='fire')player.fire*=1+(val-1)*m;else if(key==='power')player.power*=1+(val-1)*m;else if(key==='proj')player.proj=Math.min(7,player.proj+1);else if(key==='pierce')player.pierce=Math.min(6,player.pierce+1);else if(key==='homing')player.homing=Math.min(8,player.homing+val*m);else if(key==='range')player.range*=1+(val-1)*m;else if(key==='crit')player.crit=Math.min(.45,player.crit+val*m);else if(key==='spread')player.spread=Math.min(.65,player.spread+val*m);else if(key==='maxHp'){player.maxHp+=Math.round(val*m);player.hp+=Math.round(val*m)}else if(key==='speed')player.speed+=val*m;state.runes.push(name);toast((rare?'Rare ':'')+name+' ✦ '+r[3]);updateHUD()}
function updateDrops(dt){for(let d of drops){d.life-=dt;d.spin+=dt*3;let dd=dist(d,player);if(dd<95){let k=Math.min(1,dt*6);d.x+=(player.x-d.x)*k;d.y+=(player.y-d.y)*k}if(dd<18){d.life=0;if(d.type==='rune')applyRune(d.rune,d.rare);else{player.hp=Math.min(player.maxHp,player.hp+12);toast('Sweet berry +12 hearts');updateHUD()}}}drops=drops.filter(d=>d.life>0)}
function drawDrop(d){let p=worldToScreen(d.x,d.y);X.save();X.translate(Math.round(p.x),Math.round(p.y));let bob=Math.sin(d.spin)*3;if(d.type==='rune'){X.fillStyle=d.rare?'#ffe77a':'#fff5c2';X.fillRect(-5,-6+bob,10,10);X.fillStyle=BIOMES[biomeIndex(d.x,d.y)].accent;X.fillRect(-2,-3+bob,4,4)}else{X.fillStyle='#e95e7d';X.fillRect(-5,-4+bob,10,8);X.fillStyle='#6da55b';X.fillRect(0,-7+bob,3,4)}X.restore()}
function gainXP(n){player.xp+=n;while(player.xp>=player.next){player.xp-=player.next;player.lv++;player.next=Math.floor(player.next*1.28+3);player.maxHp+=2;player.hp=Math.min(player.maxHp,player.hp+8);player.power*=1.025;player.fire*=1.012;toast('Level '+player.lv+'! Wild magic grows ✦')}updateHUD()}
function particlesBurst(x,y,c,n){for(let i=0;i<n;i++)particles.push({x,y,vx:rnd(-70,70),vy:rnd(-70,70),life:rnd(.2,.55),c})}
function updateParticles(dt){for(let p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;p.life-=dt}particles=particles.filter(p=>p.life>0)}
function drawParticles(){for(let p of particles){let q=worldToScreen(p.x,p.y);X.globalAlpha=clamp(p.life*3,0,1);X.fillStyle=p.c;X.fillRect(Math.round(q.x),Math.round(q.y),3,3)}X.globalAlpha=1}
function envPhysics(dt){let e=biome().effect;if(e==='mud')player.envSlow=.83;else if(e==='ice')player.envSlow=1.08;else if(e==='heat'||e==='ash')player.envSlow=.92;else player.envSlow=1;if(e==='current'){player.x+=Math.sin(time*.7)*9*dt;player.y+=5*dt}if(e==='gust'||e==='wind'||e==='storm')player.x+=Math.sin(time*1.3)*12*dt}
function update(dt){time+=dt;shotT=Math.max(0,shotT-dt);screenShake=Math.max(0,screenShake-dt*18);envPhysics(dt);let mag=Math.hypot(input.mx,input.my);if(mag>.05){let nx=input.mx/mag,ny=input.my/mag,s=player.speed*(player.envSlow||1)*Math.min(1,mag);player.x+=nx*s*dt;player.y+=ny*s*dt;player.heading=Math.atan2(ny,nx)}if(input.shoot)fire();
 let ring=biomeIndex();if(ring>state.bestRing){state.bestRing=ring;toast('Discovered: '+BIOMES[ring].name+' ✦ '+BIOMES[ring].animals.join(' · '));state.relics++;updateHUD()}
 ensureLandmarks();interactLandmarks();spawnT-=dt;let cap=10+Math.min(24,ring);if(spawnT<=0&&mobs.length<cap){spawnMob(false);spawnT=Math.max(.18,1.05-ring*.022)}for(let m of [...mobs])updateMob(m,dt);updateShots(dt);updateDrops(dt);updateParticles(dt);mobs=mobs.filter(m=>dist(m,player)<1300);landmarks=landmarks.filter(l=>Math.abs(l.ring-ring)<=2);if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}}
function draw(){drawGround();for(let l of landmarks)drawLandmark(l);for(let d of drops)drawDrop(d);for(let s of shots){let p=worldToScreen(s.x,s.y);X.fillStyle=s.crit?'#fff4a3':s.c;X.fillRect(Math.round(p.x-s.r),Math.round(p.y-s.r),s.r*2,s.r*2);X.fillStyle='#fff';X.fillRect(Math.round(p.x-1),Math.round(p.y-1),2,2)}for(let s of enemyShots){let p=worldToScreen(s.x,s.y);X.fillStyle=s.c;X.fillRect(Math.round(p.x-s.r),Math.round(p.y-s.r),s.r*2,s.r*2)}for(let m of mobs)drawPixelAnimal(m);drawParticles();drawPlayer();drawEffects();drawCompass()}
function drawCompass(){let ring=biomeIndex(),next=(ring+1)*RING,rad=Math.hypot(player.x,player.y),remain=Math.max(0,next-rad),b=biome();X.save();X.globalAlpha=.9;X.fillStyle='#172033aa';X.fillRect(W/2-72,42,144,26);X.fillStyle='#fff';X.font='900 9px monospace';X.textAlign='center';X.fillText(b.name.toUpperCase(),W/2,53);X.fillStyle=b.accent;X.fillText(ring<29?Math.ceil(remain)+'m TO '+BIOMES[ring+1].name.toUpperCase():'HEART OF THE ELDER WILDS',W/2,64);X.restore()}
function updateHUD(){let b=biome(),r=biomeIndex();$('hp').textContent=Math.max(0,Math.ceil(player.hp));$('maxhp').textContent=Math.ceil(player.maxHp);$('hpfill').style.width=(100*clamp(player.hp/player.maxHp,0,1))+'%';$('lv').textContent=player.lv;$('xp').textContent=Math.floor(player.xp)+'/'+player.next;$('biome').textContent=(r+1)+'/30 '+b.name;$('weapon').textContent=player.proj+'× Wand · '+player.fire.toFixed(1)+' rate · '+(player.power).toFixed(1)+' power';$('danger').textContent='Wild '+(r+1);$('relics').textContent=state.relics;$('flowfill').style.width=clamp(player.shield/30*100,0,100)+'%'}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');toastT=2.4}
function reset(){player.x=player.y=0;Object.assign(player,{hp:60,maxHp:60,speed:170,lv:1,xp:0,next:8,power:1,fire:1,proj:1,spread:0,pierce:0,bounce:0,homing:0,crit:.05,range:1,shield:0,heading:0});mobs=[];shots=[];enemyShots=[];drops=[];landmarks=[];particles=[];state.kills=0;state.relics=0;state.bestRing=0;state.discoveries.clear();state.runes=[];time=0;dead=false;paused=false;spawnT=0;updateHUD()}
function gameOver(){dead=true;paused=true;$('controls').classList.add('hide');$('death').classList.remove('hide');$('dlevel').textContent=player.lv;$('dtime').textContent=Math.floor(time/60)+':'+String(Math.floor(time%60)).padStart(2,'0');$('dkills').textContent=state.kills;$('drelics').textContent=state.relics}
function loop(ts){let dt=Math.min(.033,(ts-last)/1000||0);last=ts;if(started&&!paused&&!dead)update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
const joy=$('joystick'),knob=$('joyknob');function joyMove(e){if(input.pid!==e.pointerId)return;let r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),lim=r.width*.34,d=Math.hypot(dx,dy)||1,k=Math.min(1,lim/d);dx*=k;dy*=k;knob.style.transform=`translate(${dx}px,${dy}px)`;input.mx=dx/lim;input.my=dy/lim}joy.onpointerdown=e=>{input.pid=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e)};joy.onpointermove=joyMove;function joyEnd(e){if(input.pid!==e.pointerId)return;input.pid=null;input.mx=input.my=0;knob.style.transform='translate(0,0)'}joy.onpointerup=joyEnd;joy.onpointercancel=joyEnd;
const shoot=$('shoot');shoot.onpointerdown=e=>{e.preventDefault();shoot.setPointerCapture(e.pointerId);input.shoot=true;shoot.classList.add('pressed');fire()};function shootEnd(){input.shoot=false;shoot.classList.remove('pressed')}shoot.onpointerup=shootEnd;shoot.onpointercancel=shootEnd;
$('play').onclick=()=>{reset();started=true;$('start').classList.add('hide');$('controls').classList.remove('hide');toast('The tiny trail begins…')};$('again').onclick=()=>{reset();$('death').classList.add('hide');$('controls').classList.remove('hide')};
window.__TWBB_V16__={version:16,biomes:BIOMES,state:()=>({ring:biomeIndex()+1,biome:biome().name,player:{...player},kills:state.kills,relics:state.relics,runes:[...state.runes]}),dropRune:()=>dropRune(player.x+30,player.y,true),warp:n=>{let i=clamp((n|0)-1,0,29);player.x=i*RING+20;player.y=0;updateHUD()},spawnApex:()=>spawnMob(true)};
})();