(()=>{'use strict';
const C=document.getElementById('g'),X=C.getContext('2d'),BIOMES=window.TWBB_WORLD;X.imageSmoothingEnabled=false;
const $=id=>document.getElementById(id),TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
let W=0,H=0,DPR=1,last=0,started=false,dead=false,paused=false,time=0,spawnT=0,shotT=0,toastT=0,screenShake=0;
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*DPR;C.height=H*DPR;C.style.width=W+'px';C.style.height=H+'px';X.setTransform(DPR,0,0,DPR,0,0);X.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const RING=780,state={kills:0,relics:0,discoveries:new Set(),runes:[],bestRing:0,places:0};
const player={x:0,y:0,r:12,hp:60,maxHp:60,speed:170,lv:1,xp:0,next:8,power:1,fire:1,proj:1,spread:0,pierce:0,bounce:0,homing:0,crit:.05,range:1,shield:0,heading:0,envSlow:1};
let mobs=[],shots=[],enemyShots=[],drops=[],landmarks=[],particles=[];
const input={mx:0,my:0,shoot:false,pid:null};
function biomeIndex(x=player.x,y=player.y){return clamp(Math.floor(Math.hypot(x,y)/RING),0,29)}function biome(){return BIOMES[biomeIndex()]}function tierAt(x,y){return biomeIndex(x,y)+1}function worldToScreen(x,y){return{x:W/2+x-player.x,y:H/2+y-player.y}}
function hash(n){return Math.abs(Math.sin(n*127.1+Math.cos(n*9.13))*43758.5453)%1}function h2(x,y,s=0){return hash(x*91.7+y*173.3+s*31.7)}function choose(arr,h){return arr[Math.floor(h*arr.length)%arr.length]}function px(x,y,w,h,c){X.fillStyle=c;X.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function visible(p,m=80){return p.x>-m&&p.x<W+m&&p.y>-m&&p.y<H+m}
function shadow(x,y,w){X.fillStyle='#14201933';X.fillRect(Math.round(x-w/2),Math.round(y),Math.round(w),5)}
function drawPlant(type,x,y,s,b,h){const p=worldToScreen(x,y);if(!visible(p,60))return;X.save();X.translate(Math.round(p.x),Math.round(p.y));let c=b.accent,d=b.shade,g=b.ground,u=Math.max(1,Math.round(s));
 if(/birch|pine|fir|tree|oak|maple|willow|palm|baobab|acacia/i.test(type)){shadow(0,8,20*u);let trunk=/birch/.test(type)?'#ede7d1':'#745441';px(-2*u,-2*u,4*u,14*u,trunk);let leaf=/snow|storm|fir|pine/i.test(type)?'#557467':/autumn|maple/.test(type)?'#db8452':/palm|date/i.test(type)?'#5d9b58':b.shade;if(/palm|date/.test(type)){for(let a=0;a<6;a++){let aa=a*TAU/6;px(Math.cos(aa)*8*u-4*u,-10*u+Math.sin(aa)*3*u,8*u,3*u,leaf)}}else if(/baobab/.test(type)){px(-10*u,-12*u,20*u,8*u,leaf);px(-7*u,-16*u,14*u,6*u,leaf)}else{px(-8*u,-10*u,16*u,8*u,leaf);px(-6*u,-15*u,12*u,8*u,leaf);if(/pine|fir|snowPine|stormPine/.test(type)){px(-7*u,-13*u,14*u,4*u,leaf);px(-5*u,-18*u,10*u,5*u,leaf);px(-3*u,-22*u,6*u,5*u,leaf)}}}
 else if(/bamboo/.test(type)){for(let i=-1;i<=1;i++){px(i*5*u,-18*u,3*u,22*u,'#5d9b58');px(i*5*u-2*u,-12*u,7*u,2*u,'#89c86f')}}
 else if(/cactus/.test(type)){px(-3*u,-14*u,6*u,17*u,'#5aa56c');px(-7*u,-8*u,4*u,3*u,'#5aa56c');px(4*u,-11*u,4*u,3*u,'#5aa56c');if(h>.7)px(-2*u,-17*u,4*u,4*u,'#f2a6bd')}
 else if(/crystal|obsidian|iceSpikes|stalagmite|lavaCrystal/i.test(type)){let cc=/lava/.test(type)?'#ff724d':/obsidian/.test(type)?'#343044':/ice/.test(type)?'#dff7ff':c;px(-4*u,-10*u,5*u,12*u,cc);px(2*u,-16*u,5*u,18*u,cc);px(7*u,-7*u,4*u,9*u,cc);px(3*u,-13*u,2*u,5*u,'#fff8')}
 else if(/mushroom/i.test(type)){px(-1*u,-5*u,2*u,7*u,'#e8d9c0');px(-5*u,-8*u,10*u,4*u,/glow|fire/.test(type)?c:'#d7858d');if(/glow/.test(type)){X.globalAlpha=.15;X.fillStyle=c;X.beginPath();X.arc(0,-6*u,11*u,0,TAU);X.fill();X.globalAlpha=1}}
 else if(/reed|cattail|grass|heather|scrub|bush|fern|moss|kelp|seaGrass|lichen|ivy|vine|monstera|papyrus|juniper/i.test(type)){let cc=/kelp|reed|moss|fern|ivy|vine|monstera/.test(type)?b.shade:'#7da75d';for(let i=0;i<4;i++){let xx=(-5+i*3)*u,hh=(5+h2(i,h,2)*8)*u;px(xx,-hh,2*u,hh,cc)}if(/cattail/.test(type))px(-5*u,-12*u,3*u,5*u,'#795744')}
 else if(/flower|daisy|buttercup|clover|tulip|sunflower|bluebell|orchid|foxglove|bromeliad/i.test(type)){px(-1*u,-5*u,2*u,7*u,'#5f9d55');let cc=/sunflower|buttercup/.test(type)?'#ffe06f':/bluebell/.test(type)?'#8f82d7':/orchid|foxglove|tulip/.test(type)?'#ef9ac2':c;px(-4*u,-8*u,8*u,3*u,cc);px(-2*u,-10*u,4*u,7*u,cc)}
 else if(/termiteMound|dune|snowdrift/i.test(type)){let cc=/snow/.test(type)?'#edf9ff':/dune/.test(type)?'#e8cf85':'#9e754e';px(-9*u,-4*u,18*u,7*u,cc);px(-5*u,-9*u,10*u,8*u,cc)}
 else{px(-4*u,-5*u,8*u,7*u,b.shade)}X.restore()}
function drawProp(type,x,y,s,b,h){const p=worldToScreen(x,y);if(!visible(p,70))return;X.save();X.translate(Math.round(p.x),Math.round(p.y));let u=Math.max(1,Math.round(s));shadow(0,5,15*u);
 if(/rock|boulder|stone|obsidian|cairn/i.test(type)){let cc=/obsidian/.test(type)?'#343044':'#817b74';px(-7*u,-4*u,14*u,8*u,cc);px(-4*u,-8*u,8*u,5*u,'#9a958c');if(/cairn/.test(type)){px(-4*u,-11*u,8*u,4*u,cc);px(-2*u,-14*u,4*u,3*u,cc)}}
 else if(/log|driftwood|woodpile|root|fallen/i.test(type)){px(-10*u,-3*u,20*u,6*u,'#73533d');px(-9*u,-2*u,4*u,4*u,'#9d7755');if(/woodpile/.test(type))px(-8*u,-8*u,16*u,5*u,'#8a6243')}
 else if(/stump/.test(type)){px(-6*u,-7*u,12*u,10*u,'#74513e');px(-5*u,-9*u,10*u,4*u,'#aa7f5c')}
 else if(/sign/.test(type)){px(-2*u,-9*u,4*u,14*u,'#795b43');px(-8*u,-13*u,16*u,7*u,'#b98b5a');px(-4*u,-11*u,8*u,2*u,'#6f543d')}
 else if(/fence|bambooFence/i.test(type)){let cc=/bamboo/.test(type)?'#719b50':'#9b724c';px(-12*u,-6*u,24*u,3*u,cc);px(-12*u,0,24*u,3*u,cc);px(-10*u,-9*u,3*u,14*u,cc);px(7*u,-9*u,3*u,14*u,cc)}
 else if(/bones|skull|antler|fossil/i.test(type)){px(-7*u,-2*u,14*u,3*u,'#e8dfc7');px(-2*u,-6*u,4*u,10*u,'#e8dfc7');if(/skull/.test(type)){px(-5*u,-8*u,10*u,7*u,'#e8dfc7');px(-3*u,-6*u,2*u,2*u,'#4a413b');px(2*u,-6*u,2*u,2*u,'#4a413b')}}
 else if(/lantern|torch|lightningRod/i.test(type)){px(-1*u,-9*u,2*u,13*u,'#5b4d49');px(-4*u,-13*u,8*u,7*u,b.accent);X.globalAlpha=.12;X.fillStyle=b.accent;X.beginPath();X.arc(0,-10*u,12*u,0,TAU);X.fill();X.globalAlpha=1}
 else if(/barrel|crate|basket|pottery|hay|pumpkin|fishCrate|fruitCrate|caravanCrate/i.test(type)){let cc=/pottery/.test(type)?'#b76d51':/hay/.test(type)?'#d3ad54':/pumpkin/.test(type)?'#d98042':'#8c6748';px(-7*u,-7*u,14*u,12*u,cc);px(-6*u,-4*u,12*u,2*u,'#0002')}
 else if(/anchor/.test(type)){px(-2*u,-12*u,4*u,16*u,'#5b636c');px(-8*u,-1*u,16*u,3*u,'#5b636c');px(-8*u,-1*u,3*u,6*u,'#5b636c');px(5*u,-1*u,3*u,6*u,'#5b636c')}
 else if(/shell|starfish/.test(type)){px(-5*u,-4*u,10*u,8*u,/starfish/.test(type)?'#e99973':'#f2d4b4')}
 else if(/totem|ruinPillar|brokenStatue|ancientStone/i.test(type)){px(-6*u,-14*u,12*u,18*u,'#7d7c71');px(-8*u,-17*u,16*u,4*u,'#9a9786');px(-3*u,-10*u,6*u,3*u,b.accent)}
 else{px(-6*u,-6*u,12*u,10*u,'#8c735d')}X.restore()}
function drawStructure(type,x,y,b,h,large=false){const p=worldToScreen(x,y);if(!visible(p,130))return;X.save();X.translate(Math.round(p.x),Math.round(p.y));let S=large?1.2:1;shadow(0,25*S,64*S);let wall='#d8c39d',wood='#79583e',roof=b.shade,light=b.accent;
 if(/bridge|boardwalk|ropeBridge|lavaBridge/i.test(type)){px(-45*S,-7*S,90*S,14*S,/lava/.test(type)?'#6e4a3f':'#9b724c');for(let i=-36;i<=36;i+=12)px(i*S,-10*S,4*S,20*S,'#6e523e');if(/rope/.test(type)){px(-45*S,-18*S,4*S,30*S,'#6e523e');px(41*S,-18*S,4*S,30*S,'#6e523e')}}
 else if(/tower|lighthouse|obelisk/i.test(type)){px(-13*S,-42*S,26*S,66*S,/lighthouse/.test(type)?'#e8e3cf':'#8b887f');px(-18*S,-47*S,36*S,8*S,roof);px(-8*S,-30*S,7*S,8*S,light);px(2*S,-30*S,7*S,8*S,light);if(/lighthouse/.test(type)){px(-10*S,-50*S,20*S,9*S,'#fff0a4');X.globalAlpha=.08;X.fillStyle='#fff8b7';X.beginPath();X.moveTo(0,-46*S);X.lineTo(90*S,-62*S);X.lineTo(90*S,-32*S);X.fill();X.globalAlpha=1}}
 else if(/shrine|temple|pagoda|altar/i.test(type)){px(-24*S,-22*S,48*S,44*S,'#87877c');px(-31*S,-27*S,62*S,8*S,'#a09e8e');px(-17*S,-42*S,34*S,18*S,roof);px(-5*S,-16*S,10*S,14*S,light);if(/temple|pagoda/.test(type)){px(-20*S,-48*S,40*S,6*S,roof);px(-15*S,-58*S,30*S,12*S,roof)}}
 else if(/gate|arch/i.test(type)){px(-28*S,-38*S,10*S,62*S,'#88867d');px(18*S,-38*S,10*S,62*S,'#88867d');px(-28*S,-42*S,56*S,10*S,'#9d9a8c');px(-14*S,-35*S,28*S,5*S,light)}
 else if(/windmill/i.test(type)){px(-15*S,-28*S,30*S,50*S,wall);px(-18*S,-33*S,36*S,10*S,roof);X.strokeStyle=wood;X.lineWidth=4*S;for(let a=0;a<4;a++){X.beginPath();X.moveTo(0,-18*S);X.lineTo(Math.cos(a*Math.PI/2)*33*S,-18*S+Math.sin(a*Math.PI/2)*33*S);X.stroke()}}
 else if(/well/i.test(type)){px(-18*S,-8*S,36*S,22*S,'#8d887d');px(-20*S,-12*S,40*S,7*S,'#a9a49a');px(-15*S,-28*S,4*S,20*S,wood);px(11*S,-28*S,4*S,20*S,wood);px(-17*S,-31*S,34*S,5*S,roof)}
 else if(/dock|boat|boathouse/i.test(type)){px(-35*S,2*S,70*S,10*S,wood);for(let i=-30;i<=30;i+=15)px(i*S,-1*S,4*S,17*S,'#5e493a');if(/boat/.test(type)){px(-23*S,-15*S,46*S,14*S,'#825e45');px(-15*S,-20*S,30*S,6*S,'#b28158')}}
 else if(/mine|lift/i.test(type)){px(-30*S,-30*S,60*S,52*S,'#34353b');px(-25*S,-35*S,7*S,60*S,wood);px(18*S,-35*S,7*S,60*S,wood);px(-25*S,-38*S,50*S,7*S,wood);px(-15*S,-20*S,30*S,6*S,'#15161a')}
 else if(/forge/i.test(type)){px(-28*S,-20*S,56*S,42*S,'#6e5a50');px(-32*S,-25*S,64*S,8*S,'#40383a');px(-8*S,-11*S,16*S,18*S,'#ff794d');px(15*S,-40*S,9*S,30*S,'#564a46')}
 else if(/camp|tent|caravan|market|picnic/i.test(type)){if(/tent|camp|picnic/.test(type)){X.fillStyle=/picnic/.test(type)?'#e89db8':'#d6a36d';X.beginPath();X.moveTo(-24*S,18*S);X.lineTo(0,-24*S);X.lineTo(24*S,18*S);X.fill();px(-4*S,0,8*S,18*S,'#664a3b')}else{px(-30*S,-18*S,60*S,38*S,'#b7885c');px(-34*S,-24*S,68*S,8*S,roof);for(let i=-20;i<=20;i+=20)px(i*S,-12*S,10*S,10*S,light)}}
 else{px(-28*S,-20*S,56*S,42*S,wall);px(-33*S,-26*S,66*S,10*S,roof);px(-22*S,-13*S,12*S,12*S,light);px(10*S,-13*S,12*S,12*S,light);px(-7*S,3*S,14*S,19*S,wood);if(/treehouse/.test(type)){px(-3*S,20*S,6*S,28*S,wood);px(-18*S,12*S,36*S,7*S,wood)}}
 X.restore();}
function drawFeature(type,x,y,b,h){const p=worldToScreen(x,y);if(!visible(p,170))return;X.save();X.translate(Math.round(p.x),Math.round(p.y));let water='#69bfc4';
 if(/pond|pool|hole|watering|bog|tide|oasis|lake/i.test(type)){X.fillStyle=/lava/.test(type)?'#ff6948':/frozen|ice/.test(type)?'#cfefff':water;X.beginPath();X.ellipse(0,0,55+h*25,25+h*14,0,0,TAU);X.fill();X.globalAlpha=.35;X.fillStyle='#fff';X.fillRect(-24,-7,28,3);X.globalAlpha=1}
 else if(/stream|river/i.test(type)){X.fillStyle=/lava/.test(type)?'#ff6846':water;X.fillRect(-80,-12-h*8,160,24+h*16);X.globalAlpha=.25;X.fillStyle='#fff';for(let i=-60;i<70;i+=30)X.fillRect(i,-4,18,2);X.globalAlpha=1}
 else if(/waterfall/i.test(type)){px(-30,-60,60,80,b.shade);px(-14,-55,28,66,'#7fd5d9');px(-23,10,46,14,'#69bfc4');X.globalAlpha=.4;px(-10,-50,8,55,'#fff');X.globalAlpha=1}
 else if(/chasm|ravine|cliff|crater/i.test(type)){X.fillStyle='#252632';X.beginPath();X.ellipse(0,5,62+h*20,25+h*12,0,0,TAU);X.fill();px(-55,-4,110,5,b.shade)}
 else if(/grove|forest|thicket|maze|garden|field|patch|orchard/i.test(type)){for(let i=0;i<10;i++){let a=i*2.399+h*TAU,r=18+(i%4)*13,t=choose(b.flora,h2(i,h,8));drawPlant(t,x+Math.cos(a)*r,y+Math.sin(a)*r,1,b,h2(i,h,9))}}
 else if(/ruin|hall|courtyard/i.test(type)){for(let i=0;i<5;i++){let a=i*TAU/5,r=35;drawProp(i%2?'ruinPillar':'ancientStone',x+Math.cos(a)*r,y+Math.sin(a)*r,1,b,h2(i,h,4))}px(-18,-3,36,6,'#8f8b80')}
 else if(/stoneCircle|rockArch|stepping|stonePath/i.test(type)){for(let i=0;i<8;i++){let a=i*TAU/8,r=/Path/.test(type)?0:34,xx=/Path/.test(type)?(i-4)*15:Math.cos(a)*r,yy=/Path/.test(type)?Math.sin(i)*5:Math.sin(a)*r;drawProp('rock',x+xx,y+yy,.8,b,h)}}
 else if(/shipwreck/i.test(type)){px(-50,-5,100,12,'#664b3a');px(-35,-18,70,10,'#8c6748');px(-3,-50,6,42,'#604939');px(3,-45,35,4,'#d9d1bb')}
 else if(/fossil/i.test(type)){for(let i=0;i<7;i++){let a=i*TAU/7;drawProp('bones',x+Math.cos(a)*38,y+Math.sin(a)*18,.8,b,h)}}
 else{for(let i=0;i<7;i++){let a=i*TAU/7;drawProp(choose(b.props,h2(i,h,3)),x+Math.cos(a)*35,y+Math.sin(a)*22,.8,b,h)}}X.restore()}
function drawTrail(){let b=biome(),rad=Math.hypot(player.x,player.y),a=Math.atan2(player.y,player.x),center=worldToScreen(0,0);X.save();X.globalAlpha=.16;X.strokeStyle='#f5e0ba';X.lineWidth=18;X.beginPath();let start=Math.max(0,rad-900),end=rad+900;for(let r=start;r<=end;r+=80){let aa=a+Math.sin(r*.003)*.12,p=worldToScreen(Math.cos(aa)*r,Math.sin(aa)*r);if(r===start)X.moveTo(p.x,p.y);else X.lineTo(p.x,p.y)}X.stroke();X.restore()}
function drawDenseWorld(){const b=biome(),idx=b.i;X.fillStyle=b.ground;X.fillRect(0,0,W,H);drawTrail();
 const cell=64,sx=Math.floor((player.x-W/2)/cell)-2,ex=Math.ceil((player.x+W/2)/cell)+2,sy=Math.floor((player.y-H/2)/cell)-2,ey=Math.ceil((player.y+H/2)/cell)+2;for(let cy=sy;cy<=ey;cy++)for(let cx=sx;cx<=ex;cx++){let h=h2(cx,cy,idx),wx=cx*cell+10+h2(cx,cy,11)*44,wy=cy*cell+8+h2(cx,cy,12)*48,p=worldToScreen(wx,wy);if(!visible(p,50))continue;if(h>.08){let t=choose(b.flora,h2(cx,cy,21));drawPlant(t,wx,wy,.72+h2(cx,cy,22)*.52,b,h)}if(h>.53){let t=choose(b.props,h2(cx,cy,31));drawProp(t,wx+16,wy-12,.65+h2(cx,cy,32)*.45,b,h)}if(h>.82){let t=choose(b.flora,h2(cx,cy,41));drawPlant(t,wx-17,wy+13,.65,b,h)}}
 const fcell=330,fsx=Math.floor((player.x-W/2-180)/fcell),fex=Math.ceil((player.x+W/2+180)/fcell),fsy=Math.floor((player.y-H/2-180)/fcell),fey=Math.ceil((player.y+H/2+180)/fcell);for(let cy=fsy;cy<=fey;cy++)for(let cx=fsx;cx<=fex;cx++){let h=h2(cx,cy,idx+100);if(h<.48)continue;let wx=cx*fcell+55+h2(cx,cy,101)*220,wy=cy*fcell+55+h2(cx,cy,102)*220;drawFeature(choose(b.features,h2(cx,cy,103)),wx,wy,b,h)}
 const scell=520,ssx=Math.floor((player.x-W/2-150)/scell),sex=Math.ceil((player.x+W/2+150)/scell),ssy=Math.floor((player.y-H/2-150)/scell),sey=Math.ceil((player.y+H/2+150)/scell);for(let cy=ssy;cy<=sey;cy++)for(let cx=ssx;cx<=sex;cx++){let h=h2(cx,cy,idx+200);if(h<.58)continue;let wx=cx*scell+90+h2(cx,cy,201)*340,wy=cy*scell+90+h2(cx,cy,202)*340,type=choose(b.structures,h2(cx,cy,203));drawStructure(type,wx,wy,b,h,h>.9);let id='place-'+idx+'-'+cx+'-'+cy;if(dist(player,{x:wx,y:wy})<75&&!state.discoveries.has(id)){state.discoveries.add(id);state.places++;state.relics++;toast('Found '+pretty(type)+' ✦');updateHUD()}}}
function pretty(s){return s.replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase())}
function drawAmbient(){let b=biome(),idx=b.i;for(let i=0;i<22;i++){let h=h2(i,idx,500),x=(h2(i,idx,501)*1.3-.15)*W,y=(h2(i,idx,502)*1.25-.1)*H,phase=time*(.3+h)+i;if(/rain|storm|snow|fog|dark|ash|embers/.test(b.effect)&&i>8)continue;X.globalAlpha=.35+.3*Math.sin(phase)*.3;X.fillStyle=b.accent;if(i%3===0){X.fillRect(Math.round(x+Math.sin(phase)*14),Math.round(y+Math.cos(phase*.7)*9),2,2)}else if(/meadow|forest|woods|jungle|grove|wild/i.test(b.name.toLowerCase())){X.fillRect(Math.round(x+Math.sin(phase)*9),Math.round(y+Math.cos(phase)*6),3,2)}}X.globalAlpha=1}
function drawEffects(){const b=biome(),t=time;if(['rain','storm'].includes(b.effect)){X.strokeStyle='#d9efff88';X.lineWidth=1;for(let i=0;i<50;i++){let x=(i*97+t*260)%W,y=(i*53+t*420)%H;X.beginPath();X.moveTo(x,y);X.lineTo(x-4,y+10);X.stroke()}}if(b.effect==='snow'||b.effect==='frost'){X.fillStyle='#fff9';for(let i=0;i<38;i++)X.fillRect((i*83+t*18)%W,(i*47+t*36)%H,2,2)}if(b.effect==='fog'||b.effect==='clouds'){X.fillStyle='#e7f3ee1b';for(let i=0;i<6;i++)X.fillRect(((i*211+t*16)%(W+250))-120,70+i*90,220,44)}if(b.effect==='embers'||b.effect==='ash'){for(let i=0;i<26;i++){X.fillStyle=b.effect==='embers'?'#ffb35f88':'#d8c9be55';X.fillRect((i*79+t*(15+i%3*8))%W,(H-(i*43+t*22)%H),2,2)}}if(b.effect==='fireflies'||b.effect==='glow'){X.fillStyle='#efff7acc';for(let i=0;i<18;i++)X.fillRect((i*119+Math.sin(t+i)*25)%W,(i*61+Math.cos(t*1.2+i)*20)%H,2,2)}}
function landmarkKind(i){return['chest','shrine','camp','spring','tablet','nest','altar','mapStone','foodPatch','cache'][i%10]}
function ensureLandmarks(){let ring=biomeIndex();for(let r=Math.max(0,ring-1);r<=Math.min(29,ring+1);r++)for(let j=0;j<8;j++){let a=hash(r*77+j*17)*TAU,rad=(r+.12+.75*hash(r*33+j))*RING,id=r+'-'+j;if(!landmarks.some(l=>l.id===id))landmarks.push({id,ring:r,x:Math.cos(a)*rad,y:Math.sin(a)*rad,kind:landmarkKind(r+j),used:false})}}
function drawLandmark(l){let p=worldToScreen(l.x,l.y);if(!visible(p,70))return;let b=BIOMES[l.ring];X.save();X.translate(Math.round(p.x),Math.round(p.y));X.fillStyle='#0003';X.fillRect(-15,10,30,6);if(l.kind==='chest'||l.kind==='cache'){px(-13,-7,26,17,l.used?'#777':'#8b5b3f');px(-13,-7,26,5,'#c88a55');px(-2,-2,4,6,'#ffe77a')}else if(l.kind==='shrine'||l.kind==='altar'){px(-10,-18,20,30,'#d8d0c4');px(-15,8,30,5,'#8f8b86');px(-3,-12,6,6,b.accent)}else if(l.kind==='camp'){drawStructure('camp',l.x,l.y,b,.5,false);X.restore();return}else if(l.kind==='spring'){X.fillStyle='#8ce4e8';X.beginPath();X.ellipse(0,2,17,10,0,0,TAU);X.fill();px(-9,-1,12,2,'#d7ffff')}else if(l.kind==='tablet'||l.kind==='mapStone'){px(-10,-18,20,31,'#8e918a');px(-5,-10,10,3,b.accent);px(-5,-3,10,3,b.accent)}else if(l.kind==='foodPatch'){for(let i=0;i<5;i++)drawPlant('berry',l.x+(i-2)*8,l.y+(i%2)*6,1,b,i*.2)}else{px(-15,2,30,8,'#8d6d48');px(-10,-3,20,5,'#d9bf83')}X.restore()}
function interactLandmarks(){for(let l of landmarks){if(l.used||dist(player,l)>32)continue;l.used=true;state.discoveries.add(l.id);state.places++;if(l.kind==='chest'||l.kind==='cache'){dropRune(l.x,l.y,true);dropRune(l.x+12,l.y,true);toast('Treasure cache! Two charms ✦')}else if(l.kind==='shrine'||l.kind==='altar'){player.maxHp+=4;player.hp=Math.min(player.maxHp,player.hp+16);state.relics++;toast('Sacred place: +4 max hearts ◇')}else if(l.kind==='spring'){player.hp=Math.min(player.maxHp,player.hp+30);toast('Restorative spring ♡')}else if(l.kind==='camp'){player.shield=Math.min(30,player.shield+14);toast('Trail camp: +14 ward')}else if(l.kind==='tablet'||l.kind==='mapStone'){player.power*=1.045;toast('Ancient knowledge: wand stronger')}else if(l.kind==='foodPatch'){player.hp=Math.min(player.maxHp,player.hp+18);toast('Wild berries: +18 hearts')}else{gainXP(5+tierAt(l.x,l.y));toast('Curious nest: knowledge gained')}updateHUD()}}
const animalColors=['#f5c7b8','#cba67a','#d8c2a0','#93a96f','#b9958a','#91b6b0','#d49c65','#a1a5c2'];
function drawPixelAnimal(m){const p=worldToScreen(m.x,m.y),s=m.size;if(!visible(p,80))return;X.save();X.translate(Math.round(p.x),Math.round(p.y));X.scale(m.vx<0?-1:1,1);const u=Math.max(2,Math.round(s/6));px(-3*u,2*u,6*u,2*u,'#0003');px(-3*u,-2*u,6*u,4*u,m.c);px(-2*u,-4*u,4*u,3*u,m.c);px(-3*u,-5*u,u,2*u,m.c);px(2*u,-5*u,u,2*u,m.c);px(-u,-4*u,u,u,'#fff7f0');px(u,-4*u,u,u,'#fff7f0');px(-u+1,-4*u+1,1,1,'#293143');px(u+1,-4*u+1,1,1,'#293143');px(-u,-2*u,2*u,u,m.accent);px(-3*u,2*u,u,2*u,m.dark);px(2*u,2*u,u,2*u,m.dark);if(m.elite){X.strokeStyle='#ffe77a';X.lineWidth=2;X.strokeRect(-4*u,-6*u,8*u,10*u)}X.restore();let bw=Math.max(18,s*2.1);if(m.hp<m.maxHp||m.elite){px(p.x-bw/2,p.y-s-11,bw,4,'#1c2330aa');px(p.x-bw/2,p.y-s-11,bw*(m.hp/m.maxHp),4,m.elite?'#ffd765':'#ff7794')}}
function drawPlayer(){X.save();X.translate(Math.round(W/2),Math.round(H/2));if(screenShake)X.translate(rnd(-screenShake,screenShake),rnd(-screenShake,screenShake));px(-11,10,22,6,'#0003');px(-9,-9,18,20,'#fff0f5');px(-7,-15,5,8,'#fff0f5');px(2,-15,5,8,'#fff0f5');px(-5,-6,3,3,'#293143');px(3,-6,3,3,'#293143');px(-2,-1,4,2,'#f28bad');px(-9,8,5,5,'#e9b6c9');px(4,8,5,5,'#e9b6c9');X.rotate(player.heading);px(6,-2,15,4,'#8c684d');px(18,-5,5,10,'#b8f0dd');px(20,-3,5,6,'#fff0a6');X.restore()}
function spawnMob(forceElite=false){let ring=biomeIndex(),b=BIOMES[ring],ang=rnd(0,TAU),rad=Math.max(W,H)*.7+rnd(80,180),x=player.x+Math.cos(ang)*rad,y=player.y+Math.sin(ang)*rad,actual=tierAt(x,y),species=b.animals[Math.floor(Math.random()*3)],ferocity=1+actual*.16,size=9+actual*.72+rnd(-2,3),elite=forceElite||(actual%5===0&&Math.random()<.035),hp=(13+actual*4.8)*(elite?4.5:1),role=actual<5?'skitter':actual<10?'chase':actual<16?'pounce':actual<22?'strafe':'apex';mobs.push({x,y,vx:0,vy:0,size,hp,maxHp:hp,species,ring:actual-1,role,elite,c:animalColors[(actual+species.length)%animalColors.length],dark:'#6f5d55',accent:b.accent,hit:0,atk:rnd(.2,1.2),phase:rnd(0,TAU),ferocity})}
function updateMob(m,dt){let dx=player.x-m.x,dy=player.y-m.y,d=Math.hypot(dx,dy)||1,nx=dx/d,ny=dy/d,s=42+m.ferocity*12;if(m.role==='skitter'){s*=.72;nx+=Math.sin(time*2+m.phase)*.25;ny+=Math.cos(time*2+m.phase)*.25}else if(m.role==='pounce'&&m.atk<.2)s*=3.2;else if(m.role==='strafe'){let tx=-ny,ty=nx;nx=nx*.55+tx*Math.sin(time+m.phase)*.75;ny=ny*.55+ty*Math.sin(time+m.phase)*.75}else if(m.role==='apex')s*=1.12;m.vx=nx*s;m.vy=ny*s;m.x+=m.vx*dt;m.y+=m.vy*dt;m.atk-=dt;m.hit=Math.max(0,m.hit-dt);if(d<m.size+12&&m.atk<=0){damagePlayer((4+m.ferocity*1.4)*(m.elite?1.55:1));m.atk=.75;m.x-=nx*18;m.y-=ny*18}if((m.role==='strafe'||m.role==='apex')&&m.atk<=0&&d<430){enemyShots.push({x:m.x,y:m.y,vx:nx*(125+m.ferocity*8),vy:ny*(125+m.ferocity*8),life:3,damage:3+m.ferocity,r:4+(m.elite?2:0),c:BIOMES[m.ring].accent});m.atk=m.role==='apex'?.6:1.2}}
function damagePlayer(n){if(player.shield>0){let a=Math.min(player.shield,n);player.shield-=a;n-=a}if(n<=0)return;player.hp-=n;screenShake=5;particlesBurst(player.x,player.y,'#ff7794',8);if(player.hp<=0)gameOver();updateHUD()}
function nearestTarget(){let best=null,bd=460*player.range;for(let m of mobs){let d=dist(player,m);if(d<bd){bd=d;best=m}}return best}
function fire(){if(shotT>0||paused||dead)return;let t=nearestTarget(),a=t?Math.atan2(t.y-player.y,t.x-player.x):player.heading;player.heading=a;let count=player.proj,spread=player.spread||(.12*(count-1));shotT=.32/player.fire;for(let i=0;i<count;i++){let off=count===1?0:(i-(count-1)/2)*spread/Math.max(1,count-1),aa=a+off,spd=390+player.lv*2;shots.push({x:player.x+Math.cos(aa)*18,y:player.y+Math.sin(aa)*18,vx:Math.cos(aa)*spd,vy:Math.sin(aa)*spd,life:1.15*player.range,damage:(8+player.lv*.65)*player.power,pierce:player.pierce,hit:new Set(),r:4+Math.min(3,player.power-1),c:biome().accent,crit:Math.random()<player.crit})}particlesBurst(player.x+Math.cos(a)*18,player.y+Math.sin(a)*18,biome().accent,3)}
function updateShots(dt){for(let s of shots){if(player.homing&&mobs.length){let t=mobs.reduce((a,b)=>dist(s,b)<dist(s,a)?b:a,mobs[0]),a=Math.atan2(t.y-s.y,t.x-s.x),spd=Math.hypot(s.vx,s.vy),ca=Math.atan2(s.vy,s.vx),dif=Math.atan2(Math.sin(a-ca),Math.cos(a-ca));ca+=dif*Math.min(1,dt*player.homing);s.vx=Math.cos(ca)*spd;s.vy=Math.sin(ca)*spd}s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(let m of [...mobs]){if(s.hit.has(m)||dist(s,m)>m.size+s.r)continue;s.hit.add(m);m.hp-=s.damage*(s.crit?1.8:1);particlesBurst(m.x,m.y,s.c,5);if(m.hp<=0)killMob(m);if(s.pierce>0)s.pierce--;else{s.life=0;break}}}shots=shots.filter(s=>s.life>0);for(let s of enemyShots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(dist(s,player)<s.r+10){damagePlayer(s.damage);s.life=0}}enemyShots=enemyShots.filter(s=>s.life>0)}
function killMob(m){let i=mobs.indexOf(m);if(i>=0)mobs.splice(i,1);state.kills++;gainXP(1+Math.floor((m.ring+1)/3));particlesBurst(m.x,m.y,m.accent,m.elite?18:8);let chance=.22+m.ring*.006;if(m.elite||Math.random()<chance)dropRune(m.x,m.y,m.elite);else if(Math.random()<.1)drops.push({x:m.x,y:m.y,type:'berry',life:16,spin:0});if(m.elite){state.relics++;toast('Apex '+m.species+' defeated! ◇')}updateHUD()}
const RUNES=[['Quickleaf','fire',1.12,'Faster casting'],['Star Seed','power',1.13,'Stronger bolts'],['Twin Petal','proj',1,'Extra projectile'],['Needle Fern','pierce',1,'Piercing'],['Moon Eye','homing',.8,'Seeking shots'],['Longtail','range',1.12,'Longer reach'],['Lucky Bell','crit',.04,'Critical chance'],['Thorn Crown','spread',.08,'Wider volley'],['Heart Berry','maxHp',5,'More hearts'],['Swift Paw','speed',8,'Move faster']];
function dropRune(x,y,rare=false){let r=RUNES[Math.floor(Math.random()*RUNES.length)];drops.push({x:x+rnd(-10,10),y:y+rnd(-10,10),type:'rune',rune:r,rare,life:22,spin:0})}function applyRune(r,rare){let [name,key,val]=r,m=rare?1.45:1;if(key==='fire')player.fire*=1+(val-1)*m;else if(key==='power')player.power*=1+(val-1)*m;else if(key==='proj')player.proj=Math.min(7,player.proj+1);else if(key==='pierce')player.pierce=Math.min(6,player.pierce+1);else if(key==='homing')player.homing=Math.min(8,player.homing+val*m);else if(key==='range')player.range*=1+(val-1)*m;else if(key==='crit')player.crit=Math.min(.45,player.crit+val*m);else if(key==='spread')player.spread=Math.min(.65,player.spread+val*m);else if(key==='maxHp'){player.maxHp+=Math.round(val*m);player.hp+=Math.round(val*m)}else if(key==='speed')player.speed+=val*m;state.runes.push(name);toast((rare?'Rare ':'')+name+' ✦ '+r[3]);updateHUD()}
function updateDrops(dt){for(let d of drops){d.life-=dt;d.spin+=dt*3;let dd=dist(d,player);if(dd<95){let k=Math.min(1,dt*6);d.x+=(player.x-d.x)*k;d.y+=(player.y-d.y)*k}if(dd<18){d.life=0;if(d.type==='rune')applyRune(d.rune,d.rare);else{player.hp=Math.min(player.maxHp,player.hp+12);toast('Sweet berry +12 hearts');updateHUD()}}}drops=drops.filter(d=>d.life>0)}function drawDrop(d){let p=worldToScreen(d.x,d.y);X.save();X.translate(Math.round(p.x),Math.round(p.y));let bob=Math.sin(d.spin)*3;if(d.type==='rune'){px(-5,-6+bob,10,10,d.rare?'#ffe77a':'#fff5c2');px(-2,-3+bob,4,4,BIOMES[biomeIndex(d.x,d.y)].accent)}else{px(-5,-4+bob,10,8,'#e95e7d');px(0,-7+bob,3,4,'#6da55b')}X.restore()}
function gainXP(n){player.xp+=n;while(player.xp>=player.next){player.xp-=player.next;player.lv++;player.next=Math.floor(player.next*1.28+3);player.maxHp+=2;player.hp=Math.min(player.maxHp,player.hp+8);player.power*=1.025;player.fire*=1.012;toast('Level '+player.lv+'! Wild magic grows ✦')}updateHUD()}
function particlesBurst(x,y,c,n){for(let i=0;i<n;i++)particles.push({x,y,vx:rnd(-70,70),vy:rnd(-70,70),life:rnd(.2,.55),c})}function updateParticles(dt){for(let p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;p.life-=dt}particles=particles.filter(p=>p.life>0)}function drawParticles(){for(let p of particles){let q=worldToScreen(p.x,p.y);X.globalAlpha=clamp(p.life*3,0,1);px(q.x,q.y,3,3,p.c)}X.globalAlpha=1}
function envPhysics(dt){let e=biome().effect;if(e==='mud')player.envSlow=.83;else if(e==='ice')player.envSlow=1.08;else if(e==='heat'||e==='ash')player.envSlow=.92;else player.envSlow=1;if(e==='current'){player.x+=Math.sin(time*.7)*9*dt;player.y+=5*dt}if(e==='gust'||e==='wind'||e==='storm')player.x+=Math.sin(time*1.3)*12*dt}
function update(dt){time+=dt;shotT=Math.max(0,shotT-dt);screenShake=Math.max(0,screenShake-dt*18);envPhysics(dt);let mag=Math.hypot(input.mx,input.my);if(mag>.05){let nx=input.mx/mag,ny=input.my/mag,s=player.speed*player.envSlow*Math.min(1,mag);player.x+=nx*s*dt;player.y+=ny*s*dt;player.heading=Math.atan2(ny,nx)}if(input.shoot)fire();let ring=biomeIndex();if(ring>state.bestRing){state.bestRing=ring;toast('Discovered '+BIOMES[ring].name+' ✦ '+BIOMES[ring].animals.join(' · '));state.relics++;updateHUD()}ensureLandmarks();interactLandmarks();spawnT-=dt;let cap=10+Math.min(24,ring);if(spawnT<=0&&mobs.length<cap){spawnMob(false);spawnT=Math.max(.18,1.05-ring*.022)}for(let m of [...mobs])updateMob(m,dt);updateShots(dt);updateDrops(dt);updateParticles(dt);mobs=mobs.filter(m=>dist(m,player)<1300);landmarks=landmarks.filter(l=>Math.abs(l.ring-ring)<=2);if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}}
function draw(){drawDenseWorld();for(let l of landmarks)drawLandmark(l);drawAmbient();for(let d of drops)drawDrop(d);for(let s of shots){let p=worldToScreen(s.x,s.y);px(p.x-s.r,p.y-s.r,s.r*2,s.r*2,s.crit?'#fff4a3':s.c);px(p.x-1,p.y-1,2,2,'#fff')}for(let s of enemyShots){let p=worldToScreen(s.x,s.y);px(p.x-s.r,p.y-s.r,s.r*2,s.r*2,s.c)}for(let m of mobs)drawPixelAnimal(m);drawParticles();drawPlayer();drawEffects();drawCompass()}
function drawCompass(){let ring=biomeIndex(),next=(ring+1)*RING,rad=Math.hypot(player.x,player.y),remain=Math.max(0,next-rad),b=biome();X.save();X.globalAlpha=.9;px(W/2-82,42,164,28,'#172033aa');X.fillStyle='#fff';X.font='900 9px monospace';X.textAlign='center';X.fillText(b.name.toUpperCase(),W/2,53);X.fillStyle=b.accent;X.fillText(ring<29?Math.ceil(remain)+'m TO '+BIOMES[ring+1].name.toUpperCase():'HEART OF THE ELDER WILDS',W/2,64);X.restore()}
function updateHUD(){let b=biome(),r=biomeIndex();$('hp').textContent=Math.max(0,Math.ceil(player.hp));$('maxhp').textContent=Math.ceil(player.maxHp);$('hpfill').style.width=100*clamp(player.hp/player.maxHp,0,1)+'%';$('lv').textContent=player.lv;$('xp').textContent=Math.floor(player.xp)+'/'+player.next;$('biome').textContent=(r+1)+'/30 '+b.name;$('weapon').textContent=player.proj+'× Wand · '+player.fire.toFixed(1)+' rate · '+player.power.toFixed(1)+' power';$('danger').textContent='Wild '+(r+1);$('relics').textContent=state.relics;$('flowfill').style.width=clamp(player.shield/30*100,0,100)+'%'}function toast(t){$('toast').textContent=t;$('toast').classList.add('show');toastT=2.4}
function reset(){Object.assign(player,{x:0,y:0,hp:60,maxHp:60,speed:170,lv:1,xp:0,next:8,power:1,fire:1,proj:1,spread:0,pierce:0,bounce:0,homing:0,crit:.05,range:1,shield:0,heading:0,envSlow:1});mobs=[];shots=[];enemyShots=[];drops=[];landmarks=[];particles=[];Object.assign(state,{kills:0,relics:0,bestRing:0,places:0});state.discoveries.clear();state.runes=[];time=0;dead=false;paused=false;spawnT=0;updateHUD()}
function gameOver(){dead=true;paused=true;$('controls').classList.add('hide');$('death').classList.remove('hide');$('dlevel').textContent=player.lv;$('dtime').textContent=Math.floor(time/60)+':'+String(Math.floor(time%60)).padStart(2,'0');$('dkills').textContent=state.kills;$('drelics').textContent=state.relics}
function loop(ts){let dt=Math.min(.033,(ts-last)/1000||0);last=ts;if(started&&!paused&&!dead)update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
const joy=$('joystick'),knob=$('joyknob');function joyMove(e){if(input.pid!==e.pointerId)return;let r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,lim=r.width*.34,d=Math.hypot(dx,dy)||1,k=Math.min(1,lim/d);dx*=k;dy*=k;knob.style.transform=`translate(${dx}px,${dy}px)`;input.mx=dx/lim;input.my=dy/lim}joy.onpointerdown=e=>{input.pid=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e)};joy.onpointermove=joyMove;function joyEnd(e){if(input.pid!==e.pointerId)return;input.pid=null;input.mx=input.my=0;knob.style.transform='translate(0,0)'}joy.onpointerup=joyEnd;joy.onpointercancel=joyEnd;
const shoot=$('shoot');shoot.onpointerdown=e=>{e.preventDefault();shoot.setPointerCapture(e.pointerId);input.shoot=true;shoot.classList.add('pressed');fire()};function shootEnd(){input.shoot=false;shoot.classList.remove('pressed')}shoot.onpointerup=shootEnd;shoot.onpointercancel=shootEnd;
$('play').onclick=()=>{reset();started=true;$('start').classList.add('hide');$('controls').classList.remove('hide');toast('The tiny trail begins…')};$('again').onclick=()=>{reset();$('death').classList.add('hide');$('controls').classList.remove('hide')};
window.__TWBB_V17__={version:17,biomes:BIOMES,state:()=>({ring:biomeIndex()+1,biome:biome().name,player:{...player},kills:state.kills,relics:state.relics,places:state.places,runes:[...state.runes]}),dropRune:()=>dropRune(player.x+30,player.y,true),warp:n=>{let i=clamp((n|0)-1,0,29);player.x=i*RING+20;player.y=0;updateHUD()},spawnApex:()=>spawnMob(true)};
})();