(()=>{'use strict';
const C=document.getElementById('g'),X=C.getContext('2d'),BIOMES=window.TWBB_WORLD;X.imageSmoothingEnabled=false;
const $=id=>document.getElementById(id),TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
let W=0,H=0,DPR=1,last=0,started=false,dead=false,paused=false,time=0,spawnT=0,shotT=0,toastT=0,screenShake=0;
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*DPR;C.height=H*DPR;C.style.width=W+'px';C.style.height=H+'px';X.setTransform(DPR,0,0,DPR,0,0);X.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const RING=780,state={kills:0,relics:0,discoveries:new Set(),runes:[],bestRing:0,places:0};
const player={x:0,y:0,r:12,hp:60,maxHp:60,speed:170,lv:1,xp:0,next:8,power:1,fire:1,proj:1,spread:0,pierce:0,homing:0,crit:.05,range:1,shield:0,heading:0,envSlow:1};
let mobs=[],shots=[],enemyShots=[],drops=[],landmarks=[],particles=[];const input={mx:0,my:0,shoot:false,pid:null};
function biomeIndex(x=player.x,y=player.y){return clamp(Math.floor(Math.hypot(x,y)/RING),0,29)}function biome(){return BIOMES[biomeIndex()]}function tierAt(x,y){return biomeIndex(x,y)+1}function worldToScreen(x,y){return{x:W/2+x-player.x,y:H/2+y-player.y}}
function hash(n){return Math.abs(Math.sin(n*127.1+Math.cos(n*9.13))*43758.5453)%1}function h2(x,y,s=0){return hash(x*91.7+y*173.3+s*31.7)}function choose(a,h){return a[Math.floor(h*a.length)%a.length]}function px(x,y,w,h,c){X.fillStyle=c;X.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}function visible(p,m=80){return p.x>-m&&p.x<W+m&&p.y>-m&&p.y<H+m}function shadow(x,y,w){px(x-w/2,y,w,5,'#14201933')}
function drawPlant(type,x,y,s,b,h){const p=worldToScreen(x,y);if(!visible(p,60))return;X.save();X.translate(Math.round(p.x),Math.round(p.y));let u=Math.max(1,Math.round(s)),c=b.accent;
 if(/birch|pine|fir|tree|oak|maple|willow|palm|baobab|acacia/i.test(type)){shadow(0,8,20*u);let trunk=/birch/i.test(type)?'#ede7d1':'#745441',leaf=/snow|storm|fir|pine/i.test(type)?'#557467':/autumn|maple/i.test(type)?'#db8452':/palm|date/i.test(type)?'#5d9b58':b.shade;px(-2*u,-2*u,4*u,14*u,trunk);if(/palm|date/i.test(type)){for(let a=0;a<6;a++){let aa=a*TAU/6;px(Math.cos(aa)*8*u-4*u,-10*u+Math.sin(aa)*3*u,8*u,3*u,leaf)}}else if(/baobab/i.test(type)){px(-10*u,-12*u,20*u,8*u,leaf);px(-7*u,-16*u,14*u,6*u,leaf)}else{px(-8*u,-10*u,16*u,8*u,leaf);px(-6*u,-15*u,12*u,8*u,leaf);if(/pine|fir/i.test(type)){px(-7*u,-13*u,14*u,4*u,leaf);px(-5*u,-18*u,10*u,5*u,leaf);px(-3*u,-22*u,6*u,5*u,leaf)}}}
 else if(/bamboo/i.test(type)){for(let i=-1;i<=1;i++){px(i*5*u,-18*u,3*u,22*u,'#5d9b58');px(i*5*u-2*u,-12*u,7*u,2*u,'#89c86f')}}
 else if(/cactus/i.test(type)){px(-3*u,-14*u,6*u,17*u,'#5aa56c');px(-7*u,-8*u,4*u,3*u,'#5aa56c');px(4*u,-11*u,4*u,3*u,'#5aa56c');if(h>.7)px(-2*u,-17*u,4*u,4*u,'#f2a6bd')}
 else if(/crystal|obsidian|iceSpikes|stalagmite|lavaCrystal/i.test(type)){let cc=/lava/i.test(type)?'#ff724d':/obsidian/i.test(type)?'#343044':/ice/i.test(type)?'#dff7ff':c;px(-4*u,-10*u,5*u,12*u,cc);px(2*u,-16*u,5*u,18*u,cc);px(7*u,-7*u,4*u,9*u,cc);px(3*u,-13*u,2*u,5*u,'#fff8')}
 else if(/mushroom/i.test(type)){px(-u,-5*u,2*u,7*u,'#e8d9c0');px(-5*u,-8*u,10*u,4*u,/glow|fire/i.test(type)?c:'#d7858d')}
 else if(/flower|daisy|buttercup|clover|tulip|sunflower|bluebell|orchid|foxglove|bromeliad/i.test(type)){px(-u,-5*u,2*u,7*u,'#5f9d55');let cc=/sunflower|buttercup/i.test(type)?'#ffe06f':/bluebell/i.test(type)?'#8f82d7':/orchid|foxglove|tulip/i.test(type)?'#ef9ac2':c;px(-4*u,-8*u,8*u,3*u,cc);px(-2*u,-10*u,4*u,7*u,cc)}
 else if(/termiteMound|dune|snowdrift/i.test(type)){let cc=/snow/i.test(type)?'#edf9ff':/dune/i.test(type)?'#e8cf85':'#9e754e';px(-9*u,-4*u,18*u,7*u,cc);px(-5*u,-9*u,10*u,8*u,cc)}
 else{let cc=/kelp|reed|moss|fern|ivy|vine|monstera/i.test(type)?b.shade:'#7da75d';for(let i=0;i<4;i++){let xx=(-5+i*3)*u,hh=(5+h2(i,h,2)*8)*u;px(xx,-hh,2*u,hh,cc)}}X.restore()}
function drawProp(type,x,y,s,b,h){const p=worldToScreen(x,y);if(!visible(p,70))return;X.save();X.translate(Math.round(p.x),Math.round(p.y));let u=Math.max(1,Math.round(s));shadow(0,5,15*u);
 if(/rock|boulder|stone|obsidian|cairn/i.test(type)){let cc=/obsidian/i.test(type)?'#343044':'#817b74';px(-7*u,-4*u,14*u,8*u,cc);px(-4*u,-8*u,8*u,5*u,'#9a958c');if(/cairn/i.test(type)){px(-4*u,-11*u,8*u,4*u,cc);px(-2*u,-14*u,4*u,3*u,cc)}}
 else if(/log|driftwood|woodpile|root|fallen/i.test(type)){px(-10*u,-3*u,20*u,6*u,'#73533d');px(-9*u,-2*u,4*u,4*u,'#9d7755')}
 else if(/stump/i.test(type)){px(-6*u,-7*u,12*u,10*u,'#74513e');px(-5*u,-9*u,10*u,4*u,'#aa7f5c')}
 else if(/sign/i.test(type)){px(-2*u,-9*u,4*u,14*u,'#795b43');px(-8*u,-13*u,16*u,7*u,'#b98b5a')}
 else if(/fence/i.test(type)){let cc=/bamboo/i.test(type)?'#719b50':'#9b724c';px(-12*u,-6*u,24*u,3*u,cc);px(-12*u,0,24*u,3*u,cc);px(-10*u,-9*u,3*u,14*u,cc);px(7*u,-9*u,3*u,14*u,cc)}
 else if(/bones|skull|antler|fossil/i.test(type)){px(-7*u,-2*u,14*u,3*u,'#e8dfc7');px(-2*u,-6*u,4*u,10*u,'#e8dfc7');if(/skull/i.test(type)){px(-5*u,-8*u,10*u,7*u,'#e8dfc7');px(-3*u,-6*u,2*u,2*u,'#4a413b');px(2*u,-6*u,2*u,2*u,'#4a413b')}}
 else if(/lantern|torch|lightningRod/i.test(type)){px(-u,-9*u,2*u,13*u,'#5b4d49');px(-4*u,-13*u,8*u,7*u,b.accent)}
 else if(/totem|ruinPillar|brokenStatue|ancientStone/i.test(type)){px(-6*u,-14*u,12*u,18*u,'#7d7c71');px(-8*u,-17*u,16*u,4*u,'#9a9786');px(-3*u,-10*u,6*u,3*u,b.accent)}
 else{px(-7*u,-7*u,14*u,12*u,/pumpkin/i.test(type)?'#d98042':'#8c6748');px(-6*u,-4*u,12*u,2*u,'#0002')}X.restore()}
function drawStructure(type,x,y,b,h,large=false){const p=worldToScreen(x,y);if(!visible(p,140))return;X.save();X.translate(Math.round(p.x),Math.round(p.y));let S=large?1.2:1,wall='#d8c39d',wood='#79583e',roof=b.shade,light=b.accent;shadow(0,25*S,64*S);
 if(/bridge|boardwalk|ropeBridge|lavaBridge/i.test(type)){px(-45*S,-7*S,90*S,14*S,/lava/i.test(type)?'#6e4a3f':'#9b724c');for(let i=-36;i<=36;i+=12)px(i*S,-10*S,4*S,20*S,'#6e523e')}
 else if(/tower|lighthouse|obelisk/i.test(type)){px(-13*S,-42*S,26*S,66*S,/lighthouse/i.test(type)?'#e8e3cf':'#8b887f');px(-18*S,-47*S,36*S,8*S,roof);px(-8*S,-30*S,7*S,8*S,light);px(2*S,-30*S,7*S,8*S,light)}
 else if(/shrine|temple|pagoda|altar/i.test(type)){px(-24*S,-22*S,48*S,44*S,'#87877c');px(-31*S,-27*S,62*S,8*S,'#a09e8e');px(-17*S,-42*S,34*S,18*S,roof);px(-5*S,-16*S,10*S,14*S,light)}
 else if(/gate|arch/i.test(type)){px(-28*S,-38*S,10*S,62*S,'#88867d');px(18*S,-38*S,10*S,62*S,'#88867d');px(-28*S,-42*S,56*S,10*S,'#9d9a8c')}
 else if(/windmill/i.test(type)){px(-15*S,-28*S,30*S,50*S,wall);px(-18*S,-33*S,36*S,10*S,roof);X.strokeStyle=wood;X.lineWidth=4*S;for(let a=0;a<4;a++){X.beginPath();X.moveTo(0,-18*S);X.lineTo(Math.cos(a*Math.PI/2)*33*S,-18*S+Math.sin(a*Math.PI/2)*33*S);X.stroke()}}
 else if(/well/i.test(type)){px(-18*S,-8*S,36*S,22*S,'#8d887d');px(-15*S,-28*S,4*S,20*S,wood);px(11*S,-28*S,4*S,20*S,wood);px(-17*S,-31*S,34*S,5*S,roof)}
 else if(/dock|boat|boathouse/i.test(type)){px(-35*S,2*S,70*S,10*S,wood);if(/boat/i.test(type)){px(-23*S,-15*S,46*S,14*S,'#825e45');px(-15*S,-20*S,30*S,6*S,'#b28158')}}
 else if(/mine|lift/i.test(type)){px(-30*S,-30*S,60*S,52*S,'#34353b');px(-25*S,-35*S,7*S,60*S,wood);px(18*S,-35*S,7*S,60*S,wood);px(-25*S,-38*S,50*S,7*S,wood);px(-15*S,-20*S,30*S,6*S,'#15161a')}
 else if(/forge/i.test(type)){px(-28*S,-20*S,56*S,42*S,'#6e5a50');px(-32*S,-25*S,64*S,8*S,'#40383a');px(-8*S,-11*S,16*S,18*S,'#ff794d')}
 else if(/camp|tent|caravan|market|picnic/i.test(type)){if(/tent|camp|picnic/i.test(type)){X.fillStyle=/picnic/i.test(type)?'#e89db8':'#d6a36d';X.beginPath();X.moveTo(-24*S,18*S);X.lineTo(0,-24*S);X.lineTo(24*S,18*S);X.fill();px(-4*S,0,8*S,18*S,'#664a3b')}else{px(-30*S,-18*S,60*S,38*S,'#b7885c');px(-34*S,-24*S,68*S,8*S,roof)}}
 else{px(-28*S,-20*S,56*S,42*S,wall);px(-33*S,-26*S,66*S,10*S,roof);px(-22*S,-13*S,12*S,12*S,light);px(10*S,-13*S,12*S,12*S,light);px(-7*S,3*S,14*S,19*S,wood)}X.restore()}
// Composite features are intentionally rendered WITHOUT a parent canvas translation.
// Their children receive world coordinates exactly once, preventing camera-relative drift.
function drawFeature(type,x,y,b,h){const p=worldToScreen(x,y);if(!visible(p,180))return;
 if(/grove|forest|thicket|maze|garden|field|patch|orchard/i.test(type)){for(let i=0;i<10;i++){let a=i*2.399+h*TAU,r=18+(i%4)*13;drawPlant(choose(b.flora,h2(i,h,8)),x+Math.cos(a)*r,y+Math.sin(a)*r,1,b,h2(i,h,9))}return}
 if(/ruin|hall|courtyard/i.test(type)){for(let i=0;i<5;i++){let a=i*TAU/5;drawProp(i%2?'ruinPillar':'ancientStone',x+Math.cos(a)*35,y+Math.sin(a)*35,1,b,h2(i,h,4))}X.save();X.translate(Math.round(p.x),Math.round(p.y));px(-18,-3,36,6,'#8f8b80');X.restore();return}
 if(/stoneCircle|rockArch|stepping|stonePath/i.test(type)){for(let i=0;i<8;i++){let a=i*TAU/8,isPath=/Path/i.test(type),xx=isPath?(i-4)*15:Math.cos(a)*34,yy=isPath?Math.sin(i)*5:Math.sin(a)*34;drawProp('rock',x+xx,y+yy,.8,b,h)}return}
 if(/fossil/i.test(type)){for(let i=0;i<7;i++){let a=i*TAU/7;drawProp('bones',x+Math.cos(a)*38,y+Math.sin(a)*18,.8,b,h)}return}
 if(!/pond|pool|hole|watering|bog|tide|oasis|lake|stream|river|waterfall|chasm|ravine|cliff|crater|shipwreck/i.test(type)){for(let i=0;i<7;i++){let a=i*TAU/7;drawProp(choose(b.props,h2(i,h,3)),x+Math.cos(a)*35,y+Math.sin(a)*22,.8,b,h)}return}
 X.save();X.translate(Math.round(p.x),Math.round(p.y));let water='#69bfc4';if(/pond|pool|hole|watering|bog|tide|oasis|lake/i.test(type)){X.fillStyle=/frozen|ice/i.test(type)?'#cfefff':water;X.beginPath();X.ellipse(0,0,55+h*25,25+h*14,0,0,TAU);X.fill();X.globalAlpha=.35;px(-24,-7,28,3,'#fff');X.globalAlpha=1}else if(/stream|river/i.test(type)){px(-80,-12-h*8,160,24+h*16,/lava/i.test(type)?'#ff6846':water)}else if(/waterfall/i.test(type)){px(-30,-60,60,80,b.shade);px(-14,-55,28,66,'#7fd5d9');px(-23,10,46,14,'#69bfc4')}else if(/chasm|ravine|cliff|crater/i.test(type)){X.fillStyle='#252632';X.beginPath();X.ellipse(0,5,62+h*20,25+h*12,0,0,TAU);X.fill();px(-55,-4,110,5,b.shade)}else{px(-50,-5,100,12,'#664b3a');px(-35,-18,70,10,'#8c6748');px(-3,-50,6,42,'#604939')}X.restore()}
function drawTrail(){let rad=Math.hypot(player.x,player.y),a=Math.atan2(player.y,player.x);X.save();X.globalAlpha=.16;X.strokeStyle='#f5e0ba';X.lineWidth=18;X.beginPath();let start=Math.max(0,rad-900),end=rad+900,first=true;for(let r=start;r<=end;r+=80){let aa=a+Math.sin(r*.003)*.12,p=worldToScreen(Math.cos(aa)*r,Math.sin(aa)*r);first?(X.moveTo(p.x,p.y),first=false):X.lineTo(p.x,p.y)}X.stroke();X.restore()}
function drawDenseWorld(){const b=biome(),idx=b.i;px(0,0,W,H,b.ground);drawTrail();const cell=64,sx=Math.floor((player.x-W/2)/cell)-2,ex=Math.ceil((player.x+W/2)/cell)+2,sy=Math.floor((player.y-H/2)/cell)-2,ey=Math.ceil((player.y+H/2)/cell)+2;for(let cy=sy;cy<=ey;cy++)for(let cx=sx;cx<=ex;cx++){let h=h2(cx,cy,idx),wx=cx*cell+10+h2(cx,cy,11)*44,wy=cy*cell+8+h2(cx,cy,12)*48;if(h>.08)drawPlant(choose(b.flora,h2(cx,cy,21)),wx,wy,.72+h2(cx,cy,22)*.52,b,h);if(h>.53)drawProp(choose(b.props,h2(cx,cy,31)),wx+16,wy-12,.65+h2(cx,cy,32)*.45,b,h);if(h>.82)drawPlant(choose(b.flora,h2(cx,cy,41)),wx-17,wy+13,.65,b,h)}const fcell=330;for(let cy=Math.floor((player.y-H/2-180)/fcell);cy<=Math.ceil((player.y+H/2+180)/fcell);cy++)for(let cx=Math.floor((player.x-W/2-180)/fcell);cx<=Math.ceil((player.x+W/2+180)/fcell);cx++){let h=h2(cx,cy,idx+100);if(h>.48)drawFeature(choose(b.features,h2(cx,cy,103)),cx*fcell+55+h2(cx,cy,101)*220,cy*fcell+55+h2(cx,cy,102)*220,b,h)}const scell=520;for(let cy=Math.floor((player.y-H/2-150)/scell);cy<=Math.ceil((player.y+H/2+150)/scell);cy++)for(let cx=Math.floor((player.x-W/2-150)/scell);cx<=Math.ceil((player.x+W/2+150)/scell);cx++){let h=h2(cx,cy,idx+200);if(h<.58)continue;let wx=cx*scell+90+h2(cx,cy,201)*340,wy=cy*scell+90+h2(cx,cy,202)*340,type=choose(b.structures,h2(cx,cy,203));drawStructure(type,wx,wy,b,h,h>.9);let id='place-'+idx+'-'+cx+'-'+cy;if(dist(player,{x:wx,y:wy})<75&&!state.discoveries.has(id)){state.discoveries.add(id);state.places++;state.relics++;toast('Found '+pretty(type)+' ✦');updateHUD()}}}
function pretty(s){return s.replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase())}
function drawAmbient(){let b=biome(),idx=b.i;for(let i=0;i<22;i++){let h=h2(i,idx,500),x=(h2(i,idx,501)*1.3-.15)*W,y=(h2(i,idx,502)*1.25-.1)*H,phase=time*(.3+h)+i;if(/rain|storm|snow|fog|dark|ash|embers/.test(b.effect)&&i>8)continue;X.globalAlpha=.35;px(x+Math.sin(phase)*10,y+Math.cos(phase*.7)*7,i%3?3:2,2,b.accent)}X.globalAlpha=1}
function drawEffects(){const b=biome(),t=time;if(['rain','storm'].includes(b.effect)){X.strokeStyle='#d9efff88';for(let i=0;i<50;i++){let x=(i*97+t*260)%W,y=(i*53+t*420)%H;X.beginPath();X.moveTo(x,y);X.lineTo(x-4,y+10);X.stroke()}}if(b.effect==='snow'||b.effect==='frost'){for(let i=0;i<38;i++)px((i*83+t*18)%W,(i*47+t*36)%H,2,2,'#fff9')}if(b.effect==='fog'||b.effect==='clouds'){for(let i=0;i<6;i++)px(((i*211+t*16)%(W+250))-120,70+i*90,220,44,'#e7f3ee1b')}if(b.effect==='embers'||b.effect==='ash'){for(let i=0;i<26;i++)px((i*79+t*(15+i%3*8))%W,H-(i*43+t*22)%H,2,2,b.effect==='embers'?'#ffb35f88':'#d8c9be55')}}
function landmarkKind(i){return['chest','shrine','camp','spring','tablet','nest','altar','mapStone','foodPatch','cache'][i%10]}function ensureLandmarks(){let ring=biomeIndex();for(let r=Math.max(0,ring-1);r<=Math.min(29,ring+1);r++)for(let j=0;j<8;j++){let a=hash(r*77+j*17)*TAU,rad=(r+.12+.75*hash(r*33+j))*RING,id=r+'-'+j;if(!landmarks.some(l=>l.id===id))landmarks.push({id,ring:r,x:Math.cos(a)*rad,y:Math.sin(a)*rad,kind:landmarkKind(r+j),used:false})}}
function drawLandmark(l){let p=worldToScreen(l.x,l.y);if(!visible(p,80))return;let b=BIOMES[l.ring];if(l.kind==='camp'){drawStructure('camp',l.x,l.y,b,.5,false);return}if(l.kind==='foodPatch'){for(let i=0;i<5;i++)drawPlant('berry',l.x+(i-2)*8,l.y+(i%2)*6,1,b,i*.2);return}X.save();X.translate(Math.round(p.x),Math.round(p.y));shadow(0,10,30);if(l.kind==='chest'||l.kind==='cache'){px(-13,-7,26,17,l.used?'#777':'#8b5b3f');px(-13,-7,26,5,'#c88a55');px(-2,-2,4,6,'#ffe77a')}else if(l.kind==='shrine'||l.kind==='altar'){px(-10,-18,20,30,'#d8d0c4');px(-15,8,30,5,'#8f8b86');px(-3,-12,6,6,b.accent)}else if(l.kind==='spring'){X.fillStyle='#8ce4e8';X.beginPath();X.ellipse(0,2,17,10,0,0,TAU);X.fill()}else if(l.kind==='tablet'||l.kind==='mapStone'){px(-10,-18,20,31,'#8e918a');px(-5,-10,10,3,b.accent);px(-5,-3,10,3,b.accent)}else{px(-15,2,30,8,'#8d6d48');px(-10,-3,20,5,'#d9bf83')}X.restore()}
function interactLandmarks(){for(let l of landmarks){if(l.used||dist(player,l)>32)continue;l.used=true;state.discoveries.add(l.id);state.places++;if(l.kind==='chest'||l.kind==='cache'){dropRune(l.x,l.y,true);dropRune(l.x+12,l.y,true);toast('Treasure cache! Two charms ✦')}else if(l.kind==='shrine'||l.kind==='altar'){player.maxHp+=4;player.hp=Math.min(player.maxHp,player.hp+16);state.relics++;toast('Sacred place: +4 max hearts ◇')}else if(l.kind==='spring'){player.hp=Math.min(player.maxHp,player.hp+30);toast('Restorative spring ♡')}else if(l.kind==='camp'){player.shield=Math.min(30,player.shield+14);toast('Trail camp: +14 ward')}else if(l.kind==='tablet'||l.kind==='mapStone'){player.power*=1.045;toast('Ancient knowledge: wand stronger')}else if(l.kind==='foodPatch'){player.hp=Math.min(player.maxHp,player.hp+18);toast('Wild berries: +18 hearts')}else{gainXP(5+tierAt(l.x,l.y));toast('Curious nest: knowledge gained')}updateHUD()}}
const animalColors=['#f5c7b8','#cba67a','#d8c2a0','#93a96f','#b9958a','#91b6b0','#d49c65','#a1a5c2'];function drawPixelAnimal(m){let p=worldToScreen(m.x,m.y);if(!visible(p,80))return;X.save();X.translate(p.x,p.y);X.scale(m.vx<0?-1:1,1);let u=Math.max(2,Math.round(m.size/6));px(-3*u,-2*u,6*u,4*u,m.c);px(-2*u,-4*u,4*u,3*u,m.c);px(-3*u,-5*u,u,2*u,m.c);px(2*u,-5*u,u,2*u,m.c);px(-u,-4*u,u,u,'#fff');px(u,-4*u,u,u,'#fff');px(-u+1,-4*u+1,1,1,'#293143');px(u+1,-4*u+1,1,1,'#293143');if(m.elite){X.strokeStyle='#ffe77a';X.strokeRect(-4*u,-6*u,8*u,10*u)}X.restore()}
function drawPlayer(){X.save();X.translate(W/2,H/2);if(screenShake)X.translate(rnd(-screenShake,screenShake),rnd(-screenShake,screenShake));px(-9,-9,18,20,'#fff0f5');px(-7,-15,5,8,'#fff0f5');px(2,-15,5,8,'#fff0f5');px(-5,-6,3,3,'#293143');px(3,-6,3,3,'#293143');px(-2,-1,4,2,'#f28bad');X.rotate(player.heading);px(6,-2,15,4,'#8c684d');px(18,-5,5,10,'#b8f0dd');X.restore()}
function spawnMob(forceElite=false){let ring=biomeIndex(),b=BIOMES[ring],a=rnd(0,TAU),rad=Math.max(W,H)*.7+rnd(80,180),x=player.x+Math.cos(a)*rad,y=player.y+Math.sin(a)*rad,actual=tierAt(x,y),species=b.animals[Math.floor(Math.random()*3)],ferocity=1+actual*.16,size=9+actual*.72+rnd(-2,3),elite=forceElite||(actual%5===0&&Math.random()<.035),hp=(13+actual*4.8)*(elite?4.5:1),role=actual<5?'skitter':actual<10?'chase':actual<16?'pounce':actual<22?'strafe':'apex';mobs.push({x,y,vx:0,vy:0,size,hp,maxHp:hp,species,ring:actual-1,role,elite,c:animalColors[(actual+species.length)%animalColors.length],accent:b.accent,atk:rnd(.2,1.2),phase:rnd(0,TAU),ferocity})}
function updateMob(m,dt){let dx=player.x-m.x,dy=player.y-m.y,d=Math.hypot(dx,dy)||1,nx=dx/d,ny=dy/d,s=42+m.ferocity*12;if(m.role==='skitter')s*=.72;else if(m.role==='pounce'&&m.atk<.2)s*=3.2;else if(m.role==='strafe'){let tx=-ny,ty=nx;nx=nx*.55+tx*Math.sin(time+m.phase)*.75;ny=ny*.55+ty*Math.sin(time+m.phase)*.75}else if(m.role==='apex')s*=1.12;m.vx=nx*s;m.vy=ny*s;m.x+=m.vx*dt;m.y+=m.vy*dt;m.atk-=dt;if(d<m.size+12&&m.atk<=0){damagePlayer((4+m.ferocity*1.4)*(m.elite?1.55:1));m.atk=.75}if((m.role==='strafe'||m.role==='apex')&&m.atk<=0&&d<430){enemyShots.push({x:m.x,y:m.y,vx:nx*(125+m.ferocity*8),vy:ny*(125+m.ferocity*8),life:3,damage:3+m.ferocity,r:4,c:m.accent});m.atk=m.role==='apex'?.6:1.2}}
function damagePlayer(n){if(player.shield>0){let a=Math.min(player.shield,n);player.shield-=a;n-=a}if(n<=0)return;player.hp-=n;screenShake=5;if(player.hp<=0)gameOver();updateHUD()}function nearestTarget(){let best=null,bd=460*player.range;for(let m of mobs){let d=dist(player,m);if(d<bd){bd=d;best=m}}return best}
function fire(){if(shotT>0||paused||dead)return;let t=nearestTarget(),a=t?Math.atan2(t.y-player.y,t.x-player.x):player.heading;player.heading=a;shotT=.32/player.fire;let count=player.proj,spread=player.spread||(.12*(count-1));for(let i=0;i<count;i++){let off=count===1?0:(i-(count-1)/2)*spread/Math.max(1,count-1),aa=a+off,spd=390+player.lv*2;shots.push({x:player.x+Math.cos(aa)*18,y:player.y+Math.sin(aa)*18,vx:Math.cos(aa)*spd,vy:Math.sin(aa)*spd,life:1.15*player.range,damage:(8+player.lv*.65)*player.power,pierce:player.pierce,hit:new Set(),r:4,c:biome().accent,crit:Math.random()<player.crit})}}
function updateShots(dt){for(let s of shots){if(player.homing&&mobs.length){let t=mobs.reduce((a,b)=>dist(s,b)<dist(s,a)?b:a,mobs[0]),a=Math.atan2(t.y-s.y,t.x-s.x),sp=Math.hypot(s.vx,s.vy),ca=Math.atan2(s.vy,s.vx),dif=Math.atan2(Math.sin(a-ca),Math.cos(a-ca));ca+=dif*Math.min(1,dt*player.homing);s.vx=Math.cos(ca)*sp;s.vy=Math.sin(ca)*sp}s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(let m of [...mobs]){if(s.hit.has(m)||dist(s,m)>m.size+s.r)continue;s.hit.add(m);m.hp-=s.damage*(s.crit?1.8:1);if(m.hp<=0)killMob(m);if(s.pierce>0)s.pierce--;else{s.life=0;break}}}shots=shots.filter(s=>s.life>0);for(let s of enemyShots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(dist(s,player)<s.r+10){damagePlayer(s.damage);s.life=0}}enemyShots=enemyShots.filter(s=>s.life>0)}
function killMob(m){let i=mobs.indexOf(m);if(i>=0)mobs.splice(i,1);state.kills++;gainXP(1+Math.floor((m.ring+1)/3));if(m.elite||Math.random()<.22+m.ring*.006)dropRune(m.x,m.y,m.elite);if(m.elite){state.relics++;toast('Apex '+m.species+' defeated! ◇')}updateHUD()}
const RUNES=[['Quickleaf','fire',1.12,'Faster casting'],['Star Seed','power',1.13,'Stronger bolts'],['Twin Petal','proj',1,'Extra projectile'],['Needle Fern','pierce',1,'Piercing'],['Moon Eye','homing',.8,'Seeking shots'],['Longtail','range',1.12,'Longer reach'],['Lucky Bell','crit',.04,'Critical chance'],['Heart Berry','maxHp',5,'More hearts'],['Swift Paw','speed',8,'Move faster']];function dropRune(x,y,rare=false){drops.push({x,y,type:'rune',rune:RUNES[Math.floor(Math.random()*RUNES.length)],rare,life:22,spin:0})}function applyRune(r,rare){let [name,key,val]=r,m=rare?1.45:1;if(key==='fire')player.fire*=1+(val-1)*m;else if(key==='power')player.power*=1+(val-1)*m;else if(key==='proj')player.proj=Math.min(7,player.proj+1);else if(key==='pierce')player.pierce=Math.min(6,player.pierce+1);else if(key==='homing')player.homing=Math.min(8,player.homing+val*m);else if(key==='range')player.range*=1+(val-1)*m;else if(key==='crit')player.crit=Math.min(.45,player.crit+val*m);else if(key==='maxHp'){player.maxHp+=Math.round(val*m);player.hp+=Math.round(val*m)}else if(key==='speed')player.speed+=val*m;toast((rare?'Rare ':'')+name+' ✦');updateHUD()}
function updateDrops(dt){for(let d of drops){d.life-=dt;d.spin+=dt*3;let dd=dist(d,player);if(dd<95){let k=Math.min(1,dt*6);d.x+=(player.x-d.x)*k;d.y+=(player.y-d.y)*k}if(dd<18){d.life=0;applyRune(d.rune,d.rare)}}drops=drops.filter(d=>d.life>0)}function drawDrop(d){let p=worldToScreen(d.x,d.y),bob=Math.sin(d.spin)*3;px(p.x-5,p.y-6+bob,10,10,d.rare?'#ffe77a':'#fff5c2')}
function gainXP(n){player.xp+=n;while(player.xp>=player.next){player.xp-=player.next;player.lv++;player.next=Math.floor(player.next*1.28+3);player.maxHp+=2;player.hp=Math.min(player.maxHp,player.hp+8);player.power*=1.025;player.fire*=1.012;toast('Level '+player.lv+'!')}updateHUD()}
function envPhysics(dt){let e=biome().effect;player.envSlow=e==='mud'?.83:e==='ice'?1.08:(e==='heat'||e==='ash')?.92:1;if(e==='current'){player.x+=Math.sin(time*.7)*9*dt;player.y+=5*dt}if(e==='gust'||e==='wind'||e==='storm')player.x+=Math.sin(time*1.3)*12*dt}
function update(dt){time+=dt;shotT=Math.max(0,shotT-dt);screenShake=Math.max(0,screenShake-dt*18);envPhysics(dt);let mag=Math.hypot(input.mx,input.my);if(mag>.05){let nx=input.mx/mag,ny=input.my/mag,s=player.speed*player.envSlow*Math.min(1,mag);player.x+=nx*s*dt;player.y+=ny*s*dt;player.heading=Math.atan2(ny,nx)}if(input.shoot)fire();let ring=biomeIndex();if(ring>state.bestRing){state.bestRing=ring;toast('Discovered '+BIOMES[ring].name);state.relics++;updateHUD()}ensureLandmarks();interactLandmarks();spawnT-=dt;let cap=10+Math.min(24,ring);if(spawnT<=0&&mobs.length<cap){spawnMob();spawnT=Math.max(.18,1.05-ring*.022)}for(let m of [...mobs])updateMob(m,dt);updateShots(dt);updateDrops(dt);mobs=mobs.filter(m=>dist(m,player)<1300);landmarks=landmarks.filter(l=>Math.abs(l.ring-ring)<=2);if(toastT>0&&(toastT-=dt)<=0)$('toast').classList.remove('show')}
function draw(){drawDenseWorld();for(let l of landmarks)drawLandmark(l);drawAmbient();for(let d of drops)drawDrop(d);for(let s of shots){let p=worldToScreen(s.x,s.y);px(p.x-s.r,p.y-s.r,s.r*2,s.r*2,s.crit?'#fff4a3':s.c)}for(let s of enemyShots){let p=worldToScreen(s.x,s.y);px(p.x-s.r,p.y-s.r,s.r*2,s.r*2,s.c)}for(let m of mobs)drawPixelAnimal(m);drawPlayer();drawEffects();drawCompass()}
function drawCompass(){let ring=biomeIndex(),next=(ring+1)*RING,rad=Math.hypot(player.x,player.y),remain=Math.max(0,next-rad),b=biome();X.save();px(W/2-82,42,164,28,'#172033aa');X.fillStyle='#fff';X.font='900 9px monospace';X.textAlign='center';X.fillText(b.name.toUpperCase(),W/2,53);X.fillStyle=b.accent;X.fillText(ring<29?Math.ceil(remain)+'m TO '+BIOMES[ring+1].name.toUpperCase():'HEART OF THE ELDER WILDS',W/2,64);X.restore()}
function updateHUD(){let b=biome(),r=biomeIndex();$('hp').textContent=Math.max(0,Math.ceil(player.hp));$('maxhp').textContent=Math.ceil(player.maxHp);$('hpfill').style.width=100*clamp(player.hp/player.maxHp,0,1)+'%';$('lv').textContent=player.lv;$('xp').textContent=Math.floor(player.xp)+'/'+player.next;$('biome').textContent=(r+1)+'/30 '+b.name;$('weapon').textContent=player.proj+'× Wand · '+player.fire.toFixed(1)+' rate · '+player.power.toFixed(1)+' power';$('danger').textContent='Wild '+(r+1);$('relics').textContent=state.relics;$('flowfill').style.width=clamp(player.shield/30*100,0,100)+'%'}function toast(t){$('toast').textContent=t;$('toast').classList.add('show');toastT=2.4}
function reset(){Object.assign(player,{x:0,y:0,hp:60,maxHp:60,speed:170,lv:1,xp:0,next:8,power:1,fire:1,proj:1,spread:0,pierce:0,homing:0,crit:.05,range:1,shield:0,heading:0,envSlow:1});mobs=[];shots=[];enemyShots=[];drops=[];landmarks=[];Object.assign(state,{kills:0,relics:0,bestRing:0,places:0});state.discoveries.clear();time=0;dead=false;paused=false;spawnT=0;updateHUD()}function gameOver(){dead=true;paused=true;$('controls').classList.add('hide');$('death').classList.remove('hide');$('dlevel').textContent=player.lv;$('dtime').textContent=Math.floor(time/60)+':'+String(Math.floor(time%60)).padStart(2,'0');$('dkills').textContent=state.kills;$('drelics').textContent=state.relics}
function loop(ts){let dt=Math.min(.033,(ts-last)/1000||0);last=ts;if(started&&!paused&&!dead)update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
const joy=$('joystick'),knob=$('joyknob');function joyMove(e){if(input.pid!==e.pointerId)return;let r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,lim=r.width*.34,d=Math.hypot(dx,dy)||1,k=Math.min(1,lim/d);dx*=k;dy*=k;knob.style.transform=`translate(${dx}px,${dy}px)`;input.mx=dx/lim;input.my=dy/lim}joy.onpointerdown=e=>{input.pid=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e)};joy.onpointermove=joyMove;function joyEnd(e){if(input.pid!==e.pointerId)return;input.pid=null;input.mx=input.my=0;knob.style.transform='translate(0,0)'}joy.onpointerup=joyEnd;joy.onpointercancel=joyEnd;const shoot=$('shoot');shoot.onpointerdown=e=>{e.preventDefault();shoot.setPointerCapture(e.pointerId);input.shoot=true;shoot.classList.add('pressed');fire()};function shootEnd(){input.shoot=false;shoot.classList.remove('pressed')}shoot.onpointerup=shootEnd;shoot.onpointercancel=shootEnd;$('play').onclick=()=>{reset();started=true;$('start').classList.add('hide');$('controls').classList.remove('hide');toast('The tiny trail begins…')};$('again').onclick=()=>{reset();$('death').classList.add('hide');$('controls').classList.remove('hide')};
window.__TWBB_V18__={version:18,state:()=>({ring:biomeIndex()+1,biome:biome().name,player:{...player},kills:state.kills,relics:state.relics,places:state.places}),warp:n=>{let i=clamp((n|0)-1,0,29);player.x=i*RING+20;player.y=0;updateHUD()},spawnApex:()=>spawnMob(true)};
})();