(()=>{'use strict';
const C=document.getElementById('g'),X=C.getContext('2d'),BIOMES=window.TWBB_WORLD;
if(!C||!X||!BIOMES) throw new Error('TWBB v19 boot data missing');
X.imageSmoothingEnabled=false;
const $=id=>document.getElementById(id),TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),d2=(ax,ay,bx,by)=>Math.hypot(ax-bx,ay-by);
let W=0,H=0,DPR=1,last=0,started=false,paused=false,dead=false,time=0,spawnT=0,shotT=0,toastT=0,shake=0,flash=0,eventT=18,eventText='';
const RING=780,CELL=72,FEATURE_CELL=360,STRUCT_CELL=560;
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*DPR;C.height=H*DPR;C.style.width=W+'px';C.style.height=H+'px';X.setTransform(DPR,0,0,DPR,0,0);X.imageSmoothingEnabled=false} addEventListener('resize',resize);resize();
function hash(n){return Math.abs(Math.sin(n*127.1+Math.cos(n*9.13))*43758.5453)%1}
function h2(x,y,s=0){return hash(x*91.7+y*173.3+s*31.7)}
function choose(a,h){return a[Math.floor(h*a.length)%a.length]}
function biomeIndexAt(x,y){return clamp(Math.floor(Math.hypot(x,y)/RING),0,29)}
function biomeAt(x,y){return BIOMES[biomeIndexAt(x,y)]}
function biome(){return biomeAt(player.x,player.y)}
function toScreen(x,y){return{x:W/2+x-player.x,y:H/2+y-player.y}}
function visibleS(x,y,m=100){return x>-m&&x<W+m&&y>-m&&y<H+m}
function rect(x,y,w,h,c){X.fillStyle=c;X.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function text(t,x,y,size=10,c='#fff',align='center'){X.fillStyle=c;X.font=`900 ${size}px ui-monospace,monospace`;X.textAlign=align;X.textBaseline='middle';X.fillText(t,x,y)}
function pretty(s){return String(s).replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase())}
const state={kills:0,relics:0,bestRing:0,places:0,combo:0,comboT:0,bestCombo:0,biomeKills:Array(30).fill(0),apexDefeated:new Set(),perks:[],eventKills:0};
const player={x:0,y:0,hp:72,maxHp:72,speed:188,lv:1,xp:0,next:10,power:1,fire:1,proj:1,spread:.13,pierce:0,homing:0,crit:.06,range:1,shield:0,heading:0,envSlow:1,dash:0,dashCd:2.7,invuln:0,magnet:105,luck:0,boltSize:4,chain:0,explode:0,frost:0,orbit:0,lifeSteal:0};
const input={mx:0,my:0,shoot:false,pid:null};
let mobs=[],shots=[],enemyShots=[],drops=[],particles=[],floaters=[],landmarks=[],orbiters=[];
const RUNES=[['Quickleaf','fire',.16,'Faster casting'],['Star Seed','power',.18,'Stronger bolts'],['Twin Petal','proj',1,'Extra projectile'],['Needle Fern','pierce',1,'Piercing'],['Moon Eye','homing',1.2,'Seeking bolts'],['Longtail','range',.18,'Longer reach'],['Lucky Bell','crit',.055,'Critical chance'],['Swift Paw','speed',12,'Move faster'],['Big Spark','size',1,'Larger bolts'],['Storm Seed','chain',1,'Chain lightning']];
const PERKS=[
{id:'rapid',icon:'⚡',name:'PETAL STORM',desc:'+28% fire rate',apply(){player.fire*=1.28}},
{id:'triple',icon:'✦',name:'TRIPLE BLOOM',desc:'+2 projectiles',apply(){player.proj=Math.min(9,player.proj+2)}},
{id:'heavy',icon:'💥',name:'BIG BONK',desc:'+32% damage, larger bolts',apply(){player.power*=1.32;player.boltSize=Math.min(9,player.boltSize+1)}},
{id:'pierce',icon:'➶',name:'THORN NEEDLE',desc:'+2 pierce',apply(){player.pierce=Math.min(8,player.pierce+2)}},
{id:'seeker',icon:'☄',name:'MOON SEEKER',desc:'Strong homing',apply(){player.homing=Math.min(8,player.homing+2.2)}},
{id:'dash',icon:'💨',name:'BUNNY HOP',desc:'Dash cooldown -30%',apply(){player.dashCd=Math.max(.65,player.dashCd*.7);player.speed+=9}},
{id:'heart',icon:'♥',name:'GIANT HEART',desc:'+20 max HP, heal fully',apply(){player.maxHp+=20;player.hp=player.maxHp}},
{id:'crit',icon:'★',name:'LUCKY FANG',desc:'+12% crit chance',apply(){player.crit=Math.min(.55,player.crit+.12)}},
{id:'explode',icon:'✹',name:'BURST BERRY',desc:'Kills explode nearby',apply(){player.explode++}},
{id:'chain',icon:'ϟ',name:'CHAIN SPARK',desc:'Shots arc to another animal',apply(){player.chain++}},
{id:'frost',icon:'❄',name:'FROST BLOOM',desc:'Hits slow animals',apply(){player.frost++}},
{id:'orbit',icon:'◎',name:'WISP FRIEND',desc:'Gain an orbiting wisp',apply(){player.orbit++;syncOrbiters()}},
{id:'magnet',icon:'◇',name:'TREASURE NOSE',desc:'Much larger pickup radius',apply(){player.magnet+=85;player.luck+=.08}},
{id:'vamp',icon:'♡',name:'SWEET TOOTH',desc:'Heal from every 12 kills',apply(){player.lifeSteal++}}
];
function toast(t,d=2.1){const e=$('toast');e.textContent=t;e.classList.add('show');toastT=d}
function floater(t,x,y,c='#fff',size=10){floaters.push({t,x,y,c,size,life:.9})}
function burst(x,y,c,n=8,spd=80){for(let i=0;i<n;i++){let a=rnd(0,TAU),s=rnd(spd*.35,spd);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rnd(.25,.65),c,r:rnd(2,4)})}}
function updateFX(dt){for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.94;p.vy*=.94;p.life-=dt}particles=particles.filter(p=>p.life>0);for(const f of floaters){f.y-=24*dt;f.life-=dt}floaters=floaters.filter(f=>f.life>0);shake=Math.max(0,shake-dt*22);flash=Math.max(0,flash-dt*3)}
function plantS(type,sx,sy,s,b,h){let u=Math.max(1,Math.round(s));X.save();X.translate(Math.round(sx),Math.round(sy));rect(-7*u,4*u,14*u,4*u,'#17251c22');if(/birch|pine|fir|tree|oak|maple|willow|palm|baobab|acacia/i.test(type)){let trunk=/birch/i.test(type)?'#eee7d4':'#745441',leaf=/snow|storm|fir|pine/i.test(type)?'#557467':/maple|autumn/i.test(type)?'#db8452':/palm|date/i.test(type)?'#5d9b58':b.shade;rect(-2*u,-2*u,4*u,15*u,trunk);if(/palm|date/i.test(type)){for(let a=0;a<6;a++){let aa=a*TAU/6;rect(Math.cos(aa)*8*u-4*u,-11*u+Math.sin(aa)*3*u,8*u,3*u,leaf)}}else if(/baobab/i.test(type)){rect(-10*u,-12*u,20*u,8*u,leaf);rect(-7*u,-17*u,14*u,6*u,leaf)}else{rect(-8*u,-10*u,16*u,8*u,leaf);rect(-6*u,-16*u,12*u,8*u,leaf);if(/pine|fir/i.test(type)){rect(-7*u,-14*u,14*u,4*u,leaf);rect(-5*u,-19*u,10*u,5*u,leaf);rect(-3*u,-23*u,6*u,5*u,leaf)}}}else if(/bamboo/i.test(type)){for(let i=-1;i<=1;i++){rect(i*5*u,-19*u,3*u,23*u,'#5d9b58');rect(i*5*u-2*u,-13*u,7*u,2*u,'#89c86f')}}else if(/cactus/i.test(type)){rect(-3*u,-15*u,6*u,18*u,'#5aa56c');rect(-7*u,-9*u,5*u,3*u,'#5aa56c');rect(4*u,-12*u,5*u,3*u,'#5aa56c');if(h>.7)rect(-2*u,-18*u,4*u,4*u,'#f2a6bd')}else if(/crystal|obsidian|iceSpikes|stalagmite|lavaCrystal/i.test(type)){let cc=/lava/i.test(type)?'#ff724d':/obsidian/i.test(type)?'#343044':/ice/i.test(type)?'#dff7ff':b.accent;rect(-5*u,-10*u,6*u,13*u,cc);rect(2*u,-17*u,6*u,20*u,cc);rect(8*u,-8*u,4*u,11*u,cc);rect(4*u,-14*u,2*u,6*u,'#fff8')}else if(/mushroom/i.test(type)){rect(-1*u,-5*u,2*u,8*u,'#eadfc8');rect(-5*u,-9*u,10*u,4*u,/glow|fire/i.test(type)?b.accent:'#d7858d')}else if(/flower|daisy|buttercup|clover|tulip|sunflower|bluebell|orchid|foxglove|bromeliad|moonFlower|iceFlower|ancientFlower/i.test(type)){rect(-1*u,-5*u,2*u,8*u,'#5f9d55');let cc=/sunflower|buttercup/i.test(type)?'#ffe06f':/bluebell/i.test(type)?'#9186e0':/orchid|foxglove|tulip|flower/i.test(type)?'#ef9ac2':b.accent;rect(-4*u,-9*u,8*u,3*u,cc);rect(-2*u,-11*u,4*u,7*u,cc)}else if(/termiteMound|dune|snowdrift/i.test(type)){let cc=/snow/i.test(type)?'#eef9ff':/dune/i.test(type)?'#e8cf85':'#9e754e';rect(-9*u,-4*u,18*u,7*u,cc);rect(-5*u,-9*u,10*u,8*u,cc)}else{let cc=/reed|kelp|moss|fern|ivy|vine|monstera|papyrus|cattail/i.test(type)?b.shade:'#759e58';for(let i=0;i<4;i++){let hh=(5+h2(i,h,2)*8)*u;rect((-5+i*3)*u,-hh,2*u,hh,cc)}}X.restore()}
function propS(type,sx,sy,s,b,h){let u=Math.max(1,Math.round(s));X.save();X.translate(Math.round(sx),Math.round(sy));rect(-7*u,3*u,14*u,4*u,'#17251c22');if(/rock|boulder|stone|obsidian|cairn|iceRock/i.test(type)){let cc=/obsidian/i.test(type)?'#343044':/ice/i.test(type)?'#cdeaf2':'#817b74';rect(-7*u,-4*u,14*u,8*u,cc);rect(-4*u,-8*u,8*u,5*u,'#9a958c')}else if(/log|driftwood|woodpile|root|fallen|charLog|giantLog|damLog/i.test(type)){rect(-10*u,-3*u,20*u,6*u,'#73533d');rect(-9*u,-2*u,4*u,4*u,'#9d7755')}else if(/stump/i.test(type)){rect(-6*u,-7*u,12*u,10*u,'#74513e');rect(-5*u,-9*u,10*u,4*u,'#aa7f5c')}else if(/sign/i.test(type)){rect(-2*u,-9*u,4*u,14*u,'#795b43');rect(-8*u,-13*u,16*u,7*u,'#b98b5a');rect(-4*u,-11*u,8*u,2*u,'#6f543d')}else if(/fence/i.test(type)){rect(-12*u,-6*u,24*u,3*u,'#9b724c');rect(-12*u,0,24*u,3*u,'#9b724c');rect(-10*u,-9*u,3*u,14*u,'#9b724c');rect(7*u,-9*u,3*u,14*u,'#9b724c')}else if(/bones|skull|antler|fossil/i.test(type)){rect(-7*u,-2*u,14*u,3*u,'#e8dfc7');rect(-2*u,-6*u,4*u,10*u,'#e8dfc7');if(/skull/i.test(type)){rect(-5*u,-8*u,10*u,7*u,'#e8dfc7');rect(-3*u,-6*u,2*u,2*u,'#4a413b');rect(2*u,-6*u,2*u,2*u,'#4a413b')}}else if(/lantern|torch|lightningRod/i.test(type)){rect(-1*u,-9*u,2*u,13*u,'#5b4d49');rect(-4*u,-13*u,8*u,7*u,b.accent)}else if(/barrel|crate|basket|pottery|hay|pumpkin|fishCrate|fruitCrate|caravanCrate|mineCart/i.test(type)){let cc=/pottery/i.test(type)?'#b76d51':/hay/i.test(type)?'#d3ad54':/pumpkin/i.test(type)?'#d98042':'#8c6748';rect(-7*u,-7*u,14*u,12*u,cc);rect(-6*u,-4*u,12*u,2*u,'#0002')}else if(/anchor/i.test(type)){rect(-2*u,-12*u,4*u,16*u,'#5b636c');rect(-8*u,-1*u,16*u,3*u,'#5b636c')}else if(/shell|starfish/i.test(type)){rect(-5*u,-4*u,10*u,8*u,/starfish/i.test(type)?'#e99973':'#f2d4b4')}else if(/totem|ruinPillar|brokenStatue|ancientStone/i.test(type)){rect(-6*u,-14*u,12*u,18*u,'#7d7c71');rect(-8*u,-17*u,16*u,4*u,'#9a9786');rect(-3*u,-10*u,6*u,3*u,b.accent)}else rect(-6*u,-6*u,12*u,10*u,'#8c735d');X.restore()}
function structureS(type,sx,sy,b,h,large=false){let S=large?1.18:1;X.save();X.translate(Math.round(sx),Math.round(sy));rect(-32*S,22*S,64*S,6*S,'#17251c26');let wall='#d8c39d',wood='#79583e',roof=b.shade,light=b.accent;if(/bridge|boardwalk|ropeBridge|lavaBridge/i.test(type)){rect(-45*S,-7*S,90*S,14*S,/lava/i.test(type)?'#6e4a3f':'#9b724c');for(let i=-36;i<=36;i+=12)rect(i*S,-10*S,4*S,20*S,'#6e523e')}else if(/tower|lighthouse|obelisk/i.test(type)){rect(-13*S,-42*S,26*S,66*S,/lighthouse/i.test(type)?'#e8e3cf':'#8b887f');rect(-18*S,-47*S,36*S,8*S,roof);rect(-8*S,-30*S,7*S,8*S,light);rect(2*S,-30*S,7*S,8*S,light)}else if(/shrine|temple|pagoda|altar/i.test(type)){rect(-24*S,-22*S,48*S,44*S,'#87877c');rect(-31*S,-27*S,62*S,8*S,'#a09e8e');rect(-17*S,-42*S,34*S,18*S,roof);rect(-5*S,-16*S,10*S,14*S,light)}else if(/gate|arch/i.test(type)){rect(-28*S,-38*S,10*S,62*S,'#88867d');rect(18*S,-38*S,10*S,62*S,'#88867d');rect(-28*S,-42*S,56*S,10*S,'#9d9a8c')}else if(/windmill/i.test(type)){rect(-15*S,-28*S,30*S,50*S,wall);rect(-18*S,-33*S,36*S,10*S,roof);X.strokeStyle=wood;X.lineWidth=4*S;for(let a=0;a<4;a++){X.beginPath();X.moveTo(0,-18*S);X.lineTo(Math.cos(a*Math.PI/2)*33*S,-18*S+Math.sin(a*Math.PI/2)*33*S);X.stroke()}}else if(/well/i.test(type)){rect(-18*S,-8*S,36*S,22*S,'#8d887d');rect(-20*S,-12*S,40*S,7*S,'#a9a49a');rect(-15*S,-28*S,4*S,20*S,wood);rect(11*S,-28*S,4*S,20*S,wood);rect(-17*S,-31*S,34*S,5*S,roof)}else if(/dock|boat|boathouse/i.test(type)){rect(-35*S,2*S,70*S,10*S,wood);if(/boat/i.test(type)){rect(-23*S,-15*S,46*S,14*S,'#825e45');rect(-15*S,-20*S,30*S,6*S,'#b28158')}}else if(/mine|lift/i.test(type)){rect(-30*S,-30*S,60*S,52*S,'#34353b');rect(-25*S,-35*S,7*S,60*S,wood);rect(18*S,-35*S,7*S,60*S,wood);rect(-25*S,-38*S,50*S,7*S,wood)}else if(/forge/i.test(type)){rect(-28*S,-20*S,56*S,42*S,'#6e5a50');rect(-32*S,-25*S,64*S,8*S,'#40383a');rect(-8*S,-11*S,16*S,18*S,'#ff794d')}else if(/camp|tent|picnic/i.test(type)){X.fillStyle=/picnic/i.test(type)?'#e89db8':'#d6a36d';X.beginPath();X.moveTo(-24*S,18*S);X.lineTo(0,-24*S);X.lineTo(24*S,18*S);X.fill();rect(-4*S,0,8*S,18*S,'#664a3b')}else{rect(-28*S,-20*S,56*S,42*S,wall);rect(-33*S,-26*S,66*S,10*S,roof);rect(-22*S,-13*S,12*S,12*S,light);rect(10*S,-13*S,12*S,12*S,light);rect(-7*S,3*S,14*S,19*S,wood)}X.restore()}
function featureS(type,sx,sy,b,h){X.save();X.translate(Math.round(sx),Math.round(sy));let water='#69bfc4';if(/pond|pool|hole|watering|bog|tide|oasis|lake|fishingHole|moonPond|mistPond/i.test(type)){X.fillStyle=/lava/i.test(type)?'#ff6948':/frozen|ice/i.test(type)?'#cfefff':water;X.beginPath();X.ellipse(0,0,55+h*25,25+h*14,0,0,TAU);X.fill();rect(-24,-7,28,3,'#ffffff55')}else if(/stream|river|lavaRiver/i.test(type)){rect(-80,-12-h*8,160,24+h*16,/lava/i.test(type)?'#ff6846':water);for(let i=-60;i<70;i+=30)rect(i,-4,18,2,'#ffffff44')}else if(/waterfall/i.test(type)){rect(-30,-60,60,80,b.shade);rect(-14,-55,28,66,'#7fd5d9');rect(-23,10,46,14,'#69bfc4');rect(-10,-50,8,55,'#ffffff77')}else if(/chasm|ravine|cliff|crater/i.test(type)){X.fillStyle='#252632';X.beginPath();X.ellipse(0,5,62+h*20,25+h*12,0,0,TAU);X.fill();rect(-55,-4,110,5,b.shade)}else if(/shipwreck/i.test(type)){rect(-50,-5,100,12,'#664b3a');rect(-35,-18,70,10,'#8c6748');rect(-3,-50,6,42,'#604939')}else{for(let i=0;i<8;i++){let a=i*TAU/8,r=24+(i%3)*10,xx=Math.cos(a)*r,yy=Math.sin(a)*r;rect(xx-5,yy-4,10,7,i%2?b.shade:'#82776b');if(i%3===0)rect(xx-2,yy-9,4,6,b.accent)}}X.restore()}
function drawWorld(){const centerBiome=biome();rect(0,0,W,H,centerBiome.ground);let sx=Math.floor((player.x-W/2)/CELL)-2,ex=Math.ceil((player.x+W/2)/CELL)+2,sy=Math.floor((player.y-H/2)/CELL)-2,ey=Math.ceil((player.y+H/2)/CELL)+2;for(let cy=sy;cy<=ey;cy++)for(let cx=sx;cx<=ex;cx++){let wx=cx*CELL+8+h2(cx,cy,11)*54,wy=cy*CELL+8+h2(cx,cy,12)*54,b=biomeAt(wx,wy),hh=h2(cx,cy,b.i),p=toScreen(wx,wy);if(!visibleS(p.x,p.y,70))continue;if(hh>.10)plantS(choose(b.flora,h2(cx,cy,21)),p.x,p.y,.72+h2(cx,cy,22)*.5,b,hh);if(hh>.58)propS(choose(b.props,h2(cx,cy,31)),p.x+15,p.y-10,.7+h2(cx,cy,32)*.35,b,hh);if(hh>.86)plantS(choose(b.flora,h2(cx,cy,41)),p.x-17,p.y+13,.65,b,hh)}sx=Math.floor((player.x-W/2-190)/FEATURE_CELL);ex=Math.ceil((player.x+W/2+190)/FEATURE_CELL);sy=Math.floor((player.y-H/2-190)/FEATURE_CELL);ey=Math.ceil((player.y+H/2+190)/FEATURE_CELL);for(let cy=sy;cy<=ey;cy++)for(let cx=sx;cx<=ex;cx++){let wx=cx*FEATURE_CELL+55+h2(cx,cy,101)*240,wy=cy*FEATURE_CELL+55+h2(cx,cy,102)*240,b=biomeAt(wx,wy),hh=h2(cx,cy,b.i+100);if(hh<.48)continue;let p=toScreen(wx,wy);if(!visibleS(p.x,p.y,180))continue;let type=choose(b.features,h2(cx,cy,103));if(/grove|forest|thicket|maze|garden|field|patch|orchard|flowerRing|bambooThicket|palmGrove|acaciaGrove|pineGrove|taigaGrove|elderGrove/i.test(type)){for(let i=0;i<10;i++){let a=i*2.399+hh*TAU,r=18+(i%4)*13;plantS(choose(b.flora,h2(i,hh,8)),p.x+Math.cos(a)*r,p.y+Math.sin(a)*r,1,b,h2(i,hh,9))}}else if(/ruin|hall|courtyard|stoneCircle|rockArch|stepping|stonePath|fossil|rockField|crystalField|obsidianField/i.test(type)){for(let i=0;i<8;i++){let a=i*TAU/8,r=34;propS(/fossil/i.test(type)?'bones':/crystal/i.test(type)?'crystal':/obsidian/i.test(type)?'obsidian':'rock',p.x+Math.cos(a)*r,p.y+Math.sin(a)*r,.85,b,hh)}}else featureS(type,p.x,p.y,b,hh)}sx=Math.floor((player.x-W/2-170)/STRUCT_CELL);ex=Math.ceil((player.x+W/2+170)/STRUCT_CELL);sy=Math.floor((player.y-H/2-170)/STRUCT_CELL);ey=Math.ceil((player.y+H/2+170)/STRUCT_CELL);for(let cy=sy;cy<=ey;cy++)for(let cx=sx;cx<=ex;cx++){let wx=cx*STRUCT_CELL+90+h2(cx,cy,201)*360,wy=cy*STRUCT_CELL+90+h2(cx,cy,202)*360,b=biomeAt(wx,wy),hh=h2(cx,cy,b.i+200);if(hh<.57)continue;let p=toScreen(wx,wy);if(!visibleS(p.x,p.y,150))continue;let type=choose(b.structures,h2(cx,cy,203));structureS(type,p.x,p.y,b,hh,hh>.9);let id=`p:${cx}:${cy}`;if(d2(player.x,player.y,wx,wy)<72&&!state.apexDefeated.has(id)){state.apexDefeated.add(id);state.places++;state.relics++;toast('Found '+pretty(type)+' ✦');burst(wx,wy,b.accent,12,55)}}X.save();X.globalAlpha=.13;X.strokeStyle='#f8e4bd';X.lineWidth=16;X.beginPath();for(let r=0;r<30*RING;r+=72){let a=Math.sin(r*.0027)*.18,p=toScreen(Math.cos(a)*r,Math.sin(a)*r);if(r===0)X.moveTo(p.x,p.y);else X.lineTo(p.x,p.y)}X.stroke();X.restore()}
function landmarkKind(i){return['chest','shrine','camp','spring','tablet','nest'][i%6]}
function ensureLandmarks(){let ring=biomeIndexAt(player.x,player.y);for(let r=Math.max(0,ring-1);r<=Math.min(29,ring+1);r++)for(let j=0;j<6;j++){let id=`l:${r}:${j}`;if(landmarks.some(l=>l.id===id))continue;let a=hash(r*77+j*17)*TAU,rad=(r+.16+.68*hash(r*33+j))*RING;landmarks.push({id,ring:r,x:Math.cos(a)*rad,y:Math.sin(a)*rad,kind:landmarkKind(r+j),used:false})}}
function drawLandmarks(){for(const l of landmarks){let p=toScreen(l.x,l.y);if(!visibleS(p.x,p.y,90))continue;let b=BIOMES[l.ring];if(l.kind==='camp'){structureS('camp',p.x,p.y,b,.5,false)}else if(l.kind==='chest'){propS('crate',p.x,p.y,1.25,b,.7)}else if(l.kind==='shrine'){structureS('shrine',p.x,p.y,b,.5,false)}else if(l.kind==='spring'){X.fillStyle='#84dfe7';X.beginPath();X.ellipse(p.x,p.y,18,10,0,0,TAU);X.fill();rect(p.x-9,p.y-2,12,2,'#fff9')}else if(l.kind==='tablet'){propS('ancientStone',p.x,p.y,1.2,b,.5)}else{for(let i=0;i<5;i++)plantS('flower',p.x+(i-2)*8,p.y+(i%2)*5,1,b,i*.2)}}}
function interactLandmarks(){for(const l of landmarks){if(l.used||d2(player.x,player.y,l.x,l.y)>30)continue;l.used=true;state.places++;state.relics++;if(l.kind==='chest'){dropCharm(l.x,l.y,true);dropCharm(l.x+12,l.y,true);toast('Treasure! Two charms ✦')}else if(l.kind==='shrine'){player.maxHp+=8;player.hp=player.maxHp;toast('Shrine blessing: full heal +8 HP')}else if(l.kind==='spring'){player.hp=Math.min(player.maxHp,player.hp+35);player.shield=Math.min(40,player.shield+10);toast('Magic spring: healed + ward')}else if(l.kind==='camp'){player.shield=Math.min(40,player.shield+18);toast('Campfire rest: +18 ward')}else if(l.kind==='tablet'){player.power*=1.07;toast('Ancient rune: +7% wand power')}else{gainXP(10+BIOMES[l.ring].i);toast('Secret nest: big XP!')}burst(l.x,l.y,BIOMES[l.ring].accent,14,65)}}
function spawnMob(opts={}){let ring=biomeIndexAt(player.x,player.y),ang=rnd(0,TAU),rad=Math.max(W,H)*.65+rnd(90,180),x=player.x+Math.cos(ang)*rad,y=player.y+Math.sin(ang)*rad,b=biomeAt(x,y),tier=b.i+1;let apex=!!opts.apex,elite=apex||Math.random()<.035+tier*.002;let species=apex?b.animals[2]:b.animals[Math.floor(Math.random()*3)],size=10+tier*.72+(apex?13:elite?6:0),role=apex?'apex':tier<5?'skitter':tier<10?(Math.random()<.25?'charger':'chase'):tier<18?(Math.random()<.28?'shooter':'charger'):(Math.random()<.3?'tank':'shooter');let hp=(15+tier*5.2)*(apex?9:elite?3.1:role==='tank'?1.8:1),speed=48+tier*2.1+(role==='charger'?15:0);mobs.push({x,y,vx:0,vy:0,hp,maxHp:hp,size,role,species,ring:b.i,elite,apex,speed,atk:rnd(.3,1.2),charge:0,slow:0,phase:rnd(0,TAU),c:['#efb6a4','#caa179','#9fbd87','#93b6ba','#c99888','#aaa5c8'][(tier+species.length)%6],accent:b.accent})}
function spawnApexForRing(r){if(mobs.some(m=>m.apex&&m.ring===r))return;let b=BIOMES[r],a=Math.atan2(player.y,player.x),rad=330,x=player.x+Math.cos(a+.8)*rad,y=player.y+Math.sin(a+.8)*rad,tier=r+1,hp=(35+tier*9)*9;mobs.push({x,y,vx:0,vy:0,hp,maxHp:hp,size:25+tier*.8,role:'apex',species:'Apex '+b.animals[2],ring:r,elite:true,apex:true,speed:58+tier*1.8,atk:1,charge:0,slow:0,phase:rnd(0,TAU),c:'#cf8d78',accent:b.accent});toast('⚠ APEX '+b.animals[2].toUpperCase()+' HAS ARRIVED!',3);shake=8}
function updateMob(m,dt){let dx=player.x-m.x,dy=player.y-m.y,d=Math.hypot(dx,dy)||1,nx=dx/d,ny=dy/d,spd=m.speed*(m.slow>0?.58:1);m.slow=Math.max(0,m.slow-dt);m.atk-=dt;if(m.role==='skitter'){nx+=Math.sin(time*3+m.phase)*.4;ny+=Math.cos(time*2.3+m.phase)*.4;spd*=.82}else if(m.role==='charger'){if(m.charge>0){spd*=3.1;m.charge-=dt}else if(m.atk<.15&&d<360){m.charge=.24;m.atk=1.6;burst(m.x,m.y,'#fff3a0',4,30)}}else if(m.role==='shooter'){if(d<220){nx=-nx;ny=-ny;spd*=.75}else{let tx=-ny,ty=nx;nx=.55*nx+.7*tx*Math.sin(time+m.phase);ny=.55*ny+.7*ty*Math.sin(time+m.phase)}if(m.atk<=0&&d<470){enemyShots.push({x:m.x,y:m.y,vx:(dx/d)*(150+m.ring*3),vy:(dy/d)*(150+m.ring*3),life:3.2,r:5,damage:6+m.ring*.55,c:m.accent});m.atk=1.25}}else if(m.role==='tank')spd*=.62;else if(m.apex){spd*=1.05;if(m.atk<=0&&d<520){for(let i=-2;i<=2;i++){let a=Math.atan2(dy,dx)+i*.18;enemyShots.push({x:m.x,y:m.y,vx:Math.cos(a)*(175+m.ring*2),vy:Math.sin(a)*(175+m.ring*2),life:3.2,r:6,damage:7+m.ring*.6,c:m.accent})}m.atk=.95}}m.vx=nx*spd;m.vy=ny*spd;m.x+=m.vx*dt;m.y+=m.vy*dt;if(d<m.size+12&&m.atk<=0){damagePlayer((m.apex?13:5)+m.ring*.55);m.atk=.85;m.x-=nx*24;m.y-=ny*24}}
function drawAnimal(m){let p=toScreen(m.x,m.y);if(!visibleS(p.x,p.y,100))return;let u=Math.max(2,Math.round(m.size/6));X.save();X.translate(Math.round(p.x),Math.round(p.y));X.scale(m.vx<0?-1:1,1);rect(-3*u,2*u,6*u,2*u,'#0003');rect(-3*u,-2*u,6*u,4*u,m.c);rect(-2*u,-4*u,4*u,3*u,m.c);rect(-3*u,-5*u,u,2*u,m.c);rect(2*u,-5*u,u,2*u,m.c);rect(-u,-4*u,u,u,'#fff7f0');rect(u,-4*u,u,u,'#fff7f0');rect(-u+1,-4*u+1,1,1,'#293143');rect(u+1,-4*u+1,1,1,'#293143');rect(-u,-2*u,2*u,u,m.accent);if(m.elite){X.strokeStyle=m.apex?'#fff1a0':'#ffe77a';X.lineWidth=m.apex?3:2;X.strokeRect(-4*u,-6*u,8*u,10*u)}X.restore();if(m.hp<m.maxHp||m.elite){let bw=Math.max(24,m.size*2.3);rect(p.x-bw/2,p.y-m.size-14,bw,5,'#172033aa');rect(p.x-bw/2,p.y-m.size-14,bw*clamp(m.hp/m.maxHp,0,1),5,m.apex?'#ffcf5d':'#ff7794');if(m.apex)text(m.species,p.x,p.y-m.size-22,8,'#fff')}}
function nearestTarget(x=player.x,y=player.y,max=520*player.range,exclude=null){let best=null,bd=max;for(const m of mobs){if(m===exclude)continue;let d=d2(x,y,m.x,m.y);if(d<bd){bd=d;best=m}}return best}
function fire(){if(shotT>0||paused||dead)return;let target=nearestTarget(),a=target?Math.atan2(target.y-player.y,target.x-player.x):player.heading;player.heading=a;shotT=.31/player.fire;let count=player.proj,totalSpread=player.spread*Math.max(0,count-1);for(let i=0;i<count;i++){let off=count===1?0:-totalSpread/2+totalSpread*i/(count-1),aa=a+off,spd=430+player.lv*2;shots.push({x:player.x+Math.cos(aa)*18,y:player.y+Math.sin(aa)*18,vx:Math.cos(aa)*spd,vy:Math.sin(aa)*spd,life:1.18*player.range,damage:(9+player.lv*.72)*player.power,pierce:player.pierce,hit:new Set(),r:player.boltSize,c:biome().accent,crit:Math.random()<player.crit})}burst(player.x+Math.cos(a)*18,player.y+Math.sin(a)*18,biome().accent,3,35)}
function damageMob(m,dmg,shot){if(!m||m.hp<=0)return;let crit=shot?.crit;m.hp-=dmg;if(player.frost)m.slow=Math.max(m.slow,.4+.12*player.frost);burst(m.x,m.y,shot?.c||m.accent,crit?8:4,crit?90:55);floater((crit?'★ ':'')+Math.round(dmg),m.x,m.y-m.size,crit?'#fff3a0':'#fff',crit?12:9);if(player.chain&&shot){let t=nearestTarget(m.x,m.y,120+player.chain*22,m);if(t&&!shot.hit.has(t)){shot.hit.add(t);damageMob(t,dmg*(.36+.08*Math.min(3,player.chain)),null);burst(t.x,t.y,'#fff3a0',5,45)}}if(m.hp<=0)killMob(m)}
function updateShots(dt){for(const s of shots){if(player.homing&&mobs.length){let t=nearestTarget(s.x,s.y,320);if(t){let desired=Math.atan2(t.y-s.y,t.x-s.x),cur=Math.atan2(s.vy,s.vx),dif=Math.atan2(Math.sin(desired-cur),Math.cos(desired-cur)),spd=Math.hypot(s.vx,s.vy);cur+=dif*Math.min(1,dt*(2+player.homing));s.vx=Math.cos(cur)*spd;s.vy=Math.sin(cur)*spd}}s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(const m of [...mobs]){if(s.hit.has(m)||d2(s.x,s.y,m.x,m.y)>m.size+s.r)continue;s.hit.add(m);damageMob(m,s.damage*(s.crit?1.85:1),s);if(s.pierce>0)s.pierce--;else{s.life=0;break}}}shots=shots.filter(s=>s.life>0);for(const e of enemyShots){e.x+=e.vx*dt;e.y+=e.vy*dt;e.life-=dt;if(d2(e.x,e.y,player.x,player.y)<e.r+11&&player.invuln<=0){damagePlayer(e.damage);e.life=0}}enemyShots=enemyShots.filter(e=>e.life>0)}
function killMob(m){let i=mobs.indexOf(m);if(i>=0)mobs.splice(i,1);state.kills++;state.eventKills++;state.combo=Math.min(20,state.combo+1);state.comboT=2.4;state.bestCombo=Math.max(state.bestCombo,state.combo);state.biomeKills[m.ring]++;let mult=1+state.combo*.06;for(let n=0;n<(m.apex?9:m.elite?3:1);n++)drops.push({x:m.x+rnd(-12,12),y:m.y+rnd(-12,12),type:'xp',value:(2+Math.floor(m.ring/3))*mult,life:20,spin:rnd(0,TAU)});if(m.elite||Math.random()<.12+player.luck)dropCharm(m.x,m.y,m.elite);if(Math.random()<.07)drops.push({x:m.x,y:m.y,type:'heart',value:12,life:16,spin:0});if(player.explode){let rad=65+player.explode*13;for(const o of [...mobs])if(d2(m.x,m.y,o.x,o.y)<rad)damageMob(o,(8+player.lv)*(.35+.12*player.explode),null);burst(m.x,m.y,'#ffd075',16,110)}if(player.lifeSteal&&state.kills%Math.max(5,12-player.lifeSteal*2)===0)player.hp=Math.min(player.maxHp,player.hp+5+player.lifeSteal*2);if(m.apex){state.apexDefeated.add(m.ring);state.relics+=3;player.hp=Math.min(player.maxHp,player.hp+25);toast('APEX DOWN! Choose an evolution ✦',3);flash=.55;shake=10;setTimeout(()=>{if(started&&!dead)offerLevel(true)},120)}else if(state.biomeKills[m.ring]===10&&!state.apexDefeated.has(m.ring))spawnApexForRing(m.ring);updateHUD()}
function dropCharm(x,y,rare=false){drops.push({x:x+rnd(-12,12),y:y+rnd(-12,12),type:'charm',rune:RUNES[Math.floor(Math.random()*RUNES.length)],rare,life:22,spin:0})}
function applyCharm(r,rare){let [name,key,val,desc]=r,m=rare?1.55:1;if(key==='fire')player.fire*=1+val*m;else if(key==='power')player.power*=1+val*m;else if(key==='proj')player.proj=Math.min(9,player.proj+1);else if(key==='pierce')player.pierce=Math.min(8,player.pierce+1);else if(key==='homing')player.homing=Math.min(8,player.homing+val*m);else if(key==='range')player.range*=1+val*m;else if(key==='crit')player.crit=Math.min(.55,player.crit+val*m);else if(key==='speed')player.speed+=val*m;else if(key==='size')player.boltSize=Math.min(9,player.boltSize+1);else if(key==='chain')player.chain++;toast((rare?'RARE ':'')+name+' · '+desc);burst(player.x,player.y,'#fff3a0',12,75);updateHUD()}
function updateDrops(dt){for(const d of drops){d.life-=dt;d.spin+=dt*4;let dd=d2(d.x,d.y,player.x,player.y);if(dd<player.magnet){let k=Math.min(1,dt*(4+player.magnet/90));d.x+=(player.x-d.x)*k;d.y+=(player.y-d.y)*k}if(dd<18){d.life=0;if(d.type==='xp')gainXP(d.value);else if(d.type==='charm')applyCharm(d.rune,d.rare);else{player.hp=Math.min(player.maxHp,player.hp+d.value);floater('+'+d.value+'♥',player.x,player.y-18,'#ffb2c5',10)}}}drops=drops.filter(d=>d.life>0)}
function drawDrops(){for(const d of drops){let p=toScreen(d.x,d.y),bob=Math.sin(d.spin)*3;if(!visibleS(p.x,p.y,40))continue;if(d.type==='xp'){rect(p.x-3,p.y-3+bob,6,6,'#bdf3dd');rect(p.x-1,p.y-1+bob,2,2,'#fff')}else if(d.type==='charm'){rect(p.x-6,p.y-6+bob,12,12,d.rare?'#ffe36e':'#fff4c5');rect(p.x-2,p.y-2+bob,4,4,biomeAt(d.x,d.y).accent)}else{rect(p.x-5,p.y-4+bob,10,8,'#ec6d8e');rect(p.x,p.y-7+bob,3,4,'#6da55b')}}}
function gainXP(n){player.xp+=n;while(player.xp>=player.next){player.xp-=player.next;player.lv++;player.next=Math.floor(player.next*1.24+5);player.hp=Math.min(player.maxHp,player.hp+7);offerLevel(false);break}updateHUD()}
function offerLevel(apex=false){if(paused||dead)return;paused=true;input.shoot=false;$('shoot').classList.remove('pressed');let pool=[...PERKS],picks=[];while(picks.length<3&&pool.length){let idx=Math.floor(Math.random()*pool.length);picks.push(pool.splice(idx,1)[0])}let box=$('choices');box.innerHTML='';box.classList.add('showChoice');for(const p of picks){let b=document.createElement('button');b.className='choice';b.innerHTML=`<b>${p.icon} ${p.name}</b><span>${p.desc}</span>`;b.onclick=()=>{p.apply();state.perks.push(p.id);box.classList.remove('showChoice');box.innerHTML='';paused=false;toast((apex?'APEX EVOLUTION: ':'Level up: ')+p.name,2.2);burst(player.x,player.y,'#fff3a0',18,100);updateHUD()};box.appendChild(b)}}
function damagePlayer(n){if(player.invuln>0)return;if(player.shield>0){let a=Math.min(player.shield,n);player.shield-=a;n-=a}if(n<=0)return;player.hp-=n;player.invuln=.42;shake=7;flash=.22;burst(player.x,player.y,'#ff7897',12,95);floater('-'+Math.ceil(n),player.x,player.y-20,'#ff91aa',12);if(player.hp<=0)gameOver();updateHUD()}
function dash(){if(player.dash>0||paused||dead)return;let mag=Math.hypot(input.mx,input.my),nx=mag>.1?input.mx/mag:Math.cos(player.heading),ny=mag>.1?input.my/mag:Math.sin(player.heading);player.x+=nx*112;player.y+=ny*112;player.invuln=.38;player.dash=player.dashCd;shake=3;burst(player.x,player.y,'#dff7ff',14,85);updateHUD()}
function syncOrbiters(){while(orbiters.length<player.orbit)orbiters.push({a:rnd(0,TAU),shot:0})}
function updateOrbiters(dt){syncOrbiters();for(let i=0;i<orbiters.length;i++){let o=orbiters[i];o.a+=dt*(1.4+i*.12);o.shot-=dt;if(o.shot<=0){let ox=player.x+Math.cos(o.a)*34,oy=player.y+Math.sin(o.a)*34,t=nearestTarget(ox,oy,280);if(t){let a=Math.atan2(t.y-oy,t.x-ox),spd=360;shots.push({x:ox,y:oy,vx:Math.cos(a)*spd,vy:Math.sin(a)*spd,life:.9,damage:(6+player.lv*.45)*player.power,pierce:0,hit:new Set(),r:3,c:'#fff3a0',crit:false});o.shot=1.2}}}}
function drawOrbiters(){for(const o of orbiters){let x=player.x+Math.cos(o.a)*34,y=player.y+Math.sin(o.a)*34,p=toScreen(x,y);rect(p.x-4,p.y-4,8,8,'#fff3a0');rect(p.x-1,p.y-1,2,2,'#fff')}}
function envPhysics(dt){let e=biome().effect;player.envSlow=e==='mud'?.84:e==='ice'?1.06:e==='heat'||e==='ash'?.93:1;if(e==='current')player.y+=4*dt;if(e==='gust'||e==='wind'||e==='storm')player.x+=Math.sin(time*1.4)*8*dt}
function triggerEvent(){const events=['STAMPede','TREASURE','FRENZY'];let ev=events[Math.floor(Math.random()*events.length)];state.eventKills=0;if(ev==='STAMPede'){eventText='STAMPede! BIG PACK INCOMING';for(let i=0;i<7;i++)spawnMob({});toast('🐾 STAMPEDE! Survive the pack!',3)}else if(ev==='TREASURE'){eventText='GOLDEN TRAIL';for(let i=0;i<5;i++)drops.push({x:player.x+rnd(-160,160),y:player.y+rnd(-160,160),type:'charm',rune:RUNES[Math.floor(Math.random()*RUNES.length)],rare:i===0,life:20,spin:0});toast('✨ GOLDEN TRAIL! Grab the charms!',3)}else{eventText='BONK FRENZY';player.shield=Math.min(40,player.shield+12);for(let i=0;i<4;i++)spawnMob({});toast('⚡ BONK FRENZY! Combo time!',3)}eventT=rnd(28,42)}
function update(dt){time+=dt;shotT=Math.max(0,shotT-dt);player.invuln=Math.max(0,player.invuln-dt);player.dash=Math.max(0,player.dash-dt);if(state.comboT>0){state.comboT-=dt;if(state.comboT<=0)state.combo=0}eventT-=dt;if(eventT<=0)triggerEvent();envPhysics(dt);let mag=Math.hypot(input.mx,input.my);if(mag>.05){let nx=input.mx/mag,ny=input.my/mag,s=player.speed*player.envSlow*Math.min(1,mag);player.x+=nx*s*dt;player.y+=ny*s*dt;player.heading=Math.atan2(ny,nx)}if(input.shoot)fire();let ring=biomeIndexAt(player.x,player.y);if(ring>state.bestRing){state.bestRing=ring;state.relics++;toast('NEW BIOME: '+BIOMES[ring].name+' ✦',2.6);burst(player.x,player.y,BIOMES[ring].accent,18,90)}ensureLandmarks();interactLandmarks();spawnT-=dt;let cap=9+Math.min(22,ring);if(spawnT<=0&&mobs.length<cap){spawnMob({});spawnT=Math.max(.25,1.05-ring*.018)}for(const m of [...mobs])updateMob(m,dt);updateShots(dt);updateDrops(dt);updateOrbiters(dt);updateFX(dt);mobs=mobs.filter(m=>d2(m.x,m.y,player.x,player.y)<1350||m.apex);landmarks=landmarks.filter(l=>Math.abs(l.ring-ring)<=2);if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}updateHUD()}
function drawEffects(){let b=biome(),t=time;if(['rain','storm'].includes(b.effect)){X.strokeStyle='#d9efff77';for(let i=0;i<34;i++){let x=(i*97+t*260)%W,y=(i*53+t*420)%H;X.beginPath();X.moveTo(x,y);X.lineTo(x-4,y+9);X.stroke()}}if(b.effect==='snow'||b.effect==='frost'){for(let i=0;i<30;i++)rect((i*83+t*18)%W,(i*47+t*36)%H,2,2,'#ffffff99')}if(b.effect==='fog'||b.effect==='clouds'){for(let i=0;i<5;i++)rect(((i*211+t*16)%(W+250))-120,70+i*100,220,38,'#e7f3ee14')}if(b.effect==='embers'||b.effect==='ash'){for(let i=0;i<20;i++)rect((i*79+t*22)%W,(H-(i*43+t*22)%H),2,2,b.effect==='embers'?'#ffb35f77':'#d8c9be44')}}
function drawPlayer(){X.save();X.translate(Math.round(W/2+rnd(-shake,shake)),Math.round(H/2+rnd(-shake,shake)));let blink=player.invuln>0&&Math.floor(time*20)%2===0;X.globalAlpha=blink?.45:1;rect(-11,10,22,6,'#0003');rect(-9,-9,18,20,'#fff0f5');rect(-7,-15,5,8,'#fff0f5');rect(2,-15,5,8,'#fff0f5');rect(-5,-6,3,3,'#293143');rect(3,-6,3,3,'#293143');rect(-2,-1,4,2,'#f28bad');rect(-9,8,5,5,'#e9b6c9');rect(4,8,5,5,'#e9b6c9');X.rotate(player.heading);rect(6,-2,15,4,'#8c684d');rect(18,-5,6,10,'#b8f0dd');rect(20,-3,5,6,'#fff0a6');X.restore()}
function drawUIOverlay(){let b=biome(),ring=b.i,need=state.apexDefeated.has(ring)?'APEX CLEARED':state.biomeKills[ring]>=10?'APEX ACTIVE':`${state.biomeKills[ring]}/10 HUNT`;rect(W/2-78,42,156,30,'#172033b8');text(b.name.toUpperCase(),W/2,51,9,'#fff');text(need,W/2,64,9,b.accent);if(state.combo>1){let s=12+Math.min(8,state.combo);text('x'+state.combo+' BONK COMBO!',W/2,92,s,'#fff3a0');rect(W/2-55,103,110,4,'#17203388');rect(W/2-55,103,110*clamp(state.comboT/2.4,0,1),4,'#fff3a0')}if(eventText&&eventT>23)text(eventText,W/2,H-165,10,'#fff3a0');if(flash>0){X.globalAlpha=flash*.28;rect(0,0,W,H,'#fff');X.globalAlpha=1}}
function draw(){drawWorld();drawLandmarks();drawDrops();for(const s of shots){let p=toScreen(s.x,s.y);rect(p.x-s.r,p.y-s.r,s.r*2,s.r*2,s.crit?'#fff3a0':s.c);rect(p.x-1,p.y-1,2,2,'#fff')}for(const e of enemyShots){let p=toScreen(e.x,e.y);rect(p.x-e.r,p.y-e.r,e.r*2,e.r*2,e.c)}for(const m of mobs)drawAnimal(m);for(const p of particles){let q=toScreen(p.x,p.y);X.globalAlpha=clamp(p.life*2.5,0,1);rect(q.x,q.y,p.r,p.r,p.c)}X.globalAlpha=1;drawOrbiters();drawPlayer();for(const f of floaters){let q=toScreen(f.x,f.y);X.globalAlpha=clamp(f.life*2,0,1);text(f.t,q.x,q.y,f.size,f.c)}X.globalAlpha=1;drawEffects();drawUIOverlay()}
function updateHUD(){let b=biome(),r=b.i;$('hp').textContent=Math.max(0,Math.ceil(player.hp));$('maxhp').textContent=Math.ceil(player.maxHp);$('hpfill').style.width=100*clamp(player.hp/player.maxHp,0,1)+'%';$('lv').textContent=player.lv;$('xp').textContent=Math.floor(player.xp)+'/'+player.next;$('biome').textContent=(r+1)+'/30 '+b.name;$('weapon').textContent=player.proj+'× · '+player.fire.toFixed(1)+' rate · '+player.power.toFixed(1)+' power';$('danger').textContent='Wild '+(r+1);$('relics').textContent=state.relics;$('flowfill').style.width=clamp(player.shield/40*100,0,100)+'%';let db=$('dash');if(db)db.textContent=player.dash>0?player.dash.toFixed(1):'DASH'}
function reset(){Object.assign(player,{x:0,y:0,hp:72,maxHp:72,speed:188,lv:1,xp:0,next:10,power:1,fire:1,proj:1,spread:.13,pierce:0,homing:0,crit:.06,range:1,shield:0,heading:0,envSlow:1,dash:0,dashCd:2.7,invuln:0,magnet:105,luck:0,boltSize:4,chain:0,explode:0,frost:0,orbit:0,lifeSteal:0});mobs=[];shots=[];enemyShots=[];drops=[];particles=[];floaters=[];landmarks=[];orbiters=[];Object.assign(state,{kills:0,relics:0,bestRing:0,places:0,combo:0,comboT:0,bestCombo:0,eventKills:0});state.biomeKills=Array(30).fill(0);state.apexDefeated=new Set();state.perks=[];time=0;spawnT=0;eventT=18;eventText='';dead=false;paused=false;updateHUD()}
function gameOver(){dead=true;paused=true;input.shoot=false;$('controls').classList.add('hide');$('death').classList.remove('hide');$('dlevel').textContent=player.lv;$('dtime').textContent=Math.floor(time/60)+':'+String(Math.floor(time%60)).padStart(2,'0');$('dkills').textContent=state.kills;$('drelics').textContent=state.relics;let bc=$('dbest');if(bc)bc.textContent=state.bestCombo+'×'}
function loop(ts){let dt=Math.min(.033,(ts-last)/1000||0);last=ts;if(started&&!paused&&!dead)update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
const joy=$('joystick'),knob=$('joyknob');function joyMove(e){if(input.pid!==e.pointerId)return;let r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,lim=r.width*.34,d=Math.hypot(dx,dy)||1,k=Math.min(1,lim/d);dx*=k;dy*=k;knob.style.transform=`translate(${dx}px,${dy}px)`;input.mx=dx/lim;input.my=dy/lim}joy.onpointerdown=e=>{input.pid=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e)};joy.onpointermove=joyMove;function joyEnd(e){if(input.pid!==e.pointerId)return;input.pid=null;input.mx=input.my=0;knob.style.transform='translate(0,0)'}joy.onpointerup=joyEnd;joy.onpointercancel=joyEnd;
const shoot=$('shoot');shoot.onpointerdown=e=>{e.preventDefault();shoot.setPointerCapture(e.pointerId);input.shoot=true;shoot.classList.add('pressed');fire()};function shootEnd(){input.shoot=false;shoot.classList.remove('pressed')}shoot.onpointerup=shootEnd;shoot.onpointercancel=shootEnd;
const dashBtn=$('dash');if(dashBtn)dashBtn.onpointerdown=e=>{e.preventDefault();dash()};
$('play').onclick=()=>{reset();started=true;$('start').classList.add('hide');$('controls').classList.remove('hide');toast('Hunt 10 animals to summon each biome apex!')};$('again').onclick=()=>{reset();$('death').classList.add('hide');$('controls').classList.remove('hide')};
window.__TWBB_V19__={version:19,state:()=>({biome:biome().name,ring:biome().i+1,kills:state.kills,combo:state.combo,bestCombo:state.bestCombo,biomeKills:[...state.biomeKills],player:{...player}}),warp:n=>{let i=clamp((n|0)-1,0,29);player.x=i*RING+20;player.y=0;updateHUD()},spawnApex:()=>spawnApexForRing(biome().i),level:()=>offerLevel(false),event:()=>{eventT=0}};
})();