(()=>{'use strict';
const C=document.getElementById('g'),X=C.getContext('2d'),B=window.TWBB_WORLD;if(!C||!X||!B)throw Error('v21 boot');X.imageSmoothingEnabled=false;
const $=id=>document.getElementById(id),TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),D=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
let W=0,H=0,DPR=1,last=0,time=0,started=false,paused=false,dead=false,spawnT=0,shotT=0,toastT=0,eventT=16,shake=0,flash=0;
const RING=780,CELL=72,F=360,S=560,PR=11;
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*DPR;C.height=H*DPR;C.style.width=W+'px';C.style.height=H+'px';X.setTransform(DPR,0,0,DPR,0,0);X.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const hash=n=>Math.abs(Math.sin(n*127.1+Math.cos(n*9.13))*43758.5453)%1,h2=(x,y,s=0)=>hash(x*91.7+y*173.3+s*31.7),choose=(a,h)=>a[Math.floor(h*a.length)%a.length];
const bi=(x=player.x,y=player.y)=>clamp(Math.floor(Math.hypot(x,y)/RING),0,29),bio=(x=player.x,y=player.y)=>B[bi(x,y)],screen=(x,y)=>({x:W/2+x-player.x,y:H/2+y-player.y});
function r(x,y,w,h,c){X.fillStyle=c;X.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}function txt(t,x,y,s=10,c='#fff',a='center'){X.fillStyle=c;X.font=`900 ${s}px ui-monospace,monospace`;X.textAlign=a;X.textBaseline='middle';X.fillText(t,x,y)}
const state={kills:0,relics:0,places:0,bestRing:0,combo:0,comboT:0,bestCombo:0,biomeKills:Array(30).fill(0),apex:new Set(),bosses:new Set(),secrets:new Set(),quests:[],completed:0,essence:0,weaponXP:0,weaponLv:1,evolution:null,eventKills:0};
const player={x:0,y:0,hp:80,maxHp:80,speed:195,lv:1,xp:0,next:9,power:1,fire:1,proj:1,spread:.12,pierce:0,homing:0,crit:.08,range:1,shield:0,heading:0,magnet:120,bolt:4,chain:0,explode:0,frost:0,orbit:0,lifesteal:0,dashCd:2.5,dash:0,inv:0,ult:0,ultMax:100};
const input={mx:0,my:0,shoot:false,pid:null};let mobs=[],shots=[],enemy=[],drops=[],particles=[],floaters=[],orbiters=[];
const PERKS=[['PETAL STORM','⚡','+30% fire rate',()=>player.fire*=1.3],['TRIPLE BLOOM','✦','+2 projectiles',()=>player.proj=Math.min(9,player.proj+2)],['BIG BONK','💥','+35% damage and size',()=>{player.power*=1.35;player.bolt=Math.min(10,player.bolt+1)}],['THORN NEEDLE','➶','+2 pierce',()=>player.pierce=Math.min(9,player.pierce+2)],['MOON SEEKER','☄','Strong homing',()=>player.homing=Math.min(8,player.homing+2.2)],['BUNNY HOP','💨','Dash recharges faster',()=>{player.dashCd=Math.max(.6,player.dashCd*.72);player.speed+=10}],['GIANT HEART','♥','+24 max HP, full heal',()=>{player.maxHp+=24;player.hp=player.maxHp}],['LUCKY FANG','★','+14% crit',()=>player.crit=Math.min(.6,player.crit+.14)],['BURST BERRY','✹','Kills explode',()=>player.explode++],['CHAIN SPARK','ϟ','Shots chain',()=>player.chain++],['FROST BLOOM','❄','Hits slow enemies',()=>player.frost++],['WISP FRIEND','◎','Gain orbiting familiar',()=>{player.orbit++;syncWisps()}],['TREASURE NOSE','◇','Huge pickup radius',()=>player.magnet+=100],['SWEET TOOTH','♡','Heal on kills',()=>player.lifesteal++],['ULTIMATE HEART','☀','Ultimate charges faster',()=>player.ultMax=Math.max(45,player.ultMax-15)]];
const EVOS={bloom:{name:'ROYAL BLOOM',desc:'9-way flower barrage',apply(){player.proj=9;player.fire*=1.35;player.spread=.55}},storm:{name:'THUNDER WAND',desc:'Chain lightning storm',apply(){player.chain+=3;player.fire*=1.25;player.power*=1.25}},comet:{name:'STAR COMET',desc:'Huge homing explosive bolts',apply(){player.homing=8;player.explode+=2;player.bolt=9;player.power*=1.35}},frost:{name:'WINTER CROWN',desc:'Freeze fields and pierce',apply(){player.frost+=3;player.pierce+=4;player.range*=1.25}},guardian:{name:'WISP COURT',desc:'Four orbiting familiars',apply(){player.orbit=Math.max(4,player.orbit+2);syncWisps()}}};
const QUESTS=[['Cull the Pack','kill',18],['Treasure Trail','place',3],['Combo Trial','combo',12],['Apex Hunt','apex',1],['Relic Run','relic',3]];
function toast(t,d=2){let e=$('toast');e.textContent=t;e.classList.add('show');toastT=d}function floater(t,x,y,c='#fff',s=10){floaters.push({t,x,y,c,s,life:.8})}function burst(x,y,c,n=8,spd=90){for(let i=0;i<n;i++){let a=rnd(0,TAU),v=rnd(spd*.3,spd);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rnd(.2,.65),c,sz:rnd(2,4)})}}
function initQuest(){let q=QUESTS[(bi()+state.completed)%QUESTS.length];state.quests=[{name:q[0],type:q[1],need:q[2],start:{kills:state.kills,places:state.places,relics:state.relics,ring:bi()},done:false}];hud()}
function qProg(q){if(q.type==='kill')return state.kills-q.start.kills;if(q.type==='place')return state.places-q.start.places;if(q.type==='combo')return state.bestCombo;if(q.type==='apex')return state.apex.has(q.start.ring)?1:0;if(q.type==='relic')return state.relics-q.start.relics;return 0}
function checkQuest(){let q=state.quests[0];if(q&&!q.done&&qProg(q)>=q.need){q.done=true;state.completed++;state.essence+=3;state.relics++;toast('QUEST COMPLETE ✦ +3 ESSENCE',2.7);for(let i=0;i<3;i++)dropRune(player.x+rnd(-35,35),player.y+rnd(-35,35),true);setTimeout(initQuest,0)}hud()}
function plantS(t,x,y,s,b,h){let u=Math.max(1,Math.round(s));X.save();X.translate(x|0,y|0);r(-7*u,4*u,14*u,4*u,'#17251c22');if(/tree|birch|pine|fir|oak|maple|willow|palm|baobab|acacia/i.test(t)){r(-2*u,-2*u,4*u,15*u,/birch/i.test(t)?'#eee7d4':'#745441');r(-8*u,-11*u,16*u,8*u,/snow|storm|fir|pine/i.test(t)?'#557467':b.shade);r(-6*u,-17*u,12*u,8*u,b.shade)}else if(/cactus/i.test(t)){r(-3*u,-15*u,6*u,18*u,'#5aa56c');r(-7*u,-9*u,5*u,3*u,'#5aa56c')}else if(/crystal|obsidian|iceSpikes|stalagmite|lavaCrystal/i.test(t)){r(-5*u,-10*u,6*u,13*u,b.accent);r(2*u,-17*u,6*u,20*u,b.accent)}else if(/mushroom/i.test(t)){r(-1*u,-5*u,2*u,8*u,'#eadfc8');r(-5*u,-9*u,10*u,4*u,b.accent)}else if(/flower|daisy|buttercup|clover|tulip|sunflower|bluebell|orchid|foxglove|bromeliad|moonFlower|iceFlower|ancientFlower/i.test(t)){r(-1*u,-5*u,2*u,8*u,'#5f9d55');r(-4*u,-9*u,8*u,4*u,b.accent)}else for(let i=0;i<4;i++){let hh=(6+h2(i,h,2)*9)*u;r((-5+i*3)*u,-hh,2*u,hh,b.shade)}X.restore()}
function propS(t,x,y,s,b){let u=Math.max(1,Math.round(s));X.save();X.translate(x|0,y|0);r(-7*u,3*u,14*u,4*u,'#17251c22');if(/rock|boulder|stone|obsidian|cairn|iceRock/i.test(t)){r(-7*u,-4*u,14*u,8*u,'#817b74');r(-4*u,-8*u,8*u,5*u,'#9a958c')}else if(/log|driftwood|woodpile|root|fallen|charLog|giantLog|damLog/i.test(t))r(-10*u,-3*u,20*u,6*u,'#73533d');else if(/sign/i.test(t)){r(-2*u,-9*u,4*u,14*u,'#795b43');r(-8*u,-13*u,16*u,7*u,'#b98b5a')}else if(/lantern|torch|lightningRod/i.test(t)){r(-1*u,-9*u,2*u,13*u,'#5b4d49');r(-4*u,-13*u,8*u,7*u,b.accent)}else if(/totem|ruinPillar|brokenStatue|ancientStone/i.test(t)){r(-6*u,-14*u,12*u,18*u,'#7d7c71');r(-8*u,-17*u,16*u,4*u,'#9a9786')}else r(-6*u,-6*u,12*u,10*u,'#8c735d');X.restore()}
function structureS(t,x,y,b,h,large=false){let z=large?1.2:1;X.save();X.translate(x|0,y|0);r(-32*z,22*z,64*z,6*z,'#17251c26');let wall='#d8c39d',wood='#79583e',roof=b.shade;if(/bridge|boardwalk|ropeBridge|lavaBridge|dock/i.test(t)){r(-45*z,-7*z,90*z,14*z,'#9b724c');for(let i=-36;i<=36;i+=12)r(i*z,-10*z,4*z,20*z,wood)}else if(/tower|lighthouse|obelisk/i.test(t)){r(-13*z,-42*z,26*z,66*z,'#8b887f');r(-18*z,-47*z,36*z,8*z,roof)}else if(/shrine|temple|pagoda|altar/i.test(t)){r(-24*z,-22*z,48*z,44*z,'#87877c');r(-31*z,-27*z,62*z,8*z,'#a09e8e');r(-17*z,-42*z,34*z,18*z,roof)}else if(/gate|arch/i.test(t)){r(-28*z,-38*z,10*z,62*z,'#88867d');r(18*z,-38*z,10*z,62*z,'#88867d');r(-28*z,-42*z,56*z,10*z,'#9d9a8c')}else if(/mine|lift/i.test(t)){r(-30*z,-30*z,60*z,52*z,'#34353b');r(-25*z,-35*z,7*z,60*z,wood);r(18*z,-35*z,7*z,60*z,wood)}else if(/camp|tent|picnic/i.test(t)){X.fillStyle='#d6a36d';X.beginPath();X.moveTo(-24*z,18*z);X.lineTo(0,-24*z);X.lineTo(24*z,18*z);X.fill()}else{r(-28*z,-20*z,56*z,42*z,wall);r(-33*z,-26*z,66*z,10*z,roof);r(-7*z,3*z,14*z,19*z,wood)}X.restore()}
function featureS(t,x,y,b,h){X.save();X.translate(x|0,y|0);if(/pond|pool|hole|watering|bog|tide|oasis|lake/i.test(t)){X.fillStyle='#69bfc4';X.beginPath();X.ellipse(0,0,58+h*22,26+h*12,0,0,TAU);X.fill()}else if(/stream|river/i.test(t))r(-80,-12,160,24,'#69bfc4');else if(/waterfall/i.test(t)){r(-30,-60,60,80,b.shade);r(-14,-55,28,66,'#7fd5d9')}else if(/chasm|ravine|cliff|crater/i.test(t)){X.fillStyle='#252632';X.beginPath();X.ellipse(0,5,65+h*20,27+h*12,0,0,TAU);X.fill()}else if(/ruin|hall|courtyard/i.test(t)){for(let i=0;i<5;i++){let a=i*TAU/5;propS('ruinPillar',Math.cos(a)*36,Math.sin(a)*22,1,b)}}else for(let i=0;i<8;i++){let a=i*TAU/8;plantS(choose(b.flora,h2(i,h,8)),Math.cos(a)*36,Math.sin(a)*22,1,b,h)}X.restore()}
function structAt(cx,cy){let wx=cx*S+90+h2(cx,cy,201)*360,wy=cy*S+90+h2(cx,cy,202)*360,bb=bio(wx,wy),h=h2(cx,cy,203);return h>.6?{wx,wy,b:bb,h,type:choose(bb.structures,h),large:h>.92}:null}
function featAt(cx,cy){let wx=cx*F+55+h2(cx,cy,101)*230,wy=cy*F+55+h2(cx,cy,102)*230,bb=bio(wx,wy),h=h2(cx,cy,103);return h>.52?{wx,wy,b:bb,h,type:choose(bb.features,h)}:null}
function hitRect(x,y,cx,cy,hw,hh,rad=PR){let nx=clamp(x,cx-hw,cx+hw),ny=clamp(y,cy-hh,cy+hh);return Math.hypot(x-nx,y-ny)<rad}
function hitEllipse(x,y,cx,cy,rx,ry,rad=PR){let dx=(x-cx)/(rx+rad),dy=(y-cy)/(ry+rad);return dx*dx+dy*dy<1}
function structureBlocks(o,x,y){let t=o.type,z=o.large?1.2:1;if(/bridge|boardwalk|ropeBridge|lavaBridge|dock|boat/i.test(t))return false;if(/gate|arch/i.test(t))return hitRect(x,y,o.wx-23*z,o.wy-7*z,6*z,32*z)||hitRect(x,y,o.wx+23*z,o.wy-7*z,6*z,32*z);if(/tower|lighthouse|obelisk/i.test(t))return hitRect(x,y,o.wx,o.wy-8*z,18*z,34*z);if(/shrine|temple|pagoda|altar/i.test(t))return hitRect(x,y,o.wx,o.wy-5*z,29*z,29*z);if(/mine|lift/i.test(t))return hitRect(x,y,o.wx,o.wy-5*z,32*z,29*z);if(/camp|tent|picnic/i.test(t))return hitRect(x,y,o.wx,o.wy,25*z,22*z);return hitRect(x,y,o.wx,o.wy,32*z,25*z)}
function featureBlocks(o,x,y){let t=o.type;if(/pond|pool|hole|watering|bog|tide|oasis|lake/i.test(t))return hitEllipse(x,y,o.wx,o.wy,58+o.h*22,26+o.h*12);if(/chasm|ravine|cliff|crater/i.test(t))return hitEllipse(x,y,o.wx,o.wy+5,65+o.h*20,27+o.h*12);if(/waterfall/i.test(t))return hitRect(x,y,o.wx,o.wy-20,32,60);if(/ruin|hall/i.test(t)){for(let i=0;i<5;i++){let a=i*TAU/5;if(hitRect(x,y,o.wx+Math.cos(a)*36,o.wy+Math.sin(a)*22,8,18))return true}}return false}
function blocked(x,y){let scx=Math.floor(x/S),scy=Math.floor(y/S);for(let cy=scy-1;cy<=scy+1;cy++)for(let cx=scx-1;cx<=scx+1;cx++){let o=structAt(cx,cy);if(o&&structureBlocks(o,x,y))return true}let fcx=Math.floor(x/F),fcy=Math.floor(y/F);for(let cy=fcy-1;cy<=fcy+1;cy++)for(let cx=fcx-1;cx<=fcx+1;cx++){let o=featAt(cx,cy);if(o&&featureBlocks(o,x,y))return true}return false}
function movePlayer(dx,dy){let nx=player.x+dx,ny=player.y+dy;if(!blocked(nx,player.y))player.x=nx;if(!blocked(player.x,ny))player.y=ny}
function drawWorld(){let b=bio();r(0,0,W,H,b.ground);let sx=Math.floor((player.x-W/2)/CELL)-2,ex=Math.ceil((player.x+W/2)/CELL)+2,sy=Math.floor((player.y-H/2)/CELL)-2,ey=Math.ceil((player.y+H/2)/CELL)+2;for(let cy=sy;cy<=ey;cy++)for(let cx=sx;cx<=ex;cx++){let wx=cx*CELL+8+h2(cx,cy,1)*52,wy=cy*CELL+8+h2(cx,cy,2)*52,p=screen(wx,wy),bb=bio(wx,wy),h=h2(cx,cy,bi(wx,wy));if(p.x<-70||p.x>W+70||p.y<-70||p.y>H+70)continue;if(h>.06)plantS(choose(bb.flora,h2(cx,cy,21)),p.x,p.y,.7+h2(cx,cy,22)*.5,bb,h);if(h>.62)propS(choose(bb.props,h2(cx,cy,31)),p.x+17,p.y-11,.7,bb)}let fsx=Math.floor((player.x-W/2-180)/F),fex=Math.ceil((player.x+W/2+180)/F),fsy=Math.floor((player.y-H/2-180)/F),fey=Math.ceil((player.y+H/2+180)/F);for(let cy=fsy;cy<=fey;cy++)for(let cx=fsx;cx<=fex;cx++){let o=featAt(cx,cy);if(o){let p=screen(o.wx,o.wy);if(p.x>-170&&p.x<W+170&&p.y>-170&&p.y<H+170)featureS(o.type,p.x,p.y,o.b,o.h)}}let ssx=Math.floor((player.x-W/2-160)/S),sex=Math.ceil((player.x+W/2+160)/S),ssy=Math.floor((player.y-H/2-160)/S),sey=Math.ceil((player.y+H/2+160)/S);for(let cy=ssy;cy<=sey;cy++)for(let cx=ssx;cx<=sex;cx++){let o=structAt(cx,cy);if(!o)continue;let p=screen(o.wx,o.wy);if(p.x>-140&&p.x<W+140&&p.y>-140&&p.y<H+140){structureS(o.type,p.x,p.y,o.b,o.h,o.large);let id=`s-${cx}-${cy}`;if(D(player,{x:o.wx,y:o.wy})<85&&!state.secrets.has(id)){state.secrets.add(id);state.places++;state.relics++;state.essence++;toast('SECRET PLACE ✦ +1 ESSENCE');dropRune(o.wx,o.wy,true);checkQuest()}}}}
function spawnMob(kind='normal',boss=false){let a=rnd(0,TAU),rad=Math.max(W,H)*.65+rnd(80,160),x=player.x+Math.cos(a)*rad,y=player.y+Math.sin(a)*rad,ring=bi(x,y),b=B[ring],tier=ring+1,elite=kind==='apex',hp=(18+tier*6)*(elite?8:boss?24:1),sz=11+tier*.8+(elite?8:0)+(boss?22:0);mobs.push({x,y,hp,maxHp:hp,sz,ring,sp:choose(b.animals,Math.random()),elite,boss,atk:rnd(.4,1.2),slow:0})}
function bossName(m){return m.boss?['THE BURROW KING','MOSS COLOSSUS','CRYSTAL MAW','DUNE TYRANT','STORM EMPEROR','ELDER TITAN'][Math.min(5,Math.floor(m.ring/5))]:'APEX '+m.sp.toUpperCase()}
function updateMob(m,dt){let dx=player.x-m.x,dy=player.y-m.y,d=Math.hypot(dx,dy)||1,nx=dx/d,ny=dy/d,spd=55+m.ring*3+(m.elite?20:0)+(m.boss?18:0);if(m.slow>0){m.slow-=dt;spd*=.5}if(m.boss&&m.hp<m.maxHp*.5)spd*=1.35;let mx=nx*spd*dt,my=ny*spd*dt;if(!blocked(m.x+mx,m.y))m.x+=mx;if(!blocked(m.x,m.y+my))m.y+=my;m.atk-=dt;if(m.boss&&m.atk<=0&&d<600){let n=m.hp<m.maxHp*.5?12:8;for(let i=0;i<n;i++){let a=i*TAU/n+time*.4;enemy.push({x:m.x,y:m.y,vx:Math.cos(a)*150,vy:Math.sin(a)*150,life:4,damage:7+m.ring*.5,r:5})}m.atk=1.3}else if((m.elite||m.ring>12)&&m.atk<=0&&d<480){enemy.push({x:m.x,y:m.y,vx:nx*(130+m.ring*3),vy:ny*(130+m.ring*3),life:4,damage:5+m.ring*.35,r:4});m.atk=1.2}if(d<m.sz+PR&&m.atk<=0){damage(6+m.ring*.45+(m.elite?4:0)+(m.boss?8:0));m.atk=.7}}
function damage(n){if(player.inv>0)return;if(player.shield>0){let a=Math.min(n,player.shield);player.shield-=a;n-=a}player.hp-=n;shake=6;flash=.25;player.inv=.35;if(player.hp<=0)gameOver();hud()}
function nearest(x=player.x,y=player.y,range=520*player.range){let best=null,bd=range;for(let m of mobs){let d=Math.hypot(m.x-x,m.y-y);if(d<bd){bd=d;best=m}}return best}
function fire(){if(shotT>0||paused||dead)return;let t=nearest(),a=t?Math.atan2(t.y-player.y,t.x-player.x):player.heading;player.heading=a;shotT=.28/player.fire;for(let i=0;i<player.proj;i++){let off=player.proj===1?0:(i-(player.proj-1)/2)*player.spread/Math.max(1,player.proj-1),aa=a+off,sp=430;shots.push({x:player.x+Math.cos(aa)*18,y:player.y+Math.sin(aa)*18,vx:Math.cos(aa)*sp,vy:Math.sin(aa)*sp,life:1.25*player.range,damage:(10+player.lv*.7)*player.power,pierce:player.pierce,r:player.bolt,crit:Math.random()<player.crit,hit:new Set()})}burst(player.x+Math.cos(a)*18,player.y+Math.sin(a)*18,bio().accent,4,50)}
function hitMob(m,s){let dmg=s.damage*(s.crit?2:1);m.hp-=dmg;if(player.frost)m.slow=Math.max(m.slow,.8+.25*player.frost);floater((s.crit?'CRIT ':'')+Math.round(dmg),m.x,m.y,s.crit?'#ffe477':'#fff',s.crit?13:10);burst(m.x,m.y,bio(m.x,m.y).accent,5,65);player.ult=Math.min(player.ultMax,player.ult+1.8);if(player.chain){let t=mobs.filter(x=>x!==m&&x.hp>0).sort((a,b)=>D(a,m)-D(b,m))[0];if(t&&D(t,m)<180){t.hp-=dmg*(.35+.1*Math.min(3,player.chain));if(t.hp<=0)kill(t)}}if(m.hp<=0)kill(m)}
function kill(m){let i=mobs.indexOf(m);if(i>=0)mobs.splice(i,1);state.kills++;state.biomeKills[m.ring]++;state.combo++;state.comboT=2.8;state.bestCombo=Math.max(state.bestCombo,state.combo);state.weaponXP++;player.ult=Math.min(player.ultMax,player.ult+4);if(player.lifesteal&&state.kills%(14-Math.min(5,player.lifesteal*2))===0)player.hp=Math.min(player.maxHp,player.hp+6);for(let j=0;j<1+(m.elite?7:0)+(m.boss?14:0);j++)drops.push({x:m.x+rnd(-20,20),y:m.y+rnd(-20,20),type:'xp',v:m.boss?3:m.elite?2:1,life:20});if(Math.random()<.18+(m.elite?.5:0)+(m.boss?.8:0))dropRune(m.x,m.y,m.elite||m.boss);if(player.explode){for(let n of [...mobs])if(D(n,m)<85+player.explode*25){n.hp-=10*player.power*player.explode;if(n.hp<=0)kill(n)}burst(m.x,m.y,'#ffb26b',10,100)}if(m.elite){state.apex.add(m.ring);state.relics+=2;state.essence+=2;toast('APEX DEFEATED ✦ +2 ESSENCE',2.7);showChoices()}if(m.boss){state.bosses.add(Math.floor(m.ring/5));state.relics+=5;state.essence+=6;toast('BOSS DEFEATED ✦ LEGENDARY REWARD',3);showEvolution()}if(state.weaponXP>=12*state.weaponLv){state.weaponXP=0;state.weaponLv++;toast('WAND MASTERY '+state.weaponLv+' ✦');showChoices()}checkQuest();hud()}
function updateShots(dt){for(let s of shots){if(player.homing){let t=nearest(s.x,s.y,260);if(t){let a=Math.atan2(t.y-s.y,t.x-s.x),ca=Math.atan2(s.vy,s.vx),dif=Math.atan2(Math.sin(a-ca),Math.cos(a-ca)),sp=Math.hypot(s.vx,s.vy);ca+=dif*Math.min(1,dt*player.homing);s.vx=Math.cos(ca)*sp;s.vy=Math.sin(ca)*sp}}s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(let m of [...mobs]){if(s.hit.has(m)||D(s,m)>m.sz+s.r)continue;s.hit.add(m);hitMob(m,s);if(s.pierce>0)s.pierce--;else{s.life=0;break}}}shots=shots.filter(s=>s.life>0);for(let e of enemy){e.x+=e.vx*dt;e.y+=e.vy*dt;e.life-=dt;if(D(e,player)<e.r+PR){damage(e.damage);e.life=0}}enemy=enemy.filter(e=>e.life>0)}
function dropRune(x,y,rare=false){drops.push({x:x+rnd(-10,10),y:y+rnd(-10,10),type:'rune',rare,life:22})}function applyRune(rare){let p=PERKS[Math.floor(Math.random()*PERKS.length)];p[3]();state.relics+=rare?1:0;toast((rare?'RARE ':'')+p[0]+' ✦ '+p[2]);hud()}function updateDrops(dt){for(let d of drops){d.life-=dt;let dd=D(d,player);if(dd<player.magnet){let k=Math.min(1,dt*7);d.x+=(player.x-d.x)*k;d.y+=(player.y-d.y)*k}if(dd<18){d.life=0;if(d.type==='xp'){gainXP(d.v);state.essence+=.05*d.v}else applyRune(d.rare)}}drops=drops.filter(d=>d.life>0)}function gainXP(v){player.xp+=v;while(player.xp>=player.next){player.xp-=player.next;player.lv++;player.next=Math.floor(player.next*1.22+3);showChoices()}hud()}
function showChoices(){paused=true;let box=$('choices');box.innerHTML='';box.style.display='grid';for(let p of [...PERKS].sort(()=>Math.random()-.5).slice(0,3)){let b=document.createElement('button');b.className='choice';b.innerHTML=`<b>${p[1]} ${p[0]}</b><span>${p[2]}</span>`;b.onclick=()=>{p[3]();box.style.display='none';paused=false;hud()};box.appendChild(b)}}function showEvolution(){paused=true;let box=$('choices');box.innerHTML='';box.style.display='grid';for(let e of Object.values(EVOS).filter(e=>e.name!==state.evolution).sort(()=>Math.random()-.5).slice(0,3)){let b=document.createElement('button');b.className='choice legendary';b.innerHTML=`<b>★ ${e.name}</b><span>${e.desc}</span>`;b.onclick=()=>{e.apply();state.evolution=e.name;box.style.display='none';paused=false;hud()};box.appendChild(b)}}
function syncWisps(){orbiters=Array.from({length:player.orbit},(_,i)=>({a:i*TAU/Math.max(1,player.orbit),cool:0}))}function updateWisps(dt){for(let w of orbiters){w.a+=dt*1.8;w.cool-=dt;if(w.cool<=0){let x=player.x+Math.cos(w.a)*38,y=player.y+Math.sin(w.a)*38,t=nearest(x,y,300);if(t){let a=Math.atan2(t.y-y,t.x-x);shots.push({x,y,vx:Math.cos(a)*360,vy:Math.sin(a)*360,life:1,damage:7*player.power,pierce:0,r:3,crit:false,hit:new Set()});w.cool=.65}}}}
function doDash(){if(player.dash>0||paused)return;let mag=Math.hypot(input.mx,input.my),nx=mag>.1?input.mx/mag:Math.cos(player.heading),ny=mag>.1?input.my/mag:Math.sin(player.heading);for(let i=0;i<7;i++)movePlayer(nx*15,ny*15);player.dash=player.dashCd;player.inv=.42;shake=4;burst(player.x,player.y,'#fff',14,120)}
function ultimate(){if(player.ult<player.ultMax||paused)return;player.ult=0;shake=10;flash=.5;toast('MEGA BONK!!! ☀');for(let m of [...mobs])if(D(m,player)<520){m.hp-=55*player.power;burst(m.x,m.y,'#fff3a0',12,130);if(m.hp<=0)kill(m)}for(let i=0;i<28;i++){let a=i*TAU/28;shots.push({x:player.x,y:player.y,vx:Math.cos(a)*460,vy:Math.sin(a)*460,life:1.25,damage:18*player.power,pierce:3,r:6,crit:false,hit:new Set()})}}
function triggerEvent(){eventT=rnd(18,28);let k=Math.floor(Math.random()*4);if(k===0){toast('STAMPEDE! SURVIVE THE RUSH',2.5);for(let i=0;i<8;i++)spawnMob()}else if(k===1){toast('TREASURE BLOOM ✦',2.2);for(let i=0;i<7;i++)dropRune(player.x+rnd(-100,100),player.y+rnd(-100,100),i<2)}else if(k===2){toast('BONK FRENZY: COMBO BONUS!',2.4);state.combo=Math.max(state.combo,5);state.comboT=6}else{toast('WORLD BOSS AWAKENS',2.8);spawnMob('normal',true)}}function ensureApex(){let ring=bi();if(state.biomeKills[ring]>=10&&!state.apex.has(ring)&&!mobs.some(m=>m.elite&&m.ring===ring)){spawnMob('apex');toast('APEX HUNT STARTED!',2.3)}if((ring+1)%5===0&&!state.bosses.has(Math.floor(ring/5))&&state.biomeKills[ring]>=18&&!mobs.some(m=>m.boss)){spawnMob('normal',true);toast('REGION BOSS ENTERS THE WILD!',2.8)}}
function update(dt){time+=dt;shotT=Math.max(0,shotT-dt);player.dash=Math.max(0,player.dash-dt);player.inv=Math.max(0,player.inv-dt);if(state.comboT>0){state.comboT-=dt;if(state.comboT<=0)state.combo=0}let mag=Math.hypot(input.mx,input.my);if(mag>.05){let nx=input.mx/mag,ny=input.my/mag,s=player.speed;movePlayer(nx*s*dt,ny*s*dt);player.heading=Math.atan2(ny,nx)}if(input.shoot)fire();spawnT-=dt;let cap=12+Math.min(26,bi());if(spawnT<=0&&mobs.length<cap){spawnMob();spawnT=Math.max(.18,.8-bi()*.015)}for(let m of [...mobs])updateMob(m,dt);updateShots(dt);updateDrops(dt);updateWisps(dt);mobs=mobs.filter(m=>D(m,player)<1500||m.boss);for(let p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.94;p.vy*=.94;p.life-=dt}particles=particles.filter(p=>p.life>0);for(let f of floaters){f.y-=24*dt;f.life-=dt}floaters=floaters.filter(f=>f.life>0);shake=Math.max(0,shake-dt*22);flash=Math.max(0,flash-dt*3);eventT-=dt;if(eventT<=0)triggerEvent();ensureApex();if(bi()>state.bestRing){state.bestRing=bi();state.relics++;state.essence++;toast('NEW BIOME ✦ '+bio().name);initQuest()}if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}checkQuest();hud()}
function drawPlayer(){X.save();X.translate(W/2+rnd(-shake,shake),H/2+rnd(-shake,shake));r(-10,9,20,6,'#0003');r(-9,-9,18,20,'#fff0f5');r(-7,-15,5,8,'#fff0f5');r(2,-15,5,8,'#fff0f5');r(-5,-6,3,3,'#293143');r(3,-6,3,3,'#293143');X.rotate(player.heading);r(6,-2,15,4,'#8c684d');r(18,-5,5,10,bio().accent);X.restore()}
function drawMob(m){let p=screen(m.x,m.y);if(p.x<-90||p.x>W+90||p.y<-90||p.y>H+90)return;let u=Math.max(2,Math.round(m.sz/7));X.save();X.translate(p.x|0,p.y|0);if(m.boss){X.strokeStyle='#ffe477';X.lineWidth=4;X.strokeRect(-5*u,-7*u,10*u,12*u)}else if(m.elite){X.strokeStyle='#fff3a0';X.lineWidth=2;X.strokeRect(-4*u,-6*u,8*u,10*u)}r(-3*u,-2*u,6*u,5*u,m.boss?'#8b5f66':'#cba67a');r(-2*u,-5*u,4*u,4*u,m.boss?'#b77b80':'#d8c2a0');r(-u,-4*u,u,u,'#fff');r(u,-4*u,u,u,'#fff');X.restore();let bw=Math.max(26,m.sz*2.3);r(p.x-bw/2,p.y-m.sz-14,bw,5,'#172033aa');r(p.x-bw/2,p.y-m.sz-14,bw*(m.hp/m.maxHp),5,m.boss?'#ffd35c':m.elite?'#ff9b74':'#f27f9c');if(m.boss)txt(bossName(m),p.x,p.y-m.sz-24,9,'#fff3a0')}
function draw(){drawWorld();for(let d of drops){let p=screen(d.x,d.y);r(p.x-4,p.y-4,8,8,d.type==='xp'?'#b9f3ff':d.rare?'#ffe477':'#fff3c7')}for(let s of shots){let p=screen(s.x,s.y);r(p.x-s.r,p.y-s.r,s.r*2,s.r*2,s.crit?'#fff3a0':bio(s.x,s.y).accent)}for(let e of enemy){let p=screen(e.x,e.y);r(p.x-e.r,p.y-e.r,e.r*2,e.r*2,'#ff7b6d')}for(let m of mobs)drawMob(m);for(let p of particles){let q=screen(p.x,p.y);X.globalAlpha=clamp(p.life*3,0,1);r(q.x,q.y,p.sz,p.sz,p.c)}X.globalAlpha=1;for(let f of floaters){let q=screen(f.x,f.y);X.globalAlpha=clamp(f.life*2,0,1);txt(f.t,q.x,q.y,f.s,f.c)}X.globalAlpha=1;for(let w of orbiters){let p=screen(player.x+Math.cos(w.a)*38,player.y+Math.sin(w.a)*38);r(p.x-4,p.y-4,8,8,'#fff3a0')}drawPlayer();drawHUD();if(flash){X.fillStyle=`rgba(255,255,255,${flash*.18})`;X.fillRect(0,0,W,H)}}
function drawHUD(){let q=state.quests[0],prog=q?Math.min(q.need,qProg(q)):0,b=bio();X.save();X.globalAlpha=.92;r(W/2-95,43,190,39,'#172033bb');txt(b.name.toUpperCase(),W/2,53,9,'#fff');txt(q?`${q.name}: ${prog}/${q.need}`:'NO QUEST',W/2,68,9,b.accent);if(state.combo>1)txt(`${state.combo}× COMBO`,W/2,91,14,'#fff3a0');let boss=mobs.find(m=>m.boss);if(boss){r(W*.15,112,W*.7,10,'#172033cc');r(W*.15,112,W*.7*(boss.hp/boss.maxHp),10,'#ffd35c');txt(bossName(boss),W/2,105,10,'#fff3a0')}X.restore()}
function hud(){let q=state.quests[0];$('hp').textContent=Math.max(0,Math.ceil(player.hp));$('maxhp').textContent=Math.ceil(player.maxHp);$('hpfill').style.width=100*clamp(player.hp/player.maxHp,0,1)+'%';$('lv').textContent=player.lv;$('xp').textContent=Math.floor(player.xp)+'/'+player.next;$('biome').textContent=(bi()+1)+'/30 '+bio().name;$('weapon').textContent=(state.evolution||'Wand')+' · M'+state.weaponLv+' · '+player.proj+'×';$('danger').textContent='Wild '+(bi()+1);$('relics').textContent=Math.floor(state.relics);$('flowfill').style.width=100*clamp(player.ult/player.ultMax,0,1)+'%';let e=$('questmini');if(e)e.textContent=q?q.name+': '+Math.min(q.need,qProg(q))+'/'+q.need:'Exploring'}
function reset(){Object.assign(player,{x:0,y:0,hp:80,maxHp:80,speed:195,lv:1,xp:0,next:9,power:1,fire:1,proj:1,spread:.12,pierce:0,homing:0,crit:.08,range:1,shield:0,heading:0,magnet:120,bolt:4,chain:0,explode:0,frost:0,orbit:0,lifesteal:0,dashCd:2.5,dash:0,inv:0,ult:0,ultMax:100});mobs=[];shots=[];enemy=[];drops=[];particles=[];floaters=[];orbiters=[];Object.assign(state,{kills:0,relics:0,places:0,bestRing:0,combo:0,comboT:0,bestCombo:0,completed:0,essence:0,weaponXP:0,weaponLv:1,evolution:null,eventKills:0});state.biomeKills=Array(30).fill(0);state.apex.clear();state.bosses.clear();state.secrets.clear();state.quests=[];time=0;spawnT=0;eventT=14;dead=false;paused=false;initQuest();hud()}
function gameOver(){dead=true;paused=true;$('controls').classList.add('hide');$('death').classList.remove('hide');$('dlevel').textContent=player.lv;$('dtime').textContent=Math.floor(time/60)+':'+String(Math.floor(time%60)).padStart(2,'0');$('dkills').textContent=state.kills;$('drelics').textContent=Math.floor(state.relics)}function loop(ts){let dt=Math.min(.033,(ts-last)/1000||0);last=ts;if(started&&!paused&&!dead)update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
const joy=$('joystick'),knob=$('joyknob');function jm(e){if(input.pid!==e.pointerId)return;let b=joy.getBoundingClientRect(),dx=e.clientX-b.left-b.width/2,dy=e.clientY-b.top-b.height/2,lim=b.width*.34,d=Math.hypot(dx,dy)||1,k=Math.min(1,lim/d);dx*=k;dy*=k;knob.style.transform=`translate(${dx}px,${dy}px)`;input.mx=dx/lim;input.my=dy/lim}joy.onpointerdown=e=>{input.pid=e.pointerId;joy.setPointerCapture(e.pointerId);jm(e)};joy.onpointermove=jm;function je(e){if(input.pid!==e.pointerId)return;input.pid=null;input.mx=input.my=0;knob.style.transform='translate(0,0)'}joy.onpointerup=je;joy.onpointercancel=je;const shoot=$('shoot');shoot.onpointerdown=e=>{e.preventDefault();shoot.setPointerCapture(e.pointerId);input.shoot=true;fire()};shoot.onpointerup=shoot.onpointercancel=()=>input.shoot=false;$('dash').onclick=doDash;$('ult').onclick=ultimate;$('play').onclick=()=>{reset();started=true;$('start').classList.add('hide');$('controls').classList.remove('hide');toast('THE GRAND BONK BEGINS ✦')};$('again').onclick=()=>{reset();$('death').classList.add('hide');$('controls').classList.remove('hide')};
window.__TWBB_V21__={version:21,state:()=>({biome:bio().name,ring:bi()+1,kills:state.kills,quests:state.completed,bosses:[...state.bosses],evolution:state.evolution,player:{...player}}),blocked:(x,y)=>blocked(x,y),boss:()=>spawnMob('normal',true),evolve:()=>showEvolution(),ultimate};
})();