(()=>{'use strict';
const C=document.getElementById('g'),X=C?.getContext('2d'),B=window.TWBB_WORLD;if(!C||!X||!B)throw Error('v23 boot');
const $=i=>document.getElementById(i),T=Math.PI*2,cl=(v,a,b)=>Math.max(a,Math.min(b,v)),rd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
let W,H,D,last=0,tm=0,start=0,pause=0,dead=0,spawnT=0,shotT=0,eventT=20,toastT=0,shake=0,flash=0;
const R=780,S=580,F=380,CELL=74,PR=11;
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;C.width=W*D;C.height=H*D;C.style.width=W+'px';C.style.height=H+'px';X.setTransform(D,0,0,D,0,0);X.imageSmoothingEnabled=false}addEventListener('resize',resize);resize();
const hs=n=>Math.abs(Math.sin(n*127.1+Math.cos(n*9.13))*43758.5453)%1,h2=(x,y,s=0)=>hs(x*91.7+y*173.3+s*31.7),pick=(a,h)=>a[Math.floor(h*a.length)%a.length];
const p={x:0,y:0,hp:80,maxHp:80,speed:188,lv:1,xp:0,next:10,power:1,fire:1,proj:1,spread:.12,pierce:0,homing:0,crit:.06,range:1,shield:0,heading:0,magnet:110,bolt:4,chain:0,explode:0,frost:0,orbit:0,lifesteal:0,dash:0,dashCd:3,inv:0,ult:0,ultMax:120};
const st={kills:0,relics:0,places:0,best:0,combo:0,comboT:0,bestCombo:0,bk:Array(30).fill(0),apex:new Set(),bosses:new Set(),secrets:new Set(),completed:0,quest:null,weaponXP:0,weaponLv:1,evolution:null,overrun:0,pressure:0,threat:1};
const inp={mx:0,my:0,shoot:false,pid:null};let mobs=[],shots=[],enemy=[],drops=[],parts=[],wisps=[];
const bi=(x=p.x,y=p.y)=>cl(Math.floor(Math.hypot(x,y)/R),0,29),bio=(x=p.x,y=p.y)=>B[bi(x,y)],scr=(x,y)=>({x:W/2+x-p.x,y:H/2+y-p.y});
function rect(x,y,w,h,c){X.fillStyle=c;X.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function text(s,x,y,z=10,c='#fff'){X.fillStyle=c;X.font=`900 ${z}px ui-monospace,monospace`;X.textAlign='center';X.textBaseline='middle';X.fillText(s,x,y)}
function toast(s,d=2.2){let e=$('toast');e.textContent=s;e.classList.add('show');toastT=d}
function so(cx,cy){let x=cx*S+80+h2(cx,cy,201)*400,y=cy*S+80+h2(cx,cy,202)*400,h=h2(cx,cy,203);if(h<=.61)return null;let b=bio(x,y);return{x,y,h,b,type:pick(b.structures,h),large:h>.92}}
function fo(cx,cy){let x=cx*F+50+h2(cx,cy,101)*270,y=cy*F+50+h2(cx,cy,102)*270,h=h2(cx,cy,103);if(h<=.56)return null;let b=bio(x,y);return{x,y,h,b,type:pick(b.features,h)}}
function hr(x,y,cx,cy,hw,hh,r=PR){let nx=cl(x,cx-hw,cx+hw),ny=cl(y,cy-hh,cy+hh);return Math.hypot(x-nx,y-ny)<r}
function he(x,y,cx,cy,rx,ry,r=PR){let dx=(x-cx)/(rx+r),dy=(y-cy)/(ry+r);return dx*dx+dy*dy<1}
function blocked(x,y){let sx=Math.floor(x/S),sy=Math.floor(y/S);for(let yy=sy-1;yy<=sy+1;yy++)for(let xx=sx-1;xx<=sx+1;xx++){let o=so(xx,yy);if(!o)continue;let t=o.type,z=o.large?1.18:1;if(/bridge|boardwalk|ropeBridge|lavaBridge|dock|boat/i.test(t))continue;if(/gate|arch/i.test(t)){if(hr(x,y,o.x-23*z,o.y-6*z,7*z,31*z)||hr(x,y,o.x+23*z,o.y-6*z,7*z,31*z))return true}else if(hr(x,y,o.x,o.y,32*z,28*z))return true}let fx=Math.floor(x/F),fy=Math.floor(y/F);for(let yy=fy-1;yy<=fy+1;yy++)for(let xx=fx-1;xx<=fx+1;xx++){let o=fo(xx,yy);if(!o)continue;let t=o.type;if(/pond|pool|hole|watering|bog|tide|oasis|lake/i.test(t)&&he(x,y,o.x,o.y,58+o.h*22,26+o.h*12))return true;if(/chasm|ravine|cliff|crater/i.test(t)&&he(x,y,o.x,o.y+5,65+o.h*20,27+o.h*12))return true}return false}
function move(o,dx,dy){let nx=o.x+dx,ny=o.y+dy;if(!blocked(nx,o.y))o.x=nx;if(!blocked(o.x,ny))o.y=ny}
function readiness(){let build=p.lv*.72+st.weaponLv*1.5+st.relics*.18+(st.evolution?4:0)+p.proj*.35+p.pierce*.22+p.chain*.35+p.orbit*.45;return build}
function threat(){let r=bi(),need=1+r*1.8,under=Math.max(0,need-readiness()),rush=Math.max(0,r-Math.floor(tm/55));st.pressure=under+rush*1.5;st.overrun=st.pressure>3.5;st.threat=1+r*.18+st.pressure*.28;return st.threat}
const PERKS=[['PETAL STORM','⚡','+22% fire rate',()=>p.fire*=1.22],['TWIN BLOOM','✦','+1 projectile',()=>p.proj=Math.min(7,p.proj+1)],['BIG BONK','💥','+25% damage',()=>p.power*=1.25],['THORN NEEDLE','➶','+1 pierce',()=>p.pierce=Math.min(7,p.pierce+1)],['MOON SEEKER','☄','Homing',()=>p.homing=Math.min(7,p.homing+1.6)],['BUNNY HOP','💨','Faster dash',()=>p.dashCd=Math.max(1,p.dashCd*.82)],['GIANT HEART','♥','+18 max HP',()=>{p.maxHp+=18;p.hp+=18}],['CHAIN SPARK','ϟ','Shots chain',()=>p.chain++],['FROST BLOOM','❄','Slow on hit',()=>p.frost++],['WISP FRIEND','◎','Orbiting familiar',()=>{p.orbit++;sync()}]];
const EVOS=[['ROYAL BLOOM','Wide projectile fan',()=>{p.proj=Math.max(5,p.proj);p.fire*=1.25;p.spread=.5}],['THUNDER WAND','Powerful chain lightning',()=>{p.chain+=3;p.power*=1.22}],['STAR COMET','Homing explosive bolts',()=>{p.homing=7;p.explode+=2;p.bolt=8}],['WINTER CROWN','Heavy freeze and pierce',()=>{p.frost+=3;p.pierce+=3}],['WISP COURT','Four combat familiars',()=>{p.orbit=Math.max(4,p.orbit);sync()}]];
const QUESTS=[['Cull the Pack','kill',22],['Treasure Trail','place',3],['Combo Trial','combo',15],['Apex Hunt','apex',1]];
function initQ(){let q=QUESTS[(bi()+st.completed)%QUESTS.length];st.quest={name:q[0],type:q[1],need:q[2],ring:bi(),start:{kills:st.kills,places:st.places}};hud()}
function qp(){let q=st.quest;if(!q)return 0;if(q.type==='kill')return st.kills-q.start.kills;if(q.type==='place')return st.places-q.start.places;if(q.type==='combo')return st.bestCombo;if(q.type==='apex')return st.apex.has(q.ring)?1:0;return 0}
function checkQ(){if(st.quest&&qp()>=st.quest.need){st.completed++;st.relics++;toast('QUEST COMPLETE ✦');dropRune(p.x,p.y,true);initQ()}}
function drawWorld(){let b=bio();rect(0,0,W,H,b.ground);let sx=Math.floor((p.x-W/2)/CELL)-2,ex=Math.ceil((p.x+W/2)/CELL)+2,sy=Math.floor((p.y-H/2)/CELL)-2,ey=Math.ceil((p.y+H/2)/CELL)+2;for(let cy=sy;cy<=ey;cy++)for(let cx=sx;cx<=ex;cx++){let wx=cx*CELL+8+h2(cx,cy,1)*54,wy=cy*CELL+8+h2(cx,cy,2)*54,q=scr(wx,wy),bb=bio(wx,wy),h=h2(cx,cy,bi(wx,wy));if(h>.08){rect(q.x-2,q.y-9,4,12,bb.shade);if(h>.5)rect(q.x-7,q.y-13,14,7,bb.accent)}if(h>.72)rect(q.x+10,q.y-5,12,8,'#74695f')}let ax=Math.floor((p.x-W/2-180)/S),axx=Math.ceil((p.x+W/2+180)/S),ay=Math.floor((p.y-H/2-180)/S),ayy=Math.ceil((p.y+H/2+180)/S);for(let cy=ay;cy<=ayy;cy++)for(let cx=ax;cx<=axx;cx++){let o=so(cx,cy);if(!o)continue;let q=scr(o.x,o.y),t=o.type;if(/bridge|boardwalk|dock/i.test(t))rect(q.x-44,q.y-7,88,14,'#9b724c');else if(/gate|arch/i.test(t)){rect(q.x-28,q.y-38,10,62,'#88867d');rect(q.x+18,q.y-38,10,62,'#88867d')}else{rect(q.x-28,q.y-20,56,42,'#d8c39d');rect(q.x-33,q.y-27,66,9,o.b.shade)}let id=`${cx}:${cy}`;if(dist(p,o)<82&&!st.secrets.has(id)){st.secrets.add(id);st.places++;st.relics++;toast('SECRET PLACE ✦');dropRune(o.x,o.y,true);checkQ()}}}
function archetype(r){let roll=Math.random();if(r<2)return roll<.7?'chaser':'skitter';if(r<5)return roll<.4?'chaser':roll<.7?'flanker':'charger';if(r<10)return roll<.25?'chaser':roll<.5?'flanker':roll<.75?'charger':'sniper';return roll<.18?'tank':roll<.4?'flanker':roll<.62?'charger':roll<.82?'sniper':'orbiter'}
function spawnMob(kind='normal',boss=false){let a=rd(0,T),rr=Math.max(W,H)*.6+rd(50,130),x=p.x+Math.cos(a)*rr,y=p.y+Math.sin(a)*rr;for(let k=0;k<8&&blocked(x,y);k++){a+=.8;x=p.x+Math.cos(a)*rr;y=p.y+Math.sin(a)*rr}let r=bi(x,y),elite=kind==='apex',role=archetype(r),th=threat(),base=42*Math.pow(1.19,r),hp=base*th*(role==='tank'?1.8:1)*(elite?6:boss?18:1),spd=(72+r*3.4)*Math.min(1.7,th)*(role==='tank'?.72:role==='skitter'?1.25:1);mobs.push({x,y,hp,maxHp:hp,sz:12+r*.7+(role==='tank'?5:0)+(elite?9:0)+(boss?20:0),ring:r,sp:pick(B[r].animals,Math.random()),role,elite,boss,atk:rd(.3,1),slow:0,spd,phase:rd(0,T)})}
function bossName(m){return m.boss?['BURROW KING','MOSS COLOSSUS','CRYSTAL MAW','DUNE TYRANT','STORM EMPEROR','ELDER TITAN'][Math.min(5,Math.floor(m.ring/5))]:'APEX '+m.sp.toUpperCase()}
function damage(n){if(p.inv>0)return;if(p.shield){let a=Math.min(n,p.shield);p.shield-=a;n-=a}p.hp-=n;p.inv=.3;shake=6;flash=.2;if(p.hp<=0)over();hud()}
function shootEnemy(m,a,speed,damage,n=1,spread=.18){for(let i=0;i<n;i++){let aa=a+(i-(n-1)/2)*spread;enemy.push({x:m.x,y:m.y,vx:Math.cos(aa)*speed,vy:Math.sin(aa)*speed,life:4,damage,r:4})}}
function updateMob(m,dt){let dx=p.x-m.x,dy=p.y-m.y,d=Math.hypot(dx,dy)||1,nx=dx/d,ny=dy/d,sp=m.spd*(m.slow>0?.5:1);m.slow=Math.max(0,m.slow-dt);m.atk-=dt;if(m.role==='flanker'){let side=Math.sin(tm*1.8+m.phase);move(m,(nx-side*ny*.75)*sp*dt,(ny+side*nx*.75)*sp*dt)}else if(m.role==='orbiter'){let side=d>180?1:-.5;move(m,(nx*.45-ny*side)*sp*dt,(ny*.45+nx*side)*sp*dt)}else if(m.role==='sniper'){if(d>330)move(m,nx*sp*dt,ny*sp*dt);else if(d<240)move(m,-nx*sp*dt,-ny*sp*dt)}else if(m.role==='charger'&&m.atk<-.6){move(m,nx*sp*3.1*dt,ny*sp*3.1*dt)}else move(m,nx*sp*dt,ny*sp*dt);if((m.role==='sniper'||m.role==='orbiter'||m.elite||m.boss)&&m.atk<=0&&d<620){let n=m.boss?(m.hp<m.maxHp*.5?14:9):m.elite?3:1;shootEnemy(m,Math.atan2(dy,dx),145+m.ring*5+(st.overrun?35:0),6+m.ring*.7+(st.overrun?3:0),n,m.boss?.28:.16);m.atk=m.boss?1.05:m.elite?.9:1.5}if(d<m.sz+PR&&m.atk<=0){damage(8+m.ring*.65+(m.elite?5:0)+(m.boss?10:0));m.atk=.55}}
function nearest(x=p.x,y=p.y,range=500*p.range){let best=null,bd=range;for(let m of mobs){let d=Math.hypot(m.x-x,m.y-y);if(d<bd){bd=d;best=m}}return best}
function fire(){if(shotT>0||pause||dead)return;let n=nearest(),a=n?Math.atan2(n.y-p.y,n.x-p.x):p.heading;p.heading=a;shotT=.34/p.fire;for(let i=0;i<p.proj;i++){let off=p.proj===1?0:(i-(p.proj-1)/2)*p.spread/Math.max(1,p.proj-1),aa=a+off;shots.push({x:p.x+Math.cos(aa)*18,y:p.y+Math.sin(aa)*18,vx:Math.cos(aa)*410,vy:Math.sin(aa)*410,life:1.2*p.range,damage:(8.5+p.lv*.5)*p.power,pierce:p.pierce,r:p.bolt,crit:Math.random()<p.crit,hit:new Set()})}}
function kill(m){let i=mobs.indexOf(m);if(i>=0)mobs.splice(i,1);st.kills++;st.bk[m.ring]++;st.combo++;st.comboT=2.5;st.bestCombo=Math.max(st.bestCombo,st.combo);st.weaponXP++;p.ult=Math.min(p.ultMax,p.ult+3);drops.push({x:m.x,y:m.y,type:'xp',v:m.elite?3:m.boss?6:1,life:18});if(Math.random()<.1+(m.elite?.55:0)+(m.boss?.9:0))dropRune(m.x,m.y,m.elite||m.boss);if(m.elite){st.apex.add(m.ring);st.relics+=2;toast('APEX DEFEATED ✦');choices()}if(m.boss){st.bosses.add(Math.floor(m.ring/5));st.relics+=4;toast('BOSS DEFEATED ✦');evolve()}if(st.weaponXP>=16*st.weaponLv){st.weaponXP=0;st.weaponLv++;toast('WAND MASTERY '+st.weaponLv);choices()}checkQ();hud()}
function hit(m,s){let d=s.damage*(s.crit?1.8:1);m.hp-=d;if(p.frost)m.slow=Math.max(m.slow,.7+.2*p.frost);p.ult=Math.min(p.ultMax,p.ult+1.1);if(p.chain){let n=mobs.find(v=>v!==m&&dist(v,m)<160);if(n){n.hp-=d*.32;if(n.hp<=0)kill(n)}}if(m.hp<=0)kill(m)}
function updateShots(dt){for(let s of shots){if(p.homing){let n=nearest(s.x,s.y,240);if(n){let a=Math.atan2(n.y-s.y,n.x-s.x),ca=Math.atan2(s.vy,s.vx),df=Math.atan2(Math.sin(a-ca),Math.cos(a-ca)),sp=Math.hypot(s.vx,s.vy);ca+=df*Math.min(1,dt*p.homing);s.vx=Math.cos(ca)*sp;s.vy=Math.sin(ca)*sp}}s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(let m of [...mobs]){if(s.hit.has(m)||dist(s,m)>m.sz+s.r)continue;s.hit.add(m);hit(m,s);if(s.pierce>0)s.pierce--;else{s.life=0;break}}}shots=shots.filter(s=>s.life>0);for(let e of enemy){e.x+=e.vx*dt;e.y+=e.vy*dt;e.life-=dt;if(dist(e,p)<e.r+PR){damage(e.damage);e.life=0}}enemy=enemy.filter(e=>e.life>0)}
function dropRune(x,y,rare=false){drops.push({x,y,type:'rune',rare,life:20})}
function applyRune(rare){let q=PERKS[Math.floor(Math.random()*PERKS.length)];q[3]();if(rare)st.relics++;toast((rare?'RARE ':'')+q[0]+' ✦');hud()}
function gain(v){p.xp+=v;while(p.xp>=p.next){p.xp-=p.next;p.lv++;p.next=Math.floor(p.next*1.25+4);choices()}hud()}
function updateDrops(dt){for(let d of drops){d.life-=dt;let q=dist(d,p);if(q<p.magnet){d.x+=(p.x-d.x)*Math.min(1,dt*6);d.y+=(p.y-d.y)*Math.min(1,dt*6)}if(q<18){d.life=0;d.type==='xp'?gain(d.v):applyRune(d.rare)}}drops=drops.filter(d=>d.life>0)}
function choices(){pause=1;let box=$('choices');box.innerHTML='';box.style.display='grid';for(let q of [...PERKS].sort(()=>Math.random()-.5).slice(0,3)){let b=document.createElement('button');b.className='choice';b.innerHTML=`<b>${q[1]} ${q[0]}</b><span>${q[2]}</span>`;b.onclick=()=>{q[3]();box.style.display='none';pause=0;hud()};box.appendChild(b)}}
function evolve(){pause=1;let box=$('choices');box.innerHTML='';box.style.display='grid';for(let q of [...EVOS].filter(v=>v[0]!==st.evolution).sort(()=>Math.random()-.5).slice(0,3)){let b=document.createElement('button');b.className='choice legendary';b.innerHTML=`<b>★ ${q[0]}</b><span>${q[1]}</span>`;b.onclick=()=>{q[2]();st.evolution=q[0];box.style.display='none';pause=0;hud()};box.appendChild(b)}}
function sync(){wisps=Array.from({length:p.orbit},(_,i)=>({a:i*T/Math.max(1,p.orbit),cool:0}))}
function updateWisps(dt){for(let w of wisps){w.a+=dt*1.7;w.cool-=dt;if(w.cool<=0){let x=p.x+Math.cos(w.a)*38,y=p.y+Math.sin(w.a)*38,n=nearest(x,y,280);if(n){let a=Math.atan2(n.y-y,n.x-x);shots.push({x,y,vx:Math.cos(a)*340,vy:Math.sin(a)*340,life:1,damage:5.5*p.power,pierce:0,r:3,crit:false,hit:new Set()});w.cool=.8}}}}
function dash(){if(p.dash>0||pause)return;let m=Math.hypot(inp.mx,inp.my),nx=m>.1?inp.mx/m:Math.cos(p.heading),ny=m>.1?inp.my/m:Math.sin(p.heading);for(let i=0;i<8;i++)move(p,nx*11,ny*11);p.dash=p.dashCd;p.inv=.35}
function ultimate(){if(p.ult<p.ultMax||pause)return;p.ult=0;shake=9;toast('MEGA BONK!!! ☀');for(let m of [...mobs])if(dist(m,p)<430){m.hp-=35*p.power;if(m.hp<=0)kill(m)}}
function eventNow(){eventT=rd(22,34);let k=Math.floor(Math.random()*3);if(k===0){toast('AMBUSH!');for(let i=0;i<5+bi();i++)spawnMob()}else if(k===1){toast('HUNTING PACK!');for(let i=0;i<4+Math.floor(bi()/2);i++)spawnMob('normal')}else{toast('WORLD BOSS AWAKENS');spawnMob('normal',true)}}
function ensureBoss(){let r=bi();if(st.bk[r]>=14&&!st.apex.has(r)&&!mobs.some(m=>m.elite&&m.ring===r)){spawnMob('apex');toast('APEX HUNT STARTED!')}if((r+1)%5===0&&st.bk[r]>=24&&!st.bosses.has(Math.floor(r/5))&&!mobs.some(m=>m.boss)){spawnMob('normal',true);toast('REGION BOSS ENTERS THE WILD!')}}
function update(dt){tm+=dt;shotT=Math.max(0,shotT-dt);p.dash=Math.max(0,p.dash-dt);p.inv=Math.max(0,p.inv-dt);if(st.comboT>0){st.comboT-=dt;if(st.comboT<=0)st.combo=0}let old=bi(),m=Math.hypot(inp.mx,inp.my);if(m>.05){let nx=inp.mx/m,ny=inp.my/m;move(p,nx*p.speed*dt,ny*p.speed*dt);p.heading=Math.atan2(ny,nx)}let now=bi();if(now>old){threat();if(st.overrun){toast('⚠ OVERRUN — YOU PUSHED TOO FAR ⚠',3);for(let i=0;i<4+now;i++)spawnMob()}}if(inp.shoot)fire();threat();spawnT-=dt;let cap=10+bi()*2+Math.floor(st.pressure*5);if(spawnT<=0&&mobs.length<Math.min(70,cap)){spawnMob();spawnT=Math.max(.09,.72/(1+bi()*.08+st.pressure*.22))}for(let q of [...mobs])updateMob(q,dt);updateShots(dt);updateDrops(dt);updateWisps(dt);mobs=mobs.filter(q=>dist(q,p)<1700||q.boss);eventT-=dt;if(eventT<=0)eventNow();ensureBoss();if(bi()>st.best){st.best=bi();st.relics++;toast('NEW BIOME ✦ '+bio().name);initQ()}if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}shake=Math.max(0,shake-dt*20);flash=Math.max(0,flash-dt*3);checkQ();hud()}
function drawMob(m){let q=scr(m.x,m.y),u=Math.max(2,Math.round(m.sz/7));rect(q.x-3*u,q.y-2*u,6*u,5*u,m.boss?'#7d4755':m.elite?'#a76d5a':'#cba67a');rect(q.x-2*u,q.y-5*u,4*u,4*u,m.role==='sniper'?'#8bc5d8':m.role==='charger'?'#d68b6c':'#d8c2a0');if(m.elite||m.boss){X.strokeStyle=m.boss?'#ffe477':'#fff3a0';X.lineWidth=m.boss?4:2;X.strokeRect(q.x-4*u,q.y-6*u,8*u,10*u)}if(m.hp<m.maxHp){let w=Math.max(20,m.sz*2);rect(q.x-w/2,q.y-m.sz-10,w,4,'#2229');rect(q.x-w/2,q.y-m.sz-10,w*(m.hp/m.maxHp),4,'#ef799d')}}
function draw(){drawWorld();for(let d of drops){let q=scr(d.x,d.y);rect(q.x-4,q.y-4,8,8,d.type==='xp'?'#b9f3ff':d.rare?'#ffe477':'#fff3c7')}for(let s of shots){let q=scr(s.x,s.y);rect(q.x-s.r,q.y-s.r,s.r*2,s.r*2,'#fff3a0')}for(let e of enemy){let q=scr(e.x,e.y);rect(q.x-e.r,q.y-e.r,e.r*2,e.r*2,'#ff6f67')}for(let m of mobs)drawMob(m);for(let w of wisps){let q=scr(p.x+Math.cos(w.a)*38,p.y+Math.sin(w.a)*38);rect(q.x-4,q.y-4,8,8,'#fff3a0')}X.save();X.translate(W/2+rd(-shake,shake),H/2+rd(-shake,shake));rect(-9,-9,18,20,'#fff0f5');rect(-7,-15,5,8,'#fff0f5');rect(2,-15,5,8,'#fff0f5');X.rotate(p.heading);rect(6,-2,15,4,'#8c684d');X.restore();let q=st.quest;rect(W/2-110,43,220,48,'#172033cc');text(bio().name.toUpperCase(),W/2,54,9,'#fff');text(q?`${q.name}: ${Math.min(q.need,qp())}/${q.need}`:'EXPLORING',W/2,69,9,bio().accent);text(st.overrun?'⚠ OVERRUN ⚠':`THREAT ${st.threat.toFixed(1)} · READINESS ${readiness().toFixed(1)}`,W/2,84,8,st.overrun?'#ff7b6d':'#fff3a0');if(st.combo>1)text(`${st.combo}× COMBO`,W/2,105,13,'#fff3a0');let boss=mobs.find(m=>m.boss);if(boss){rect(W*.15,125,W*.7,10,'#172033cc');rect(W*.15,125,W*.7*(boss.hp/boss.maxHp),10,'#ffd35c');text(bossName(boss),W/2,118,10,'#fff3a0')}}
function hud(){$('hp').textContent=Math.max(0,Math.ceil(p.hp));$('maxhp').textContent=p.maxHp;$('hpfill').style.width=100*cl(p.hp/p.maxHp,0,1)+'%';$('lv').textContent=p.lv;$('xp').textContent=Math.floor(p.xp)+'/'+p.next;$('biome').textContent=(bi()+1)+'/30 '+bio().name;$('weapon').textContent=(st.evolution||'Wand')+' · M'+st.weaponLv+' · '+p.proj+'×';$('danger').textContent=st.overrun?'OVERRUN':'Threat '+st.threat.toFixed(1);$('relics').textContent=st.relics;$('flowfill').style.width=100*cl(p.ult/p.ultMax,0,1)+'%';let e=$('questmini');if(e&&st.quest)e.textContent=st.quest.name+': '+Math.min(st.quest.need,qp())+'/'+st.quest.need}
function safeSpawn(){if(!blocked(0,0))return;for(let rr=20;rr<260;rr+=20)for(let i=0;i<24;i++){let a=i*T/24,x=Math.cos(a)*rr,y=Math.sin(a)*rr;if(!blocked(x,y)){p.x=x;p.y=y;return}}}
function reset(){Object.assign(p,{x:0,y:0,hp:80,maxHp:80,speed:188,lv:1,xp:0,next:10,power:1,fire:1,proj:1,spread:.12,pierce:0,homing:0,crit:.06,range:1,shield:0,heading:0,magnet:110,bolt:4,chain:0,explode:0,frost:0,orbit:0,lifesteal:0,dash:0,dashCd:3,inv:0,ult:0,ultMax:120});mobs=[];shots=[];enemy=[];drops=[];wisps=[];Object.assign(st,{kills:0,relics:0,places:0,best:0,combo:0,comboT:0,bestCombo:0,completed:0,weaponXP:0,weaponLv:1,evolution:null,overrun:0,pressure:0,threat:1});st.bk=Array(30).fill(0);st.apex.clear();st.bosses.clear();st.secrets.clear();tm=0;spawnT=0;eventT=20;dead=0;pause=0;safeSpawn();initQ();hud()}
function over(){dead=1;pause=1;$('controls').classList.add('hide');$('death').classList.remove('hide');$('dlevel').textContent=p.lv;$('dtime').textContent=Math.floor(tm/60)+':'+String(Math.floor(tm%60)).padStart(2,'0');$('dkills').textContent=st.kills;$('drelics').textContent=st.relics}
function loop(ts){let dt=Math.min(.033,(ts-last)/1000||0);last=ts;if(start&&!pause&&!dead)update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
const joy=$('joystick'),knob=$('joyknob');function jm(e){if(inp.pid!==e.pointerId)return;let b=joy.getBoundingClientRect(),dx=e.clientX-b.left-b.width/2,dy=e.clientY-b.top-b.height/2,lim=b.width*.34,d=Math.hypot(dx,dy)||1,k=Math.min(1,lim/d);dx*=k;dy*=k;knob.style.transform=`translate(${dx}px,${dy}px)`;inp.mx=dx/lim;inp.my=dy/lim}joy.onpointerdown=e=>{inp.pid=e.pointerId;joy.setPointerCapture(e.pointerId);jm(e)};joy.onpointermove=jm;joy.onpointerup=joy.onpointercancel=e=>{if(inp.pid===e.pointerId){inp.pid=null;inp.mx=inp.my=0;knob.style.transform='translate(0,0)'}};const sh=$('shoot');sh.onpointerdown=e=>{e.preventDefault();sh.setPointerCapture(e.pointerId);inp.shoot=true;fire()};sh.onpointerup=sh.onpointercancel=()=>inp.shoot=false;$('dash').onclick=dash;$('ult').onclick=ultimate;$('play').onclick=()=>{reset();start=1;$('start').classList.add('hide');$('controls').classList.remove('hide');toast('v23 — THE WILD FIGHTS BACK')};$('again').onclick=()=>{reset();$('death').classList.add('hide');$('controls').classList.remove('hide')};
window.__TWBB_V23__={version:23,state:()=>({ring:bi()+1,level:p.lv,readiness:readiness(),pressure:st.pressure,threat:st.threat,overrun:st.overrun,mobs:mobs.length,player:{...p}}),boss:()=>spawnMob('normal',true)};})();