'use strict';
const WORLD_SEED=731927,TILE=48,PLAYER_R=10,MAX_MOBS=38,MAX_WANDERERS=4;
const c=document.getElementById('g'),ctx=c.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;
let DPR=Math.min(2,window.devicePixelRatio||1),w=0,h=0,last=performance.now(),started=false,dead=false;
let player,mobs=[],wanderers=[],drops=[],landmarks=[],particles=[],shots=[],ambient=[],run=0,kills=0,relics=0,level=1,xp=0,xpNeed=6,maxHp=48,hp=48,invuln=0,attackCd=0,regenDelay=0,spawnShield=0,screenShake=0,bossTimer=0,regionCount=0,lastRegionKey='',tutorialStep=0,hostileTarget=null,autoAttack=true,worldEventTimer=38;
const keys={},discovered=new Set();let audioOn=true,audioCtx=null,toastTimer=0,regionBannerTimer=0,regionBanner='';
const rarity=['Common','Uncommon','Rare','Epic','Legendary','Mythic'];
const rarityColor=['#f4f0e8','#92d8a2','#75bff0','#c5a0ff','#ffd76b','#ff8fd7'];
const rarityGlow=['#ffffff00','#8ee9a755','#71c9ff88','#c7a3ffbb','#ffe070dd','#ff85dfff'];
const weapons=[
{name:'Twig Sword',rarity:0,power:1,range:66,cd:.44,kb:24,type:'melee',kind:'sword'},
{name:'Rusty Axe',rarity:0,power:1.12,range:62,cd:.56,kb:34,type:'melee',kind:'axe'},
{name:'Iron Sword',rarity:1,power:1.42,range:72,cd:.38,kb:28,type:'melee',kind:'sword'},
{name:'Thorn Mace',rarity:1,power:1.55,range:66,cd:.53,kb:45,type:'melee',kind:'mace'},
{name:'Pink Spear',rarity:2,power:1.78,range:104,cd:.50,kb:34,type:'melee',kind:'spear'},
{name:'Moon Bow',rarity:2,power:1.65,range:315,cd:.53,kb:17,type:'ranged',kind:'bow'},
{name:'Twin Daggers',rarity:2,power:1.46,range:59,cd:.23,kb:15,type:'melee',kind:'daggers'},
{name:'Sun Chakram',rarity:2,power:1.72,range:260,cd:.46,kb:25,type:'ranged',kind:'chakram'},
{name:'Bonk Hammer',rarity:3,power:2.5,range:79,cd:.74,kb:72,type:'melee',kind:'hammer'},
{name:'Star Wand',rarity:3,power:1.92,range:300,cd:.48,kb:22,type:'ranged',kind:'wand'},
{name:'Frost Glaive',rarity:3,power:2.28,range:114,cd:.48,kb:46,type:'melee',kind:'glaive'},
{name:'Ember Cannon',rarity:3,power:2.16,range:275,cd:.67,kb:58,type:'ranged',kind:'cannon'},
{name:'Sakura Blade',rarity:4,power:3.18,range:87,cd:.29,kb:39,type:'melee',kind:'blade'},
{name:'Comet Wand',rarity:4,power:2.82,range:355,cd:.41,kb:31,type:'ranged',kind:'wand'},
{name:'Royal Maul',rarity:4,power:3.72,range:84,cd:.78,kb:96,type:'melee',kind:'hammer'},
{name:'Aurora Bow',rarity:4,power:2.95,range:390,cd:.46,kb:28,type:'ranged',kind:'bow'},
{name:'Void Scythe',rarity:5,power:4.48,range:124,cd:.41,kb:70,type:'melee',kind:'scythe'},
{name:'Celestial Bell',rarity:5,power:4.15,range:330,cd:.37,kb:52,type:'ranged',kind:'bell'},
{name:'Heartbreaker',rarity:5,power:4.9,range:94,cd:.31,kb:58,type:'melee',kind:'blade'},
{name:'Worldstar Staff',rarity:5,power:4.42,range:420,cd:.39,kb:38,type:'ranged',kind:'staff'}];
let weapon=weapons[0];
const mobDefs={
slime:{hp:14,spd:34,dmg:5,xp:1,r:13,ai:'chase',tier:0},pink:{hp:17,spd:38,dmg:5,xp:1,r:14,ai:'chase',tier:0},bee:{hp:11,spd:64,dmg:5,xp:1,r:10,ai:'zig',tier:0},frog:{hp:18,spd:43,dmg:6,xp:1,r:12,ai:'hop',tier:0},bat:{hp:14,spd:70,dmg:6,xp:1,r:11,ai:'zig',tier:0},
boar:{hp:27,spd:46,dmg:8,xp:2,r:16,ai:'charge',tier:1},mushroom:{hp:21,spd:30,dmg:7,xp:2,r:14,ai:'chase',tier:1},ghost:{hp:24,spd:49,dmg:7,xp:2,r:15,ai:'phase',tier:1},crab:{hp:27,spd:35,dmg:8,xp:2,r:15,ai:'strafe',tier:1},wisp:{hp:16,spd:58,dmg:6,xp:2,r:10,ai:'orbit',tier:1},snowbun:{hp:20,spd:56,dmg:6,xp:2,r:12,ai:'hop',tier:1},
skeleton:{hp:34,spd:42,dmg:9,xp:3,r:15,ai:'chase',tier:2},cactus:{hp:36,spd:27,dmg:10,xp:3,r:16,ai:'chase',tier:2},wolf:{hp:31,spd:72,dmg:9,xp:3,r:14,ai:'pack',tier:2},moth:{hp:24,spd:62,dmg:8,xp:3,r:13,ai:'orbit',tier:2},mimic:{hp:46,spd:48,dmg:11,xp:4,r:17,ai:'charge',tier:2},crystalbeetle:{hp:43,spd:36,dmg:10,xp:4,r:16,ai:'strafe',tier:2},
emberling:{hp:41,spd:52,dmg:12,xp:4,r:15,ai:'zig',tier:3},frostling:{hp:44,spd:46,dmg:11,xp:4,r:15,ai:'orbit',tier:3},golem:{hp:78,spd:25,dmg:14,xp:6,r:21,ai:'charge',tier:3},shroomknight:{hp:59,spd:38,dmg:13,xp:5,r:18,ai:'strafe',tier:3},serpent:{hp:52,spd:66,dmg:12,xp:5,r:17,ai:'zig',tier:3},treant:{hp:91,spd:21,dmg:15,xp:7,r:23,ai:'chase',tier:3},
voidling:{hp:72,spd:69,dmg:15,xp:7,r:17,ai:'phase',tier:4},starbeast:{hp:102,spd:45,dmg:17,xp:9,r:22,ai:'orbit',tier:4},riftHound:{hp:84,spd:82,dmg:16,xp:8,r:18,ai:'pack',tier:4},
king:{hp:190,spd:31,dmg:13,xp:14,r:29,ai:'boss',tier:2,boss:true},wraithQueen:{hp:275,spd:44,dmg:16,xp:22,r:27,ai:'orbit',tier:3,boss:true},magmaToad:{hp:340,spd:28,dmg:19,xp:28,r:31,ai:'hop',tier:4,boss:true},frostStag:{hp:380,spd:62,dmg:20,xp:32,r:30,ai:'charge',tier:4,boss:true},worldEater:{hp:560,spd:39,dmg:24,xp:50,r:36,ai:'boss',tier:5,boss:true}};
const biomeNames=['Meadow','Blossom Woods','Moon Fields','Misty Marsh','Emberlands','Frostvale','Crystal Steppe','Sunken Garden','Duskwild','Starfall Reach'];
const biomeMinTier=[0,0,1,1,2,2,2,3,3,4];
const palettes=[
{a:'#cfe9ad',b:'#c6e0a3',edge:'#9fca86',tree:'#70a15f',detail:'#f1a6c3',water:'#8fd2e2',sky:'#eaf7d8'},
{a:'#edccd9',b:'#e5c1d2',edge:'#c99fb5',tree:'#8a7598',detail:'#fff0a5',water:'#a7d7e8',sky:'#f9e9f1'},
{a:'#b9d8c8',b:'#aed0be',edge:'#8db7a1',tree:'#678d7c',detail:'#c3adef',water:'#86cad8',sky:'#dcebe5'},
{a:'#a9c8b6',b:'#9fbbaa',edge:'#819f90',tree:'#607a70',detail:'#84d4e2',water:'#75b7c9',sky:'#c9ddd2'},
{a:'#e6b09a',b:'#dba18c',edge:'#bf816e',tree:'#896455',detail:'#ffd079',water:'#8f8792',sky:'#f3cab8'},
{a:'#d9ecf1',b:'#cde3eb',edge:'#adcbd6',tree:'#7699a4',detail:'#a8c9ee',water:'#a9d9e9',sky:'#eef8fb'},
{a:'#c8d5e8',b:'#bdcadf',edge:'#96a8c5',tree:'#65738f',detail:'#9b86df',water:'#91bfdc',sky:'#e8edf8'},
{a:'#b9d9c2',b:'#afd0b7',edge:'#89ac92',tree:'#587e64',detail:'#f0a1c1',water:'#7dc8ba',sky:'#d9f0df'},
{a:'#9aa8a2',b:'#909e98',edge:'#6f7c77',tree:'#4b5954',detail:'#d292c9',water:'#677f86',sky:'#bdc5c1'},
{a:'#8899bd',b:'#8091b3',edge:'#65759a',tree:'#505f80',detail:'#ffd578',water:'#728eb6',sky:'#b6c2dd'}];
const landmarkDefs=[
{name:'Ancient Ruins',kind:'ruins',tier:0,text:'Old magic hums under broken stone.'},{name:'Fairy Grove',kind:'grove',tier:0,text:'Tiny lights stitch your wounds closed.'},{name:'Moon Obelisk',kind:'obelisk',tier:1,text:'Moonlight hardens your resolve.'},{name:'Starfall Crater',kind:'crater',tier:2,text:'A fallen star left impossible metal.'},{name:'Elder Tree',kind:'elder',tier:1,text:'The oldest roots lend you strength.'},{name:'Hidden Spring',kind:'spring',tier:0,text:'Cold bright water restores you.'},{name:'Lost Camp',kind:'camp',tier:0,text:'Someone ran. Their supplies stayed.'},{name:'Forgotten Vault',kind:'vault',tier:2,text:'The lock opens for something brave.'},{name:'Crystal Choir',kind:'choir',tier:2,text:'The stones sing when you approach.'},{name:'Sunken Shrine',kind:'shrine',tier:3,text:'A drowned bell answers from below.'},{name:'Witch Lantern',kind:'lantern',tier:3,text:'A purple flame points somewhere worse.'},{name:'Dragon Grave',kind:'grave',tier:3,text:'Huge ribs arch over scorched earth.'},{name:'Astral Gate',kind:'gate',tier:4,text:'The air beyond it looks incorrectly blue.'},{name:'Worldheart',kind:'worldheart',tier:4,text:'Something beneath the world is awake.'}];
function resize(){w=innerWidth;h=innerHeight;c.width=Math.floor(w*DPR);c.height=Math.floor(h*DPR);c.style.width=w+'px';c.style.height=h+'px';ctx.setTransform(DPR,0,0,DPR,0,0);ctx.imageSmoothingEnabled=false}addEventListener('resize',resize,{passive:true});resize();
function hash(a,b,s=0){let n=Math.sin((a+WORLD_SEED*.001)*127.1+(b-WORLD_SEED*.002)*311.7+s*74.7)*43758.5453123;return n-Math.floor(n)}
function noise(x,y,s=0){const ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy,sm=t=>t*t*(3-2*t),ux=sm(fx),uy=sm(fy),a=hash(ix,iy,s),b=hash(ix+1,iy,s),d=hash(ix,iy+1,s),e=hash(ix+1,iy+1,s);return a+(b-a)*ux+((d+(e-d)*ux)-(a+(b-a)*ux))*uy}
function dangerAt(x,y){const d=Math.hypot(x,y);return Math.max(0,Math.min(5,Math.floor(d/1250)+Math.floor(run/180)))}
function biomeAtWorld(x,y){const tier=dangerAt(x,y),n=noise(x/820,y/820,8),m=noise(x/420,y/420,27);let choices=tier<=0?[0,1]:tier===1?[0,1,2,3]:tier===2?[2,3,4,5,6]:tier===3?[4,5,6,7,8]:[6,7,8,9];return choices[Math.min(choices.length-1,Math.floor(((n*.72+m*.28))*choices.length))]}
function terrainAt(tx,ty){if(Math.abs(tx)<=2&&Math.abs(ty)<=2)return'grass';const wx=tx*TILE,wy=ty*TILE,b=biomeAtWorld(wx,wy),large=noise(tx/5.4,ty/5.4,13),small=hash(tx,ty,2),path=noise(tx/15,ty/15,21);if((b===4&&large<.075&&path>.28))return'lava';if((b===5||b===6)&&large<.07&&path>.28)return'icewater';if(large<.105&&path>.27)return'water';if(small>.952)return b===4?'basalt':b===5?'pine':b===6?'crystal':b===8?'deadtree':b===9?'starrock':'tree';if(b===3&&small>.912)return'reeds';if(b===7&&small>.912)return'lotus';if(b===2&&small>.914)return'mooncrystal';if(small>.884)return'flower';return'grass'}
function colliderForTile(tx,ty){const t=terrainAt(tx,ty),x=tx*TILE,y=ty*TILE;if(['water','lava','icewater'].includes(t))return{x,y,w:TILE,h:TILE,type:'rect'};if(['tree','pine','deadtree'].includes(t))return{x:x+17,y:y+24,w:14,h:20,type:'rect'};if(['basalt','starrock'].includes(t))return{x:x+10,y:y+16,w:28,h:24,type:'rect'};if(['crystal','mooncrystal'].includes(t))return{x:x+14,y:y+11,w:20,h:28,type:'rect'};return null}
function circleRect(cx,cy,r,box){const nx=Math.max(box.x,Math.min(cx,box.x+box.w)),ny=Math.max(box.y,Math.min(cy,box.y+box.h)),dx=cx-nx,dy=cy-ny;return dx*dx+dy*dy<r*r}
function blockedCircle(x,y,r=PLAYER_R){const minTx=Math.floor((x-r)/TILE),maxTx=Math.floor((x+r)/TILE),minTy=Math.floor((y-r)/TILE),maxTy=Math.floor((y+r)/TILE);for(let ty=minTy;ty<=maxTy;ty++)for(let tx=minTx;tx<=maxTx;tx++){const box=colliderForTile(tx,ty);if(box&&circleRect(x,y,r,box))return true}return false}
function moveBody(body,dx,dy,r){const dist=Math.hypot(dx,dy),steps=Math.max(1,Math.ceil(dist/4));dx/=steps;dy/=steps;for(let i=0;i<steps;i++){const nx=body.x+dx;if(!blockedCircle(nx,body.y,r))body.x=nx;const ny=body.y+dy;if(!blockedCircle(body.x,ny,r))body.y=ny}return body}
function lineClear(ax,ay,bx,by){const d=Math.hypot(bx-ax,by-ay),n=Math.max(1,Math.ceil(d/10));for(let i=1;i<n;i++){const t=i/n;if(blockedCircle(ax+(bx-ax)*t,ay+(by-ay)*t,4))return false}return true}
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1550)}
function sound(type){if(!audioOn)return;try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();const now=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();let f={hurt:100,loot:610,level:500,discover:720,boss:75,hit:180,hostile:260,mythic:880}[type]||190;o.type=type==='hurt'||type==='boss'?'sawtooth':type==='mythic'?'sine':'square';o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(Math.max(60,f*(['loot','discover','mythic'].includes(type)?1.45:.7)),now+.11);g.gain.setValueAtTime(type==='boss'?.05:.032,now);g.gain.exponentialRampToValueAtTime(.001,now+.15);o.connect(g);g.connect(audioCtx.destination);o.start(now);o.stop(now+.16)}catch(_){}}
function puff(x,y,col,n=7,speed=95){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=Math.random()*speed;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,t:.3+Math.random()*.3,col,size:2+Math.random()*2})}}
function hud(){document.getElementById('hp').textContent=Math.max(0,Math.ceil(hp));document.getElementById('maxhp').textContent=maxHp;document.getElementById('lv').textContent=level;document.getElementById('xp').textContent=xp+'/'+xpNeed;const we=document.getElementById('wp');we.textContent=rarity[weapon.rarity]+' · '+weapon.name;we.style.borderColor=rarityColor[weapon.rarity];we.style.boxShadow=weapon.rarity>=4?'0 0 12px '+rarityColor[weapon.rarity]+',0 3px 0 #0002':'0 3px 0 #0002';document.getElementById('relic').textContent=relics;document.getElementById('disc').textContent=discovered.size;document.getElementById('danger').textContent='Danger '+(dangerAt(player.x,player.y)+1);document.getElementById('hpfill').style.width=Math.max(0,hp/maxHp*100)+'%'}
function safeSpawnAround(x,y,minD=260,maxD=690){for(let tries=0;tries<35;tries++){const a=Math.random()*Math.PI*2,d=minD+Math.random()*(maxD-minD),sx=x+Math.cos(a)*d,sy=y+Math.sin(a)*d;if(!blockedCircle(sx,sy,24))return{x:sx,y:sy}}return{x:x+maxD,y}}
function mobPoolForTier(tier,biome){let list=['slime','pink','bee','frog','bat'];if(tier>=1)list.push('boar','mushroom','ghost','crab','wisp','snowbun');if(tier>=2)list.push('skeleton','cactus','wolf','moth','mimic','crystalbeetle');if(tier>=3)list.push('emberling','frostling','golem','shroomknight','serpent','treant');if(tier>=4)list.push('voidling','starbeast','riftHound');if(biome===4)list.push('emberling','magmaToad');if(biome===5)list.push('snowbun','frostling');if(biome===6)list.push('crystalbeetle');if(biome===8)list.push('ghost','voidling');return list}
function spawnMob(forceType,near=false){if(mobs.length>=MAX_MOBS)return;const pt=safeSpawnAround(player.x,player.y,near?170:300,near?340:720),tier=dangerAt(pt.x,pt.y),biome=biomeAtWorld(pt.x,pt.y),list=mobPoolForTier(tier,biome),type=forceType||list[(Math.random()*list.length)|0],def=mobDefs[type];if(!def)return;const scale=def.boss?1:1+Math.min(1.1,tier*.12+run/850);mobs.push({x:pt.x,y:pt.y,type,hp:def.hp*scale,max:def.hp*scale,ph:Math.random()*6.28,hit:0,contact:0,charge:0,chargeDir:0,seed:Math.random()*8,hop:Math.random(),elite:!def.boss&&tier>=2&&Math.random()<.06+tier*.018,telegraph:0})}
function spawnWanderer(){if(wanderers.length>=MAX_WANDERERS)return;const pt=safeSpawnAround(player.x,player.y,300,720),names=['Momo','Pip','Nori','Lulu','Bibi','Kiko','Mimi','Taro'];wanderers.push({id:'w'+Math.random(),name:names[(Math.random()*names.length)|0],x:pt.x,y:pt.y,hp:65+dangerAt(pt.x,pt.y)*12,max:65+dangerAt(pt.x,pt.y)*12,dir:Math.random()*6.28,hostile:false,hit:0,contact:0,think:Math.random()*2,weapon:weapons[Math.min(weapons.length-1,2+dangerAt(pt.x,pt.y)*2)],seed:Math.random()*8})}
function landmarkForCell(cx,cy){const r=hash(cx,cy,51);if(r<.48)return null;const x=(cx+.16+hash(cx,cy,52)*.68)*860,y=(cy+.16+hash(cx,cy,53)*.68)*860;if(blockedCircle(x,y,34))return null;const tier=dangerAt(x,y),eligible=landmarkDefs.map((d,i)=>({d,i})).filter(o=>o.d.tier<=tier+1),pick=eligible[Math.floor(hash(cx,cy,54)*eligible.length)]||eligible[0];return{id:cx+','+cy,x,y,type:pick.i,found:discovered.has(cx+','+cy),pulse:hash(cx,cy,55)*6.28}}
function refreshLandmarks(){landmarks.length=0;const cx=Math.floor(player.x/860),cy=Math.floor(player.y/860);for(let yy=cy-2;yy<=cy+2;yy++)for(let xx=cx-2;xx<=cx+2;xx++){const l=landmarkForCell(xx,yy);if(l)landmarks.push(l)}}
function regionName(x,y){const b=biomeNames[biomeAtWorld(x,y)],a=['Whispering','Little','Glimmer','Honey','Velvet','Moonlit','Silver','Dreaming','Hollow','Secret','Fallen','Starlit'],n=['Reach','Vale','Hollow','Wilds','Garden','March','Fields','Crossing','Basin','Glen','Frontier','Drift'];const rx=Math.floor(x/640),ry=Math.floor(y/640);return a[Math.floor(hash(rx,ry,91)*a.length)]+' '+b+' '+n[Math.floor(hash(rx,ry,92)*n.length)]}
function reset(){player={x:0,y:0,vx:0,vy:0,dir:0};mobs=[];wanderers=[];drops=[];landmarks=[];particles=[];shots=[];ambient=[];discovered.clear();run=0;kills=0;relics=0;level=1;xp=0;xpNeed=6;maxHp=48;hp=48;weapon=weapons[0];invuln=0;attackCd=.25;regenDelay=0;spawnShield=8;screenShake=0;bossTimer=72;worldEventTimer=36;regionCount=1;lastRegionKey='0,0';tutorialStep=0;hostileTarget=null;regionBanner='Gentle Meadow';regionBannerTimer=3;refreshLandmarks();for(let i=0;i<6;i++)spawnMob();spawnWanderer();drops.push({x:90,y:35,type:'weapon',weapon:weapons[2],t:120,bob:1,spawnGift:true});drops.push({x:-70,y:55,type:'food',t:90,bob:3,spawnGift:true});hud();updateCompass()}
