(() => {
'use strict';
const $=id=>document.getElementById(id);
const canvas=$('game'),ctx=canvas.getContext('2d'),pad=$('flightPad'),puck=$('padPuck');
const scoreEl=$('score'),hullEl=$('hull'),levelEl=$('level'),weaponEl=$('weapon');
const overlay=$('overlay'),overlayTitle=$('overlayTitle'),overlayText=$('overlayText'),routeChoice=$('routeChoice'),startBtn=$('startBtn');
ctx.imageSmoothingEnabled=false;
const W=canvas.width,H=canvas.height,TOP=28,BOTTOM=H-28;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),rand=(a,b)=>a+Math.random()*(b-a),pick=a=>a[(Math.random()*a.length)|0];
const hit=(a,b)=>a.x-a.w/2<b.x+b.w/2&&a.x+a.w/2>b.x-b.w/2&&a.y-a.h/2<b.y+b.h/2&&a.y+a.h/2>b.y-b.h/2;
const BIOMES={
 meadow:{name:'Cloudberry',sky1:'#10294f',sky2:'#67b6c8',ground:'#355b51',accent:'#b8ef9a',horizon:'#a9e6dd'},
 canyon:{name:'Ember',sky1:'#25162e',sky2:'#c55a47',ground:'#59342f',accent:'#ffd06c',horizon:'#ff9a69'},
 ruins:{name:'Ruins',sky1:'#0b1230',sky2:'#354467',ground:'#283650',accent:'#7ce6df',horizon:'#8fa5d8'},
 storm:{name:'Storm',sky1:'#0b1120',sky2:'#26394f',ground:'#1d2a3d',accent:'#d9efff',horizon:'#92b7d4'},
 nebula:{name:'Nebula',sky1:'#211132',sky2:'#70407c',ground:'#3a2148',accent:'#ffc0ef',horizon:'#c293df'}
};
const ROUTES=[['meadow','canyon'],['ruins','storm'],['nebula','canyon'],['storm','meadow'],['ruins','nebula']];
const WEAPONS={
 pulse:{name:'Pulse',symbol:'•',color:'#fff1a0',cool:.14,speed:800},
 rapid:{name:'Rapid',symbol:'»',color:'#7dffef',cool:.06,speed:1080},
 scatter:{name:'Scatter',symbol:'✣',color:'#ffb5e5',cool:.20,speed:640},
 wave:{name:'Wave',symbol:'≈',color:'#9fc5ff',cool:.12,speed:620},
 seeker:{name:'Seek',symbol:'◇',color:'#b7ff8c',cool:.27,speed:560},
 lance:{name:'Lance',symbol:'◆',color:'#ffd06e',cool:.38,speed:500},
 helix:{name:'Helix',symbol:'∞',color:'#bca8ff',cool:.13,speed:680},
 flak:{name:'Flak',symbol:'✹',color:'#ff9b77',cool:.30,speed:520},
 rail:{name:'Rail',symbol:'━',color:'#ffffff',cool:.24,speed:1280},
 drone:{name:'Drone',symbol:'⊙',color:'#7fffc3',cool:.18,speed:700}
};
const WEAPON_ORDER=Object.keys(WEAPONS);
const ENEMY={
 scout:{hp:1,w:28,h:18,v:198,pts:100,rate:2.0},zig:{hp:2,w:30,h:20,v:165,pts:190,rate:1.7},diver:{hp:2,w:31,h:20,v:152,pts:240,rate:99},
 turret:{hp:4,w:36,h:27,v:132,pts:350,rate:1.25},tank:{hp:8,w:48,h:33,v:108,pts:540,rate:1.5},mine:{hp:1,w:25,h:25,v:126,pts:180,rate:99},
 splitter:{hp:3,w:36,h:25,v:144,pts:320,rate:1.9},carrier:{hp:10,w:55,h:38,v:92,pts:780,rate:2.5},sniper:{hp:3,w:33,h:22,v:122,pts:390,rate:2.8},
 orbiter:{hp:2,w:28,h:28,v:138,pts:280,rate:1.8},guardian:{hp:5,w:40,h:31,v:114,pts:520,rate:1.7},rammer:{hp:3,w:32,h:23,v:130,pts:360,rate:99},
 swarm:{hp:1,w:19,h:14,v:230,pts:120,rate:2.8},bomber:{hp:5,w:42,h:30,v:112,pts:470,rate:2.2},phaser:{hp:3,w:31,h:22,v:146,pts:330,rate:1.9},
 skater:{hp:2,w:29,h:19,v:170,pts:260,rate:1.6},mortar:{hp:4,w:37,h:28,v:104,pts:430,rate:2.4},commander:{hp:6,w:44,h:33,v:100,pts:620,rate:1.5}
};
const COLORS={scout:'#a9ef8c',zig:'#ee9bd0',diver:'#ff7f8e',turret:'#8ce6de',tank:'#f2b96b',mine:'#ffca6e',splitter:'#c7a8ff',carrier:'#f6a86b',sniper:'#ff8f70',orbiter:'#9ab7ff',guardian:'#73c9ff',rammer:'#ff6d87',swarm:'#e7ff91',bomber:'#ffa86e',phaser:'#a7a2ff',skater:'#72e4ff',mortar:'#ffc07a',commander:'#fff0a0'};
const input={active:false,id:null,sx:0,sy:0,startX:150,startY:H/2,rawX:150,rawY:H/2,targetX:150,targetY:H/2,puckX:0,puckY:0};
let state,running=false,paused=false,raf=0,last=0,audioCtx=null;
const stars=Array.from({length:150},()=>({x:rand(0,W),y:rand(0,H),z:rand(.15,1),s:Math.random()<.82?1:2}));
function fresh(){return{score:0,hull:6,maxHull:6,level:1,biome:'meadow',time:0,sectionTime:0,shield:0,combo:0,comboT:0,shake:0,flash:0,hitStop:0,boss:false,bossObj:null,volley:0,waveId:0,groups:{},player:{x:150,y:H/2,w:32,h:20,cool:.1,inv:0,tilt:0,weapon:'pulse',weaponLevel:1},shots:[],enemyShots:[],enemies:[],terrain:[],powers:[],particles:[],popups:[],director:{waveAt:.8,terrainAt:3.6,powerAt:6.5,setAt:10,eliteAt:13,beat:0}}}
function updateHud(){const w=WEAPONS[state.player.weapon];scoreEl.textContent=state.score.toLocaleString();hullEl.textContent='♥'.repeat(Math.max(0,state.hull))+'♡'.repeat(Math.max(0,state.maxHull-state.hull));levelEl.textContent=state.level;weaponEl.textContent=`${w.symbol} ${w.name} ${'★'.repeat(state.player.weaponLevel)}`}
function resetInput(x=150,y=H/2){Object.assign(input,{active:false,id:null,startX:x,startY:y,rawX:x,rawY:y,targetX:x,targetY:y,puckX:0,puckY:0});pad.classList.remove('active');renderPuck()}
function reset(){state=fresh();resetInput();updateHud()}
function ensureAudio(){if(!audioCtx){const A=window.AudioContext||window.webkitAudioContext;if(A)audioCtx=new A()}if(audioCtx?.state==='suspended')audioCtx.resume()}
function sfx(f,d=.04,type='square',gain=.01,slide=0){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain(),n=audioCtx.currentTime;o.type=type;o.frequency.setValueAtTime(f,n);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(40,f+slide),n+d);g.gain.setValueAtTime(gain,n);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g).connect(audioCtx.destination);o.start(n);o.stop(n+d)}
function popup(text,x,y,color='#fff',t=.7){state.popups.push({text,x,y,color,t,max:t})}
function burst(x,y,color,n=10,speed=160){for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),v=rand(speed*.3,speed);state.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,t:rand(.2,.55),max:.55,color,size:pick([2,3,3,4])})}}
function begin(){ensureAudio();reset();running=true;paused=false;overlay.classList.add('hidden');last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);canvas.focus()}
function axis(v,dead=.02){const a=Math.abs(v);if(a<=dead)return 0;const t=clamp((a-dead)/(1-dead),0,1);return Math.sign(v)*Math.pow(t,.74)}
function renderPuck(){if(puck)puck.style.transform=`translate(calc(-50% + ${input.puckX*22}px),calc(-50% + ${input.puckY*46}px))`}
function updatePad(x,y){const r=pad.getBoundingClientRect(),nx=axis((x-input.sx)/Math.max(32,r.width*.54)),ny=axis((y-input.sy)/Math.max(58,r.height*.42));input.rawX=clamp(input.startX+nx*145,76,320);input.rawY=clamp(input.startY+ny*300,TOP+18,BOTTOM-18);input.puckX=clamp((x-input.sx)/Math.max(1,r.width*.31),-1,1);input.puckY=clamp((y-input.sy)/Math.max(1,r.height*.21),-1,1);renderPuck()}
function padDown(e){if(!running||paused||input.active)return;e.preventDefault();ensureAudio();input.active=true;input.id=e.pointerId;input.sx=e.clientX;input.sy=e.clientY;input.startX=state.player.x;input.startY=state.player.y;pad.classList.add('active');try{pad.setPointerCapture(e.pointerId)}catch{}}
function padMove(e){if(!input.active||e.pointerId!==input.id)return;e.preventDefault();updatePad(e.clientX,e.clientY)}
function padUp(e){if(!input.active||e.pointerId!==input.id)return;e.preventDefault();input.active=false;input.id=null;input.rawX=state.player.x;input.rawY=state.player.y;input.targetX=state.player.x;input.targetY=state.player.y;input.puckX=input.puckY=0;pad.classList.remove('active');renderPuck()}
function shot(x,y,vx,vy,w,h,d,color,extra={}){state.shots.push({x,y,vx,vy,w,h,d,color,age:0,...extra})}
function nearest(x,y,max=760,exclude=null){let best=null,bd=max;for(const e of state.enemies){if(e.dead||e===exclude||e.phaseInvisible)continue;const d=Math.hypot(e.x-x,e.y-y);if(d<bd){bd=d;best=e}}if(state.bossObj){const d=Math.hypot(state.bossObj.x-x,state.bossObj.y-y);if(d<bd)best=state.bossObj}return best}
function fire(){const p=state.player;if(p.cool>0)return;const l=p.weaponLevel,w=WEAPONS[p.weapon];state.volley++;
 if(p.weapon==='pulse'){const ys=l===1?[0]:l===2?[-6,6]:[-9,0,9],heavy=l===3&&state.volley%5===0;ys.forEach(y=>shot(p.x+22,p.y+y,w.speed,0,heavy?20:13,heavy?6:4,heavy?1.9:1,w.color,{pierce:heavy?2:0}))}
 else if(p.weapon==='rapid'){const ys=l===1?[0]:l===2?[-5,5]:[-8,0,8];ys.forEach((y,i)=>shot(p.x+22,p.y+y,w.speed+i*22,0,10,3,.55,w.color,{pierce:l===3&&state.volley%10===0?1:0}))}
 else if(p.weapon==='scatter'){const n=l===1?3:l===2?5:7;for(let i=0;i<n;i++){const a=(i-(n-1)/2)*.082;shot(p.x+20,p.y,w.speed,w.speed*a,10,4,.72,w.color)}}
 else if(p.weapon==='wave'){const lanes=l===1?[0]:l===2?[-8,8]:[-12,0,12];lanes.forEach((y,i)=>shot(p.x+20,p.y+y,w.speed,0,11,5,.75,w.color,{wave:true,amp:68+l*12,freq:8+i*.45,phase:i*2.2}))}
 else if(p.weapon==='seeker'){for(let i=0;i<l;i++)shot(p.x+20,p.y+(i-(l-1)/2)*10,w.speed,rand(-25,25),10,7,.9,w.color,{homing:true,turn:5+l*.35})}
 else if(p.weapon==='lance'){for(let i=0;i<(l===3?2:1);i++)shot(p.x+24,p.y+i*10,w.speed,0,22+l*5,10+l*2,2.7+l,w.color,{pierce:1+l,blast:32+l*9})}
 else if(p.weapon==='helix'){const n=l===1?2:l===2?3:4;for(let i=0;i<n;i++)shot(p.x+20,p.y,w.speed,0,10,5,.72,w.color,{wave:true,amp:45+15*l,freq:10,phase:i*Math.PI*2/n,pierce:l===3?1:0})}
 else if(p.weapon==='flak'){const n=l===1?1:l===2?2:3;for(let i=0;i<n;i++)shot(p.x+20,p.y+(i-(n-1)/2)*8,w.speed,rand(-35,35),12,8,1.1,w.color,{flak:true,blast:55+10*l,life:.65+.08*l})}
 else if(p.weapon==='rail'){const n=l===1?1:l===2?2:3;for(let i=0;i<n;i++)shot(p.x+24,p.y+(i-(n-1)/2)*7,w.speed,0,28,3,1.65,w.color,{pierce:3+l})}
 else if(p.weapon==='drone'){const offs=l===1?[0]:l===2?[-12,12]:[-16,0,16];offs.forEach((y,i)=>shot(p.x+18,p.y+y,w.speed,Math.sin(state.volley*.8+i)*60,9,6,.78,w.color,{homing:l>=2,turn:3.6+l*.3,orbitTrail:true}))}
 p.cool=Math.max(.04,w.cool-(l-1)*.014);sfx(p.weapon==='rapid'?1040:p.weapon==='lance'?180:p.weapon==='rail'?1250:650,.022,'square',.006,p.weapon==='lance'?-40:50)}
function award(points,x,y){state.combo=Math.min(20,state.combo+1);state.comboT=3;const g=Math.round(points*(1+state.combo*.06));state.score+=g;popup('+'+g,x,y,'#fff2a0');updateHud()}
function damage(n=1){const p=state.player;if(p.inv>0)return;if(state.shield>0){state.shield--;p.inv=.7;burst(p.x,p.y,'#73c9ff',14,170);sfx(180,.08,'triangle',.02,220);return}state.hull-=n;state.combo=0;p.inv=1.05;state.shake=14;state.flash=.1;burst(p.x,p.y,'#ff8c9e',18,210);sfx(90,.12,'sawtooth',.025,30);updateHud();if(state.hull<=0)gameOver()}
function spawnEnemy(type,x,y,extra={}){const e=ENEMY[type],elite=!!extra.elite;state.enemies.push({type,x,y,baseY:y,w:e.w,h:e.h,hp:e.hp*(elite?2:1),maxHp:e.hp*(elite?2:1),vx:-(e.v+state.level*7)*(elite?1.05:1),vy:0,t:rand(0,5),fire:rand(.6,1.3),rate:e.rate,pts:Math.round(e.pts*(elite?2.1:1)),flash:0,tele:0,elite,...extra})}
function group(n){const id='g'+(++state.waveId);state.groups[id]={left:n,clean:true};return id}
function wave(kind){const y=rand(95,H-95),L=state.level;
 if(kind==='line'){const g=group(6);for(let i=0;i<6;i++)spawnEnemy('scout',W+60+i*44,y+(i-2.5)*20,{group:g})}
 else if(kind==='vee'){const g=group(5);for(let i=0;i<5;i++)spawnEnemy(i===2?'zig':'scout',W+60+i*48,y+Math.abs(i-2)*34-35,{group:g})}
 else if(kind==='swarm'){const g=group(9);for(let i=0;i<9;i++)spawnEnemy('swarm',W+40+i*34,80+(i%3)*160,{group:g,phase:i*.8})}
 else if(kind==='divers'){spawnEnemy('diver',W+90,75);spawnEnemy('diver',W+155,H-75);if(L>3)spawnEnemy('diver',W+220,y)}
 else if(kind==='mines'){for(let i=0;i<6;i++)spawnEnemy('mine',W+70+i*72,85+(i%3)*150,{phase:i*.8})}
 else if(kind==='armor'){spawnEnemy('tank',W+90,y);spawnEnemy('turret',W+175,clamp(y-85,70,H-70));spawnEnemy('guardian',W+230,clamp(y+75,70,H-70))}
 else if(kind==='snipers'){spawnEnemy('sniper',W+90,115);spawnEnemy('sniper',W+180,H-115);spawnEnemy('skater',W+250,y)}
 else if(kind==='carrier'){spawnEnemy('carrier',W+100,y,{elite:L>=4});spawnEnemy('swarm',W+180,y-55);spawnEnemy('swarm',W+220,y+55)}
 else if(kind==='bombers'){spawnEnemy('bomber',W+90,130);spawnEnemy('bomber',W+190,H-130);spawnEnemy('mortar',W+270,y)}
 else if(kind==='phase'){spawnEnemy('phaser',W+90,120,{phase:0});spawnEnemy('phaser',W+170,H-120,{phase:2});spawnEnemy('orbiter',W+245,y)}
 else if(kind==='command'){spawnEnemy('commander',W+110,y);spawnEnemy('zig',W+180,y-70);spawnEnemy('zig',W+180,y+70);spawnEnemy('rammer',W+260,y)}
 else{spawnEnemy('splitter',W+90,y);spawnEnemy('splitter',W+170,clamp(y+95,80,H-80))}}
function chooseWave(){const L=state.level,p=['line','vee','swarm'];if(L>=2)p.push('divers','mines','bombers');if(L>=3)p.push('armor','snipers','split','phase');if(L>=4)p.push('carrier','command','bombers','phase');return pick(p)}
function spawnElite(){const pool=state.level<3?['zig','diver','bomber','skater']:['tank','sniper','guardian','phaser','commander','carrier'];spawnEnemy(pick(pool),W+100,rand(100,H-100),{elite:true})}
function tunnel(){const gap=rand(225,265)-state.level*4,w=rand(90,140),c=rand(145,H-145),speed=-(178+state.level*7),topH=c-gap/2,bY=c+gap/2,bH=H-bY;state.terrain.push({x:W+w/2,y:topH/2,w,h:topH,vx:speed,solid:true,type:'wall'});state.terrain.push({x:W+w/2,y:bY+bH/2,w,h:bH,vx:speed,solid:true,type:'wall'})}
function breakables(n=4){for(let i=0;i<n;i++){const r=rand(15,26);state.terrain.push({x:W+70+i*95,y:rand(75,H-75),w:r*2,h:r*2,r,vx:-(185+state.level*8),vy:rand(-20,20),solid:true,destructible:true,hp:2+Math.floor(state.level/2),spin:rand(0,6),type:state.biome==='canyon'?'rock':'crystal'})}}
function setPiece(){const b=state.biome,k=state.director.beat++%4;if(b==='meadow'){tunnel();wave(k%2?'swarm':'vee')}else if(b==='canyon'){breakables(6);wave(k%2?'bombers':'armor')}else if(b==='ruins'){tunnel();wave(k%2?'snipers':'phase')}else if(b==='storm'){wave(k%2?'command':'swarm');spawnElite()}else{wave(k%2?'phase':'carrier');breakables(3)}}
function unlocked(){return WEAPON_ORDER.slice(0,Math.min(WEAPON_ORDER.length,3+state.level*2))}
function power(x=W+30,y=rand(85,H-85),forced=null,weaponType=null){const r=Math.random(),kind=forced||(r<.7?'weapon':r<.84?'heal':r<.95?'shield':'score');if(kind==='weapon'&&!weaponType)weaponType=pick(unlocked());state.powers.push({kind,weaponType,x,y,w:29,h:29,vx:-125,vy:0,t:0})}
function powerColor(p){if(p.kind==='weapon')return WEAPONS[p.weaponType||'pulse'].color;return p.kind==='heal'?'#79ec8f':p.kind==='shield'?'#73c9ff':'#fff'}
function collect(p){if(p.kind==='heal')state.hull=Math.min(state.maxHull,state.hull+2);else if(p.kind==='shield')state.shield=Math.min(3,state.shield+1);else if(p.kind==='score')state.score+=2200;else{if(state.player.weapon===p.weaponType)state.player.weaponLevel=Math.min(3,state.player.weaponLevel+1);else{state.player.weapon=p.weaponType;state.player.weaponLevel=1}state.player.cool=0;popup(`${WEAPONS[p.weaponType].symbol}${state.player.weaponLevel===3?'✦':''}`,state.player.x,state.player.y-32,WEAPONS[p.weaponType].color,1)}burst(state.player.x,state.player.y,powerColor(p),15,150);sfx(560,.08,'triangle',.02,500);updateHud()}
function bullet(x,y,vx,vy,w=9,h=9,extra={}){state.enemyShots.push({x,y,vx,vy,w,h,grazed:false,...extra})}
function enemyFire(e){const p=state.player,base=Math.atan2(p.y-e.y,p.x-e.x),sp=158+state.level*7;if(e.type==='sniper'){e.tele=.75;e.aimY=p.y;return}if(e.type==='bomber'){bullet(e.x-15,e.y,-110,0,15,15,{bomb:true,t:.9});return}if(e.type==='mortar'){bullet(e.x-15,e.y,-125,(p.y-e.y)*.45,14,14,{bomb:true,t:1.1});return}const spread=e.type==='turret'?[-.15,0,.15]:e.type==='commander'?[-.18,-.06,.06,.18]:e.elite?[-.09,.09]:[0];for(const a of spread)bullet(e.x-12,e.y,Math.cos(base+a)*sp,Math.sin(base+a)*sp,e.type==='commander'?8:9,e.type==='commander'?8:9)}
function explodeBomb(sh){sh.dead=true;for(let i=0;i<8;i++){const a=i*Math.PI/4;bullet(sh.x,sh.y,Math.cos(a)*125,Math.sin(a)*125,8,8)}}
function groupKill(e){if(!e.group||!state.groups[e.group])return;const g=state.groups[e.group];g.left--;if(g.left<=0&&g.clean){award(850+state.level*180,state.player.x,state.player.y-40);if(Math.random()<.6)power(W+60,state.player.y,'weapon')}}
function killEnemy(e){if(e.dead)return;e.dead=true;groupKill(e);award(e.pts,e.x,e.y);burst(e.x,e.y,e.elite?'#fff1a0':COLORS[e.type]||'#fff',e.elite?22:12,e.elite?260:180);if(e.type==='splitter'){spawnEnemy('swarm',e.x,e.y-16,{vx:-240});spawnEnemy('swarm',e.x,e.y+16,{vx:-240})}if(e.type==='carrier'){spawnEnemy('swarm',e.x,e.y-25);spawnEnemy('swarm',e.x,e.y+25);power(e.x,e.y,'weapon')}else if(e.elite)power(e.x,e.y,'weapon');else if(Math.random()<.1)power(e.x,e.y);state.hitStop=Math.max(state.hitStop,e.elite?.05:.018);sfx(145,.06,'square',.012,-50)}
function spawnBoss(){state.boss=true;state.enemies=[];state.enemyShots=[];const hp=90+state.level*30;state.bossObj={x:W+140,y:H/2,w:125,h:96,hp,maxHp:hp,t:0,fire:.9,phase:0,mode:'normal'};state.flash=.14;sfx(110,.4,'square',.03,-20)}
function bossAttack(b){const p=state.player,L=state.level,ph=b.phase++%(L===5?4:3);if(ph===0){const base=Math.atan2(p.y-b.y,p.x-b.x);for(let i=-2-L%2;i<=2+L%2;i++){const a=base+i*.14;bullet(b.x-55,b.y,Math.cos(a)*(190+L*8),Math.sin(a)*(190+L*8),10,10)}}else if(ph===1){if(L===2||L===5){for(let i=0;i<12+L;i++){const a=i*Math.PI*2/(12+L)+b.t*.35;bullet(b.x-40,b.y,Math.cos(a)*(140+L*4),Math.sin(a)*(140+L*4),9,9)}}else if(L===3){for(let i=0;i<3;i++)spawnEnemy('phaser',b.x-90-i*35,b.y+(i-1)*65)}else if(L===4){for(let i=0;i<4;i++)spawnEnemy('rammer',b.x-70-i*40,80+i*120,{ram:.4})}else{for(let i=-2;i<=2;i++)bullet(b.x-50,b.y,-210,i*70)}}else if(ph===2){for(let i=-2;i<=2;i++)bullet(b.x-50,clamp(p.y+i*55,45,H-45),-235,0,16,6,{hot:true})}else{for(let i=0;i<5;i++)spawnEnemy(pick(['swarm','zig','orbiter']),b.x-60-i*35,80+i*90)}sfx(140,.04,'square',.012,70)}
function director(){const d=state.director,t=state.sectionTime;if(!state.boss&&t>=46){spawnBoss();return}if(state.boss)return;if(t>=d.eliteAt&&state.level>=2){spawnElite();d.eliteAt=t+rand(13,17)}if(t>=d.waveAt){wave(chooseWave());d.waveAt=t+rand(2.2,3.1)}if(t>=d.terrainAt){if(state.biome==='canyon'||state.biome==='nebula')breakables(3);else tunnel();d.terrainAt=t+rand(6.2,8)}if(t>=d.setAt){setPiece();d.setAt=t+rand(11,14)}if(t>=d.powerAt){power();d.powerAt=t+rand(8.5,11)}}
function updatePlayer(dt){const p=state.player;const tf=1-Math.exp(-18*dt);input.targetX+=(input.rawX-input.targetX)*tf;input.targetY+=(input.rawY-input.targetY)*tf;const sf=1-Math.exp(-20*dt),oy=p.y;p.x+=(input.targetX-p.x)*sf;p.y+=(input.targetY-p.y)*sf;p.x=clamp(p.x,76,320);p.y=clamp(p.y,TOP+18,BOTTOM-18);p.tilt=clamp((p.y-oy)/Math.max(.001,dt)/280,-1,1)}
function update(dt){const s=state,p=s.player;s.time+=dt;s.sectionTime+=dt;p.cool=Math.max(0,p.cool-dt);p.inv=Math.max(0,p.inv-dt);s.flash=Math.max(0,s.flash-dt);s.comboT-=dt;if(s.comboT<=0)s.combo=Math.max(0,s.combo-dt*1.7);updatePlayer(dt);fire();director();for(const st of stars){st.x-=(35+180*st.z)*dt;if(st.x<0){st.x=W;st.y=rand(0,H)}}
 for(const sh of s.shots){sh.age+=dt;if(sh.homing){const t=nearest(sh.x,sh.y);if(t){const des=Math.atan2(t.y-sh.y,t.x-sh.x),cur=Math.atan2(sh.vy,sh.vx);let diff=((des-cur+Math.PI*3)%(Math.PI*2))-Math.PI;const a=cur+clamp(diff,-sh.turn*dt,sh.turn*dt),sp=Math.hypot(sh.vx,sh.vy);sh.vx=Math.cos(a)*sp;sh.vy=Math.sin(a)*sp}}if(sh.wave)sh.vy=Math.sin(sh.age*sh.freq+sh.phase)*sh.amp;if(sh.flak&&sh.age>sh.life){const t=nearest(sh.x,sh.y,150);if(t){for(const e of s.enemies)if(!e.dead&&Math.hypot(e.x-sh.x,e.y-sh.y)<sh.blast)e.hp-=1.2;burst(sh.x,sh.y,sh.color,10,130);sh.dead=true}}sh.x+=sh.vx*dt;sh.y+=sh.vy*dt}
 for(const e of s.enemies){e.t+=dt;e.flash=Math.max(0,e.flash-dt);e.x+=e.vx*dt;if(e.type==='zig')e.y=e.baseY+Math.sin(e.t*5)*72;if(e.type==='skater'){e.y=e.baseY+Math.sin(e.t*7)*100}if(e.type==='swarm')e.y=e.baseY+Math.sin(e.t*6+(e.phase||0))*38;if(e.type==='orbiter'){e.y=e.baseY+Math.sin(e.t*3.2+(e.phase||0))*82;e.x+=Math.cos(e.t*2.1)*28*dt}if(e.type==='diver'){e.y+=(p.y-e.y)*1.15*dt;e.vx-=24*dt}if(e.type==='phaser'){const phase=(Math.floor(e.t*1.5)%4);e.phaseInvisible=phase===2;e.y=e.baseY+Math.sin(e.t*4)*70}if(e.type==='guardian')e.y=e.baseY+Math.sin(e.t*2.2)*42;if(e.type==='rammer'){e.ram=(e.ram??rand(.8,1.5))-dt;if(e.ram<=0&&e.x>p.x+120){e.ram=99;e.vx=-410;e.vy=(p.y-e.y)*1.5}e.y+=e.vy*dt}if(e.type==='commander'){for(const o of s.enemies)if(o!==e&&!o.dead&&Math.hypot(o.x-e.x,o.y-e.y)<120)o.fire-=dt*.35}if(e.type==='carrier'&&Math.floor(e.t)!==Math.floor(e.t-dt)&&e.x<W-80&&Math.random()<.28)spawnEnemy('swarm',e.x-25,e.y+rand(-28,28),{vx:-245});if(e.tele>0){e.tele-=dt;if(e.tele<=0){const a=Math.atan2((e.aimY??p.y)-e.y,p.x-e.x);bullet(e.x-12,e.y,Math.cos(a)*(245+s.level*6),Math.sin(a)*(245+s.level*6),15,6,{hot:true});e.fire=rand(2.2,3)}}else{e.fire-=dt;if(e.fire<=0&&!['diver','mine','rammer','swarm'].includes(e.type)&&e.x<W-50){enemyFire(e);if(e.type!=='sniper')e.fire=rand(.9,1.4)*e.rate}}}
 for(const sh of s.enemyShots){sh.x+=sh.vx*dt;sh.y+=sh.vy*dt;if(sh.bomb){sh.t-=dt;if(sh.t<=0)explodeBomb(sh)}}for(const o of s.terrain){o.x+=o.vx*dt;if(o.vy)o.y+=o.vy*dt;o.spin=(o.spin||0)+dt}for(const pw of s.powers){pw.t+=dt;const dx=p.x-pw.x,dy=p.y-pw.y,d=Math.hypot(dx,dy)||1;if(d<220){const f=(1-d/220)*620;pw.vx+=dx/d*f*dt;pw.vy+=dy/d*f*dt}pw.vx+=(-125-pw.vx)*Math.min(1,dt*2);pw.vy*=Math.pow(.1,dt);pw.x+=pw.vx*dt;pw.y+=pw.vy*dt+Math.sin(pw.t*4)*10*dt}
 if(s.bossObj){const b=s.bossObj;b.t+=dt;b.x+=(W-155-b.x)*Math.min(1,dt*1.8);b.y=H/2+Math.sin(b.t*(1.1+s.level*.06))*145;b.fire-=dt;if(b.fire<=0){bossAttack(b);b.fire=Math.max(.5,1.05-s.level*.045-(b.hp/b.maxHp<.4?.12:0))}}
 for(const sh of s.shots){for(const e of s.enemies){if(sh.dead||e.dead||e.phaseInvisible||!hit(sh,e))continue;let mult=1;if(e.type!=='guardian'&&s.enemies.some(g=>!g.dead&&g.type==='guardian'&&Math.hypot(g.x-e.x,g.y-e.y)<105))mult=.45;e.hp-=sh.d*mult;e.flash=.07;burst(sh.x,sh.y,sh.color,3,70);if(sh.blast&&e.hp<=0)for(const o of s.enemies)if(!o.dead&&Math.hypot(o.x-e.x,o.y-e.y)<sh.blast)o.hp-=sh.d*.55;if(!sh.pierce||--sh.pierce<0)sh.dead=true;if(e.hp<=0)killEnemy(e)}for(const o of s.terrain){if(sh.dead||o.dead||!o.destructible||!hit(sh,o))continue;o.hp-=sh.d;if(!sh.pierce||--sh.pierce<0)sh.dead=true;if(o.hp<=0){o.dead=true;award(180+s.level*30,o.x,o.y);burst(o.x,o.y,'#ffd37b',14,220)}}if(s.bossObj&&!sh.dead&&hit(sh,s.bossObj)){s.bossObj.hp-=sh.d;if(!sh.pierce||--sh.pierce<0)sh.dead=true;if(s.bossObj.hp<=0){award(6000*s.level,s.bossObj.x,s.bossObj.y);burst(s.bossObj.x,s.bossObj.y,'#fff',60,360);s.bossObj=null;finishLevel();return}}}
 for(const e of s.enemies)if(!e.dead&&hit(p,e)){e.dead=true;damage(e.type==='tank'||e.type==='carrier'||e.elite?2:1)}for(const sh of s.enemyShots)if(!sh.dead&&hit(p,sh)){sh.dead=true;damage(1)}for(const o of s.terrain)if(!o.dead&&o.solid&&hit(p,o))damage(1);for(const pw of s.powers)if(!pw.dead&&hit(p,pw)){pw.dead=true;collect(pw)}if(s.bossObj&&hit(p,s.bossObj))damage(2);
 for(const q of s.particles){q.t-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=Math.pow(.05,dt);q.vy*=Math.pow(.05,dt)}for(const q of s.popups){q.t-=dt;q.y-=26*dt}s.shots=s.shots.filter(o=>!o.dead&&o.x<W+120&&o.y>-100&&o.y<H+100);s.enemies=s.enemies.filter(o=>!o.dead&&o.x>-130&&o.y>-150&&o.y<H+150);s.enemyShots=s.enemyShots.filter(o=>!o.dead&&o.x>-90&&o.x<W+90&&o.y>-90&&o.y<H+90);s.terrain=s.terrain.filter(o=>!o.dead&&o.x+(o.w||40)/2>-90);s.powers=s.powers.filter(o=>!o.dead&&o.x>-90);s.particles=s.particles.filter(o=>o.t>0);s.popups=s.popups.filter(o=>o.t>0);updateHud()}
function finishLevel(){running=false;cancelAnimationFrame(raf);state.boss=false;if(state.level>=5){overlayTitle.textContent='★ ★ ★';overlayText.textContent=state.score.toLocaleString();routeChoice.classList.add('hidden');startBtn.classList.remove('hidden');overlay.classList.remove('hidden');return}routeChoice.innerHTML='';routeChoice.classList.remove('hidden');for(const k of ROUTES[state.level-1]){const b=document.createElement('button');b.textContent=BIOMES[k].name;b.style.borderColor=BIOMES[k].accent;b.onclick=()=>nextLevel(k);routeChoice.appendChild(b)}overlayTitle.textContent='◆';overlayText.textContent='';startBtn.classList.add('hidden');overlay.classList.remove('hidden')}
function nextLevel(k){state.level++;state.biome=k;state.sectionTime=0;state.boss=false;state.bossObj=null;state.enemyShots=[];state.enemies=[];state.terrain=[];state.powers=[];state.groups={};state.director={waveAt:1,terrainAt:3,powerAt:5.8,setAt:9,eliteAt:12,beat:0};state.player.x=150;state.player.y=H/2;state.player.inv=1.3;state.hull=Math.min(state.maxHull,state.hull+1);state.score+=1000*state.level;resetInput();const u=unlocked();power(W+110,H/2,'weapon',u[Math.min(u.length-1,state.level*2)]);routeChoice.classList.add('hidden');overlay.classList.add('hidden');running=true;last=performance.now();raf=requestAnimationFrame(loop);updateHud()}
function gameOver(){running=false;cancelAnimationFrame(raf);overlayTitle.textContent='×';overlayText.textContent=state.score.toLocaleString();startBtn.classList.remove('hidden');routeChoice.classList.add('hidden');overlay.classList.remove('hidden')}
function drawBackground(){const b=BIOMES[state.biome],g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,b.sky1);g.addColorStop(1,b.sky2);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';for(const st of stars){ctx.globalAlpha=.2+.8*st.z;ctx.fillRect(st.x,st.y,st.s,st.s)}ctx.globalAlpha=1;ctx.fillStyle=b.horizon;ctx.globalAlpha=.18;const off=(state.time*30)%110;for(let x=-off;x<W+110;x+=110){const h=28+((x/110|0)%3)*18;ctx.fillRect(x,H*.63-h,48,h)}ctx.globalAlpha=1;ctx.fillStyle=b.ground;ctx.fillRect(0,0,W,TOP);ctx.fillRect(0,BOTTOM,W,H-BOTTOM);ctx.fillStyle=b.accent;for(let x=-((state.time*150)%64);x<W;x+=64){ctx.fillRect(x,TOP-5,34,4);ctx.fillRect(x+24,BOTTOM+1,34,4)}}
function drawShip(){const p=state.player;ctx.save();ctx.translate(Math.round(p.x),Math.round(p.y));ctx.rotate(p.tilt*.12);ctx.fillStyle='#4e6b93';ctx.fillRect(-16,-8,22,16);ctx.fillStyle='#dff8ff';ctx.fillRect(-10,-10,19,20);ctx.fillRect(5,-5,14,10);ctx.fillStyle='#65d8ff';ctx.fillRect(-2,-6,12,12);ctx.fillStyle='#24304f';ctx.fillRect(11,-2,10,4);ctx.fillStyle='#94e9ff';ctx.beginPath();ctx.moveTo(-5,-7);ctx.lineTo(-18,-16);ctx.lineTo(-11,-3);ctx.fill();ctx.beginPath();ctx.moveTo(-5,7);ctx.lineTo(-18,16);ctx.lineTo(-11,3);ctx.fill();ctx.fillStyle='#ffd46a';const f=6+Math.floor(Math.random()*5);ctx.fillRect(-22-f,-6,8+f,4);ctx.fillRect(-22-f,2,8+f,4);if(state.shield>0){ctx.strokeStyle='#73c9ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,25,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(Math.round(e.x),Math.round(e.y));ctx.globalAlpha=e.phaseInvisible?.22:1;const c=e.flash>0?'#fff':COLORS[e.type]||'#fff';ctx.fillStyle=c;if(['mine','orbiter'].includes(e.type)){ctx.rotate(e.t);ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=i%2?7:14,px=Math.cos(a)*r,py=Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(-3,-3,6,6)}else{ctx.beginPath();ctx.moveTo(e.w/2,0);ctx.lineTo(-e.w*.22,-e.h/2);ctx.lineTo(-e.w/2,-e.h*.3);ctx.lineTo(-e.w*.35,0);ctx.lineTo(-e.w/2,e.h*.3);ctx.lineTo(-e.w*.22,e.h/2);ctx.closePath();ctx.fill();ctx.fillStyle='#1d2946';ctx.fillRect(-e.w*.18,-3,e.w*.42,6);ctx.fillStyle='#fff';ctx.fillRect(e.w*.13,-2,4,4)}if(e.type==='guardian'){ctx.strokeStyle='#73c9ff';ctx.globalAlpha=.35;ctx.beginPath();ctx.arc(0,0,105,0,Math.PI*2);ctx.stroke()}if(e.elite){ctx.strokeStyle='#fff1a0';ctx.lineWidth=2;ctx.strokeRect(-e.w/2-5,-e.h/2-5,e.w+10,e.h+10)}if(e.tele>0){ctx.strokeStyle='#fff1a0';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-15,0);ctx.lineTo(-110,(e.aimY??e.y)-e.y);ctx.stroke()}ctx.restore()}
function drawTerrain(o){const b=BIOMES[state.biome];ctx.save();if(o.type==='wall'){ctx.fillStyle=b.ground;ctx.fillRect(o.x-o.w/2,o.y-o.h/2,o.w,o.h);ctx.fillStyle=b.accent;for(let y=o.y-o.h/2+12;y<o.y+o.h/2;y+=24)ctx.fillRect(o.x-o.w/2+8,y,o.w-16,3)}else{ctx.translate(o.x,o.y);ctx.rotate(o.spin||0);ctx.fillStyle=o.type==='crystal'?b.accent:'#9a684b';ctx.beginPath();ctx.moveTo(0,-o.h/2);ctx.lineTo(o.w/2,-o.h*.12);ctx.lineTo(o.w*.34,o.h/2);ctx.lineTo(-o.w*.42,o.h*.34);ctx.lineTo(-o.w/2,-o.h*.2);ctx.closePath();ctx.fill()}ctx.restore()}
function drawPower(p){const c=powerColor(p);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.t*.7);ctx.fillStyle='#0d1530';ctx.strokeStyle=c;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-14);ctx.lineTo(14,0);ctx.lineTo(0,14);ctx.lineTo(-14,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.rotate(-p.t*.7);ctx.fillStyle=c;if(p.kind==='weapon'){ctx.font='bold 14px monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(WEAPONS[p.weaponType].symbol,0,1)}else if(p.kind==='heal'){ctx.fillRect(-2,-8,4,16);ctx.fillRect(-8,-2,16,4)}else if(p.kind==='shield'){ctx.strokeRect(-6,-6,12,12)}else ctx.fillRect(-4,-4,8,8);ctx.restore()}
function drawShot(sh){ctx.save();ctx.fillStyle=sh.color;ctx.globalAlpha=.35;ctx.fillRect(sh.x-sh.w*1.7,sh.y-sh.h/2,sh.w*1.5,sh.h);ctx.globalAlpha=1;ctx.fillRect(sh.x-sh.w/2,sh.y-sh.h/2,sh.w,sh.h);ctx.restore()}
function drawEnemyShot(sh){ctx.save();ctx.fillStyle=sh.hot?'#fff0a8':sh.bomb?'#ff9f6e':'#ff6f93';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=8;ctx.beginPath();ctx.arc(sh.x,sh.y,Math.max(sh.w,sh.h)/2,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawBoss(b){const cols=[['#9df2ca','#dff8ff'],['#ff9a62','#ffd36e'],['#a9b5ff','#8ce6de'],['#8fd9ff','#fff1a0'],['#ff9ee8','#c7a8ff']][state.level-1];ctx.save();ctx.translate(b.x,b.y);ctx.fillStyle=cols[0];ctx.beginPath();ctx.moveTo(60,0);ctx.lineTo(22,-42);ctx.lineTo(-55,-34);ctx.lineTo(-72,0);ctx.lineTo(-55,34);ctx.lineTo(22,42);ctx.closePath();ctx.fill();ctx.fillStyle=cols[1];ctx.fillRect(-18,-52,30,104);ctx.fillStyle='#1d2946';ctx.beginPath();ctx.arc(4,0,19,0,Math.PI*2);ctx.fill();ctx.fillStyle=cols[1];ctx.beginPath();ctx.arc(4,0,10+Math.sin(b.t*6)*2,0,Math.PI*2);ctx.fill();ctx.restore();ctx.fillStyle='#10162acc';ctx.fillRect(W-350,18,320,14);ctx.fillStyle=cols[1];ctx.fillRect(W-348,20,316*(b.hp/b.maxHp),10)}
function draw(){const sx=state.shake?(Math.random()-.5)*state.shake:0,sy=state.shake?(Math.random()-.5)*state.shake:0;state.shake*=.88;ctx.save();ctx.translate(sx,sy);drawBackground();for(const o of state.terrain)drawTerrain(o);for(const p of state.powers)drawPower(p);for(const sh of state.shots)drawShot(sh);for(const sh of state.enemyShots)drawEnemyShot(sh);for(const e of state.enemies)drawEnemy(e);if(state.bossObj)drawBoss(state.bossObj);for(const q of state.particles){ctx.globalAlpha=clamp(q.t/q.max,0,1);ctx.fillStyle=q.color;ctx.fillRect(q.x-q.size/2,q.y-q.size/2,q.size,q.size)}ctx.globalAlpha=1;if(state.player.inv<=0||Math.floor(state.player.inv*16)%2===0)drawShip();for(const q of state.popups){ctx.globalAlpha=clamp(q.t/q.max,0,1);ctx.fillStyle=q.color;ctx.font='bold 13px monospace';ctx.textAlign='center';ctx.fillText(q.text,q.x,q.y)}ctx.globalAlpha=1;if(state.flash>0){ctx.fillStyle='#ffffff55';ctx.fillRect(0,0,W,H)}if(paused){ctx.fillStyle='#0009';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='bold 34px monospace';ctx.textAlign='center';ctx.fillText('Ⅱ',W/2,H/2)}ctx.restore()}
function loop(now){if(!running)return;const dt=Math.min(.033,(now-last)/1000||0);last=now;if(!paused){if(state.hitStop>0)state.hitStop-=dt;else update(dt)}draw();if(running)raf=requestAnimationFrame(loop)}
pad.addEventListener('pointerdown',padDown,{passive:false});pad.addEventListener('pointermove',padMove,{passive:false});pad.addEventListener('pointerup',padUp,{passive:false});pad.addEventListener('pointercancel',padUp,{passive:false});
canvas.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','p'].includes(k))e.preventDefault();if(k==='p'){paused=!paused;return}const dx=(k==='arrowright'||k==='d'?1:k==='arrowleft'||k==='a'?-1:0),dy=(k==='arrowdown'||k==='s'?1:k==='arrowup'||k==='w'?-1:0);input.rawX=clamp(input.rawX+dx*18,76,320);input.rawY=clamp(input.rawY+dy*28,TOP+18,BOTTOM-18)});
startBtn.addEventListener('click',begin);reset();draw();
})();