const fs=require('fs'),vm=require('vm'),zlib=require('zlib'),transform=require('./v10-polish8.js');
class CL{constructor(){this.s=new Set()}add(...v){v.forEach(x=>this.s.add(x))}remove(...v){v.forEach(x=>this.s.delete(x))}contains(v){return this.s.has(v)}}
class El{constructor(id=''){this.id=id;this.textContent='';this._html='';this.className='';this.classList=new CL();this.children=[];this.style={};this.listeners={};this.width=960;this.height=540}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(t,fn){(this.listeners[t]||(this.listeners[t]=[])).push(fn)}appendChild(c){this.children.push(c)}click(){const e={clientX:0,clientY:0};for(const f of(this.listeners.click||[]))f(e);if(this.onclick)this.onclick(e)}dispatch(t,e){for(const f of(this.listeners[t]||[]))f(e||{})}getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}}
const ids=['game','overlay','overlayTitle','overlayText','eyebrow','choiceGrid','startBtn','skinBtn','soundBtn','metaSummary','hudTime','hudSector','hudHull','hudShield','laserStatus','laserFill','threatStatus','threatFill','upgradeStatus','upgradeFill','buildChips'];const el=Object.fromEntries(ids.map(id=>[id,new El(id)]));
const gradient=()=>({addColorStop(){}});const ctx={imageSmoothingEnabled:true,fillStyle:'',strokeStyle:'',shadowColor:'',shadowBlur:0,lineWidth:1,font:'',textAlign:'',globalAlpha:1,createLinearGradient:gradient,createRadialGradient:gradient,fillRect(){},strokeRect(){},beginPath(){},arc(){},fill(){},stroke(){},save(){},restore(){},translate(){},rotate(){},moveTo(){},lineTo(){},closePath(){},fillText(){}};el.game.getContext=()=>ctx;
const choicePanel=new El('choicePanel');const document={getElementById:id=>el[id],createElement:tag=>new El(tag),querySelector:sel=>sel==='.choice-panel'?choicePanel:null};let raf=[],now=0;const requestAnimationFrame=fn=>(raf.push(fn),raf.length),cancelAnimationFrame=()=>{};const localStorage={m:{},getItem(k){return this.m[k]||null},setItem(k,v){this.m[k]=String(v)}};const initialSeed=(Number(process.env.STARWARD_SEED)||123456789)>>>0;let seed=initialSeed;const gameMath=Object.create(Math);gameMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const window={matchMedia:()=>({matches:false})};const sandbox={document,window,localStorage,requestAnimationFrame,cancelAnimationFrame,performance:{now:()=>now},Math:gameMath,console};vm.createContext(sandbox);
const splitLines=s=>s.match(/[^\n]*\n|[^\n]+$/g)||[],base=fs.readFileSync(__dirname+'/game.js','utf8'),parts=fs.readdirSync(__dirname+'/runtime_v9_patch').filter(f=>/^patch-\d+\.b64$/.test(f)).sort().map(f=>fs.readFileSync(__dirname+'/runtime_v9_patch/'+f,'utf8').trim()).join(''),ops=JSON.parse(zlib.gunzipSync(Buffer.from(parts,'base64')).toString('utf8')),lines=splitLines(base),out=[];for(const op of ops){if(op[0]==='=')out.push(lines.slice(op[1],op[2]).join(''));else out.push(op[1]);}
function balance(source){let n=0;source=source.replace(/const ENEMIES\s*=\s*\{[\s\S]*?\n\};/,b=>b.replace(/\bhp:(\d+(?:\.\d+)?)/g,(_,v)=>{n++;return `hp:${Math.round(Number(v)*1.75*100)/100}`;}));source=source.replace(/S\.focusTimer=7\b/g,'S.focusTimer=8').replace(/for 7 seconds/g,'for 8 seconds');const a='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.25:1;',b='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.65:1;';if(!source.includes(a)||n<5)throw Error('balance hooks missing');return source.replace(a,b);}
const source=transform.apply(balance(out.join('')));for(const t of ['aaa8BestTouchTarget','aaa8ClaimTarget','COMMAND GRADE','AAA7_STAGGER'])if(!source.includes(t))throw Error('V10.10 source missing '+t);vm.runInContext(source,sandbox);if(!window.__STARWARD__?.aaa8State||!window.__STARWARD__?.aaa8BestTouchTarget||!window.__STARWARD__?.aaa8Grade)throw Error('V10.10 hooks missing');
el.startBtn.click();for(let i=0;i<5;i++){const card=el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Dodging|Engines|Armor|Balanced Systems|Fortress Doctrine/i.test(c.innerHTML))||el.choiceGrid.children[0];card.click();}
let overlap=false,pulse=false,clarity=false,gradeValid=false,eventProtected=false,paused=0;
for(let frame=0;frame<9000;frame++){
  if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);const s=window.__STARWARD__.getState(),a=window.__STARWARD__.aaa8State();
  if(!overlap&&s.time>14){const low=window.__STARWARD__.spawnElite('scout','armored'),high=window.__STARWARD__.spawnElite('healer','commander');if(low&&high){low.x=620;low.y=260;high.x=626;high.y=262;const best=window.__STARWARD__.aaa8BestTouchTarget(623,261);overlap=best===high;window.__STARWARD__.aaa8ClaimTarget(high);pulse=!!window.__STARWARD__.aaa8State()?.lockPulse&&s.focusTarget===high&&s.focusTimer>=7.9;}}
  if(!eventProtected&&s.time>22){window.__STARWARD__.forceEvent('overdrive');const before=s.liveEvent;const target=s.enemies.find(e=>e.hp>0);if(before&&target){const acceptedBefore=window.__STARWARD__.aaa4State?.()?.eventAccepts||0;el.game.dispatch('pointerdown',{clientX:target.x+Math.min(30,target.size+10),clientY:target.y});const acceptedAfter=window.__STARWARD__.aaa4State?.()?.eventAccepts||0;eventProtected=acceptedAfter===acceptedBefore;}}
  if(!clarity&&s.time>30){for(let i=0;i<50&&s.enemies.length<60;i++){const e=window.__STARWARD__.spawnElite(i%7===0?'healer':'scout',i%5===0?'shielded':'armored');if(e){e.x=620+(i%5)*16;e.y=80+(i%18)*22;}}for(let i=0;i<190;i++)s.bullets.push({x:800,y:100+(i%300),vx:-100,vy:0,damage:1,life:2});if(raf.length){const f=raf.shift();now+=16.666;f(now);}clarity=!!window.__STARWARD__.aaa8State()?.clarity;}
  const g=window.__STARWARD__.aaa8Grade();gradeValid=/^[SABCD]$/.test(g.letter)&&Number.isFinite(g.score)&&g.score>=0;
  if(frame%100===0)el.game.dispatch('pointerdown',{clientX:168,clientY:s.ship.y});
  if(!el.overlay.classList.contains('hidden')&&!el.choiceGrid.classList.contains('hidden')&&el.choiceGrid.children.length===3){paused++;(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Dodging|Engines|Armor|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click();}
  if(s.phase==='dead')break;
}
let s=window.__STARWARD__.getState(),a=window.__STARWARD__.aaa8State();if(s.time<75)throw Error(`V10.10 run too short ${s.time.toFixed(1)}s`);if(!overlap)throw Error('Priority overlap resolution failed');if(!pulse)throw Error('Precision lock pulse/acquisition failed');if(!eventProtected)throw Error('Target-sized tap accidentally accepted live event');if(!clarity)throw Error('Clarity governor never activated');if(!gradeValid)throw Error('Command grade invalid');if(!a||a.precisionLocks<1||a.clarityFrames<1)throw Error('V10.10 telemetry invalid');if(paused>7)throw Error(`Too many blocking choices ${paused}`);
if(s.phase==='running'){window.__STARWARD__.endRun();for(let i=0;i<180&&raf.length;i++){const f=raf.shift();now+=16.666;f(now);if(window.__STARWARD__.getState().phase==='dead')break;}}
s=window.__STARWARD__.getState();if(!/COMMAND GRADE/.test(el.overlayText.innerHTML))throw Error('Command grade result missing');const g=window.__STARWARD__.aaa8Grade();console.log(`Starward V10.10 precision seed ${initialSeed} OK: ${s.time.toFixed(1)}s, locks ${a.precisionLocks}, corrected ${a.correctedLocks}, clarity ${a.clarityFrames}, grade ${g.letter}/${g.score}`);
