const fs=require('fs'),vm=require('vm'),zlib=require('zlib'),transform=require('./v12-aim-controls.js');
class CL{constructor(){this.s=new Set()}add(...v){v.forEach(x=>this.s.add(x))}remove(...v){v.forEach(x=>this.s.delete(x))}contains(v){return this.s.has(v)}}
class El{
  constructor(id=''){this.id=id;this.textContent='';this._html='';this.className='';this.classList=new CL();this.children=[];this.style={};this.listeners={};this.width=960;this.height=540;}
  set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}
  addEventListener(t,fn,opt){(this.listeners[t]||(this.listeners[t]=[])).push({fn,capture:opt===true||!!opt?.capture})}
  removeEventListener(t,fn){if(!this.listeners[t])return;this.listeners[t]=this.listeners[t].filter(x=>x.fn!==fn)}
  appendChild(c){this.children.push(c)}
  click(){this.dispatch('click',{clientX:0,clientY:0,pointerId:1})}
  dispatch(t,e={}){let stopped=false;e.preventDefault=e.preventDefault||(()=>{});e.stopImmediatePropagation=e.stopImmediatePropagation||(()=>{stopped=true});const list=[...(this.listeners[t]||[])].sort((a,b)=>Number(b.capture)-Number(a.capture));for(const item of list){item.fn(e);if(stopped)break;}if(!stopped&&this.onclick)this.onclick(e)}
  getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}
  setPointerCapture(){}releasePointerCapture(){}
}
const ids=['game','overlay','overlayTitle','overlayText','eyebrow','choiceGrid','startBtn','skinBtn','soundBtn','laserButton','metaSummary','hudTime','hudSector','hudHull','hudShield','laserStatus','laserFill','threatStatus','threatFill','upgradeStatus','upgradeFill','buildChips'];
const el=Object.fromEntries(ids.map(id=>[id,new El(id)]));
const drawText=[];const gradient=()=>({addColorStop(){}});const ctx={imageSmoothingEnabled:true,fillStyle:'',strokeStyle:'',shadowColor:'',shadowBlur:0,lineWidth:1,font:'',textAlign:'',globalAlpha:1,createLinearGradient:gradient,createRadialGradient:gradient,fillRect(){},strokeRect(){},beginPath(){},arc(){},fill(){},stroke(){},save(){},restore(){},translate(){},rotate(){},moveTo(){},lineTo(){},closePath(){},fillText(t){drawText.push(String(t))},setLineDash(){}};el.game.getContext=()=>ctx;
const choicePanel=new El('choicePanel');const document={getElementById:id=>el[id],createElement:tag=>new El(tag),querySelector:sel=>sel==='.choice-panel'?choicePanel:null};
let raf=[],now=0;const requestAnimationFrame=fn=>(raf.push(fn),raf.length),cancelAnimationFrame=()=>{};const localStorage={m:{},getItem(k){return this.m[k]||null},setItem(k,v){this.m[k]=String(v)}};
const initialSeed=(Number(process.env.STARWARD_SEED)||123456789)>>>0;let seed=initialSeed;const gameMath=Object.create(Math);gameMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const window={matchMedia:()=>({matches:false})};const sandbox={document,window,localStorage,requestAnimationFrame,cancelAnimationFrame,performance:{now:()=>now},Math:gameMath,console};vm.createContext(sandbox);
const splitLines=s=>s.match(/[^\n]*\n|[^\n]+$/g)||[],base=fs.readFileSync(__dirname+'/game.js','utf8'),parts=fs.readdirSync(__dirname+'/runtime_v9_patch').filter(f=>/^patch-\d+\.b64$/.test(f)).sort().map(f=>fs.readFileSync(__dirname+'/runtime_v9_patch/'+f,'utf8').trim()).join(''),ops=JSON.parse(zlib.gunzipSync(Buffer.from(parts,'base64')).toString('utf8')),lines=splitLines(base),out=[];for(const op of ops){if(op[0]==='=')out.push(lines.slice(op[1],op[2]).join(''));else out.push(op[1]);}
function balance(source){let n=0;source=source.replace(/const ENEMIES\s*=\s*\{[\s\S]*?\n\};/,b=>b.replace(/\bhp:(\d+(?:\.\d+)?)/g,(_,v)=>{n++;return `hp:${Math.round(Number(v)*1.75*100)/100}`;}));source=source.replace(/S\.focusTimer=7\b/g,'S.focusTimer=8').replace(/for 7 seconds/g,'for 8 seconds');const a='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.25:1;',b='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.65:1;';if(!source.includes(a)||n<5)throw Error('balance hooks missing');return source.replace(a,b);}
const source=transform.apply(balance(out.join('')));for(const term of ['V12_DECISION_GAP=38','v12SetAim','v12ResolveShotdowns','POWER CACHE DETECTED','v12EventLines','v12AppendResults','AIM CONTROL'])if(!source.includes(term))throw Error('V12 source missing '+term);vm.runInContext(source,sandbox);
if(!window.__STARWARD__?.v12State||!window.__STARWARD__?.v12SetAim||!window.__STARWARD__?.v12SpawnPowerup||!window.__STARWARD__?.v12EventAcceptRect)throw Error('V12 debug hooks missing');if(!(el.laserButton.listeners.click||[]).length)throw Error('Dedicated Star Laser button not registered');
el.startBtn.click();for(let i=0;i<5;i++){if(el.choiceGrid.children.length!==3)throw Error(`Opening draft ${i+1} broken`);(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Aim|Projectile|Armor|Balanced|Fortress/i.test(c.innerHTML))||el.choiceGrid.children[0]).click();}
let state=window.__STARWARD__.getState();if(state.phase!=='running')throw Error('Run did not start');
state.cooldowns={};window.__STARWARD__.v12SetAim(700,105);const beforeUp=state.shots.length;window.__STARWARD__.v12FireTick();const up=state.shots.slice(beforeUp).find(s=>s.v12Manual);if(!up||!(up.vy<-20))throw Error('Upward manual aiming failed');
state.cooldowns={};window.__STARWARD__.v12SetAim(700,435);const beforeDown=state.shots.length;window.__STARWARD__.v12FireTick();const down=state.shots.slice(beforeDown).find(s=>s.v12Manual);if(!down||!(down.vy>20))throw Error('Downward manual aiming failed');
window.__STARWARD__.v12ReleaseAim();state.cooldowns={};const beforeForward=state.shots.length;window.__STARWARD__.v12FireTick();const forward=state.shots.slice(beforeForward).find(s=>s.v12Manual);if(!forward||Math.abs(forward.vy)>15)throw Error('Release-to-forward fire failed');
const power=window.__STARWARD__.v12SpawnPowerup('rapid',state.ship.y,state.ship.x+250);if(!power||!window.__STARWARD__.v12CollectPowerup(power)||!(window.__STARWARD__.v12State().buffs.rapid>0))throw Error('Power-core collection failed');
const vBefore=window.__STARWARD__.v12State().shotdowns;state.bullets.push({x:430,y:270,vx:-100,vy:0,damage:1,life:4,hot:false});state.shots.push({x:430,y:270,vx:500,vy:0,damage:1,life:2,pierce:0,trail:[],kind:'pulse',color:'#fff'});window.__STARWARD__.v12ResolveShotdowns();if(!(window.__STARWARD__.v12State().shotdowns>vBefore))throw Error('Projectile interception failed');
if(!window.__STARWARD__.forceEvent('overdrive'))throw Error('Could not force live event');state=window.__STARWARD__.getState();const body=state.liveEvent.body,joined=window.__STARWARD__.v12EventLines().join(' '),tail=body.split(/\s+/).slice(-4).join(' ');if(!joined.includes(tail))throw Error(`Live event text still truncated: missing "${tail}"`);
el.game.dispatch('pointerdown',{clientX:520,clientY:120,pointerId:7});if(!window.__STARWARD__.getState().liveEvent)throw Error('Aiming accidentally accepted live event');const accept=window.__STARWARD__.v12EventAcceptRect();el.game.dispatch('pointerdown',{clientX:accept.x+accept.w/2,clientY:accept.y+accept.h/2,pointerId:8});if(window.__STARWARD__.getState().liveEvent)throw Error('Dedicated live-event ACCEPT zone failed');
state=window.__STARWARD__.getState();state.time=Math.max(state.time,31);state.laserCharge=state.laserMax;state.nextLaserAt=0;const lasersBefore=state.laserTimes.length;el.laserButton.click();if(state.laserTimes.length!==lasersBefore+1)throw Error('Star Laser button failed');
let paused=0,eventSeen=false,powerSeen=false,peak=0,laneError=0;window.__STARWARD__.v12SetAim(760,270);
for(let frame=0;frame<7800;frame++){
  if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);state=window.__STARWARD__.getState();if(state.phase==='dead')break;peak=Math.max(peak,state.enemies.length);laneError=Math.max(laneError,Math.abs(state.ship.y-270));const v=window.__STARWARD__.v12State();if(v?.powerups?.length)powerSeen=true;if(state.liveEvent)eventSeen=true;
  if(frame%18===0){const target=state.boss||state.enemies.filter(e=>e.hp>0).sort((a,b)=>(b.aaaCapital?1:0)-(a.aaaCapital?1:0)||a.x-b.x)[0];if(target)window.__STARWARD__.v12SetAim(target.x,target.y);else window.__STARWARD__.v12SetAim(820,270);}
  if(state.liveEvent&&frame%90===0){const r=window.__STARWARD__.v12EventAcceptRect();el.game.dispatch('pointerdown',{clientX:r.x+r.w/2,clientY:r.y+r.h/2,pointerId:20});}
  if(frame%60===0&&state.laserCharge>=state.laserMax&&state.time>=state.nextLaserAt)el.laserButton.click();
  if(!el.overlay.classList.contains('hidden')&&!el.choiceGrid.classList.contains('hidden')&&el.choiceGrid.children.length===3){paused++;(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Aim|Projectile|Armor|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click();}
}
state=window.__STARWARD__.getState();if(state.time<100)throw Error(`V12 run ended too early at ${state.time.toFixed(1)}s`);if(laneError>.6)throw Error(`Ship left straight flight lane by ${laneError.toFixed(2)}px`);if(!eventSeen)throw Error('No recurring live event appeared');if(!powerSeen)throw Error('No automatic power core appeared');if(peak<24)throw Error(`Combat density too low: ${peak}`);if(paused<1)throw Error('More frequent build decisions never appeared');if(paused>10)throw Error(`Too many blocking choices: ${paused}`);
if(state.phase==='running'){window.__STARWARD__.endRun();for(let i=0;i<180&&raf.length;i++){const fn=raf.shift();now+=16.666;fn(now);if(window.__STARWARD__.getState().phase==='dead')break;}}
state=window.__STARWARD__.getState();if(state.phase!=='dead')throw Error('Run-end sequence failed');if(!/AIM CONTROL/.test(el.overlayText.innerHTML))throw Error('V12 results summary missing');const v=window.__STARWARD__.v12State()||{};if(v.powerCollected<1||v.shotdowns<1||v.manualFrames<1)throw Error('V12 interaction telemetry missing');console.log(`Starward V12 seed ${initialSeed} OK: ${state.time.toFixed(1)}s, peak ${peak}, decisions ${paused}, powers ${v.powerCollected}, shotdowns ${v.shotdowns}, aimed ${v.aimedKills}, lasers ${state.laserTimes.length}`);
