const fs=require('fs'),vm=require('vm'),zlib=require('zlib'),transform=require('./v10-polish5.js');
class CL{constructor(){this.s=new Set()}add(...v){v.forEach(x=>this.s.add(x))}remove(...v){v.forEach(x=>this.s.delete(x))}contains(v){return this.s.has(v)}}
class El{constructor(id=''){this.id=id;this.textContent='';this._html='';this.className='';this.classList=new CL();this.children=[];this.style={};this.listeners={};this.width=960;this.height=540}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(t,fn){(this.listeners[t]||(this.listeners[t]=[])).push(fn)}appendChild(c){this.children.push(c)}click(){const e={clientX:0,clientY:0};for(const f of(this.listeners.click||[]))f(e);if(this.onclick)this.onclick(e)}dispatch(t,e){for(const f of(this.listeners[t]||[]))f(e||{})}getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}}
const ids=['game','overlay','overlayTitle','overlayText','eyebrow','choiceGrid','startBtn','skinBtn','soundBtn','metaSummary','hudTime','hudSector','hudHull','hudShield','laserStatus','laserFill','threatStatus','threatFill','upgradeStatus','upgradeFill','buildChips'];const el=Object.fromEntries(ids.map(id=>[id,new El(id)]));
const gradient=()=>({addColorStop(){}});const ctx={imageSmoothingEnabled:true,fillStyle:'',strokeStyle:'',shadowColor:'',shadowBlur:0,lineWidth:1,font:'',textAlign:'',globalAlpha:1,createLinearGradient:gradient,createRadialGradient:gradient,fillRect(){},strokeRect(){},beginPath(){},arc(){},fill(){},stroke(){},save(){},restore(){},translate(){},rotate(){},moveTo(){},lineTo(){},closePath(){},fillText(){}};el.game.getContext=()=>ctx;
const choicePanel=new El('choicePanel');const document={getElementById:id=>el[id],createElement:tag=>new El(tag),querySelector:sel=>sel==='.choice-panel'?choicePanel:null};let raf=[],now=0;const requestAnimationFrame=fn=>(raf.push(fn),raf.length),cancelAnimationFrame=()=>{};const localStorage={m:{},getItem(k){return this.m[k]||null},setItem(k,v){this.m[k]=String(v)}};const initialSeed=(Number(process.env.STARWARD_SEED)||123456789)>>>0;let seed=initialSeed;const gameMath=Object.create(Math);gameMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const window={matchMedia:()=>({matches:false})};const sandbox={document,window,localStorage,requestAnimationFrame,cancelAnimationFrame,performance:{now:()=>now},Math:gameMath,console};vm.createContext(sandbox);
const splitLines=s=>s.match(/[^\n]*\n|[^\n]+$/g)||[],base=fs.readFileSync(__dirname+'/game.js','utf8'),parts=fs.readdirSync(__dirname+'/runtime_v9_patch').filter(f=>/^patch-\d+\.b64$/.test(f)).sort().map(f=>fs.readFileSync(__dirname+'/runtime_v9_patch/'+f,'utf8').trim()).join(''),ops=JSON.parse(zlib.gunzipSync(Buffer.from(parts,'base64')).toString('utf8')),lines=splitLines(base),out=[];for(const op of ops){if(op[0]==='=')out.push(lines.slice(op[1],op[2]).join(''));else out.push(op[1]);}
function balance(source){let n=0;source=source.replace(/const ENEMIES\s*=\s*\{[\s\S]*?\n\};/,b=>b.replace(/\bhp:(\d+(?:\.\d+)?)/g,(_,v)=>{n++;return `hp:${Math.round(Number(v)*1.75*100)/100}`;}));source=source.replace(/S\.focusTimer=7\b/g,'S.focusTimer=8').replace(/for 7 seconds/g,'for 8 seconds');const a='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.25:1;',b='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.65:1;';if(!source.includes(a)||n<5)throw Error('balance hooks missing');return source.replace(a,b);}
const source=transform.apply(balance(out.join('')));for(const t of ['AAA5_ROLE_DETAIL','AAA5_SYSTEM_DETAIL','AAA5_BOSS_DETAIL','SYSTEM WARFARE','LOCK ENDED'])if(!source.includes(t))throw Error('V10.7 source missing '+t);vm.runInContext(source,sandbox);if(!window.__STARWARD__?.aaa5State||!window.__STARWARD__?.aaa5FocusDetail)throw Error('V10.7 hooks missing');
el.startBtn.click();for(let i=0;i<5;i++){const card=el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Dodging|Engines|Armor|Balanced Systems|Fortress Doctrine/i.test(c.innerHTML))||el.choiceGrid.children[0];card.click();}
let healerDetail=false,capitalDetail=false,bossDetail=false,expiry=false,guide=false,drawDetail=false,paused=0;
for(let frame=0;frame<7200;frame++){
  if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);const s=window.__STARWARD__.getState(),a=window.__STARWARD__.aaa5State();
  if(a?.guideFrames>0)guide=true;if(a?.detailDraws>0)drawDetail=true;
  if(!healerDetail&&s.time>14){const h=s.enemies.find(e=>e.type==='healer'&&e.hp>0)||window.__STARWARD__.spawnElite('healer','shielded');if(h){s.focusTarget=h;s.focusTimer=8;const d=window.__STARWARD__.aaa5FocusDetail();healerDetail=/Repairs damaged hostiles/i.test(d);}}
  if(!capitalDetail&&s.time>28){window.__STARWARD__.aaaSpawnCapital();const cap=s.enemies.find(e=>e.aaaCapital&&e.hp>0);if(cap){window.__STARWARD__.p2InitCapital(cap);s.focusTarget=cap;s.focusTimer=8;s.p2CapitalFocus={e:cap,id:'hangar'};const d=window.__STARWARD__.aaa5FocusDetail();capitalDetail=/Launches interceptor reinforcements/i.test(d)&&/body damage reduced/i.test(d);}}
  if(!bossDetail&&s.time>45&&!s.boss){window.__STARWARD__.spawnBoss(false);const b=s.boss;if(b){b.intro=0;const p=b.parts?.[0];if(p){s.focusTarget=b;s.focusBossPart=p;s.focusTimer=8;const d=window.__STARWARD__.aaa5FocusDetail();bossDetail=/reduce attack volume/i.test(d);}}}
  if(!expiry&&s.time>58){const t=s.enemies.find(e=>e.hp>50);if(t){s.focusTarget=t;s.focusBossPart=null;s.p2CapitalFocus=null;s.focusTimer=.001;if(raf.length){const f=raf.shift();now+=16.666;f(now);}expiry=(window.__STARWARD__.aaa5State()?.expiredLocks||0)>0;}}
  if(frame%100===0)el.game.dispatch('pointerdown',{clientX:168,clientY:s.ship.y});
  if(!el.overlay.classList.contains('hidden')&&!el.choiceGrid.classList.contains('hidden')&&el.choiceGrid.children.length===3){paused++;(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Dodging|Engines|Armor|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click();}
  if(s.phase==='dead')break;
}
const s=window.__STARWARD__.getState(),a=window.__STARWARD__.aaa5State();if(s.time<75)throw Error(`V10.7 run too short ${s.time.toFixed(1)}s`);if(!healerDetail||!capitalDetail||!bossDetail)throw Error('Tactical consequence descriptions failed');if(!expiry)throw Error('Focus expiry feedback failed');if(!guide||!drawDetail)throw Error('Tactical guide/detail rendering failed');if(!a||a.expiredLocks<1)throw Error('V10.7 telemetry invalid');if(paused>7)throw Error(`Too many blocking choices ${paused}`);console.log(`Starward V10.7 seed ${initialSeed} OK: ${s.time.toFixed(1)}s, details ${a.detailDraws}, guide ${a.guideFrames}, expired ${a.expiredLocks}, boss systems ${a.bossSystemsBroken}`);
