const fs=require('fs'),vm=require('vm'),zlib=require('zlib'),transform=require('./v20-mechanics-refresh.js');
class CL{constructor(){this.s=new Set()}add(...v){v.forEach(x=>this.s.add(x))}remove(...v){v.forEach(x=>this.s.delete(x))}contains(v){return this.s.has(v)}}
class El{constructor(id=''){this.id=id;this.textContent='';this._html='';this.className='';this.classList=new CL();this.children=[];this.style={};this.listeners={};this.width=960;this.height=540;this.onclick=null}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(t,fn,opt){(this.listeners[t]||(this.listeners[t]=[])).push({fn,capture:opt===true||!!opt?.capture})}removeEventListener(t,fn){if(this.listeners[t])this.listeners[t]=this.listeners[t].filter(x=>x.fn!==fn)}appendChild(c){this.children.push(c)}click(){this.dispatch('click',{clientX:0,clientY:0,pointerId:1})}dispatch(t,e={}){let stopped=false;e.preventDefault=e.preventDefault||(()=>{});e.stopImmediatePropagation=e.stopImmediatePropagation||(()=>{stopped=true});for(const x of [...(this.listeners[t]||[])].sort((a,b)=>Number(b.capture)-Number(a.capture))){x.fn(e);if(stopped)break}if(!stopped&&t==='click'&&this.onclick)this.onclick(e)}getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}setPointerCapture(){}releasePointerCapture(){}}
const ids=['game','overlay','overlayTitle','overlayText','eyebrow','choiceGrid','startBtn','skinBtn','soundBtn','laserButton','metaSummary','hudTime','hudSector','hudHull','hudShield','laserStatus','laserFill','threatStatus','threatFill','upgradeStatus','upgradeFill','buildChips'];const el=Object.fromEntries(ids.map(id=>[id,new El(id)]));
const gradient=()=>({addColorStop(){}}),noop=()=>{},ctx={imageSmoothingEnabled:true,fillStyle:'',strokeStyle:'',shadowColor:'',shadowBlur:0,lineWidth:1,font:'',textAlign:'',globalAlpha:1,globalCompositeOperation:'source-over',createLinearGradient:gradient,createRadialGradient:gradient,fillRect:noop,strokeRect:noop,beginPath:noop,arc:noop,fill:noop,stroke:noop,save:noop,restore:noop,translate:noop,rotate:noop,scale:noop,moveTo:noop,lineTo:noop,closePath:noop,fillText:noop,setLineDash:noop,ellipse:noop,quadraticCurveTo:noop,bezierCurveTo:noop};el.game.getContext=()=>ctx;
const choicePanel=new El('choicePanel'),document={getElementById:id=>el[id],createElement:tag=>new El(tag),querySelector:sel=>sel==='.choice-panel'?choicePanel:null};let raf=[],now=0;const requestAnimationFrame=fn=>(raf.push(fn),raf.length),cancelAnimationFrame=()=>{},localStorage={m:{},getItem(k){return this.m[k]||null},setItem(k,v){this.m[k]=String(v)}};const initialSeed=(Number(process.env.STARWARD_SEED)||123456789)>>>0;let seed=initialSeed;const gameMath=Object.create(Math);gameMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const window={matchMedia:()=>({matches:false})},sandbox={document,window,localStorage,requestAnimationFrame,cancelAnimationFrame,performance:{now:()=>now},Math:gameMath,console,Blob:global.Blob,Response:global.Response};vm.createContext(sandbox);
const splitLines=s=>s.match(/[^\n]*\n|[^\n]+$/g)||[],base=fs.readFileSync(__dirname+'/game.js','utf8'),parts=fs.readdirSync(__dirname+'/runtime_v9_patch').filter(f=>/^patch-\d+\.b64$/.test(f)).sort().map(f=>fs.readFileSync(__dirname+'/runtime_v9_patch/'+f,'utf8').trim()).join(''),ops=JSON.parse(zlib.gunzipSync(Buffer.from(parts,'base64')).toString('utf8')),lines=splitLines(base),out=[];for(const op of ops){if(op[0]==='=')out.push(lines.slice(op[1],op[2]).join(''));else out.push(op[1]);}
function balance(source){let n=0;source=source.replace(/const ENEMIES\s*=\s*\{[\s\S]*?\n\};/,b=>b.replace(/\bhp:(\d+(?:\.\d+)?)/g,(_,v)=>{n++;return `hp:${Math.round(Number(v)*1.75*100)/100}`}));source=source.replace(/S\.focusTimer=7\b/g,'S.focusTimer=8').replace(/for 7 seconds/g,'for 8 seconds');const a='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.25:1;',b='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.65:1;';if(!source.includes(a)||n<5)throw Error('balance hooks missing');return source.replace(a,b)}
const source=transform.apply(balance(out.join('')));for(const term of ['V20_MAX_RANK=5','FORMATION BROKEN','COUNTER!','COMBAT DIRECTOR','V19_RING_CAP=30'])if(!source.includes(term))throw Error('V20 source missing '+term);new Function(source);vm.runInContext(source,sandbox);
if(!window.__STARWARD__?.v20State||!window.__STARWARD__?.v20SetRank||!window.__STARWARD__?.v20StartAssault||!window.__STARWARD__?.v20EnemyFire||!window.__STARWARD__?.v20Hurt)throw Error('V20 debug hooks missing');
el.startBtn.click();for(let i=0;i<5;i++){if(el.choiceGrid.children.length!==3)throw Error('Opening draft broken '+(i+1));(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Armor|Damage|Fire Rate|Fortress|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click()}
let state=window.__STARWARD__.getState();if(state.phase!=='running')throw Error('Run did not start');let d=window.__STARWARD__.v20State();if(!d||d.rank!==1||d.phase!=='recovery')throw Error('V20 director did not initialise');
window.__STARWARD__.v20SetRank(4);if(window.__STARWARD__.v20RewardMult()<1.29)throw Error('Danger reward multiplier missing');window.__STARWARD__.v20StartAssault('crossfire');d=window.__STARWARD__.v20State();if(d.phase!=='assault'||d.assaultMod!=='crossfire'||d.assaultQuota<20)throw Error('Assault start failed');
state.bullets.length=0;const gun=window.__STARWARD__.v20SpawnEnemy('gunner',270,{x:700});window.__STARWARD__.v20EnemyFire(gun);if(state.bullets.length<4)throw Error('High-rank crossfire pattern too weak '+state.bullets.length);
function advance(frames){for(let i=0;i<frames;i++){if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);}}
const counter=window.__STARWARD__.v20SpawnEnemy('gunner',240,{x:650});counter.fire=.30;counter.hp=0;advance(2);if(window.__STARWARD__.v20State().counterKills<1)throw Error('Counter-kill reward did not register');
state=window.__STARWARD__.getState();state.ship.inv=0;window.__STARWARD__.v20Hurt(1);state.ship.inv=0;window.__STARWARD__.v20Hurt(1);if(window.__STARWARD__.v20State().rank!==3)throw Error('Sustained damage did not lower visible danger rank');window.__STARWARD__.v20SetRank(4);
let peak=0,pauses=0;for(let frame=0;frame<9600;frame++){if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);state=window.__STARWARD__.getState();if(state.phase==='dead')break;peak=Math.max(peak,state.enemies.length);const vv=window.__STARWARD__.v12State();if(frame%16===0){const p=vv?.powerups?.find(x=>!x.dead),b=state.bullets?.find(x=>x.life>0&&x.x>state.ship.x+30),priority=state.enemies.find(x=>x.v20Counter&&x.hp>0),e=state.boss||priority||state.enemies.filter(x=>x.hp>0).sort((a,b)=>(b.elite-a.elite)||(a.x-b.x))[0],t=p||b||e;if(t)window.__STARWARD__.v12SetAim(t.x,t.y);else window.__STARWARD__.v12ReleaseAim()}if(frame%110===0&&window.__STARWARD__.v18State().dashCooldown<=0)window.__STARWARD__.v18Dash(frame%220?1:-1);if(frame%88===0&&window.__STARWARD__.v18State().precision>.73)window.__STARWARD__.v12ReleaseAim();if(state.liveEvent&&frame%100===0){const r=window.__STARWARD__.v14EventBox().accept;el.game.dispatch('pointerdown',{clientX:r.x+r.w/2,clientY:r.y+r.h/2,pointerId:9,preventDefault(){},stopImmediatePropagation(){}})}if(frame%60===0&&state.laserCharge>=state.laserMax&&state.time>=state.nextLaserAt)el.laserButton.click();if(!el.overlay.classList.contains('hidden')&&!el.choiceGrid.classList.contains('hidden')&&el.choiceGrid.children.length===3){pauses++;(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Armor|Damage|Fire Rate|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click()}}
state=window.__STARWARD__.getState();d=window.__STARWARD__.v20State();if(state.time<85)throw Error('V20 run ended too early '+state.time.toFixed(1));if(peak<26)throw Error('V20 challenge density too low '+peak);if(d.assault<3)throw Error('Too few assault cycles '+d.assault);if(d.maxRank<4)throw Error('Danger rank telemetry regressed '+d.maxRank);if(d.counterKills<1)throw Error('Counter telemetry missing');if(pauses>11)throw Error('Too many blocking choices '+pauses);if(state.phase==='running'){window.__STARWARD__.endRun();for(let i=0;i<220&&raf.length;i++){const fn=raf.shift();now+=16.666;fn(now);if(window.__STARWARD__.getState().phase==='dead')break}}if(!/COMBAT DIRECTOR/.test(el.overlayText.innerHTML))throw Error('V20 results missing');console.log(`Starward V20 seed ${initialSeed} OK: ${state.time.toFixed(1)}s, peak ${peak}, assaults ${d.assaultsCleared}/${d.assault}, flawless ${d.flawlessAssaults}, counters ${d.counterKills}, rank ${d.maxRank}, pauses ${pauses}`);