const fs=require('fs'),vm=require('vm'),zlib=require('zlib'),transform=require('./v10-polish9.js');
class CL{constructor(){this.s=new Set()}add(...v){v.forEach(x=>this.s.add(x))}remove(...v){v.forEach(x=>this.s.delete(x))}contains(v){return this.s.has(v)}}
class El{constructor(id=''){this.id=id;this.textContent='';this._html='';this.className='';this.classList=new CL();this.children=[];this.style={};this.listeners={};this.width=960;this.height=540}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(t,fn){(this.listeners[t]||(this.listeners[t]=[])).push(fn)}appendChild(c){this.children.push(c)}click(){const e={clientX:0,clientY:0};for(const f of(this.listeners.click||[]))f(e);if(this.onclick)this.onclick(e)}dispatch(t,e){for(const f of(this.listeners[t]||[]))f(e||{})}getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}}
const ids=['game','overlay','overlayTitle','overlayText','eyebrow','choiceGrid','startBtn','skinBtn','soundBtn','metaSummary','hudTime','hudSector','hudHull','hudShield','laserStatus','laserFill','threatStatus','threatFill','upgradeStatus','upgradeFill','buildChips'];const el=Object.fromEntries(ids.map(id=>[id,new El(id)]));
const gradient=()=>({addColorStop(){}}),ctx={imageSmoothingEnabled:true,fillStyle:'',strokeStyle:'',shadowColor:'',shadowBlur:0,lineWidth:1,font:'',textAlign:'',globalAlpha:1,createLinearGradient:gradient,createRadialGradient:gradient,fillRect(){},strokeRect(){},beginPath(){},arc(){},fill(){},stroke(){},save(){},restore(){},translate(){},rotate(){},moveTo(){},lineTo(){},closePath(){},fillText(){},setLineDash(){}};el.game.getContext=()=>ctx;
const choicePanel=new El('choicePanel'),document={getElementById:id=>el[id],createElement:tag=>new El(tag),querySelector:sel=>sel==='.choice-panel'?choicePanel:null};let raf=[],now=0;const requestAnimationFrame=fn=>(raf.push(fn),raf.length),cancelAnimationFrame=()=>{},localStorage={m:{},getItem(k){return this.m[k]||null},setItem(k,v){this.m[k]=String(v)}};const initialSeed=(Number(process.env.STARWARD_SEED)||123456789)>>>0;let seed=initialSeed;const gameMath=Object.create(Math);gameMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const window={matchMedia:()=>({matches:false})},sandbox={document,window,localStorage,requestAnimationFrame,cancelAnimationFrame,performance:{now:()=>now},Math:gameMath,console};vm.createContext(sandbox);
const splitLines=s=>s.match(/[^\n]*\n|[^\n]+$/g)||[],base=fs.readFileSync(__dirname+'/game.js','utf8'),parts=fs.readdirSync(__dirname+'/runtime_v9_patch').filter(f=>/^patch-\d+\.b64$/.test(f)).sort().map(f=>fs.readFileSync(__dirname+'/runtime_v9_patch/'+f,'utf8').trim()).join(''),ops=JSON.parse(zlib.gunzipSync(Buffer.from(parts,'base64')).toString('utf8')),lines=splitLines(base),out=[];for(const op of ops){if(op[0]==='=')out.push(lines.slice(op[1],op[2]).join(''));else out.push(op[1]);}
function balance(source){let n=0;source=source.replace(/const ENEMIES\s*=\s*\{[\s\S]*?\n\};/,b=>b.replace(/\bhp:(\d+(?:\.\d+)?)/g,(_,v)=>{n++;return `hp:${Math.round(Number(v)*1.75*100)/100}`;}));source=source.replace(/S\.focusTimer=7\b/g,'S.focusTimer=8').replace(/for 7 seconds/g,'for 8 seconds');const a='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.25:1;',b='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.65:1;';if(!source.includes(a)||n<5)throw Error('balance hooks missing');return source.replace(a,b);}
const source=transform.apply(balance(out.join('')));for(const term of ['aaa9TouchRadius','PERFECT CHAIN','WARSHIP STAGGERED','aaa9UrgentTargets','aaa8EnsureResultsStack'])if(!source.includes(term))throw Error('V10.11 source missing '+term);vm.runInContext(source,sandbox);
if(!window.__STARWARD__?.aaa9State||!window.__STARWARD__?.aaa9TouchRadius||!window.__STARWARD__?.aaa9UrgentTargets)throw Error('V10.11 debug hooks missing');if((el.game.listeners.pointerdown||[]).length<3)throw Error('Precision pointer stack missing');
el.startBtn.click();for(let i=0;i<5;i++){if(el.choiceGrid.children.length!==3)throw Error('Opening draft broken');(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Dodging|Engines|Armor|Balanced Systems|Fortress Doctrine/i.test(c.innerHTML))||el.choiceGrid.children[0]).click();}
let overlap=false,largeTouch=false,staggerVisual=false,alertBudget=false,perfectChain=false,paused=0;
for(let frame=0;frame<9000;frame++){
  if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);let s=window.__STARWARD__.getState(),v=window.__STARWARD__.aaa9State();
  if(!overlap&&s.time>12){for(const e of s.enemies)e.x=900;const low=window.__STARWARD__.spawnElite('scout','armored'),high=window.__STARWARD__.spawnElite('healer','commander');if(low&&high){low.x=620;low.y=250;high.x=626;high.y=252;el.game.dispatch('pointerdown',{clientX:623,clientY:251});overlap=s.focusTarget===high;}}
  if(!largeTouch&&s.time>18){for(const e of s.enemies)e.x=900;const h=window.__STARWARD__.spawnElite('healer','commander');if(h){h.x=650;h.y=260;const radius=window.__STARWARD__.aaa9TouchRadius(h);el.game.dispatch('pointerdown',{clientX:h.x+50,clientY:h.y});largeTouch=radius>=54&&s.focusTarget===h;}}
  if(!staggerVisual&&s.time>24){const t=s.enemies.find(e=>e.hp>0);if(t){window.__STARWARD__.aaa7ApplyStagger(t);if(raf.length){const f=raf.shift();now+=16.666;f(now);}staggerVisual=(window.__STARWARD__.aaa9State()?.staggerFrames||0)>0;}}
  if(!alertBudget&&s.time>30){for(const e of s.enemies)e.x=900;for(let i=0;i<6;i++){const e=window.__STARWARD__.spawnElite(i%2?'healer':'sniper',i%3?'commander':'shielded');if(e){e.x=560+i*48;e.y=105+i*55;e.fire=.08;}}if(raf.length){const f=raf.shift();now+=16.666;f(now);}v=window.__STARWARD__.aaa9State();alertBudget=(v.alertFrames||0)>0&&v.maxAlertsSeen<=2;}
  if(!perfectChain&&s.time>38){s.enemies=[];s.weapons.pulse=15;s.stats.damage=2.3;s.stats.rate=2.0;const chain=[];for(let i=0;i<3;i++){const e=window.__STARWARD__.spawnElite('healer','commander');if(e){e.x=610+i*35;e.y=220+i*40;e.hp=1;e.maxHp=Math.max(e.maxHp,30);chain.push(e);}}if(chain.length===3)window.__STARWARD__.focus(chain[0]);}
  if((window.__STARWARD__.aaa9State()?.perfectChains||0)>0)perfectChain=true;
  if(frame%120===0)el.game.dispatch('pointerdown',{clientX:168,clientY:s.ship.y});
  if(!el.overlay.classList.contains('hidden')&&!el.choiceGrid.classList.contains('hidden')&&el.choiceGrid.children.length===3){paused++;(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Dodging|Engines|Armor|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click();}
  s=window.__STARWARD__.getState();if(s.phase==='dead')break;
}
const s=window.__STARWARD__.getState(),v=window.__STARWARD__.aaa9State()||{};if(s.time<70)throw Error(`V10.11 run too short ${s.time.toFixed(1)}s`);if(!overlap)throw Error('Priority overlap resolver failed');if(!largeTouch)throw Error('Expanded priority touch radius failed');if(!staggerVisual)throw Error('Stagger visual feedback never rendered');if(!alertBudget)throw Error(`Warning budget failed: max ${v.maxAlertsSeen||0}`);if(!perfectChain)throw Error('Perfect-chain mastery feedback never triggered');if(v.maxAlertsSeen>2)throw Error(`More than two simultaneous warnings: ${v.maxAlertsSeen}`);if(paused>7)throw Error(`Too many blocking choices: ${paused}`);console.log(`Starward V10.11 seed ${initialSeed} OK: ${s.time.toFixed(1)}s, chains ${v.perfectChains||0}, staggerFrames ${v.staggerFrames||0}, alerts ${v.maxAlertsSeen||0}, touchLocks ${v.largeTouchLocks||0}`);
