const fs=require('fs'),vm=require('vm'),zlib=require('zlib'),transform=require('./v18-mechanics.js');
class CL{constructor(){this.s=new Set()}add(...v){v.forEach(x=>this.s.add(x))}remove(...v){v.forEach(x=>this.s.delete(x))}contains(v){return this.s.has(v)}}
class El{constructor(id=''){this.id=id;this.textContent='';this._html='';this.className='';this.classList=new CL();this.children=[];this.style={};this.listeners={};this.width=960;this.height=540;this.onclick=null}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(t,fn,opt){(this.listeners[t]||(this.listeners[t]=[])).push({fn,capture:opt===true||!!opt?.capture})}removeEventListener(t,fn){if(this.listeners[t])this.listeners[t]=this.listeners[t].filter(x=>x.fn!==fn)}appendChild(c){this.children.push(c)}click(){this.dispatch('click',{clientX:0,clientY:0,pointerId:1})}dispatch(t,e={}){let stopped=false;e.preventDefault=e.preventDefault||(()=>{});e.stopImmediatePropagation=e.stopImmediatePropagation||(()=>{stopped=true});const list=[...(this.listeners[t]||[])].sort((a,b)=>Number(b.capture)-Number(a.capture));for(const x of list){x.fn(e);if(stopped)break}if(!stopped&&t==='click'&&this.onclick)this.onclick(e)}getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}setPointerCapture(){}releasePointerCapture(){}}
const ids=['game','overlay','overlayTitle','overlayText','eyebrow','choiceGrid','startBtn','skinBtn','soundBtn','laserButton','metaSummary','hudTime','hudSector','hudHull','hudShield','laserStatus','laserFill','threatStatus','threatFill','upgradeStatus','upgradeFill','buildChips'];const el=Object.fromEntries(ids.map(id=>[id,new El(id)]));
const gradient=()=>({addColorStop(){}}),noop=()=>{},ctx={imageSmoothingEnabled:true,fillStyle:'',strokeStyle:'',shadowColor:'',shadowBlur:0,lineWidth:1,font:'',textAlign:'',globalAlpha:1,createLinearGradient:gradient,createRadialGradient:gradient,fillRect:noop,strokeRect:noop,beginPath:noop,arc:noop,fill:noop,stroke:noop,save:noop,restore:noop,translate:noop,rotate:noop,moveTo:noop,lineTo:noop,closePath:noop,fillText:noop,setLineDash:noop,ellipse:noop,quadraticCurveTo:noop,bezierCurveTo:noop};el.game.getContext=()=>ctx;
const choicePanel=new El('choicePanel'),document={getElementById:id=>el[id],createElement:tag=>new El(tag),querySelector:sel=>sel==='.choice-panel'?choicePanel:null};let raf=[],now=0;const requestAnimationFrame=fn=>(raf.push(fn),raf.length),cancelAnimationFrame=()=>{},localStorage={m:{},getItem(k){return this.m[k]||null},setItem(k,v){this.m[k]=String(v)}};const initialSeed=(Number(process.env.STARWARD_SEED)||123456789)>>>0;let seed=initialSeed;const gameMath=Object.create(Math);gameMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const window={matchMedia:()=>({matches:false})},sandbox={document,window,localStorage,requestAnimationFrame,cancelAnimationFrame,performance:{now:()=>now},Math:gameMath,console,Blob:global.Blob,Response:global.Response};vm.createContext(sandbox);
const splitLines=s=>s.match(/[^\n]*\n|[^\n]+$/g)||[],base=fs.readFileSync(__dirname+'/game.js','utf8'),parts=fs.readdirSync(__dirname+'/runtime_v9_patch').filter(f=>/^patch-\d+\.b64$/.test(f)).sort().map(f=>fs.readFileSync(__dirname+'/runtime_v9_patch/'+f,'utf8').trim()).join(''),ops=JSON.parse(zlib.gunzipSync(Buffer.from(parts,'base64')).toString('utf8')),lines=splitLines(base),out=[];for(const op of ops){if(op[0]==='=')out.push(lines.slice(op[1],op[2]).join(''));else out.push(op[1]);}
function balance(source){let n=0;source=source.replace(/const ENEMIES\s*=\s*\{[\s\S]*?\n\};/,b=>b.replace(/\bhp:(\d+(?:\.\d+)?)/g,(_,v)=>{n++;return `hp:${Math.round(Number(v)*1.75*100)/100}`}));source=source.replace(/S\.focusTimer=7\b/g,'S.focusTimer=8').replace(/for 7 seconds/g,'for 8 seconds');const a='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.25:1;',b='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.65:1;';if(!source.includes(a)||n<5)throw Error('balance hooks missing');return source.replace(a,b)}
const source=transform.apply(balance(out.join('')));for(const term of ['V18_DASH_GESTURE=92','PHASE DASH','LOCK BURST','PILOTING MASTERY','V17_FORK_MIN=34'])if(!source.includes(term))throw Error('V18 source missing '+term);new Function(source);vm.runInContext(source,sandbox);
if(!window.__STARWARD__?.v18State||!window.__STARWARD__?.v18SpawnProtocolFork||!window.__STARWARD__?.v18Dash||!window.__STARWARD__?.v12SetAim||!window.__STARWARD__?.v12ReleaseAim)throw Error('V18 hooks missing');
el.startBtn.click();for(let i=0;i<5;i++){if(el.choiceGrid.children.length!==3)throw Error('Opening draft broken '+(i+1));(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Armor|Damage|Fire Rate|Fortress|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click()}
let state=window.__STARWARD__.getState();if(state.phase!=='running')throw Error('Run did not start');
function advance(frames){for(let i=0;i<frames;i++){if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);}}
const startY=state.ship.y;window.__STARWARD__.v12SetAim(820,110);advance(35);state=window.__STARWARD__.getState();if(!(state.ship.y<startY-25))throw Error('Direct steering did not move ship toward aim '+startY+' -> '+state.ship.y);
window.__STARWARD__.v18State().dashCooldown=0;window.__STARWARD__.v18Dash(1);advance(12);if(window.__STARWARD__.v18State().dashes<1)throw Error('Phase dash did not register');
window.__STARWARD__.v12SetAim(820,state.ship.y);window.__STARWARD__.v18State().precision=1;window.__STARWARD__.v12ReleaseAim();if(window.__STARWARD__.v18State().precisionBursts<1||window.__STARWARD__.v18State().burstWindow<=0)throw Error('Lock Burst did not trigger on charged release');
const pf=window.__STARWARD__.v18SpawnProtocolFork();if(!pf||pf.length!==3)throw Error('Protocol Fork did not create three choices');const pids=new Set(pf.map(p=>p.id));if(!['aceProtocol','gunnerProtocol','wardenProtocol'].every(x=>pids.has(x)))throw Error('Protocol choices missing');const gun=pf.find(p=>p.id==='gunnerProtocol');if(!window.__STARWARD__.v12CollectPowerup(gun))throw Error('Protocol choice could not be collected');if(window.__STARWARD__.v18State().protocol!=='gunner'||window.__STARWARD__.v18State().protocolChoices<1)throw Error('Protocol state did not apply');
if(!window.__STARWARD__.forceEvent('precisionrun'))throw Error('Precision event unavailable');state=window.__STARWARD__.getState();const wrapped=window.__STARWARD__.v14EventLines();if(wrapped.join(' ')!==state.liveEvent.body.trim())throw Error('Event text regressed');const ev=(x,y,id=1)=>({clientX:x,clientY:y,pointerId:id,preventDefault(){},stopImmediatePropagation(){}}),box=window.__STARWARD__.v14EventBox().accept;el.game.dispatch('pointerdown',ev(box.x+box.w/2,box.y+box.h/2,3));
let peak=0,pauses=0;for(let frame=0;frame<9000;frame++){if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);state=window.__STARWARD__.getState();if(state.phase==='dead')break;peak=Math.max(peak,state.enemies.length);const vv=window.__STARWARD__.v12State();if(frame%18===0){const p=vv?.powerups?.find(x=>!x.dead),b=state.bullets?.find(x=>x.life>0&&x.x>state.ship.x+35),e=state.boss||state.enemies.filter(x=>x.hp>0).sort((a,b)=>(b.elite-a.elite)||(a.x-b.x))[0],t=p||b||e;if(t)window.__STARWARD__.v12SetAim(t.x,t.y);else window.__STARWARD__.v12ReleaseAim()}if(frame%120===0&&window.__STARWARD__.v18State().dashCooldown<=0)window.__STARWARD__.v18Dash(frame%240?1:-1);if(frame%100===0&&window.__STARWARD__.v18State().precision>.74)window.__STARWARD__.v12ReleaseAim();if(state.liveEvent&&frame%90===0){const r=window.__STARWARD__.v14EventBox().accept;el.game.dispatch('pointerdown',ev(r.x+r.w/2,r.y+r.h/2,9))}if(frame%60===0&&state.laserCharge>=state.laserMax&&state.time>=state.nextLaserAt)el.laserButton.click();if(!el.overlay.classList.contains('hidden')&&!el.choiceGrid.classList.contains('hidden')&&el.choiceGrid.children.length===3){pauses++;(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Armor|Damage|Fire Rate|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click()}}
state=window.__STARWARD__.getState();const m=window.__STARWARD__.v18State(),a=window.__STARWARD__.v17State();if(state.time<105)throw Error('V18 run ended too early '+state.time.toFixed(1));if(peak<24)throw Error('V18 density too low '+peak);if(m.dashes<3)throw Error('Dash cadence did not survive runtime '+m.dashes);if(m.protocolChoices<1)throw Error('No protocol choice registered');if(a.flowBursts<1)throw Error('Gunnery Flow never occurred');if(pauses>10)throw Error('Too many blocking choices '+pauses);if(state.phase==='running'){window.__STARWARD__.endRun();for(let i=0;i<180&&raf.length;i++){const fn=raf.shift();now+=16.666;fn(now);if(window.__STARWARD__.getState().phase==='dead')break}}if(!/PILOTING MASTERY/.test(el.overlayText.innerHTML))throw Error('V18 results missing');console.log(`Starward V18 seed ${initialSeed} OK: ${state.time.toFixed(1)}s, peak ${peak}, dashes ${m.dashes}, evades ${m.perfectEvades}, grazes ${m.grazes}, bursts ${m.precisionBursts}, protocols ${m.protocolChoices}/${m.protocolForks}, pauses ${pauses}`);