const fs=require('fs'),vm=require('vm'),zlib=require('zlib'),transform=require('./v14-ui-fairness.js');
class CL{constructor(){this.s=new Set()}add(...v){v.forEach(x=>this.s.add(x))}remove(...v){v.forEach(x=>this.s.delete(x))}contains(v){return this.s.has(v)}}
class El{constructor(id=''){this.id=id;this.textContent='';this._html='';this.className='';this.classList=new CL();this.children=[];this.style={};this.listeners={};this.width=960;this.height=540;this.onclick=null}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(t,fn,opt){(this.listeners[t]||(this.listeners[t]=[])).push({fn,capture:opt===true||!!opt?.capture})}removeEventListener(t,fn){if(this.listeners[t])this.listeners[t]=this.listeners[t].filter(x=>x.fn!==fn)}appendChild(c){this.children.push(c)}click(){this.dispatch('click',{clientX:0,clientY:0})}dispatch(t,e={}){let stopped=false;e.preventDefault=e.preventDefault||(()=>{});e.stopImmediatePropagation=e.stopImmediatePropagation||(()=>{stopped=true});const list=[...(this.listeners[t]||[])].sort((a,b)=>Number(b.capture)-Number(a.capture));for(const x of list){if(stopped)break;x.fn(e)}if(!stopped&&t==='click'&&this.onclick)this.onclick(e)}getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}setPointerCapture(){}releasePointerCapture(){}}
const ids=['game','overlay','overlayTitle','overlayText','eyebrow','choiceGrid','startBtn','skinBtn','soundBtn','laserButton','metaSummary','hudTime','hudSector','hudHull','hudShield','laserStatus','laserFill','threatStatus','threatFill','upgradeStatus','upgradeFill','buildChips'];const el=Object.fromEntries(ids.map(id=>[id,new El(id)]));
const gradient=()=>({addColorStop(){}}),noop=()=>{},ctx={imageSmoothingEnabled:true,fillStyle:'',strokeStyle:'',shadowColor:'',shadowBlur:0,lineWidth:1,font:'',textAlign:'',globalAlpha:1,createLinearGradient:gradient,createRadialGradient:gradient,fillRect:noop,strokeRect:noop,beginPath:noop,arc:noop,fill:noop,stroke:noop,save:noop,restore:noop,translate:noop,rotate:noop,moveTo:noop,lineTo:noop,closePath:noop,fillText:noop,setLineDash:noop,ellipse:noop,quadraticCurveTo:noop,bezierCurveTo:noop};el.game.getContext=()=>ctx;
const choicePanel=new El('choicePanel'),document={getElementById:id=>el[id],createElement:tag=>new El(tag),querySelector:sel=>sel==='.choice-panel'?choicePanel:null};let raf=[],now=0;const requestAnimationFrame=fn=>(raf.push(fn),raf.length),cancelAnimationFrame=()=>{},localStorage={m:{},getItem(k){return this.m[k]||null},setItem(k,v){this.m[k]=String(v)}};const initialSeed=(Number(process.env.STARWARD_SEED)||123456789)>>>0;let seed=initialSeed;const gameMath=Object.create(Math);gameMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const window={matchMedia:()=>({matches:false})},sandbox={document,window,localStorage,requestAnimationFrame,cancelAnimationFrame,performance:{now:()=>now},Math:gameMath,console,Blob:global.Blob,Response:global.Response};vm.createContext(sandbox);
const splitLines=s=>s.match(/[^\n]*\n|[^\n]+$/g)||[],base=fs.readFileSync(__dirname+'/game.js','utf8'),parts=fs.readdirSync(__dirname+'/runtime_v9_patch').filter(f=>/^patch-\d+\.b64$/.test(f)).sort().map(f=>fs.readFileSync(__dirname+'/runtime_v9_patch/'+f,'utf8').trim()).join(''),ops=JSON.parse(zlib.gunzipSync(Buffer.from(parts,'base64')).toString('utf8')),lines=splitLines(base),out=[];for(const op of ops){if(op[0]==='=')out.push(lines.slice(op[1],op[2]).join(''));else out.push(op[1]);}
function balance(source){let n=0;source=source.replace(/const ENEMIES\s*=\s*\{[\s\S]*?\n\};/,b=>b.replace(/\bhp:(\d+(?:\.\d+)?)/g,(_,v)=>{n++;return `hp:${Math.round(Number(v)*1.75*100)/100}`}));source=source.replace(/S\.focusTimer=7\b/g,'S.focusTimer=8').replace(/for 7 seconds/g,'for 8 seconds');const a='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.25:1;',b='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.65:1;';if(!source.includes(a)||n<5)throw Error('balance hooks missing');return source.replace(a,b)}
const source=transform.apply(balance(out.join('')));for(const term of ['V13_DECISION_GAP=28','TRIDENT FIRE','TIME DILATION','PRECISION WINDOW','v13PowerTypes','v14WrapAll','IGNORE = KEEP FLYING'])if(!source.includes(term))throw Error('V14 source missing '+term);vm.runInContext(source,sandbox);
if(!window.__STARWARD__?.v12State||!window.__STARWARD__?.v13State||!window.__STARWARD__?.v13PowerTypes||!window.__STARWARD__?.v14EventLines)throw Error('Manual-aim debug hooks missing');
el.startBtn.click();for(let i=0;i<5;i++){if(el.choiceGrid.children.length!==3)throw Error('Opening draft broken at '+(i+1));const card=el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Armor|Fortress|Balanced|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0];card.click()}
let state=window.__STARWARD__.getState();if(state.phase!=='running')throw Error('Run did not start');
const ev=(x,y,id=1)=>({clientX:x,clientY:y,pointerId:id,preventDefault(){},stopImmediatePropagation(){this._stop=true}});
el.game.dispatch('pointerdown',ev(820,115,7));let v12=window.__STARWARD__.v12State();if(!v12?.aim.active||v12.aim.angle>=-.1)throw Error('Pointer hold did not aim upward');for(let i=0;i<100;i++)window.__STARWARD__.v12FireTick();state=window.__STARWARD__.getState();if(!state.shots.some(s=>s.v12Manual&&s.vy<0))throw Error('Manual aim did not redirect projectiles upward');
el.game.dispatch('pointermove',ev(820,425,7));v12=window.__STARWARD__.v12State();if(v12.aim.angle<=.1)throw Error('Pointer drag did not aim downward');el.game.dispatch('pointerup',ev(820,425,7));if(window.__STARWARD__.v12State().aim.active||Math.abs(window.__STARWARD__.v12State().aim.angle)>.001)throw Error('Release did not restore forward fire');
const powers=window.__STARWARD__.v13PowerTypes();if(powers.length<15||!powers.includes('trident')||!powers.includes('timeshift')||!powers.includes('aegis'))throw Error('Expanded power-mode pool missing');state.shots.length=0;state.cooldowns={};const p=window.__STARWARD__.v12SpawnPowerup('trident',270,620);if(!p||!window.__STARWARD__.v12CollectPowerup(p)||window.__STARWARD__.v12State().buffs.trident<=0)throw Error('Trident power core failed');window.__STARWARD__.v12SetAim(820,270);for(let i=0;i<100;i++)window.__STARWARD__.v12FireTick();if(!window.__STARWARD__.getState().shots.some(s=>s.v13Split))throw Error('Trident mode did not alter weapon fire');window.__STARWARD__.v12ReleaseAim();
if(!window.__STARWARD__.forceEvent('precisionrun'))throw Error('Expanded live event unavailable');state=window.__STARWARD__.getState();const original=state.liveEvent.body,wrapped=window.__STARWARD__.v14EventLines();if(wrapped.join(' ')!==original.trim())throw Error('Live-event body was truncated');if(wrapped.some(l=>l.length>82))throw Error('Live-event line exceeds readable width');const box=window.__STARWARD__.v14EventBox(),b=box.accept;el.game.dispatch('pointerdown',ev(b.x+b.w/2,b.y+b.h/2,8));if(window.__STARWARD__.getState().liveEvent)throw Error('Event ACCEPT hitbox failed');if((window.__STARWARD__.v13State()?.eventChoices||0)<1)throw Error('Event decision telemetry missing');
let fixedLane=true,maxPaused=0,powerSeen=false,decisions=0;for(let frame=0;frame<10500;frame++){
  if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);state=window.__STARWARD__.getState();v12=window.__STARWARD__.v12State();
  if(Math.abs(state.ship.y-270)>.01)fixedLane=false;if(v12?.powerups?.length)powerSeen=true;
  if(state.phase==='running'&&frame%24===0){const power=v12?.powerups?.find(x=>!x.dead),target=power||state.enemies.filter(e=>e.hp>0).sort((a,b)=>(b.elite-a.elite)||(a.x-b.x))[0]||state.boss;if(target)window.__STARWARD__.v12SetAim(target.x,target.y);else window.__STARWARD__.v12ReleaseAim()}
  if(frame%60===0)el.laserButton.click();
  if(!el.overlay.classList.contains('hidden')&&!el.choiceGrid.classList.contains('hidden')&&el.choiceGrid.children.length===3){maxPaused++;decisions=Math.max(decisions,window.__STARWARD__.v13State()?.decisionCount||0);const card=el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Armor|Second Chance|Damage|Fire Rate/i.test(c.innerHTML))||el.choiceGrid.children[0];card.click()}
  if(state.phase==='dead')break;
}
state=window.__STARWARD__.getState();if(!fixedLane)throw Error('Ship left the fixed flight lane');if(state.time<100)throw Error(`Fixed-lane run ended too early at ${state.time.toFixed(1)}s`);if(!powerSeen)throw Error('No combat power cores appeared');if((window.__STARWARD__.v13State()?.decisionCount||decisions)<2)throw Error('Higher build-decision cadence did not execute');if(maxPaused>9)throw Error('Decision cadence became overly interruptive: '+maxPaused);if((window.__STARWARD__.v12State()?.shotdowns||0)<1)throw Error('Projectile interception never occurred');
if(state.phase==='running'){window.__STARWARD__.v12ReleaseAim();window.__STARWARD__.endRun();for(let i=0;i<180&&raf.length;i++){const fn=raf.shift();now+=16.666;fn(now);if(window.__STARWARD__.getState().phase==='dead')break}}
state=window.__STARWARD__.getState();if(state.phase!=='dead')throw Error('Run-end sequence did not complete');if(!/AIM CONTROL/.test(el.overlayText.innerHTML)||!/ACTIVE GUNNERY/.test(el.overlayText.innerHTML))throw Error('Manual-control results summaries missing');console.log(`Starward V14 seed ${initialSeed} OK: ${state.time.toFixed(1)}s, decisions ${window.__STARWARD__.v13State()?.decisionCount||0}, powers ${window.__STARWARD__.v12State()?.powerCollected||0}, shotdowns ${window.__STARWARD__.v12State()?.shotdowns||0}, lines ${wrapped.length}`);