const fs=require('fs'),vm=require('vm'),zlib=require('zlib'),transform=require('./v10-polish3.js');
class CL{constructor(){this.s=new Set()}add(...v){v.forEach(x=>this.s.add(x))}remove(...v){v.forEach(x=>this.s.delete(x))}contains(v){return this.s.has(v)}}
class El{constructor(id=''){this.id=id;this.textContent='';this._html='';this.className='';this.classList=new CL();this.children=[];this.style={};this.listeners={};this.width=960;this.height=540}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(t,fn){(this.listeners[t]||(this.listeners[t]=[])).push(fn)}appendChild(c){this.children.push(c)}click(){const e={clientX:0,clientY:0};for(const f of(this.listeners.click||[]))f(e);if(this.onclick)this.onclick(e)}dispatch(t,e){for(const f of(this.listeners[t]||[]))f(e||{})}getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}}
const ids=['game','overlay','overlayTitle','overlayText','eyebrow','choiceGrid','startBtn','skinBtn','soundBtn','metaSummary','hudTime','hudSector','hudHull','hudShield','laserStatus','laserFill','threatStatus','threatFill','upgradeStatus','upgradeFill','buildChips'];
const el=Object.fromEntries(ids.map(id=>[id,new El(id)]));
const gradient=()=>({addColorStop(){}});const ctx={imageSmoothingEnabled:true,fillStyle:'',strokeStyle:'',shadowColor:'',shadowBlur:0,lineWidth:1,font:'',textAlign:'',globalAlpha:1,createLinearGradient:gradient,createRadialGradient:gradient,fillRect(){},strokeRect(){},beginPath(){},arc(){},fill(){},stroke(){},save(){},restore(){},translate(){},rotate(){},moveTo(){},lineTo(){},closePath(){},fillText(){}};el.game.getContext=()=>ctx;
const choicePanel=new El('choicePanel');const document={getElementById:id=>el[id],createElement:tag=>new El(tag),querySelector:sel=>sel==='.choice-panel'?choicePanel:null};let raf=[],now=0;const requestAnimationFrame=fn=>(raf.push(fn),raf.length),cancelAnimationFrame=()=>{};const localStorage={m:{},getItem(k){return this.m[k]||null},setItem(k,v){this.m[k]=String(v)}};const initialSeed=(Number(process.env.STARWARD_SEED)||123456789)>>>0;let seed=initialSeed;const gameMath=Object.create(Math);gameMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const window={matchMedia:()=>({matches:false})};const sandbox={document,window,localStorage,requestAnimationFrame,cancelAnimationFrame,performance:{now:()=>now},Math:gameMath,console};vm.createContext(sandbox);
const splitLines=s=>s.match(/[^\n]*\n|[^\n]+$/g)||[],base=fs.readFileSync(__dirname+'/game.js','utf8'),parts=fs.readdirSync(__dirname+'/runtime_v9_patch').filter(f=>/^patch-\d+\.b64$/.test(f)).sort().map(f=>fs.readFileSync(__dirname+'/runtime_v9_patch/'+f,'utf8').trim()).join(''),ops=JSON.parse(zlib.gunzipSync(Buffer.from(parts,'base64')).toString('utf8')),lines=splitLines(base),out=[];for(const op of ops){if(op[0]==='=')out.push(lines.slice(op[1],op[2]).join(''));else out.push(op[1]);}
function applyTargetingBalance(source){let hpValues=0;source=source.replace(/const ENEMIES\s*=\s*\{[\s\S]*?\n\};/,block=>block.replace(/\bhp:(\d+(?:\.\d+)?)/g,(_,raw)=>{hpValues++;return `hp:${Math.round(Number(raw)*1.75*100)/100}`;}));source=source.replace(/S\.focusTimer=7\b/g,'S.focusTimer=8').replace(/for 7 seconds/g,'for 8 seconds');const oldFocus='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.25:1;',newFocus='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.65:1;';if(!source.includes(oldFocus))throw Error('Focus hook missing');source=source.replace(oldFocus,newFocus);if(hpValues<5)throw Error('Enemy durability hook missing');return source;}
const source=transform.apply(applyTargetingBalance(out.join('')));for(const token of ['AAA3_CAPITAL_CLASSES','aaa3DrawTargetDossier','aaa3TuneFocusedShot','FLEET CARRIER','SIEGE FRIGATE','BULWARK CRUISER','LOCK DISCIPLINE'])if(!source.includes(token))throw Error('V10.5 source missing '+token);vm.runInContext(source,sandbox);
if(!window.__STARWARD__?.aaa3State||!window.__STARWARD__?.aaa3ClassifyCapital||!window.__STARWARD__?.aaa3FireTick)throw Error('V10.5 debug hooks missing');el.startBtn.click();for(let i=0;i<5;i++){if(el.choiceGrid.children.length!==3)throw Error('Opening choice count invalid');const card=el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Dodging|Engines|Armor|Balanced Systems|Fortress Doctrine/i.test(c.innerHTML))||el.choiceGrid.children[0];card.click();}
let capital=false,capitalClass=false,focusShot=false,recommended=false,dossier=false,paused=0;
for(let frame=0;frame<9000;frame++){
  if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);const s=window.__STARWARD__.getState();
  if(!capital&&s.time>34){window.__STARWARD__.aaaSpawnCapital();const cap=s.enemies.find(e=>e.aaaCapital&&e.hp>0);if(cap){capital=true;window.__STARWARD__.aaa3ClassifyCapital(cap,'siege');capitalClass=cap.aaaCapitalClass==='siege'&&cap.aaaCapitalMeta?.short==='SIEGE';s.focusTarget=cap;s.focusTimer=8;s.weapons.rail=Math.max(1,s.weapons.rail||0);s.cooldowns.rail=0;const before=s.shots.length;window.__STARWARD__.aaa3FireTick();const fresh=s.shots.slice(before);focusShot=fresh.some(x=>x.kind==='rail'&&x.aaaFocused&&x.pierce>=4);}}
  if(capital&&!dossier)dossier=(window.__STARWARD__.aaa3State()?.dossierDraws||0)>0;
  if(s.time>42&&!recommended){s.focusTarget=null;s.focusTimer=0;recommended=!!window.__STARWARD__.aaa3RecommendedTarget();}
  if(frame%75===0)el.game.dispatch('pointerdown',{clientX:168,clientY:s.ship.y});
  if(!el.overlay.classList.contains('hidden')&&!el.choiceGrid.classList.contains('hidden')&&el.choiceGrid.children.length===3){paused++;(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Dodging|Engines|Armor|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click();}
  if(s.phase==='dead')break;
}
const s=window.__STARWARD__.getState(),a=window.__STARWARD__.aaa3State();if(s.time<90)throw Error(`V10.5 run too short ${s.time.toFixed(1)}s`);if(!capital||!capitalClass)throw Error('Capital archetype system failed');if(!focusShot)throw Error('Weapon-specific focus behavior failed');if(!dossier)throw Error('Target dossier never rendered');if(!recommended)throw Error('Recommended-target cue failed');if(!a||a.frames<100||a.focusedShots<1||a.avgUpdateMs<0)throw Error('V10.5 telemetry invalid');if(paused>7)throw Error(`Too many blocking choices ${paused}`);for(let i=1;i<s.laserTimes.length;i++)if(s.laserTimes[i]-s.laserTimes[i-1]<29.95)throw Error('Star Laser cooldown violated');console.log(`Starward V10.5 seed ${initialSeed} OK: ${s.time.toFixed(1)}s, peak ${s.maxEnemiesSeen}, class ${Object.keys(a.capitalClasses).join('/')}, focused shots ${a.focusedShots}, dossier ${a.dossierDraws}, cues ${a.recommendedCues}, avg update ${a.avgUpdateMs.toFixed(2)}ms`);
