const fs=require('fs'),vm=require('vm');
class CL{constructor(){this.s=new Set()}add(...v){v.forEach(x=>this.s.add(x))}remove(...v){v.forEach(x=>this.s.delete(x))}contains(v){return this.s.has(v)}}
class El{constructor(id=''){this.id=id;this.textContent='';this._html='';this.className='';this.classList=new CL();this.children=[];this.style={};this.listeners={};this.width=960;this.height=540}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(t,fn){(this.listeners[t]||(this.listeners[t]=[])).push(fn)}appendChild(c){this.children.push(c)}click(){const e={clientX:0,clientY:0};for(const f of(this.listeners.click||[]))f(e);if(this.onclick)this.onclick(e)}dispatch(t,e){for(const f of(this.listeners[t]||[]))f(e||{})}getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}}
const ids=['game','overlay','overlayTitle','overlayText','eyebrow','choiceGrid','startBtn','skinBtn','soundBtn','metaSummary','hudTime','hudSector','hudHull','hudShield','laserStatus','laserFill','threatStatus','threatFill','upgradeStatus','upgradeFill','buildChips'];
const el=Object.fromEntries(ids.map(id=>[id,new El(id)]));
const gradient=()=>({addColorStop(){}});const ctx={imageSmoothingEnabled:true,fillStyle:'',strokeStyle:'',shadowColor:'',shadowBlur:0,lineWidth:1,font:'',textAlign:'',globalAlpha:1,createLinearGradient:gradient,createRadialGradient:gradient,fillRect(){},strokeRect(){},beginPath(){},arc(){},fill(){},stroke(){},save(){},restore(){},translate(){},rotate(){},moveTo(){},lineTo(){},closePath(){},fillText(){}};el.game.getContext=()=>ctx;
const choicePanel=new El('choicePanel');const document={getElementById:id=>el[id],createElement:tag=>new El(tag),querySelector:sel=>sel==='.choice-panel'?choicePanel:null};let raf=[],now=0;const requestAnimationFrame=fn=>(raf.push(fn),raf.length),cancelAnimationFrame=()=>{};const localStorage={m:{},getItem(k){return this.m[k]||null},setItem(k,v){this.m[k]=String(v)}};const initialSeed=(Number(process.env.STARWARD_SEED)||123456789)>>>0;let seed=initialSeed;const gameMath=Object.create(Math);gameMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const window={matchMedia:()=>({matches:false})};const sandbox={document,window,localStorage,requestAnimationFrame,cancelAnimationFrame,performance:{now:()=>now},Math:gameMath,console};vm.createContext(sandbox);
const zlib=require('zlib'),transform=require('./v10-final.js');const splitLines=s=>s.match(/[^\n]*\n|[^\n]+$/g)||[];const base=fs.readFileSync(__dirname+'/game.js','utf8'),parts=fs.readdirSync(__dirname+'/runtime_v9_patch').filter(f=>/^patch-\d+\.b64$/.test(f)).sort().map(f=>fs.readFileSync(__dirname+'/runtime_v9_patch/'+f,'utf8').trim()).join(''),ops=JSON.parse(zlib.gunzipSync(Buffer.from(parts,'base64')).toString('utf8')),lines=splitLines(base),out=[];for(const op of ops){if(op[0]==='=')out.push(lines.slice(op[1],op[2]).join(''));else out.push(op[1]);}
function applyTargetingBalance(source){let hpValues=0;source=source.replace(/const ENEMIES\s*=\s*\{[\s\S]*?\n\};/,block=>block.replace(/\bhp:(\d+(?:\.\d+)?)/g,(_,raw)=>{hpValues++;const boosted=Number(raw)*1.75;return `hp:${Math.round(boosted*100)/100}`;}));source=source.replace(/S\.focusTimer=7\b/g,'S.focusTimer=8');source=source.replace(/for 7 seconds/g,'for 8 seconds');const oldFocus='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.25:1;',newFocus='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.65:1;';if(!source.includes(oldFocus))throw Error('Focus-fire damage hook not found');source=source.replace(oldFocus,newFocus);if(hpValues<5)throw Error(`Targeting balance patch incomplete (${hpValues} HP values)`);return source;}
const source=transform.apply(applyTargetingBalance(out.join('')));
for(const required of ['WEAPON_EVOLUTIONS','ELITE_AFFIXES','SECTOR_RULES','MEGA_ENCOUNTERS','Glass Fleet','Prism Mirror','Arsenal Singularity','AAA_ROLE_INFO','aaaSpawnCapital','aaaWeaponFocusMultiplier','TARGET DESTROYED','P2_SYSTEM_META','CHAIN LOCK','COMMAND COLLAPSE','TACTICAL COMMAND','laserCharge:1.2','p2AppendResults();choiceGrid.classList.add'])if(!source.includes(required))throw Error(`Source missing ${required}`);if(!source.includes('?1.65:1'))throw Error('Stronger focus-fire multiplier missing');if(source.includes("canvas.addEventListener('pointerdown',aaaPointerCapital);"))throw Error('Duplicate capital pointer handler still active');
vm.runInContext(source,sandbox);
if(!el.startBtn.listeners.click)throw Error('Start button not registered');if((el.game.listeners.pointerdown||[]).length<2)throw Error('Canvas tactical interactions not registered');if(!window.__STARWARD__)throw Error('Debug state unavailable');if(!window.__STARWARD__.aaaSpawnCapital||!window.__STARWARD__.aaaSpawnFormation||!window.__STARWARD__.aaaRole)throw Error('V10 tactical debug hooks unavailable');if(!window.__STARWARD__.p2InitCapital||!window.__STARWARD__.p2BreakSystem||!window.__STARWARD__.p2State)throw Error('V10.2 systems debug hooks unavailable');if(!/ARSENAL/.test(el.metaSummary.innerHTML))throw Error('Collection progress missing from meta menu');
el.startBtn.click();
for(let i=0;i<5;i++){
  if(el.choiceGrid.children.length!==3)throw Error(`Opening step ${i+1} has ${el.choiceGrid.children.length} cards`);
  if(i===4&&!el.choiceGrid.children.every(c=>/DOCTRINE/.test(c.innerHTML)))throw Error('Final pre-flight step is not an explicit doctrine choice');
  const preferred=el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Dodging|Engines|Armor|Balanced Systems|Fortress Doctrine/i.test(c.innerHTML))||el.choiceGrid.children[0];preferred.click();
}
if(!raf.length)throw Error('Run did not start after five choices');
let pausedChoices=0,eventSeen=false,focusWorked=false,pointerFocusWorked=false,bossMechanic=false,bossParts=false,bossPartFocus=false,bossRoles=false,eliteAffix=false,evolutionWorked=false,megaWorked=false,durableEnemy=false,capitalWorked=false,capitalSystemsWorked=false,capitalPointerWorked=false,systemBreakWorked=false,formationWorked=false,guardWorked=false,tutorialWorked=false,p2Telemetry=false;
for(let frame=0;frame<15000;frame++){
  if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);const state=window.__STARWARD__.getState();
  if(state.liveEvent)eventSeen=true;
  if(state.aaa?.tutorialSpawned)tutorialWorked=true;
  if(!durableEnemy&&state.enemies.length)durableEnemy=state.enemies.some(e=>e.maxHp>=15);
  if(!evolutionWorked&&state.time>15){state.weapons.pulse=8;window.__STARWARD__.checkEvolutions();evolutionWorked=!!state.evolutions.pulseOverdrive;}
  if(!pointerFocusWorked&&state.time>18&&state.enemies.length){const target=state.enemies.find(e=>e.hp>0);if(target){el.game.dispatch('pointerdown',{clientX:target.x,clientY:target.y});pointerFocusWorked=state.focusTarget===target&&state.focusTimer>=7.8;}}
  if(!focusWorked&&state.time>20&&state.enemies.length){focusWorked=window.__STARWARD__.focus(state.enemies[0])&&state.focusTimer>=7.9;}
  if(!formationWorked&&state.time>24){formationWorked=!!window.__STARWARD__.aaaSpawnFormation();}
  if(formationWorked&&!guardWorked)guardWorked=state.enemies.some(e=>e.aaaGuarded);
  if(!eliteAffix&&state.time>28){const e=window.__STARWARD__.spawnElite('gunner','shielded');eliteAffix=!!e?.affix&&e.affix.id==='shielded'&&e.affixShield>0;}
  if(!capitalWorked&&state.time>38){capitalWorked=!!window.__STARWARD__.aaaSpawnCapital()&&window.__STARWARD__.getState().enemies.some(e=>e.aaaCapital&&e.maxHp>140);}
  if(capitalWorked&&!capitalSystemsWorked){const cap=state.enemies.find(e=>e.aaaCapital&&e.hp>0);if(cap){window.__STARWARD__.p2InitCapital(cap);capitalSystemsWorked=!!cap.p2Systems&&Object.keys(cap.p2Systems).length===3;if(capitalSystemsWorked){const sys=cap.p2Systems.hangar;el.game.dispatch('pointerdown',{clientX:cap.x+sys.ox,clientY:cap.y+sys.oy});capitalPointerWorked=state.p2CapitalFocus?.e===cap&&state.p2CapitalFocus?.id==='hangar'&&state.focusTimer>=7.8;systemBreakWorked=window.__STARWARD__.p2BreakSystem(cap,'hangar','focused')&&!cap.p2Systems.hangar.alive&&cap.aaaLaunchAt>1e8;}}}
  if(!megaWorked&&state.time>48&&!state.megaEncounter){megaWorked=window.__STARWARD__.forceMega('allied')&&window.__STARWARD__.getState().megaEncounter?.id==='allied';}
  if(!bossMechanic&&state.time>72&&!state.boss){window.__STARWARD__.spawnBoss(false);const b=window.__STARWARD__.getState().boss;bossMechanic=!!b?.type?.mechanic;bossParts=Array.isArray(b?.parts)&&b.parts.length>=2;bossRoles=!!b?.parts?.[0]?.aaaRole&&!!b?.parts?.[1]?.aaaRole;}
  if(bossMechanic&&!bossPartFocus&&state.boss&&state.boss.intro<=0){bossPartFocus=window.__STARWARD__.focusBossPart(0)&&!!window.__STARWARD__.getState().focusBossPart;}
  const p2=window.__STARWARD__.p2State();if(p2&&p2.peakEnemies>=0&&p2.peakPressure>=0)p2Telemetry=true;
  if(frame%60===0)el.game.dispatch('pointerdown',{clientX:168,clientY:270});
  if(!el.overlay.classList.contains('hidden')&&!el.choiceGrid.classList.contains('hidden')&&el.choiceGrid.children.length===3){pausedChoices++;const preferred=el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Dodging|Engines|Armor|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0];preferred.click();}
  if(state.phase==='dead')break;
}
let state=window.__STARWARD__.getState();
if(state.time<95)throw Error(`Run ended too early at ${state.time.toFixed(1)}s`);if(!eventSeen)throw Error('No real-time event appeared');if(!tutorialWorked)throw Error('Early priority-target teaching encounter failed');if(!focusWorked||!pointerFocusWorked)throw Error('8-second focus-fire interaction failed');if(!durableEnemy)throw Error('Durable-enemy health tuning missing');if(!formationWorked||!guardWorked)throw Error('Protected priority formation/guard-screen logic failed');if(!capitalWorked||!capitalSystemsWorked||!capitalPointerWorked||!systemBreakWorked)throw Error('Mini-capital subsystem interaction failed');if(!evolutionWorked)throw Error('Weapon evolution failed');if(!eliteAffix)throw Error('Elite affix system failed');if(!megaWorked)throw Error('Rare mega encounter failed');if(!bossMechanic||!bossParts||!bossPartFocus||!bossRoles)throw Error('Boss mechanics/system targeting failed');if(state.maxEnemiesSeen<30)throw Error(`Enemy density too low: peak ${state.maxEnemiesSeen}`);if(pausedChoices>7)throw Error(`Too many blocking choices: ${pausedChoices}`);if(!(state.quality>=.5&&state.quality<=1))throw Error('Adaptive quality out of range');if(!state.aaa||state.aaa.performancePressure<0||!p2Telemetry)throw Error('Tactical performance telemetry unavailable');
for(let i=1;i<state.laserTimes.length;i++){const gap=state.laserTimes[i]-state.laserTimes[i-1];if(gap<29.95)throw Error(`Star Laser cooldown violated: ${gap.toFixed(2)}s`)}if(state.laserTimes.length<2)throw Error(`Star Laser only fired ${state.laserTimes.length} time(s)`);
if(state.phase==='running'){window.__STARWARD__.forceEvent('overdrive');if(!window.__STARWARD__.acceptEvent())throw Error('Forced live event could not be accepted');window.__STARWARD__.endRun();for(let i=0;i<180&&raf.length;i++){const fn=raf.shift();now+=16.666;fn(now);if(window.__STARWARD__.getState().phase==='dead')break;}}
state=window.__STARWARD__.getState();if(state.phase!=='dead')throw Error(`Death sequence did not complete: ${state.phase}`);const meta=JSON.parse(localStorage.getItem('starwardMeta')||'{}');if(!(meta.runs>=1)||!(meta.cores>=1))throw Error('Meta progression was not saved');if(!/BUILD OF THE RUN/.test(el.overlayText.innerHTML))throw Error('Premium results screen missing build-of-run summary');if(!/TACTICAL COMMAND/.test(el.overlayText.innerHTML))throw Error('Tactical command results summary missing');if(!choicePanel.classList.contains('results-panel'))throw Error('Results presentation class missing');
const p2=window.__STARWARD__.p2State()||{};if((p2.maxFocusChain||0)<1)throw Error('Focus-chain reward never executed');if((p2.systemKills||0)<1)throw Error('Capital subsystem rewards never executed');console.log(`Starward V10.4 seed ${initialSeed} OK: ${state.time.toFixed(1)}s, peak ${state.maxEnemiesSeen}, paused ${pausedChoices}, lasers ${state.laserTimes.map(x=>x.toFixed(1)).join(', ')}, systems ${p2.systemKills||0}, max chain ${p2.maxFocusChain||0}, pressure ${(p2.peakPressure||0).toFixed(1)}, cores ${meta.cores}`);
