const fs=require('fs'),vm=require('vm'),zlib=require('zlib'),transform=require('./v21-sector-flow.js');
class CL{constructor(){this.s=new Set()}add(...v){v.forEach(x=>this.s.add(x))}remove(...v){v.forEach(x=>this.s.delete(x))}contains(v){return this.s.has(v)}}
class El{constructor(id=''){this.id=id;this.textContent='';this._html='';this.className='';this.classList=new CL();this.children=[];this.style={};this.listeners={};this.width=960;this.height=540;this.onclick=null}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(t,fn,opt){(this.listeners[t]||(this.listeners[t]=[])).push({fn,capture:opt===true||!!opt?.capture})}removeEventListener(t,fn){if(this.listeners[t])this.listeners[t]=this.listeners[t].filter(x=>x.fn!==fn)}appendChild(c){this.children.push(c)}click(){this.dispatch('click',{clientX:0,clientY:0,pointerId:1})}dispatch(t,e={}){let stopped=false;e.preventDefault=e.preventDefault||(()=>{});e.stopImmediatePropagation=e.stopImmediatePropagation||(()=>{stopped=true});for(const x of [...(this.listeners[t]||[])].sort((a,b)=>Number(b.capture)-Number(a.capture))){x.fn(e);if(stopped)break}if(!stopped&&t==='click'&&this.onclick)this.onclick(e)}getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}setPointerCapture(){}releasePointerCapture(){}}
const ids=['game','overlay','overlayTitle','overlayText','eyebrow','choiceGrid','startBtn','skinBtn','soundBtn','laserButton','metaSummary','hudTime','hudSector','hudHull','hudShield','laserStatus','laserFill','threatStatus','threatFill','upgradeStatus','upgradeFill','buildChips'];const el=Object.fromEntries(ids.map(id=>[id,new El(id)]));
const gradient=()=>({addColorStop(){}}),noop=()=>{},ctx={imageSmoothingEnabled:true,fillStyle:'',strokeStyle:'',shadowColor:'',shadowBlur:0,lineWidth:1,font:'',textAlign:'',globalAlpha:1,globalCompositeOperation:'source-over',createLinearGradient:gradient,createRadialGradient:gradient,fillRect:noop,strokeRect:noop,beginPath:noop,arc:noop,fill:noop,stroke:noop,save:noop,restore:noop,translate:noop,rotate:noop,scale:noop,moveTo:noop,lineTo:noop,closePath:noop,fillText:noop,setLineDash:noop,ellipse:noop,quadraticCurveTo:noop,bezierCurveTo:noop};el.game.getContext=()=>ctx;
const choicePanel=new El('choicePanel'),document={getElementById:id=>el[id],createElement:tag=>new El(tag),querySelector:sel=>sel==='.choice-panel'?choicePanel:null};let raf=[],now=0;const requestAnimationFrame=fn=>(raf.push(fn),raf.length),cancelAnimationFrame=()=>{},localStorage={m:{},getItem(k){return this.m[k]||null},setItem(k,v){this.m[k]=String(v)}};const initialSeed=(Number(process.env.STARWARD_SEED)||123456789)>>>0;let seed=initialSeed;const gameMath=Object.create(Math);gameMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const window={matchMedia:()=>({matches:false})},sandbox={document,window,localStorage,requestAnimationFrame,cancelAnimationFrame,performance:{now:()=>now},Math:gameMath,console,Blob:global.Blob,Response:global.Response};vm.createContext(sandbox);
const splitLines=s=>s.match(/[^\n]*\n|[^\n]+$/g)||[],base=fs.readFileSync(__dirname+'/game.js','utf8'),parts=fs.readdirSync(__dirname+'/runtime_v9_patch').filter(f=>/^patch-\d+\.b64$/.test(f)).sort().map(f=>fs.readFileSync(__dirname+'/runtime_v9_patch/'+f,'utf8').trim()).join(''),ops=JSON.parse(zlib.gunzipSync(Buffer.from(parts,'base64')).toString('utf8')),lines=splitLines(base),out=[];for(const op of ops){if(op[0]==='=')out.push(lines.slice(op[1],op[2]).join(''));else out.push(op[1]);}
function balance(source){let n=0;source=source.replace(/const ENEMIES\s*=\s*\{[\s\S]*?\n\};/,b=>b.replace(/\bhp:(\d+(?:\.\d+)?)/g,(_,v)=>{n++;return `hp:${Math.round(Number(v)*1.75*100)/100}`}));source=source.replace(/S\.focusTimer=7\b/g,'S.focusTimer=8').replace(/for 7 seconds/g,'for 8 seconds');const a='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.25:1;',b='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.65:1;';if(!source.includes(a)||n<5)throw Error('balance hooks missing');return source.replace(a,b)}
const source=transform.apply(balance(out.join('')));for(const term of ['V21_CLEAR_TIME=1.85','TACTICAL PAUSE','SECTOR CLEAR','COLLISION -','SECTOR FLOW','V20_MAX_RANK=5'])if(!source.includes(term))throw Error('V21 source missing '+term);new Function(source);vm.runInContext(source,sandbox);
if(!window.__STARWARD__?.v21State||!window.__STARWARD__?.v21TestEvent||!window.__STARWARD__?.v21SpawnSectorBoss||!window.__STARWARD__?.v21UpdateSector)throw Error('V21 debug hooks missing');
el.startBtn.click();for(let i=0;i<5;i++){if(el.choiceGrid.children.length!==3)throw Error('Opening draft broken '+(i+1));(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Armor|Damage|Fire Rate|Fortress|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click()}
let state=window.__STARWARD__.getState();if(state.phase!=='running'||state.sector!==1)throw Error('Run did not start in sector 1');
function advance(frames){for(let i=0;i<frames;i++){if(!raf.length)throw Error('RAF queue empty at '+i);const fn=raf.shift();now+=16.666;fn(now);}}
const savedTime=state.time;state.time=190;window.__STARWARD__.v21UpdateSector();if(state.sector!==1)throw Error('Legacy time-based sector advancement still active');state.time=savedTime;
window.__STARWARD__.v21TestEvent(1);const pauseStart=state.time;advance(30);state=window.__STARWARD__.getState();if(Math.abs(state.time-pauseStart)>.001)throw Error('World time advanced during event pause');if(!state.liveEvent||state.liveEvent.time>.55||state.liveEvent.time<.35)throw Error('Event timer did not continue during pause '+(state.liveEvent&&state.liveEvent.time));advance(31);state=window.__STARWARD__.getState();if(state.liveEvent)throw Error('Timed event did not expire');if(Math.abs(state.time-pauseStart)>.001)throw Error('World resumed before event timeout completed');advance(1);if(window.__STARWARD__.getState().time<=pauseStart)throw Error('World did not resume after event timeout');
window.__STARWARD__.v21TestEvent(5);advance(1);if(!window.__STARWARD__.getState().liveEvent)throw Error('Test event missing before acceptance');if(window.__STARWARD__.acceptEvent()===false)throw Error('Event acceptance failed');if(window.__STARWARD__.getState().liveEvent)throw Error('Accepted event remained active');if(window.__STARWARD__.v21State().eventAccepted<1)throw Error('Event acceptance telemetry missing');
state=window.__STARWARD__.getState();state.grace=0;state.ship.inv=0;state.enemies.length=0;state.bullets.length=0;const beforeDur=(state.hull||0)+(state.shield||0);window.__STARWARD__.v20SpawnEnemy('scout',state.ship.y,{x:state.ship.x+2});advance(2);state=window.__STARWARD__.getState();const q1=window.__STARWARD__.v21State();const afterDur=(state.hull||0)+(state.shield||0);if(q1.collisions<1)throw Error('Enemy collision did not register');if(beforeDur-afterDur<1.9)throw Error('Collision damage too weak '+(beforeDur-afterDur));if(q1.collisionDamage<1.9)throw Error('Collision damage telemetry missing');
state.enemies.length=0;state.bullets.length=0;state.ship.inv=0;const boss=window.__STARWARD__.v21SpawnSectorBoss();if(!boss||boss.forced)throw Error('Normal sector boss did not spawn');boss.hp=0;advance(2);state=window.__STARWARD__.getState();let q=window.__STARWARD__.v21State();if(!q.transition.active||q.transition.stage!=='clear')throw Error('Boss death did not start SECTOR CLEAR');if(state.sector!==1)throw Error('Sector advanced before transition');if(!q.pendingBossReward)throw Error('Boss reward was not deferred until after SECTOR CLEAR');
let guard=0;while((el.choiceGrid.classList.contains('hidden')||el.choiceGrid.children.length!==3)&&guard++<150)advance(1);if(el.choiceGrid.children.length!==3||el.choiceGrid.classList.contains('hidden'))throw Error('Boss reward did not appear after SECTOR CLEAR');if(window.__STARWARD__.getState().sector!==1)throw Error('Sector advanced before boss salvage selection');el.choiceGrid.children[0].click();advance(2);q=window.__STARWARD__.v21State();if(!q.transition.active||q.transition.stage!=='entry')throw Error('Next-sector transition did not start after boss reward');
guard=0;while(window.__STARWARD__.v21State().transition.active&&guard++<180)advance(1);state=window.__STARWARD__.getState();q=window.__STARWARD__.v21State();if(state.sector!==2)throw Error('Next sector did not begin after transition '+state.sector);if(q.sectorClears<1||q.sectorEntries<1)throw Error('Sector-flow telemetry missing');if(state.phase!=='running')throw Error('Game did not resume after next-sector entry');
let peak=0;for(let frame=0;frame<2400;frame++){if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);state=window.__STARWARD__.getState();if(state.phase==='dead')break;peak=Math.max(peak,state.enemies.length);if(state.liveEvent&&frame%40===0)window.__STARWARD__.acceptEvent();if(!el.overlay.classList.contains('hidden')&&!el.choiceGrid.classList.contains('hidden')&&el.choiceGrid.children.length===3)el.choiceGrid.children[0].click();if(frame%18===0){const t=state.boss||state.enemies.find(e=>e.hp>0);if(t)window.__STARWARD__.v12SetAim(t.x,t.y)}}
state=window.__STARWARD__.getState();if(peak<8)throw Error('Post-transition combat failed to resume '+peak);if(state.phase==='running'){window.__STARWARD__.endRun();for(let i=0;i<220&&raf.length;i++){const fn=raf.shift();now+=16.666;fn(now);if(window.__STARWARD__.getState().phase==='dead')break}}if(!/SECTOR FLOW/.test(el.overlayText.innerHTML))throw Error('V21 results missing');q=window.__STARWARD__.v21State();console.log(`Starward V21 seed ${initialSeed} OK: sector ${state.sector}, collisions ${q.collisions}, event pauses ${q.eventPauses}, clears ${q.sectorClears}, entries ${q.sectorEntries}, peak ${peak}`);