const fs=require('fs'),vm=require('vm'),zlib=require('zlib'),transform=require('./v16-power-state.js');
class CL{constructor(){this.s=new Set()}add(...v){v.forEach(x=>this.s.add(x))}remove(...v){v.forEach(x=>this.s.delete(x))}contains(v){return this.s.has(v)}}
class El{constructor(id=''){this.id=id;this.textContent='';this._html='';this.className='';this.classList=new CL();this.children=[];this.style={};this.listeners={};this.width=960;this.height=540;this.onclick=null}set innerHTML(v){this._html=v;if(v==='')this.children=[]}get innerHTML(){return this._html}addEventListener(t,fn,opt){(this.listeners[t]||(this.listeners[t]=[])).push({fn,capture:opt===true||!!opt?.capture})}removeEventListener(t,fn){if(this.listeners[t])this.listeners[t]=this.listeners[t].filter(x=>x.fn!==fn)}appendChild(c){this.children.push(c)}click(){this.dispatch('click',{clientX:0,clientY:0,pointerId:1})}dispatch(t,e={}){let stopped=false;e.preventDefault=e.preventDefault||(()=>{});e.stopImmediatePropagation=e.stopImmediatePropagation||(()=>{stopped=true});const list=[...(this.listeners[t]||[])].sort((a,b)=>Number(b.capture)-Number(a.capture));for(const x of list){x.fn(e);if(stopped)break}if(!stopped&&t==='click'&&this.onclick)this.onclick(e)}getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}setPointerCapture(){}releasePointerCapture(){}}
const ids=['game','overlay','overlayTitle','overlayText','eyebrow','choiceGrid','startBtn','skinBtn','soundBtn','laserButton','metaSummary','hudTime','hudSector','hudHull','hudShield','laserStatus','laserFill','threatStatus','threatFill','upgradeStatus','upgradeFill','buildChips'];const el=Object.fromEntries(ids.map(id=>[id,new El(id)]));
const gradient=()=>({addColorStop(){}}),noop=()=>{},ctx={imageSmoothingEnabled:true,fillStyle:'',strokeStyle:'',shadowColor:'',shadowBlur:0,lineWidth:1,font:'',textAlign:'',globalAlpha:1,createLinearGradient:gradient,createRadialGradient:gradient,fillRect:noop,strokeRect:noop,beginPath:noop,arc:noop,fill:noop,stroke:noop,save:noop,restore:noop,translate:noop,rotate:noop,moveTo:noop,lineTo:noop,closePath:noop,fillText:noop,setLineDash:noop,ellipse:noop,quadraticCurveTo:noop,bezierCurveTo:noop};el.game.getContext=()=>ctx;
const choicePanel=new El('choicePanel'),document={getElementById:id=>el[id],createElement:tag=>new El(tag),querySelector:sel=>sel==='.choice-panel'?choicePanel:null};let raf=[],now=0;const requestAnimationFrame=fn=>(raf.push(fn),raf.length),cancelAnimationFrame=()=>{},localStorage={m:{},getItem(k){return this.m[k]||null},setItem(k,v){this.m[k]=String(v)}};const initialSeed=(Number(process.env.STARWARD_SEED)||123456789)>>>0;let seed=initialSeed;const gameMath=Object.create(Math);gameMath.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const window={matchMedia:()=>({matches:false})},sandbox={document,window,localStorage,requestAnimationFrame,cancelAnimationFrame,performance:{now:()=>now},Math:gameMath,console,Blob:global.Blob,Response:global.Response};vm.createContext(sandbox);
const splitLines=s=>s.match(/[^\n]*\n|[^\n]+$/g)||[],base=fs.readFileSync(__dirname+'/game.js','utf8'),parts=fs.readdirSync(__dirname+'/runtime_v9_patch').filter(f=>/^patch-\d+\.b64$/.test(f)).sort().map(f=>fs.readFileSync(__dirname+'/runtime_v9_patch/'+f,'utf8').trim()).join(''),ops=JSON.parse(zlib.gunzipSync(Buffer.from(parts,'base64')).toString('utf8')),lines=splitLines(base),out=[];for(const op of ops){if(op[0]==='=')out.push(lines.slice(op[1],op[2]).join(''));else out.push(op[1]);}
function balance(source){let n=0;source=source.replace(/const ENEMIES\s*=\s*\{[\s\S]*?\n\};/,b=>b.replace(/\bhp:(\d+(?:\.\d+)?)/g,(_,v)=>{n++;return `hp:${Math.round(Number(v)*1.75*100)/100}`}));source=source.replace(/S\.focusTimer=7\b/g,'S.focusTimer=8').replace(/for 7 seconds/g,'for 8 seconds');const a='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.25:1;',b='const focusBonus=target===S.focusTarget&&S.focusTimer>0?1.65:1;';if(!source.includes(a)||n<5)throw Error('balance hooks missing');return source.replace(a,b)}
const source=transform.apply(balance(out.join('')));for(const term of ['V13_DECISION_GAP=28','v14WrapAll','v15BulletAtPointer','V16_POWER_KEYS','TRIDENT FIRE','TIME DILATION','MANUAL DEFENSE','IGNORE = KEEP FLYING'])if(!source.includes(term))throw Error('V16 source missing '+term);vm.runInContext(source,sandbox);
if(!window.__STARWARD__?.v12State||!window.__STARWARD__?.v13State||!window.__STARWARD__?.v14EventLines||!window.__STARWARD__?.v15State||!window.__STARWARD__?.v16PowerState||!window.__STARWARD__?.v16FireTick)throw Error('V16 debug hooks missing');if(!(el.laserButton.listeners.click||[]).length)throw Error('Star Laser button not wired');
el.startBtn.click();for(let i=0;i<5;i++){if(el.choiceGrid.children.length!==3)throw Error('Opening draft broken at '+(i+1));(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Armor|Aim|Projectile|Fortress|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click()}
let state=window.__STARWARD__.getState();if(state.phase!=='running')throw Error('Run did not start');
const ev=(x,y,id=1)=>({clientX:x,clientY:y,pointerId:id,preventDefault(){},stopImmediatePropagation(){this._stop=true}});
el.game.dispatch('pointerdown',ev(820,105,7));let v=window.__STARWARD__.v12State();if(!v?.aim.active||v.aim.angle>=-.1)throw Error('Hold-to-aim upward failed');state.cooldowns={};for(let i=0;i<80;i++)window.__STARWARD__.v16FireTick();if(!state.shots.some(s=>s.v12Manual&&s.vy<-20))throw Error('Manual aim did not redirect fire upward');el.game.dispatch('pointermove',ev(820,435,7));if(window.__STARWARD__.v12State().aim.angle<=.1)throw Error('Drag-to-aim downward failed');el.game.dispatch('pointerup',ev(820,435,7));if(window.__STARWARD__.v12State().aim.active||Math.abs(window.__STARWARD__.v12State().aim.angle)>.001)throw Error('Release did not restore forward fire');
const powers=window.__STARWARD__.v13PowerTypes();if(powers.length<15||!['trident','timeshift','aegis','seeker','ricochet','magnet'].every(x=>powers.includes(x)))throw Error('Expanded power pool missing');const initialPowerState=window.__STARWARD__.v16PowerState();if(Object.values(initialPowerState).some(x=>!Number.isFinite(x)))throw Error('Expanded power timers are not numeric');state.shots.length=0;state.cooldowns={};const p=window.__STARWARD__.v12SpawnPowerup('trident',270,620);if(!p||!window.__STARWARD__.v12CollectPowerup(p))throw Error('Trident power core collection failed');if(!(window.__STARWARD__.v16PowerState().trident>0))throw Error('Trident timer did not activate');window.__STARWARD__.v12SetAim(820,270);for(let i=0;i<80;i++)window.__STARWARD__.v16FireTick();if(!state.shots.some(s=>s.v13Split))throw Error('Trident power mode did not split fire');window.__STARWARD__.v12ReleaseAim();
if(!window.__STARWARD__.forceEvent('precisionrun'))throw Error('Precision live event unavailable');state=window.__STARWARD__.getState();const wrapped=window.__STARWARD__.v14EventLines();if(wrapped.join(' ')!==state.liveEvent.body.trim())throw Error('Event body not fully preserved');if(wrapped.some(l=>l.length>82))throw Error('Event line too wide');const box=window.__STARWARD__.v14EventBox(),accept=box.accept;el.game.dispatch('pointerdown',ev(520,115,8));if(!window.__STARWARD__.getState().liveEvent)throw Error('Aiming accidentally accepted live event');el.game.dispatch('pointerup',ev(520,115,8));el.game.dispatch('pointerdown',ev(accept.x+accept.w/2,accept.y+accept.h/2,9));if(window.__STARWARD__.getState().liveEvent)throw Error('Dedicated ACCEPT hitbox failed');
state.bullets.length=0;state.shots.length=0;const passiveBullet={x:430,y:270,vx:-80,vy:0,damage:1,life:4,hot:false};state.bullets.push(passiveBullet);state.shots.push({x:430,y:270,vx:600,vy:0,damage:1,life:2,pierce:0,trail:[],kind:'pulse',color:'#fff',v12Manual:true,v15Aimed:false});window.__STARWARD__.v12ResolveShotdowns();if(passiveBullet.life<=0)throw Error('Passive forward fire still intercepts bullets');
state.bullets.length=0;state.shots.length=0;const aimedBullet={x:430,y:270,vx:-80,vy:0,damage:1,life:4,hot:false};state.bullets.push(aimedBullet);state.shots.push({x:430,y:270,vx:600,vy:0,damage:1,life:2,pierce:0,trail:[],kind:'pulse',color:'#fff',v12Manual:true,v15Aimed:true});const manualBefore=window.__STARWARD__.v15State()?.manualShotdowns||0,comboBefore=window.__STARWARD__.v13State()?.combo||0;window.__STARWARD__.v12ResolveShotdowns();if(aimedBullet.life>0)throw Error('Aimed projectile interception failed');if((window.__STARWARD__.v15State()?.manualShotdowns||0)<=manualBefore)throw Error('Manual interception telemetry failed');if((window.__STARWARD__.v13State()?.combo||0)<=comboBefore)throw Error('Manual interception did not feed combat chain');
let fixedLane=true,powerSeen=false,maxPaused=0,eventSeen=false,peak=0;for(let frame=0;frame<10800;frame++){
  if(!raf.length)break;const fn=raf.shift();now+=16.666;fn(now);state=window.__STARWARD__.getState();v=window.__STARWARD__.v12State();if(state.phase==='dead')break;peak=Math.max(peak,state.enemies.length);if(Math.abs(state.ship.y-270)>.02)fixedLane=false;if(v?.powerups?.length)powerSeen=true;if(state.liveEvent)eventSeen=true;
  if(frame%18===0){const bullet=state.bullets.filter(b=>b.life>0&&b.x>state.ship.x+35).sort((a,b)=>a.x-b.x)[0],power=v?.powerups?.find(x=>!x.dead),enemy=state.boss||state.enemies.filter(e=>e.hp>0).sort((a,b)=>(b.elite-a.elite)||(a.x-b.x))[0],target=power||bullet||enemy;if(target)window.__STARWARD__.v12SetAim(target.x,target.y);else window.__STARWARD__.v12ReleaseAim()}
  if(state.liveEvent&&frame%80===0){const r=window.__STARWARD__.v14EventBox().accept;el.game.dispatch('pointerdown',ev(r.x+r.w/2,r.y+r.h/2,21));}
  if(frame%60===0&&state.laserCharge>=state.laserMax&&state.time>=state.nextLaserAt)el.laserButton.click();
  if(!el.overlay.classList.contains('hidden')&&!el.choiceGrid.classList.contains('hidden')&&el.choiceGrid.children.length===3){maxPaused++;(el.choiceGrid.children.find(c=>/Hull|Shield|Repair|Armor|Aim|Projectile|Damage|Fire Rate|Second Chance/i.test(c.innerHTML))||el.choiceGrid.children[0]).click()}
}
state=window.__STARWARD__.getState();v=window.__STARWARD__.v12State();const v13=window.__STARWARD__.v13State()||{},v15=window.__STARWARD__.v15State()||{};if(!fixedLane)throw Error('Ship left fixed lane');if(state.time<105)throw Error(`V16 run ended too early at ${state.time.toFixed(1)}s`);if(!powerSeen)throw Error('Power cores did not recur');if(!eventSeen)throw Error('Live decisions did not recur');if((v13.decisionCount||0)<2)throw Error('Higher upgrade cadence did not execute');if(maxPaused>10)throw Error('Upgrade cadence too interruptive: '+maxPaused);if(peak<24)throw Error('Enemy density too low: '+peak);if((v15.manualShotdowns||0)<2)throw Error('Manual interception was not meaningful');if(Object.values(window.__STARWARD__.v16PowerState()).some(x=>!Number.isFinite(x)))throw Error('Power timer became non-finite during stress run');
if(state.phase==='running'){window.__STARWARD__.v12ReleaseAim();window.__STARWARD__.endRun();for(let i=0;i<180&&raf.length;i++){const fn=raf.shift();now+=16.666;fn(now);if(window.__STARWARD__.getState().phase==='dead')break}}
state=window.__STARWARD__.getState();if(state.phase!=='dead')throw Error('Run-end sequence failed');for(const term of ['AIM CONTROL','ACTIVE GUNNERY','MANUAL DEFENSE'])if(!new RegExp(term).test(el.overlayText.innerHTML))throw Error('Results missing '+term);console.log(`Starward V16 seed ${initialSeed} OK: ${state.time.toFixed(1)}s, peak ${peak}, drafts ${v13.decisionCount||0}, powers ${v.powerCollected||0}, manualShotdowns ${v15.manualShotdowns||0}, interceptChain ${v15.bestInterceptChain||0}, aimedKills ${v.aimedKills||0}`);